### ISSUE TITLE
Post-Processing slows down to a crawl and fails with large globs

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/cromwell#1248]
@jsotobroad -- take it away

**Comment by jsotobroad** [comment]
In a scatter of 20500 shards, we ran a task that basically took in one file input and output a glob of files.  We first tried this with a glob where we expected ~900 files to be output and no memory issues were found and everything went relatively smoothly.  Because of some outside factors we decided to change this task to instead output ~3000 files in the glob.  After about 13000 tasks were processed(Sucess -> Done) we started seeing some slow down that coincided with errors in the logs like the following:
```
2016-08-03 03:34:04,971 cromwell-system-akka.actor.default-dispatcher-51 WARN  - Caught exception, retrying: Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[na:1.8.0_72]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_72]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_72]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153) ~[na:1.8.0_72]
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:93) ~[cromwell.jar:0.19]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[cromwell.jar:0.19]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[cromwell.jar:0.19]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[cromwell.jar:0.19]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider$$anonfun$3.apply(GcsFileSystemProvider.scala:242) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider$$anonfun$3.apply(GcsFileSystemProvider.scala:242) ~[cromwell.jar:0.19]
        at scala.util.Try$.apply(Try.scala:192) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider$.withRetry(GcsFileSystemProvider.scala:48) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.requestListPage$1(GcsFileSystemProvider.scala:242) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.remainingObjects$1(GcsFileSystemProvider.scala:250) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.list(GcsFileSystemProvider.scala:256) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.io.filesystem.gcs.GcsFileSystemProvider.newDirectoryStream(GcsFileSystemProvider.scala:265) ~[cromwell.jar:0.19]
        at java.nio.file.Files.newDirectoryStream(Files.java:457) ~[na:1.8.0_72]
        at better.files.File.list(File.scala:200) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesWorkflowEngineFunctions.glob(JesEngineFunctions.scala:15) ~[cromwell.jar:0.19]
        at cromwell.engine.WdlStandardLibraryImpl$$anonfun$glob$1.apply(WdlStandardLibraryImpl.scala:171) ~[cromwell.jar:0.19]
        at cromwell.engine.WdlStandardLibraryImpl$$anonfun$glob$1.apply(WdlStandardLibraryImpl.scala:169) ~[cromwell.jar:0.19]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[cromwell.jar:0.19]
        at scala.util.Try$.apply(Try.scala:192) ~[cromwell.jar:0.19]
        at scala.util.Success.map(Try.scala:237) ~[cromwell.jar:0.19]
        at cromwell.engine.WdlStandardLibraryImpl$class.glob(WdlStandardLibraryImpl.scala:169) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.WorkflowEngineFunctions.glob(EngineFunctions.scala:15) ~[cromwell.jar:0.19]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_72]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_72]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72]
        at wdl4s.expression.WdlFunctions$$anonfun$getFunction$1.apply(WdlFunctions.scala:21) ~[cromwell.jar:0.19]
        at wdl4s.expression.WdlFunctions$$anonfun$getFunction$1.apply(WdlFunctions.scala:21) ~[cromwell.jar:0.19]
        at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:126) ~[cromwell.jar:0.19]
        at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:79) ~[cromwell.jar:0.19]
        at wdl4s.WdlExpression.evaluate(WdlExpression.scala:192) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend.cromwell$engine$backend$jes$JesBackend$$outputLookup(JesBackend.scala:695) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$getOutputFoldingFunction$1.apply(JesBackend.scala:675) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$getOutputFoldingFunction$1.apply(JesBackend.scala:674) ~[cromwell.jar:0.19]
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124) ~[cromwell.jar:0.19]
        at scala.collection.immutable.List.foldLeft(List.scala:84) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend.postProcess(JesBackend.scala:665) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:705) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:705) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:700) ~[cromwell.jar:0.19]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[cromwell.jar:0.19]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[cromwell.jar:0.19]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[cromwell.jar:0.19]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[na:1.8.0_72]
        ... 54 common frames omitted
```
and
```
2016-08-03 03:33:06,985 cromwell-system-akka.actor.default-dispatcher-3 WARN  - Caught exception, retrying: Broken pipe
java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_72]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_72]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[na:1.8.0_72]
        at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431) ~[na:1.8.0_72]
        at sun.security.ssl.OutputRecord.write(OutputRecord.java:417) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:876) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:847) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:717) ~[na:1.8.0_72]
        at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1077) ~[na:1.8.0_72]
        at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1222) ~[na:1.8.0_72]
        at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1134) ~[na:1.8.0_72]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348) ~[na:1.8.0_72]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_72]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[na:1.8.0_72]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[na:1.8.0_72]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[na:1.8.0_72]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.8.0_72]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153) ~[na:1.8.0_72]
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:93) ~[cromwell.jar:0.19]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[cromwell.jar:0.19]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419) ~[cromwell.jar:0.19]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[cromwell.jar:0.19]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.Run.status(Run.scala:143) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.Run.checkStatus(Run.scala:156) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$poll$1$$anonfun$42.apply(JesBackend.scala:933) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$poll$1$$anonfun$42.apply(JesBackend.scala:933) ~[cromwell.jar:0.19]
        at scala.util.Try$.apply(Try.scala:192) ~[cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$poll$1.apply(JesBackend.scala:933) [cromwell.jar:0.19]
        at cromwell.engine.backend.jes.JesBackend$$anonfun$poll$1.apply(JesBackend.scala:927) [cromwell.jar:0.19]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [cromwell.jar:0.19]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [cromwell.jar:0.19]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [cromwell.jar:0.19]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
```
We suspect that of all the retries from the errors above plus the new succeeded tasks that now needed post processing created a backlog that may have cause Cromwell to become sluggish and eventually run out of memory.  It may have also been the opposite direction where Cromwell becoming sluggish caused these errors to start popping up.

@dshiga any additions to explain what we saw when you launched the 20k callset with 3000 intervals?

**Comment by pgrosu** [comment]
@jsotobroad  As scatter/gather seem to be concurrency events I think you're running into the maximum IOPS (Input/Output Operations Per Second) available from Google.  The simulatneous Google disk IOPS are as follows, based on the following link and shown in the table below:

https://cloud.google.com/compute/docs/disks/performance#type_comparison

Read | Write 
--- | --- 
3000 IOPS | 0 IOPS
 2250 IOPS | 3750 IOPS
 1500 IOPS | 7500 IOPS
  750 IOPS | 11250 IOPS
    0 IOPS | 15000 IOPS

There are other ways this might be tackled where the IOPS is throttled, or a few architectural changes would need to be done where it would write locally to the VM and then transferred over in a preemptive way.  There is a microservices approach, but that is a major architectural change for Cromwell.
