### ISSUE TITLE
Job Store doesn't handle File outputs

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1349]
Currently the Job Store doesn't cope with File outputs at all.  See the discussion at #1340 for thoughts about doing this in a futureproof way.  Also think about the how much logic will be shared with call cache results in #1233, and particularly about factoring out the simpleton nature in the job store and call cache result simpletons.

**Comment by mcovarr** [comment]
```
2016-08-26 16:15:29,393 cromwell-system-akka.actor.default-dispatcher-3 ERROR - JobStoreReadFailure
java.lang.RuntimeException: JobStoreResultSimpletonEntry(metrics,"gs://broad-gotc-prod-cromwell-execution/PairedEndSingleSampleWorkflow/5b7f21d8-0a96-4bbe-a96b-aa68c0454fd7/call-CollectQualityYieldMetrics/shard-8/HV2J2CCXX.8.Pond-555028.unmapped.quality_yield_metrics",File,892420,Some(287367)): unrecognized WDL type: File
	at cromwell.jobstore.SqlJobStore.cromwell$jobstore$SqlJobStore$$toSimpleton(SqlJobStore.scala:59) ~[classes/:na]
	at cromwell.jobstore.SqlJobStore$$anonfun$readJobResult$1$$anonfun$apply$5$$anonfun$3.apply(SqlJobStore.scala:69) ~[classes/:na]
	at cromwell.jobstore.SqlJobStore$$anonfun$readJobResult$1$$anonfun$apply$5$$anonfun$3.apply(SqlJobStore.scala:69) ~[classes/:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at cromwell.jobstore.SqlJobStore$$anonfun$readJobResult$1$$anonfun$apply$5.apply(SqlJobStore.scala:69) ~[classes/:na]
	at cromwell.jobstore.SqlJobStore$$anonfun$readJobResult$1$$anonfun$apply$5.apply(SqlJobStore.scala:66) ~[classes/:na]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at cromwell.jobstore.SqlJobStore$$anonfun$readJobResult$1.apply(SqlJobStore.scala:66) ~[classes/:na]
	at cromwell.jobstore.SqlJobStore$$anonfun$readJobResult$1.apply(SqlJobStore.scala:66) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.3.15.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.3.15.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.3.15.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.3.15.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.3.15.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.11-2.3.15.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.15.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
```
