### ISSUE TITLE
Unable to run under SGE with current application.conf examples

### ISSUE THREAD

**Issue by sndrtj** [broadinstitute/cromwell#1406]
I am trying to run a simple WDL file under SGE. The documentation tells me to take the [application.conf](https://raw.githubusercontent.com/broadinstitute/cromwell/develop/core/src/main/resources/application.conf) file and uncomment the SGE section. 

Cromwell will very quickly raise an exception:

```
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'backendsAllowed'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:252)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:323)
	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:381)
	at cromwell.server.WorkflowManagerSystem$class.allowedBackends(WorkflowManagerSystem.scala:24)
	at cromwell.Main$$anon$1.allowedBackends(Main.scala:97)
	at cromwell.server.WorkflowManagerSystem$class.$init$(WorkflowManagerSystem.scala:27)
	at cromwell.Main$$anon$1.<init>(Main.scala:97)
	at cromwell.Main.<init>(Main.scala:97)
	at cromwell.Main$.delayedEndpoint$cromwell$Main$1(Main.scala:49)
	at cromwell.Main$delayedInit$body.apply(Main.scala:31)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at cromwell.Main$.main(Main.scala:31)
	at cromwell.Main.main(Main.scala)
```

I managed to fix *this* exception by changing the configuration file to

```
backed {
  defaultBackend = "SGE"
  backendsAllowed = [
    "Local", "SGE"
  ]
  providers { .... }
}
```

However, this introduces another exception after a few seconds. 

```
[2016-09-13 17:39:24,467] [info] Slf4jLogger started
[2016-09-13 17:39:24,541] [info] RUN sub-command
[2016-09-13 17:39:24,542] [info]   WDL file: pipeline.wdl
[2016-09-13 17:39:24,543] [info]   Inputs: inputs.json
[2016-09-13 17:39:24,622] [info] SingleWorkflowRunnerActor: launching workflow
[2016-09-13 17:39:25,911] [info] Running with database db.url = jdbc:hsqldb:mem:${uniqueSchema};shutdown=false;hsqldb.tx=mvcc
[2016-09-13 17:39:33,39] [info] WorkflowManagerActor submitWorkflow input id = None, effective id = 8eab0d5a-925a-4e99-ae3b-f30dfadacb58
Uncaught error from thread [cromwell-system-akka.actor.default-dispatcher-2] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[cromwell-system]
java.lang.ExceptionInInitializerError
	at cromwell.engine.backend.local.SharedFileSystem$class.rootPath(SharedFileSystem.scala:113)
	at cromwell.engine.backend.sge.SgeBackend.rootPath(SgeBackend.scala:47)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$1$1.apply(MaterializeWorkflowDescriptorActor.scala:87)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$1$1.apply(MaterializeWorkflowDescriptorActor.scala:86)
	at scalaz.ValidationFlatMap.flatMap(Validation.scala:433)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$1(MaterializeWorkflowDescriptorActor.scala:86)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$2$$anonfun$apply$8.apply(MaterializeWorkflowDescriptorActor.scala:110)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$2$$anonfun$apply$8.apply(MaterializeWorkflowDescriptorActor.scala:109)
	at scalaz.ValidationFlatMap.flatMap(Validation.scala:433)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$2.apply(MaterializeWorkflowDescriptorActor.scala:109)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor$2.apply(MaterializeWorkflowDescriptorActor.scala:103)
	at scalaz.ValidationFlatMap.flatMap(Validation.scala:433)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor(MaterializeWorkflowDescriptorActor.scala:103)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor$$anonfun$receive$1.applyOrElse(MaterializeWorkflowDescriptorActor.scala:66)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at cromwell.engine.workflow.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:59)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'shared-filesystem'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:258)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:264)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
	at cromwell.engine.backend.local.SharedFileSystem$.<init>(SharedFileSystem.scala:27)
	at cromwell.engine.backend.local.SharedFileSystem$.<clinit>(SharedFileSystem.scala)
	... 25 more
```

I'm at a loss where to place the `shared-filesystem` key, and what should be in it.

**Comment by kshakir** [comment]
I'm guessing that this isn't running a build of a recent version of develop?

We have not automated publishing of develop builds of cromwell, so can you build a jar from the latest source code using `sbt assembly`, and then try your config again? If that doesn't work, and there's no private information inside you config file, please post the backend stanza from the application.conf so that we may continue debugging your issue.

**Comment by geoffjentry** [comment]
@sndrtj To follow up a bit on what @kshakir says here, for any users who do not need call caching I'd highly recommend working with the develop branch. We expect to release Any Day Now (he's been saying for a few weeks) and while it'll have its own problems with life it's already demonstrated itself to be superior in just about every way to 0.19

**Comment by sndrtj** [comment]
Great. Building the code instead of downloading the latest release works like a charm :+1:

**Comment by geoffjentry** [comment]
Awesome. Please let us know if you run into issues!
