### ISSUE TITLE
WorkflowLogger.makeFileLogger bottleneck

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1445]
Under load Cromwell seems to have a large number of engine dispatcher threads blocked with stack traces like the following:

```
"cromwell-system-akka.dispatchers.engine-dispatcher-107" #455 prio=5 os_prio=0 tid=0x00007fa5b8075000 nid=0x4598 waiting for monitor entry [0x00007fa7999d8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at cromwell.core.logging.WorkflowLogger$.makeFileLogger(WorkflowLogger.scala:26)
    - waiting to lock <0x00000000ca4a8b40> (a cromwell.core.logging.WorkflowLogger$)
    at cromwell.core.logging.WorkflowLogger.<init>(WorkflowLogger.scala:108)
    at cromwell.core.logging.WorkflowLogging$class.workflowLogger(WorkflowLogger.scala:21)
    at cromwell.engine.workflow.WorkflowActor.workflowLogger$lzycompute(WorkflowActor.scala:151)
    - locked <0x00000000eceaf5f0> (a cromwell.engine.workflow.WorkflowActor)
    at cromwell.engine.workflow.WorkflowActor.workflowLogger(WorkflowActor.scala:151)
    at cromwell.engine.workflow.WorkflowActor$$anonfun$8.applyOrElse(WorkflowActor.scala:262)
    at cromwell.engine.workflow.WorkflowActor$$anonfun$8.applyOrElse(WorkflowActor.scala:260)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
    at akka.actor.FSM$$anonfun$handleTransition$1.apply(FSM.scala:606)
    at akka.actor.FSM$$anonfun$handleTransition$1.apply(FSM.scala:606)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at akka.actor.FSM$class.handleTransition(FSM.scala:606)
    at akka.actor.FSM$class.makeTransition(FSM.scala:688)
    at cromwell.engine.workflow.WorkflowActor.makeTransition(WorkflowActor.scala:151)
    at akka.actor.FSM$class.applyState(FSM.scala:673)
    at cromwell.engine.workflow.WorkflowActor.applyState(WorkflowActor.scala:151)
    at akka.actor.FSM$class.processEvent(FSM.scala:668)
```

**Comment by mcovarr** [comment]
I thought @kshakir already addressed this?

**Comment by kshakir** [comment]
Addressed by #1456, that _should_ have made things better, but technically not yet verified / regression tested

**Comment by mcovarr** [comment]
Great, thanks.  I originally saw this issue when running a 20000-wide Hello World scatter using mock JES.  At a point when Cromwell temporarily seemed catatonic, I Control-backslashed and saw loads of engine dispatcher stack traces like the above.

Mock JES is currently [broken](#1571) due to batching API changes but hopefully it will become great again soon and the #1456 changes can be validated.

**Comment by geoffjentry** [comment]
An addendum to this and #1456 is that a) I should formalize (at least a bit) what I was going a few weeks ago w/ spamming cromwell, monitoring, etc and b) we should go over it as a group such that everyone feels comfortable doing such things

**Comment by geoffjentry** [comment]
@kcibul When making the Q3 scalability bucket I think that verification of what @kshakir said above should be part of it

**Comment by katevoss** [comment]
This has likely changed, so closing out. Feel free to open a new issue if it's still a problem.
