### ISSUE TITLE
"data exception: string data, right truncation" with "long" GCS paths or task names

### ISSUE THREAD

**Issue by mbookman** [broadinstitute/cromwell#1555]
I was trying to run the [PublicPairedSingleSampleWf](https://github.com/broadinstitute/wdl/blob/develop/scripts/broad_pipelines/PublicPairedSingleSampleWf_160927.wdl) using Cromwell 0.19.3 and it was consistently failing with the following:

```
2016-10-06 21:32:38,239 cromwell-system-akka.actor.default-dispatcher-41 INFO  - JES Run [UUID(65d59b8b):SamToFastqAndBwaMem:1]: Status change from Running to Success
2016-10-06 21:32:38,586 cromwell-system-akka.actor.default-dispatcher-4 ERROR -WorkflowActor [UUID(65d59b8b)]: Completion work failed for call SamToFastqAndBwaMem:1.
java.sql.SQLDataException: data exception: string data, right truncation;  table: EXECUTION_EVENT column: DESCRIPTION
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[cromwell.jar:0.19]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[cromwell.jar:0.19]
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[cromwell.jar:0.19]
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[cromwell.jar:0.19]
<snip>
```

I had run the previous version of the PublicPairedSingleSampleWf successfully.

I finally realized that it had nothing to do with the workflow, but rather because I changed the GCS path for Cromwell's `baseExecutionBucket` to something much longer. Instead of my previous:

```
gs://my-bucket/gatk-test/
```

I had changed to:

```
gs://my-bucket/broad_pipelines/PublicPairedSingleSampleWf_160927/
```

When I went back and shortened the path, everything worked again.

Along the way, I ran a similar test where I changed the task name for my test [vcf_chr_count.wdl](https://github.com/googlegenomics/pipelines-api-examples/blob/master/wdl_runner/workflows/vcf_chr_count/vcf_chr_count.wdl) from:

```
task vcf_split
```

to 

```
task vcf_split_what_if_i_have_a_really_long_task_is_that_the_problem
```

This also generated the same exception:

```
java.sql.SQLDataException: data exception: string data, right truncation;  table: EXECUTION_EVENT column: DESCRIPTION
```

**Comment by cjllanwarne** [comment]
Hey there, thanks for the bug report! I believe this is actually fixed in our later versions (we just released v22) - could you confirm whether upgrading resolves this issue?

Thanks!

**Comment by kcibul** [comment]
closing -- should be working as of > 22, please reopen though if you still have a problem
