### ISSUE TITLE
Malformed inputs not handled, no response

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#1740]
During testing I completely botched making my inputs file.  Rather than a nice JSON map, I created a file with just the value: no key and no enclosing curlies.  Cromwell did not take this well and never issued a response to the client.

```
spray.json.JsonParser$ParsingException: Unexpected character 'm' at input index 0 (line 1, position 1), expected JSON Value:
mcovarr
^

spray.json.JsonParser$ParsingException: Unexpected character 'm' at input index 0 (line 1, position 1), expected JSON Value:
mcovarr
^

	at spray.json.JsonParser.fail(JsonParser.scala:213)
	at spray.json.JsonParser.value(JsonParser.scala:64)
	at spray.json.JsonParser.parseJsValue(JsonParser.scala:43)
	at spray.json.JsonParser$.apply(JsonParser.scala:28)
	at spray.json.PimpedString.parseJson(package.scala:45)
	at cromwell.webservice.CromwellApiService$PartialWorkflowSources$.cromwell$webservice$CromwellApiService$PartialWorkflowSources$$workflowInputs(CromwellApiService.scala:134)
	at cromwell.webservice.CromwellApiService$PartialWorkflowSources$$anonfun$6$$anonfun$apply$12.apply(CromwellApiService.scala:161)
	at cromwell.webservice.CromwellApiService$PartialWorkflowSources$$anonfun$6$$anonfun$apply$12.apply(CromwellApiService.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
```

**Comment by geoffjentry** [comment]
Similarly I passed in `wdlInputs` instead of `workflowInputs` and got a giant stack trace on the cromwell side but no response (other than timeout) on the client side

**Comment by katevoss** [comment]
@mcovarr is there any input validation now? Or are malformed inputs still poorly handled?

**Comment by mcovarr** [comment]
not sure I'll check it out.

**Comment by katevoss** [comment]
@mcovarr did you get a chance to look at this?
