### ISSUE TITLE
Evaluating expressions containing optional type broke in 23

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1765]
In 0.22 you could have something like this in config backend:
```
runtime_attributes = """
String? pbs_email
"""
```
And then reference `pbs_email` inside an expression in the `submit` definition like so:
```
submit = """
qsub ${"-me ea -M" + pbs_email}
"""
```
so that if `pbs_email` isn't supplied, neither are the preceding option flags (as documented in `Optional Parameters and Type Constraints -> Prepending a String to an Optional Parameter` at https://software.broadinstitute.org/wdl/devzone.php)

This doesn't work anymore in 23:
```
[ERROR] [12/09/2016 11:09:29.763] [cromwell-system-akka.dispatchers.backend-dispatcher-19] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor/WorkflowActor-71ccb54a-f88c-49b2-aeee-1af92749e337/WorkflowExecutionActor-71ccb54a-f88c-49b2-aeee-1af92749e337/71ccb54a-f88c-49b2-aeee-1af92749e337-EngineJobExecutionActor-testMe.worker:NA:1/71ccb54a-f88c-49b2-aeee-1af92749e337-BackendJobExecutionActor-71ccb54a:testMe.worker:-1:1/SharedFileSystemAsyncJobExecutionActor] SharedFileSystemAsyncJobExecutionActor [UUID(71ccb54a)testMe.worker:NA:1]: Error attempting to Execute the script
java.lang.UnsupportedOperationException: Could not evaluate expression: "-m ea -M " + pbs_email
	at wdl4s.command.ParameterCommandPart.instantiate(ParameterCommandPart.scala:49)
	at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:107)
	at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:107)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at wdl4s.Task$$anonfun$instantiateCommand$1.apply(Task.scala:107)
	at wdl4s.Task$$anonfun$instantiateCommand$1.apply(Task.scala:107)
	at scala.util.Try$.apply(Try.scala:192)
	at wdl4s.Task.instantiateCommand(Task.scala:107)
	at cromwell.backend.impl.sfs.config.ConfigAsyncJobExecutionActor$class.writeTaskScript(ConfigAsyncJobExecutionActor.scala:55)
	at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.writeTaskScript(ConfigAsyncJobExecutionActor.scala:124)
	at cromwell.backend.impl.sfs.config.ConfigAsyncJobExecutionActor$class.processArgs(ConfigAsyncJobExecutionActor.scala:39)
	at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.processArgs$lzycompute(ConfigAsyncJobExecutionActor.scala:124)
	at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.processArgs(ConfigAsyncJobExecutionActor.scala:124)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor$class.executeScript(SharedFileSystemAsyncJobExecutionActor.scala:220)
	at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeScript(ConfigAsyncJobExecutionActor.scala:124)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor$$anonfun$executeOrRecover$2.apply(SharedFileSystemAsyncJobExecutionActor.scala:192)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor$$anonfun$executeOrRecover$2.apply(SharedFileSystemAsyncJobExecutionActor.scala:189)
	at scala.util.Try$.apply(Try.scala:192)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor$class.executeOrRecover(SharedFileSystemAsyncJobExecutionActor.scala:188)
	at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeOrRecover(ConfigAsyncJobExecutionActor.scala:124)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover$1.apply(AsyncBackendJobExecutionActor.scala:45)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover$1.apply(AsyncBackendJobExecutionActor.scala:45)
	at cromwell.core.retry.Retry$.withRetry(Retry.scala:37)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$class.withRetry(AsyncBackendJobExecutionActor.scala:41)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$class.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:45)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:69)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.aroundReceive(ConfigAsyncJobExecutionActor.scala:124)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: wdl4s.WdlExpressionException: Cannot perform operation: -m ea -M  + WdlOptionalValue(WdlStringType,Some(WdlString(conrad.leonard@qimrberghofer.edu.au)))
	at wdl4s.values.WdlValue$class.invalid(WdlValue.scala:12)
	at wdl4s.values.WdlString.invalid(WdlString.scala:7)
	at wdl4s.values.WdlString.add(WdlString.scala:15)
	at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$3$$anonfun$apply$1.apply(ValueEvaluator.scala:54)
	at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$3$$anonfun$apply$1.apply(ValueEvaluator.scala:54)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$3.apply(ValueEvaluator.scala:54)
	at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$3.apply(ValueEvaluator.scala:54)
	at scala.util.Success.flatMap(Try.scala:231)
	at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:54)
	at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:87)
	at wdl4s.WdlExpression.evaluate(WdlExpression.scala:163)
	at wdl4s.command.ParameterCommandPart.instantiate(ParameterCommandPart.scala:37)
```

The problem appears to be in wdl4s now that optionals are first class citizens the `evaluate` [here](https://github.com/broadinstitute/wdl4s/blob/4e236a7e6e2202cd62e2a5fee991faf9829b3e67/src/main/scala/wdl4s/command/ParameterCommandPart.scala#L38) is failing with `WdlExpressionException` because you can't add `WdlOptionalValue` to `WdlString`, rather than the `VariableNotFoundException` that is handled a couple of lines below, which usefully used to return an empty string when you tried evaluate an expression with an unsupplied "?" variable.

**Comment by delocalizer** [comment]
The problem appears to be in wdl4s now that optionals are first class citizens the `evaluate` [here](https://github.com/broadinstitute/wdl4s/blob/4e236a7e6e2202cd62e2a5fee991faf9829b3e67/src/main/scala/wdl4s/command/ParameterCommandPart.scala#L38) is failing with `WdlExpressionException` because you can't add `WdlOptionalValue` to `WdlString`, rather than the `VariableNotFoundException` that is handled a couple of lines below, which usefully used to return an empty string when you tried evaluate an expression with an unsupplied "?" variable.

**Comment by Horneth** [comment]
@delocalizer Thanks for tracking this down ! I'm working on a fix. From what you describe and what I've found out so far it looks like it would not work either even if the value is supplied. Have you hit that case as well ?

**Comment by delocalizer** [comment]
@Horneth Yes - you are right, the evaluation step doesn't work either way - actually the stacktrace in the example above is from a case where the value was supplied

**Comment by kcibul** [comment]
Just talked this over in person.  Let's fix this to maintain backwards compatibility and then describe alternative usages through functions (e.g. In a declaration where you really want a getorelse kind of functionality)

**Comment by kcibul** [comment]
And we should definitely have a test for this
