### ISSUE TITLE
Aliased Sub-workflows Broken

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#1785]
As per the test case in https://github.com/broadinstitute/centaur/pull/123.

If you assign an alias to a subworkflow call (e.g. `call subwf as subwfA`) variable resolution is not working for providing the inputs.

**Comment by cjllanwarne** [comment]
Sample output:
```
Caused by: lenthall.exception.AggregatedException: :
Variable is resolved to scope subworkflow.subwf.is but cannot be evaluated.
	at lenthall.util.TryUtil$.sequenceIterable(TryUtil.scala:26)
	at lenthall.util.TryUtil$.sequence(TryUtil.scala:33)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableScopes(WorkflowExecutionActor.scala:364)
	... 22 more
	Suppressed: wdl4s.exception.VariableLookupException: Variable is resolved to scope subworkflow.subwf.is but cannot be evaluated.
		at wdl4s.Scope$$anonfun$5.apply(Scope.scala:255)
		at wdl4s.Scope$$anonfun$5.apply(Scope.scala:246)
		at scala.Option.map(Option.scala:146)
		at wdl4s.Scope$class.lookup$1(Scope.scala:246)
		at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:263)
		at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:263)
		at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
		at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
```
