### ISSUE TITLE
wf with scatters that worked in 5155e6f and earlier versions doesn't work anymore with 340a5cf

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1802]
I have a workflow containing scatters that worked in 5155e6f and earlier versions e.g. tags/22,23 but doesn't work anymore with 340a5cf.
[Edited]
see [comment below](https://github.com/broadinstitute/cromwell/issues/1802#issuecomment-268422512) for a simpler, more generic example

**Comment by delocalizer** [comment]
I have a generic (run-anywhere) wdl now that exhibits the same behaviour (runs under previous develop version, but not with 340a5cf): 
```
workflow dna_mapping_38 {

  call createInputs

  scatter (arg in createInputs.alignedReadGroup) {
    call mapping { input: inFile=arg }
  }

  call groupItemsByKey as groupArgsByLibrary {
    input:
      keys=createInputs.library,
      items=mapping.outFile
  }

  scatter (libset in groupArgsByLibrary.groups) {
    call markDup as libraryMerge {
      input:
        inputBams=libset.right,
        outputBam="library_${libset.left}.bam"
    }
  }

  output {
    Array[File] libMerged = libraryMerge.markDupedBam
  }
}

#########
# TASKS #
#########

task createInputs {
  command {
    for i in `seq 1 5`; do echo "lib1"; touch arg$i; done
  }
  output {
    Array[File] alignedReadGroup = glob("arg*")
    Array[String] library = read_lines(stdout())
  }
}

task mapping {
  File inFile
  command {
    echo "dummy mapping"
  }
  output {
    File outFile=inFile
  }
}

task groupItemsByKey {

  Array[String] keys
  Array[String] items

  meta {
    description: "return pairs of (key, all-items-with-that-key)"
  }

  command <<<
python <<CODE
import itertools
import sys
keys = "${sep='\t' keys}".split("\t")
items = "${sep='\t' items}".split("\t")
assert len(items) == len(keys)
theKey = lambda x: x[0]
theItem = lambda x: x[1]
data = sorted(zip(keys, items), key=theKey)
for key, group in itertools.groupby(data, theKey):
    sys.stderr.write(key + "\n")
    sys.stdout.write("\t".join(theItem(i) for i in group) + "\n")
CODE
  >>>

  output {
    Array[Pair[String, Array[String]]] groups = zip(read_lines(stderr()), read_tsv(stdout()))
  }
}

task markDup {

  Array[File] inputBams
  String outputBam

  command {
    echo "dummy marking duplicates"
    touch ${outputBam}
  }

  output {
    File markDupedBam = "${outputBam}"
  }
}
```
running:
```
java -jar workspace/cromwell/target/scala-2.11/cromwell-24-5155e6f-SNAP.jar run scatterTest.wdl - - - -
```

succeeds but running with new version: 
```
java -jar workspace/cromwell/target/scala-2.11/cromwell-24-340a5cf-SNAP.jar run scatterTest.wdl - - - -
```

ends with:
```
[2016-12-21 13:01:37,48] [error] WorkflowManagerActor Workflow 28b55884-8fd1-43aa-92ea-eb4891c2c5ff failed (during ExecutingWorkflowState): Couldn't resolve all inputs for dna_mapping_38.libraryMerge at index Some(0).:
Input evaluation for Call dna_mapping_38.libraryMerge failed.:
	inputBams:
	Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
	outputBam:
	Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
wdl4s.exception.VariableLookupException: Couldn't resolve all inputs for dna_mapping_38.libraryMerge at index Some(0).:
Input evaluation for Call dna_mapping_38.libraryMerge failed.:
	inputBams:
	Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
	outputBam:
	Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
	at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor$$anonfun$resolveAndEvaluateInputs$1.applyOrElse(JobPreparationActor.scala:49)
	at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor$$anonfun$resolveAndEvaluateInputs$1.applyOrElse(JobPreparationActor.scala:48)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure.recoverWith(Try.scala:203)
	at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor.resolveAndEvaluateInputs(JobPreparationActor.scala:48)
	at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor$$anonfun$receive$1.applyOrElse(JobPreparationActor.scala:27)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor.aroundReceive(JobPreparationActor.scala:18)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	Suppressed: wdl4s.exception.ValidationException: Input evaluation for Call dna_mapping_38.libraryMerge failed.:
inputBams:
	Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
outputBam:
	Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
		at wdl4s.Call.evaluateTaskInputs(Call.scala:117)
		at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor$$anonfun$resolveAndEvaluateInputs$2.apply(JobPreparationActor.scala:42)
		at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor$$anonfun$resolveAndEvaluateInputs$2.apply(JobPreparationActor.scala:35)
		at scala.util.Try$.apply(Try.scala:192)
		at cromwell.engine.workflow.lifecycle.execution.CallPreparationActor.resolveAndEvaluateInputs(JobPreparationActor.scala:35)
		... 12 more
		Suppressed: wdl4s.exception.VariableLookupException: inputBams:
Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
			at wdl4s.Call.wdl4s$Call$$lookup$2(Call.scala:176)
			at wdl4s.Call$$anonfun$lookupFunction$1.apply(Call.scala:181)
			at wdl4s.Call$$anonfun$lookupFunction$1.apply(Call.scala:181)
			at wdl4s.Call$$anonfun$4$$anonfun$5.apply(Call.scala:103)
			at wdl4s.Call$$anonfun$4$$anonfun$5.apply(Call.scala:103)
			at scala.util.Try$.apply(Try.scala:192)
			at wdl4s.Call$$anonfun$4.apply(Call.scala:103)
			at wdl4s.Call$$anonfun$4.apply(Call.scala:101)
			at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
			at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
			at scala.collection.Iterator$class.foreach(Iterator.scala:893)
			at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
			at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
			at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
			at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
			at scala.collection.AbstractTraversable.map(Traversable.scala:104)
			at wdl4s.Call.evaluateTaskInputs(Call.scala:101)
			... 16 more
			Suppressed: wdl4s.exception.ScatterIndexNotFound: Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
				at wdl4s.Scope$class.handleScatterResolution$1(Scope.scala:208)
				at wdl4s.Scope$$anonfun$5.apply(Scope.scala:260)
				at wdl4s.Scope$$anonfun$5.apply(Scope.scala:253)
				at scala.Option.map(Option.scala:146)
				at wdl4s.Scope$class.lookup$1(Scope.scala:253)
				at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:270)
				at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:270)
				at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
				at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
				at scala.util.Try$.apply(Try.scala:192)
				at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:45)
				at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:112)
				at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:85)
				at wdl4s.WdlExpression.evaluate(WdlExpression.scala:161)
				at wdl4s.Call$$anonfun$12$$anonfun$apply$7.apply(Call.scala:146)
				at wdl4s.Call$$anonfun$12$$anonfun$apply$7.apply(Call.scala:145)
				at scala.util.Success.flatMap(Try.scala:231)
				at wdl4s.Call$$anonfun$12.apply(Call.scala:145)
				at wdl4s.Call$$anonfun$12.apply(Call.scala:144)
				at scala.util.Success.flatMap(Try.scala:231)
				at wdl4s.Call.wdl4s$Call$$lookup$2(Call.scala:144)
				... 32 more
		Suppressed: wdl4s.exception.VariableLookupException: outputBam:
Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
			at wdl4s.Call.wdl4s$Call$$lookup$2(Call.scala:176)
			at wdl4s.Call$$anonfun$lookupFunction$1.apply(Call.scala:181)
			at wdl4s.Call$$anonfun$lookupFunction$1.apply(Call.scala:181)
			at wdl4s.Call$$anonfun$4$$anonfun$5.apply(Call.scala:103)
			at wdl4s.Call$$anonfun$4$$anonfun$5.apply(Call.scala:103)
			at scala.util.Try$.apply(Try.scala:192)
			at wdl4s.Call$$anonfun$4.apply(Call.scala:103)
			at wdl4s.Call$$anonfun$4.apply(Call.scala:101)
			at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
			at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
			at scala.collection.Iterator$class.foreach(Iterator.scala:893)
			at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
			at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
			at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
			at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
			at scala.collection.AbstractTraversable.map(Traversable.scala:104)
			at wdl4s.Call.evaluateTaskInputs(Call.scala:101)
			... 16 more
			Suppressed: wdl4s.exception.ScatterIndexNotFound: Could not find the shard mapping to this scatter dna_mapping_38.$scatter_1
				at wdl4s.Scope$class.handleScatterResolution$1(Scope.scala:208)
				at wdl4s.Scope$$anonfun$5.apply(Scope.scala:260)
				at wdl4s.Scope$$anonfun$5.apply(Scope.scala:253)
				at scala.Option.map(Option.scala:146)
				at wdl4s.Scope$class.lookup$1(Scope.scala:253)
				at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:270)
				at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:270)
				at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
				at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
				at scala.util.Try$.apply(Try.scala:192)
				at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:45)
				at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:112)
				at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:85)
				at wdl4s.WdlExpression.evaluate(WdlExpression.scala:161)
				at wdl4s.expression.ValueEvaluator.wdl4s$expression$ValueEvaluator$$replaceInterpolationTag(ValueEvaluator.scala:20)
				at wdl4s.expression.ValueEvaluator$$anonfun$interpolate$2.apply(ValueEvaluator.scala:33)
				at wdl4s.expression.ValueEvaluator$$anonfun$interpolate$2.apply(ValueEvaluator.scala:33)
				at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
				at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
				at scala.collection.Iterator$class.foreach(Iterator.scala:893)
				at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
				at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
				at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
				at wdl4s.expression.ValueEvaluator.interpolate(ValueEvaluator.scala:33)
				at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:49)
				at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:85)
				at wdl4s.WdlExpression.evaluate(WdlExpression.scala:161)
				at wdl4s.Call$$anonfun$12$$anonfun$apply$7.apply(Call.scala:146)
				at wdl4s.Call$$anonfun$12$$anonfun$apply$7.apply(Call.scala:145)
				at scala.util.Success.flatMap(Try.scala:231)
				at wdl4s.Call$$anonfun$12.apply(Call.scala:145)
				at wdl4s.Call$$anonfun$12.apply(Call.scala:144)
				at scala.util.Success.flatMap(Try.scala:231)
				at wdl4s.Call.wdl4s$Call$$lookup$2(Call.scala:144)
				... 32 more

```

The problem seems to be something to do with having _two_ scatters; removing the first one and adjusting the inputs accordingly removes the problem.
