### ISSUE TITLE
Cromwell server continually throws the same exception

### ISSUE THREAD

**Issue by holmeso** [broadinstitute/cromwell#1830]
I have a wdl task that doesn't handle an optional parameter as it should.
The wdl validates (wdltool-0.8.jar), but when I submit to my server, an exception is thrown over and over again.

```
[ERROR] [01/10/2017 15:07:12.214] [cromwell-system-akka.actor.default-dispatcher-5] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor/WorkflowActor-98777f84-7e
14-4408-b31e-9b57db5d813b/WorkflowExecutionActor-98777f84-7e14-4408-b31e-9b57db5d813b/98777f84-7e14-4408-b31e-9b57db5d813b-EngineJobExecutionActor-snps.testHC:NA:1/98777f84-7e1
4-4408-b31e-9b57db5d813b-BackendJobExecutionActor-98777f84:snps.testHC:-1:1/DispatchedConfigAsyncJobExecutionActor] DispatchedConfigAsyncJobExecutionActor [UUID(98777f84)snps.t
estHC:NA:1]: Error attempting to Execute
java.lang.UnsupportedOperationException: Could not find declaration for WdlOptionalValue(WdlStringType,None)
        at wdl4s.command.ParameterCommandPart.instantiate(ParameterCommandPart.scala:48)
        at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:108)
        at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:108)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at wdl4s.Task$$anonfun$instantiateCommand$1.apply(Task.scala:108)
        at wdl4s.Task$$anonfun$instantiateCommand$1.apply(Task.scala:108)
        at scala.util.Try$.apply(Try.scala:192)
        at wdl4s.Task.instantiateCommand(Task.scala:108)
...
```

Restarting the service seems to be the only way of stopping the exception being thrown.
Would it be possible to log the exception just once so that it doesn't clog up the server logs?
Thanks

**Comment by cjllanwarne** [comment]
@holmeso - Could you copy the WDL task which caused this to happen into here?

**Comment by holmeso** [comment]
@cjllanwarne - Here goes...

This works:
```
workflow wf {
  call tsk {
    input: foo="Hello", bar="World"
  }
}
task tsk {
  String foo
  String? bar
  command {
    echo "${foo} ${"here comes bar" + bar}"
  }
}
```
This doesn't:
```
workflow wf {
  call tsk {
    input: foo="Hello"
  }
}
task tsk {
  String foo
  String? bar
  command {
    echo "${foo} ${"here comes bar" + bar}"
  }
}
```

When `bar` is left out, job stays in the running state, and exceptions are continually thrown in the server logs.
The wdl validates fine.
Thanks
