### ISSUE TITLE
Not passing in a value to an optional task input fails for ints

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#1943]
We have a task that takes in an Optional int but when we call that task with no value for that int the workflow falls over.  It might not work for other types of Optionals either but I'm not sure.  Hash for this cromwell 24 was b71f06f.  This works on 19 (yes we're still on 19 =/)

Task (stuff removed):

```
task ValidateSamFile {
  File input_bam
  File? input_bam_index
  String report_filename
  File? ref_dict
  File? ref_fasta
  File? ref_fasta_index
  Int? max_output
  Array[String]? ignore
  Int disk_size
  Int preemptible_tries

  command {
    java -Xmx4000m -jar stuff.jar  blah
  }
  runtime {
    memory: "7 GB"
    disks: "local-disk " + disk_size + " HDD"
    preemptible: preemptible_tries
  }
  output {
    File report = "${report_filename}"
  }
}
```

Call (note there is no value supplied for max_output):

```
call ValidateSamFile as ValidateReadGroupSamFile {
      input:
        ref_fasta = ref_fasta,
        ref_fasta_index = ref_fasta_index,
        ref_dict = ref_dict,
        input_bam = SortAndFixReadGroupBam.output_bam,
        report_filename = sub(sub(unmapped_bam, sub_strip_path, ""), sub_strip_unmapped, "") + ".validation_report",
        disk_size = flowcell_medium_disk,
        preemptible_tries = preemptible_tries
    }
```

error in server logs:
```
2017-01-23 15:09:09 [cromwell-system-akka.actor.default-dispatcher-89] ERROR c.b.i.j.JesAsyncBackendJobExecutionActor - JesAsyncBackendJobExecutionActor [UUID(8f35e32d)PairedEndSingleSampleWorkflow.Vali
dateReadGroupSamFile:1:1]: Error attempting to Execute
java.lang.UnsupportedOperationException: Could not find declaration for WdlOptionalValue(WdlIntegerType,None)
        at wdl4s.command.ParameterCommandPart.instantiate(ParameterCommandPart.scala:48)
        at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:108)
        at wdl4s.Task$$anonfun$instantiateCommand$1$$anonfun$apply$2.apply(Task.scala:108)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at wdl4s.Task$$anonfun$instantiateCommand$1.apply(Task.scala:108)
        at wdl4s.Task$$anonfun$instantiateCommand$1.apply(Task.scala:108)
        at scala.util.Try$.apply(Try.scala:192)
```
in metadata:
```
failures: [
{
causedBy: {
message: "Could not find declaration for WdlOptionalValue(WdlIntegerType,None)"
},
message: "java.lang.UnsupportedOperationException: Could not find declaration for WdlOptionalValue(WdlIntegerType,None)"
```

**Comment by cjllanwarne** [comment]
The `Int` problem was a bug that's fixed in our develop (see our test cases here to see that they should cover this: https://github.com/broadinstitute/centaur/tree/develop/src/main/resources/standardTestCases/optional_parameter)

Unfortunately, optional file inputs is also a known bug that I'm about to pick up. You can track that progress here: https://github.com/broadinstitute/cromwell/issues/1940
