### ISSUE TITLE
submitting wf with missing import kills server

### ISSUE THREAD

**Issue by delocalizer** [broadinstitute/cromwell#1958]
Running with release 24.

As a minimal example, the following WDL:
```
import "foo.wdl" as missing

workflow testMe {
	call doNothing
}
task doNothing {
	command {}
}
```

and a zip file containing `baz.wdl` but not `foo.wdl`:
```
[conradL@qimr13054 ~]$ unzip -l bar.zip 
Archive:  bar.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-07-2017 13:47   bar/
        0  02-07-2017 13:47   bar/baz.wdl
---------                     -------
        0                     2 files
```

submit to server:
```
[conradL@qimr13054 ~]$ curl http://localhost:8000/api/workflows/V1 -FwdlSource=@badImport.wdl -FwdlDependencies=@bar.zip
{
  "id": "b701aafd-445c-4f49-8ba6-452d56e69fd3",
  "status": "Submitted"
}
```

causes the server process to die with this in the logs:
```
2017-02-07 13:52:41,842 cromwell-system-akka.actor.default-dispatcher-33 ERROR - guardian failed, shutting down system
wdl4s.exception.ValidationException: Failed to import workflow foo.wdl.:
File not found /tmp/640585481854205084.zip4511378926145376874/bar/foo.wdl
	at wdl4s.WdlNamespace$.wdl4s$WdlNamespace$$tryResolve$1(WdlNamespace.scala:198)
	at wdl4s.WdlNamespace$$anonfun$17.apply(WdlNamespace.scala:208)
	at wdl4s.WdlNamespace$$anonfun$17.apply(WdlNamespace.scala:207)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at wdl4s.WdlNamespace$.apply(WdlNamespace.scala:207)
	at wdl4s.WdlNamespace$.wdl4s$WdlNamespace$$load(WdlNamespace.scala:177)
	at wdl4s.WdlNamespace$.loadUsingSource(WdlNamespace.scala:173)
	at wdl4s.WdlNamespaceWithWorkflow$.load(WdlNamespace.scala:542)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$validateNamespaceWithImports$1.apply(MaterializeWorkflowDescriptorActor.scala:363)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$validateNamespaceWithImports$1.apply(MaterializeWorkflowDescriptorActor.scala:356)
	at lenthall.validation.ErrorOr$ShortCircuitingFlatMap$.flatMap$extension(ErrorOr.scala:17)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.validateNamespaceWithImports(MaterializeWorkflowDescriptorActor.scala:356)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.validateNamespace(MaterializeWorkflowDescriptorActor.scala:372)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor(MaterializeWorkflowDescriptorActor.scala:172)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$3.applyOrElse(MaterializeWorkflowDescriptorActor.scala:132)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$3.applyOrElse(MaterializeWorkflowDescriptorActor.scala:130)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:663)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:117)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:117)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:117)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	Suppressed: java.nio.file.NoSuchFileException: /tmp/640585481854205084.zip4511378926145376874/bar/foo.wdl
		at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
		at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
		at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
		at java.nio.file.Files.newByteChannel(Files.java:361)
		at java.nio.file.Files.newByteChannel(Files.java:407)
		at java.nio.file.Files.readAllBytes(Files.java:3152)
		at better.files.File.loadBytes(File.scala:163)
		at better.files.File.byteArray(File.scala:166)
		at better.files.File.contentAsString(File.scala:206)
		at wdl4s.WdlNamespace$.readFile(WdlNamespace.scala:525)
		at wdl4s.WdlNamespace$.fileResolver(WdlNamespace.scala:527)
		at wdl4s.WdlNamespace$.directoryResolver(WdlNamespace.scala:533)
		at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$validateNamespaceWithImports$1$$anonfun$17.apply(MaterializeWorkflowDescriptorActor.scala:361)
		at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$validateNamespaceWithImports$1$$anonfun$17.apply(MaterializeWorkflowDescriptorActor.scala:361)
		at wdl4s.WdlNamespace$$anonfun$16.apply(WdlNamespace.scala:191)
		at wdl4s.WdlNamespace$$anonfun$16.apply(WdlNamespace.scala:191)
		at scala.util.Try$.apply(Try.scala:192)
		at wdl4s.WdlNamespace$.wdl4s$WdlNamespace$$tryResolve$1(WdlNamespace.scala:191)
		... 37 common frames omitted

```

**Comment by cjllanwarne** [comment]
Confirmed broken. We should make sure to re-enable `missing_imports` in centaur as a regression test case
