### ISSUE TITLE
JES backend giving permission error during localization that seems incorrect.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1960]
- 0.24
- single workflow mode
- JES backend

When I run the workflow, I get a localization permission error, but when I try again from the command line, there is no issue.
From cromwell:
```
....snip....
java.lang.RuntimeException: Task 773d051e-2e93-4248-bca4-e40292e0e59d:generate_true_positives failed: error code 5. Message: 9: Failed to localize files: failed to copy the following files: "gs://firecloud-tcga-open-access/tutorial/reference/whole_exome_agilent_1.1_refseq_plus_3_boosters_plus_10bp_padding_minus_mito.Homo_sapiens_assembly19.targets.interval_list -> /mnt/local-disk/firecloud-tcga-open-access/tutorial/reference/whole_exome_agilent_1.1_refseq_plus_3_boosters_plus_10bp_padding_minus_mito.Homo_sapiens_assembly19.targets.interval_list (cp failed: gsutil -q -m cp gs://firecloud-tcga-open-access/tutorial/reference/whole_exome_agilent_1.1_refseq_plus_3_boosters_plus_10bp_padding_minus_mito.Homo_sapiens_assembly19.targets.interval_list /mnt/local-disk/firecloud-tcga-open-access/tutorial/reference/whole_exome_agilent_1.1_refseq_plus_3_boosters_plus_10bp_padding_minus_mito.Homo_sapiens_assembly19.targets.interval_list, command failed: AccessDeniedException: 403 Caller does not have storage.objects.list access to bucket firecloud-tcga-open-access.\nCommandException: 1 file/object could not be transferred.\n)"
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.handleExecutionFailure(JesAsyncBackendJobExecutionActor.scala:489)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.handleExecutionFailure(JesAsyncBackendJobExecutionActor.scala:61)
....snip....
```
  
BUT I would think this next operation would fail and it does not:
```
lichtens@lichtens-big:~/test_dl_oxoq/create_bs$ gsutil ls gs://firecloud-tcga-open-access/tutorial/reference/
gs://firecloud-tcga-open-access/tutorial/reference/CNV.hg19.bypos.111213.txt
gs://firecloud-tcga-open-access/tutorial/reference/Homo_sapiens_assembly19.dict
gs://firecloud-tcga-open-access/tutorial/reference/Homo_sapiens_assembly19.fasta
gs://firecloud-tcga-open-access/tutorial/reference/Homo_sapiens_assembly19.fasta.fai
```

and:  
```
lichtens@lichtens-big:~/test_dl_oxoq/create_bs$ gsutil ls gs://firecloud-tcga-open-access/
gs://firecloud-tcga-open-access/merged/
gs://firecloud-tcga-open-access/tcga/
gs://firecloud-tcga-open-access/tutorial/
gs://firecloud-tcga-open-access/workshop/
lichtens@lichtens-big:~/test_dl_oxoq/create_bs$ 
```

@kshakir

**Comment by katevoss** [comment]
@cjllanwarne do you think this was resolved by your improvements to JES transient errors?

**Comment by aednichols** [comment]
To accept this bug report, we would probably ask the user to try
```
gsutil -q -m cp gs://firecloud-tcga-open-access/tutorial/reference/whole_exome_agilent_1.1_refseq_plus_3_boosters_plus_10bp_padding_minus_mito.Homo_sapiens_assembly19.targets.interval_list ~/test_file
```
on their local machine to make sure permissions are workable and it's really Cromwell that is screwing up.

Unfortunately the user is no longer at Broad (hi Lee!) and I am not aware of a systemic problem in this area, so I will close the issue.
