### ISSUE TITLE
Rewrite error message for type coersion

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#1998]
- 0.25-dev

The issue was Array[File]? vs. Array [File?] in the parent workflow.

```
No coercion defined from '["/home/lichtens/test_onco_m2/cromwell-executions/Mutect2_Multi/8173195d-d409-481a-8510-4c7e0e2563a2/call-Mutect2/shard-0/Mutect2/30508148-e1ff-4445-a08d-7c9405372319/call-oncotate_m2_ob/execution/synthetic.challenge.set1.tumor.oncotated.vcf"]' of type 'class wdl4s.values.WdlArray$$anon$1' to WdlOptionalType.
java.lang.IllegalArgumentException: No coercion defined from '["/home/lichtens/test_onco_m2/cromwell-executions/Mutect2_Multi/8173195d-d409-481a-8510-4c7e0e2563a2/call-Mutect2/shard-0/Mutect2/30508148-e1ff-4445-a08d-7c9405372319/call-oncotate_m2_ob/execution/synthetic.challenge.set1.tumor.oncotated.vcf"]' of type 'class wdl4s.values.WdlArray$$anon$1' to WdlOptionalType.
        at wdl4s.types.WdlType$class.coerceRawValue(WdlType.scala:32)
        at wdl4s.types.WdlOptionalType.coerceRawValue(WdlOptionalType.scala:6)
        at wdl4s.Workflow$$anonfun$11$$anonfun$12.apply(Workflow.scala:186)
        at wdl4s.Workflow$$anonfun$11$$anonfun$12.apply(Workflow.scala:186)
        at scala.util.Success.flatMap(Try.scala:231)
        at wdl4s.Workflow$$anonfun$11.apply(Workflow.scala:186)
        at wdl4s.Workflow$$anonfun$11.apply(Workflow.scala:180)
        at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
        at scala.collection.immutable.List.foldLeft(List.scala:84)
        at wdl4s.Workflow.evaluateOutputs(Workflow.scala:180)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.handleWorkflowSuccessful(WorkflowExecutionActor.scala:261)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.handleExecutionSuccess(WorkflowExecutionActor.scala:325)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$handleCallSuccessful(WorkflowExecutionActor.scala:308)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$3.applyOrElse(WorkflowExecutionActor.scala:96)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$3.applyOrElse(WorkflowExecutionActor.scala:81)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.actor.FSM$class.processEvent(FSM.scala:663)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:32)
        at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:32)
        at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:32)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cjllanwarne** [comment]
+1.

I think this error message should read: `No coercion defined from Array[File]? to Array[File?]`. No need to print out the value of the entire array to the logs.

@katevoss:
Impact: Low (a few hours of frustrating debugging the first time a user sees it)
Probability: Medium => High (if people start using conditionals more, this is going to show up for more and more people)
Fix: Easy (just change the error message)
