### ISSUE TITLE
Transient failures uploading auth file

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#2009]
Appears to be a good case for retry love:

```
java.io.IOException: Failed to upload authentication file
        at cromwell.backend.impl.jes.JesInitializationActor$$anonfun$cromwell$backend$impl$jes$JesInitializati\
onActor$$writeAuthenticationFile$1.apply(JesInitializationActor.scala:61)
        at cromwell.backend.impl.jes.JesInitializationActor$$anonfun$cromwell$backend$impl$jes$JesInitializati\
onActor$$writeAuthenticationFile$1.apply(JesInitializationActor.scala:58)
        at scala.Option.foreach(Option.scala:257)
        at cromwell.backend.impl.jes.JesInitializationActor.cromwell$backend$impl$jes$JesInitializationActor$$\
writeAuthenticationFile(JesInitializationActor.scala:58)
        at cromwell.backend.impl.jes.JesInitializationActor$$anonfun$beforeAll$1.apply(JesInitializationActor.\
scala:52)
        at cromwell.backend.impl.jes.JesInitializationActor$$anonfun$beforeAll$1.apply(JesInitializationActor.\
scala:51)
        at scala.util.Try$.apply(Try.scala:192)
        at cromwell.backend.impl.jes.JesInitializationActor.beforeAll(JesInitializationActor.scala:51)
        at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$initSequence$1$$anonfun$apply$1.apply(\
BackendWorkflowInitializationActor.scala:156)
        at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$initSequence$1$$anonfun$apply$1.apply(\
BackendWorkflowInitializationActor.scala:155)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91\
)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.SocketException: Socket is closed
        at sun.security.ssl.SSLSocketImpl.getInputStream(SSLSocketImpl.java:2218)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:642)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.cloud.storage.spi.DefaultStorageRpc.open(DefaultStorageRpc.java:563)
        at com.google.cloud.storage.BlobWriteChannel.<init>(BlobWriteChannel.java:36)
        at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:476)
        at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:471)
        at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:70)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newWriteChannel(CloudStorageFil\
eSystemProvider.java:327)
        at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.newByteChannel(CloudStorageFile\
SystemProvider.java:220)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at better.files.File.newOutputStream(File.scala:336)
        at better.files.File.outputStream(File.scala:339)
        at better.files.File.writeBytes(File.scala:264)
        at cromwell.core.path.BetterFileMethods$class.writeBytes(BetterFileMethods.scala:164)
        at cromwell.filesystems.gcs.GcsPath.writeBytes(GcsPathBuilder.scala:116)
        at cromwell.backend.impl.jes.io.package$PathEnhanced$.writeAsJson$extension(package.scala:11)
        at cromwell.backend.impl.jes.JesInitializationActor$$anonfun$cromwell$backend$impl$jes$JesInitializati\
onActor$$writeAuthenticationFile$1.apply(JesInitializationActor.scala:62)
        ... 24 more```

**Comment by mcovarr** [comment]
Similar but not exactly the same as #1924, though I suspect the suggested retry love that fixes one will fix both.

**Comment by cjllanwarne** [comment]
@geoffjentry @mcovarr are those different from our generic "retry IO operations" ticket?

**Comment by geoffjentry** [comment]
I don't know, that's why I asked that question on slack a couple of days ago ;)

**Comment by Horneth** [comment]
I think those should be covered by the retry IO ticket

**Comment by cjllanwarne** [comment]
Fixed by the IO actor in C26.
