### ISSUE TITLE
Referencing a non-existent scatter variable leaves workflow in running state

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2020]
Minimal example:

```
workflow wf {
  scatter (example in non_existent_scatter_variable) {}
}
```

Produces similar output on firecloud (489f66b), but tested also on develop (5588e73):
```java
2017-02-22 13:49:48,448 cromwell-system-akka.dispatchers.api-dispatcher-23 INFO  - Workflow 56b1f228-8054-4947-8dc3-372363c5e94b submitted.
2017-02-22 13:49:57,791 cromwell-system-akka.dispatchers.engine-dispatcher-14 INFO  - 1 new workflows fetched
2017-02-22 13:49:57,792 cromwell-system-akka.dispatchers.engine-dispatcher-14 INFO  - WorkflowManagerActor Starting workflow UUID(56b1f228-8054-4947-8dc3-372363c5e94b)
2017-02-22 13:49:57,798 cromwell-system-akka.dispatchers.engine-dispatcher-14 INFO  - WorkflowManagerActor Successfully started WorkflowActor-56b1f228-8054-4947-8dc3-372363c5e94b
2017-02-22 13:49:57,799 cromwell-system-akka.dispatchers.engine-dispatcher-14 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2017-02-22 13:49:58,220 cromwell-system-akka.dispatchers.engine-dispatcher-14 INFO  - MaterializeWorkflowDescriptorActor [UUID(56b1f228)]: Call-to-Backend assignments: 
2017-02-22 13:49:58,373 cromwell-system-akka.dispatchers.engine-dispatcher-7 ERROR - Unexpected engine failure
java.lang.RuntimeException: Unexpected engine failure
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableScopes(WorkflowExecutionActor.scala:384)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$2.applyOrElse(WorkflowExecutionActor.scala:77)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$2.applyOrElse(WorkflowExecutionActor.scala:75)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:663)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:32)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:32)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:32)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: lenthall.exception.AggregatedException: :
Variable 'non_existent_scatter_variable' not found
	at lenthall.util.TryUtil$.sequenceIterable(TryUtil.scala:26)
	at lenthall.util.TryUtil$.sequence(TryUtil.scala:33)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableScopes(WorkflowExecutionActor.scala:373)
	... 20 common frames omitted
	Suppressed: wdl4s.exception.VariableNotFoundException$$anon$1: Variable 'non_existent_scatter_variable' not found
		at wdl4s.exception.VariableNotFoundException$.apply(LookupException.scala:17)
		at wdl4s.Scope$$anonfun$6.apply(Scope.scala:268)
		at wdl4s.Scope$$anonfun$6.apply(Scope.scala:268)
		at scala.Option.getOrElse(Option.scala:121)
		at wdl4s.Scope$class.lookup$1(Scope.scala:267)
		at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:274)
		at wdl4s.Scope$$anonfun$lookupFunction$1.apply(Scope.scala:274)
		at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
		at wdl4s.expression.ValueEvaluator$$anonfun$evaluate$1.apply(ValueEvaluator.scala:45)
		at scala.util.Try$.apply(Try.scala:192)
		at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:45)
		at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:85)
		at wdl4s.WdlExpression.evaluate(WdlExpression.scala:161)
		at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$processRunnableScatter(WorkflowExecutionActor.scala:509)
		at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$20.apply(WorkflowExecutionActor.scala:361)
		at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$20.apply(WorkflowExecutionActor.scala:357)
		at scala.collection.immutable.List.map(List.scala:273)
		at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableScopes(WorkflowExecutionActor.scala:357)
		... 20 common frames omitted
```

Workflow metadata is left in `Running`:

```json
{
  "workflowName": "wf",
  "submittedFiles": {
    "inputs": "{}",
    "workflow": "workflow wf {\n  scatter (example in non_existent_scatter_variable) {}\n}\n",
    "options": "{\n\n}"
  },
  "calls": {},
  "outputs": {},
  "id": "56b1f228-8054-4947-8dc3-372363c5e94b",
  "inputs": {},
  "submission": "2017-02-22T13:49:48.451-05:00",
  "status": "Running",
  "start": "2017-02-22T13:49:57.839-05:00"
}
```

Workaround: Fix the missing scatter variable in the wdl.

**Comment by katevoss** [comment]
This sounds like a low priority bug as there is a clear workaround.

**Comment by Horneth** [comment]
Hmm that sounds a little bit worse than low to me actually because this causes the workflow to be stuc, and the user doesn't have information about why.

**Comment by kshakir** [comment]
#2030 fixes this specific issue. There remains a greater tech debt of actor supervision, where unexpected errors like this shouldn't leave the workflows in a running state.
