### ISSUE TITLE
Cromwell gave mysterious error during workflow

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2215]
- cromwell 26
- JES backend
- call caching on local mysql instance
- server mode

Ran a bunch of the initial jobs, but once it really started fan out (thousands of jobs), I got this error message.  Trying to replicate now, but not sure if I can.  Might be transient. 

Regardless, error message is not particularly helpful.  Any ideas?  

```
cromwell.core.CromwellFatalException: com.google.cloud.storage.StorageException: 410 Gone
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}

        at cromwell.core.CromwellFatalException$.apply(core.scala:17)
        at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:37)
        at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:36)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

Metadata (``http://104.154.208.235:8000/api/workflows/v2/c43e7d14-36a1-4b0b-95bf-cc381db48b5b/metadata?expandSubWorkflows=false``):

(attached)
[cromwell_jes_error_April272017.txt](https://github.com/broadinstitute/cromwell/files/962915/cromwell_jes_error_April272017.txt)

**Comment by LeeTL1220** [comment]
(As an aside, I have not been deleting any files from google buckets)

**Comment by Horneth** [comment]
Yes we saw that too, it was not being retried but is from https://github.com/broadinstitute/cromwell/commit/d1c8ea0c868c87dee8c7ed4eb09c33f78ebf137b

**Comment by LeeTL1220** [comment]
@Horneth So is this fixed?    This is a blocker for me.  I'll happily use a version from ``develop``

**Comment by ruchim** [comment]
@LeeTL1220 Do you still encounter this error?
