### ISSUE TITLE
Caused by: java.sql.SQLException: Can't get stat of './cromwell/DATABASECHANGELOGLOCK.TRG'

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2222]
When I use cromwell with mysql database I often get the following error:
```
Caused by: java.sql.SQLException: Can't get stat of './cromwell/DATABASECHANGELOGLOCK.TRG' (Errcode: 13 - Permission denied)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83)
```

What is interesting is that ./cromwell does not exist at all. In my case I use official latest docker mysql container for mysql (where I manually create cromwell database)

**Comment by antonkulaga** [comment]
It happened once but I cannot reproduce it now, will close until it reoccur
