### ISSUE TITLE
Call caching isn't working in V25 with docker hashes

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/cromwell#2229]
When using a docker hash in V25 in order to get call caching I get the following error: 

```
2017-05-01 18:06:39 [cromwell-system-akka.actor.default-dispatcher-3670] ERROR c.e.w.l.e.EngineJobExecutionActor - Failed copying cache results for job GenotypeGVCFsComparison.IndexVCF:-1:1, invalidating cache entry.
java.io.IOException: Failed to copy gs://dsde-palantir/SnapshotExperiment2015/CEUTrio/gvcfs/NA12878.d691bf66-37af-4375-9c09-6a6607f322e8.g.vcf.gz to gs://broad-dsde-methods/cromwell-execution-25/GenotypeGVCFsComparison/c5bc4f99-d969-49ca-9e2e-a3dac7a4b12a/call-IndexVCF/dsde-palantir/SnapshotExperiment2015/CEUTrio/gvcfs/NA12878.d691bf66-37af-4375-9c09-6a6607f322e8.g.vcf.gz
	at cromwell.core.path.PathCopier$$anonfun$copy$2.applyOrElse(PathCopier.scala:49)
	at cromwell.core.path.PathCopier$$anonfun$copy$2.applyOrElse(PathCopier.scala:48)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure.recoverWith(Try.scala:203)
	at cromwell.core.path.PathCopier$.copy(PathCopier.scala:48)
	at cromwell.backend.standard.StandardCacheHitCopyingActor.duplicate(StandardCacheHitCopyingActor.scala:36)
	at cromwell.backend.callcaching.CacheHitDuplicating$$anonfun$copySimpletons$1.apply(CacheHitDuplicating.scala:66)
	at cromwell.backend.callcaching.CacheHitDuplicating$$anonfun$copySimpletons$1.apply(CacheHitDuplicating.scala:62)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at cromwell.backend.callcaching.CacheHitDuplicating$class.copySimpletons(CacheHitDuplicating.scala:62)
	at cromwell.backend.callcaching.CacheHitDuplicating$class.copyCachedOutputs(CacheHitDuplicating.scala:92)
	at cromwell.backend.standard.StandardCacheHitCopyingActor.copyCachedOutputs(StandardCacheHitCopyingActor.scala:33)
	at cromwell.backend.BackendCacheHitCopyingActor$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$1.apply(BackendCacheHitCopyingActor.scala:22)
	at cromwell.backend.BackendCacheHitCopyingActor$$anonfun$receive$1$$anonfun$applyOrElse$2$$anonfun$apply$1.apply(BackendCacheHitCopyingActor.scala:22)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.storage.spi.DefaultStorageRpc.rewrite(DefaultStorageRpc.java:590)
	at com.google.cloud.storage.spi.DefaultStorageRpc.openRewrite(DefaultStorageRpc.java:578)
	at com.google.cloud.storage.StorageImpl$15.call(StorageImpl.java:419)
	at com.google.cloud.storage.StorageImpl$15.call(StorageImpl.java:416)
	at com.google.cloud.RetryHelper.doRetry(RetryHelper.java:179)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:244)
	at com.google.cloud.storage.StorageImpl.copy(StorageImpl.java:416)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.copy(CloudStorageFileSystemProvider.java:493)
	at java.nio.file.Files.copy(Files.java:1274)
	at better.files.File.copyTo(File.scala:646)
	at cromwell.core.path.BetterFileMethods$class.copyTo(BetterFileMethods.scala:415)
	at cromwell.filesystems.gcs.GcsPath.copyTo(GcsPathBuilder.scala:116)
	at cromwell.core.path.PathCopier$$anonfun$copy$1.apply$mcV$sp(PathCopier.scala:45)
	at cromwell.core.path.PathCopier$$anonfun$copy$1.apply(PathCopier.scala:44)
	at cromwell.core.path.PathCopier$$anonfun$copy$1.apply(PathCopier.scala:44)
	at scala.util.Try$.apply(Try.scala:192)
	at cromwell.core.path.PathCopier$.copy(PathCopier.scala:44)
	... 24 common frames omitted
2017-05-01 18:06:39 [cromwell-system-akka.actor.default-dispatcher-1373] INFO  c.e.w.l.e.EngineJobExecutionActor - Could not find another cache hit, falling back to running job: GenotypeGVCFsComparison.IndexVCF:-1:1
```

It seems that the file can't be copied so it invalidates the cache. The wdl task is as follows:

```
task IndexVCF {
  File combined_gvcf
  Int disk_size

  command {
    /usr/gitc/tabix ${combined_gvcf}
  }
  runtime {
    docker: "broadinstitute/genomes-in-the-cloud@sha256:d7aa37fc8351074a2d6fb949932d3283cdcefdc8e53729dcf7202bee16ab660a"
    memory: "13 GB"
    cpu: "1"
    disks: "local-disk " + disk_size + " HDD"
  }
  output {
    File gvcf = "${combined_gvcf}"
    File gvcf_index = "${combined_gvcf}.tbi"
  }
}
```

I'm going to try running this same task in V24 without the docker hash (to see if it's something to do with the file) and in V26 to see if the issue is resolved there.

**Comment by meganshand** [comment]
It turns out the original task above didn't work when `combined_gvcf="gs://dsde-palantir/SnapshotExperiment2015/CEUTrio/gvcfs/NA12878.d691bf66-37af-4375-9c09-6a6607f322e8.g.vcf.gz"` even in V24.

I updated the task to:

```
task IndexVCF {
  File combined_gvcf
  Int disk_size

  command {
    /usr/gitc/tabix ${combined_gvcf}
  }
  runtime {
    docker: "broadinstitute/genomes-in-the-cloud@sha256:d7aa37fc8351074a2d6fb949932d3283cdcefdc8e53729dcf7202bee16ab660a"
    memory: "13 GB"
    cpu: "1"
    disks: "local-disk " + disk_size + " HDD"
  }
  output {
    File gvcf_index = "${combined_gvcf}.tbi"
  }
}
```

The thing is I still don't know why the first task in the comment above doesn't work. It would be nice to have a better error message.

**Comment by geoffjentry** [comment]
@meganshand if this is still happening on a modern cromwell, please open a new ticket w/ updated info
