### ISSUE TITLE
JES fails with mysterious error 

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#2270]
-  cromwell-27-aab4763-SNAP.jar
- JES backend 
- localhost MySQL with call caching enabled.
- server mode

This error is above my ability to debug.  Cromwell failed after that.  It did not exit, but was no longer responsive.

```[ERROR] [05/12/2017 21:47:03.777] [cromwell-system-akka.dispatchers.engine-dispatcher-7] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor] WorkflowManagerActor Workflow 6c383c35-d791-4971-aecd-0723726c8a7b failed (during ExecutingWorkflowState): JesAsyncBackendJobExecutionActor failed and didn't catch its exception.
java.lang.RuntimeException: JesAsyncBackendJobExecutionActor failed and didn't catch its exception.
        at cromwell.backend.standard.StandardSyncExecutionActor$$anonfun$jobFailingDecider$1.applyOrElse(StandardSyncExecutionActor.scala:147)
        at cromwell.backend.standard.StandardSyncExecutionActor$$anonfun$jobFailingDecider$1.applyOrElse(StandardSyncExecutionActor.scala:144)
        at akka.actor.SupervisorStrategy.handleFailure(FaultHandling.scala:296)
        at akka.actor.dungeon.FaultHandling$class.handleFailure(FaultHandling.scala:263)
        at akka.actor.ActorCell.handleFailure(ActorCell.scala:374)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:459)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.RuntimeException: Google credentials are invalid: 500 Internal Server Error
{
  "error" : "internal_failure"
}
        at cromwell.filesystems.gcs.auth.GoogleAuthMode$class.validate(GoogleAuthMode.scala:66)
        at cromwell.filesystems.gcs.auth.GoogleAuthMode$class.validateCredential(GoogleAuthMode.scala:62)
        at cromwell.filesystems.gcs.auth.RefreshTokenMode.validateCredential(GoogleAuthMode.scala:127)
        at cromwell.filesystems.gcs.auth.RefreshTokenMode.credential(GoogleAuthMode.scala:147)
        at cromwell.filesystems.gcs.GcsPathBuilder.<init>(GcsPathBuilder.scala:57)
        at cromwell.filesystems.gcs.GcsPathBuilderFactory.withOptions(GcsPathBuilderFactory.scala:37)
        at cromwell.backend.impl.jes.JesWorkflowPaths.<init>(JesWorkflowPaths.scala:25)
        at cromwell.backend.impl.jes.JesWorkflowPaths.copy(JesWorkflowPaths.scala:19)
        at cromwell.backend.impl.jes.JesWorkflowPaths.withDescriptor(JesWorkflowPaths.scala:54)
        at cromwell.backend.io.WorkflowPaths$class.toJobPaths(WorkflowPaths.scala:51)
        at cromwell.backend.impl.jes.JesWorkflowPaths.toJobPaths(JesWorkflowPaths.scala:19)
        at cromwell.backend.io.WorkflowPaths$class.toJobPaths(WorkflowPaths.scala:36)
        at cromwell.backend.impl.jes.JesWorkflowPaths.toJobPaths(JesWorkflowPaths.scala:19)
        at cromwell.backend.standard.StandardCachingActorHelper$class.jobPaths(StandardCachingActorHelper.scala:64)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.jobPaths$lzycompute(JesAsyncBackendJobExecutionActor.scala:67)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.jobPaths(JesAsyncBackendJobExecutionActor.scala:67)
        at cromwell.backend.standard.StandardCachingActorHelper$class.startMetadataKeyValues(StandardCachingActorHelper.scala:76)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.startMetadataKeyValues$lzycompute(JesAsyncBackendJobExecutionActor.scala:339)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.startMetadataKeyValues(JesAsyncBackendJobExecutionActor.scala:339)
        at cromwell.backend.standard.StandardAsyncExecutionActor$class.executeOrRecover(StandardAsyncExecutionActor.scala:516)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.executeOrRecover(JesAsyncBackendJobExecutionActor.scala:67)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover$1.apply(AsyncBackendJobExecutionActor.scala:54)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover$1.apply(AsyncBackendJobExecutionActor.scala:54)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:36)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$class.withRetry(AsyncBackendJobExecutionActor.scala:50)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$class.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:54)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:77)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
        at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.aroundReceive(JesAsyncBackendJobExecutionActor.scala:67)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        ... 5 more
Caused by: com.google.api.client.http.HttpResponseException: 500 Internal Server Error
{
  "error" : "internal_failure"
}
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1070)
        at com.google.auth.oauth2.UserCredentials.refreshAccessToken(UserCredentials.java:207)
        at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:149)
        at cromwell.filesystems.gcs.auth.GoogleAuthMode$$anonfun$validateCredential$1.apply$mcV$sp(GoogleAuthMode.scala:62)
        at cromwell.filesystems.gcs.auth.GoogleAuthMode$$anonfun$validateCredential$1.apply(GoogleAuthMode.scala:62)
        at cromwell.filesystems.gcs.auth.GoogleAuthMode$$anonfun$validateCredential$1.apply(GoogleAuthMode.scala:62)
        at scala.util.Try$.apply(Try.scala:192)
        at cromwell.filesystems.gcs.auth.GoogleAuthMode$class.validate(GoogleAuthMode.scala:65)
        ... 46 more

[INFO] [05/12/2017 21:47:03.777] [cromwell-system-akka.dispatchers.engine-dispatcher-7] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor] WorkflowManagerActor WorkflowActor-6c383c35-d791-4971-aecd-0723726c8a7b is in a terminal state: WorkflowFailedState
^C[INFO] [05/15/2017 14:06:33.456] [shutdownHook1] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor] WorkflowManagerActor: Received shutdown signal.
[INFO] [05/15/2017 14:06:33.457] [cromwell-system-akka.dispatchers.engine-dispatcher-91] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor] WorkflowManagerActor All workflows finished
```

**Comment by Horneth** [comment]
Probably linked to https://github.com/broadinstitute/cromwell/issues/1886
Retrying credentials validation here https://github.com/broadinstitute/cromwell/blob/develop/filesystems/gcs/src/main/scala/cromwell/filesystems/gcs/auth/GoogleAuthMode.scala#L66 should fix all those issues

**Comment by geoffjentry** [comment]
@LeeTL1220 please open a new ticket if this is happening in a modern cromwell
