### ISSUE TITLE
running cromwell from docker

### ISSUE THREAD

**Issue by antonkulaga** [broadinstitute/cromwell#2284]
I am constantly having issues when I run docker-compose of cromwell. Even though I do not have docker-user in my config file, I still get:
```
cromwell_1  | [ERROR] [05/20/2017 12:57:46.015] [cromwell-system-akka.dispatchers.engine-dispatcher-22] [akka://cromwell-system/user/cromwell-service/WorkflowManagerActor/WorkflowActor-f7fdd305-d137-4128-bf68-7c39fd6c834b/WorkflowInitializationActor-f7fdd305-d137-4128-bf68-7c39fd6c834b/Local] Error parsing generated wdl:
cromwell_1  | task submit {
cromwell_1  | 
cromwell_1  | String job_id
cromwell_1  | String job_name
cromwell_1  | String cwd
cromwell_1  | String out
cromwell_1  | String err
cromwell_1  | String script
cromwell_1  | String? docker Int? max_runtime = 2
cromwell_1  | command {
cromwell_1  | /bin/bash ${script}
cromwell_1  | }
cromwell_1  | }
cromwell_1  | 
cromwell_1  | 
cromwell_1  | task submit_docker {
cromwell_1  | 
cromwell_1  | String job_id
cromwell_1  | String job_name
cromwell_1  | String cwd
cromwell_1  | String out
cromwell_1  | String err
cromwell_1  | String script
cromwell_1  | 
cromwell_1  | String docker_cwd
cromwell_1  | String? docker Int? max_runtime = 2
cromwell_1  | command {
cromwell_1  | 
cromwell_1  |         docker run \
cromwell_1  |           --rm -i \
cromwell_1  |           ${"--user " + docker_user} \
cromwell_1  |           --entrypoint /bin/bash \
cromwell_1  |           -v ${cwd}:${docker_cwd} \
cromwell_1  |           ${docker} ${script}
cromwell_1  |         
cromwell_1  | }
cromwell_1  | }
cromwell_1  | java.lang.RuntimeException: Error parsing generated wdl:
cromwell_1  | task submit {
cromwell_1  | 
cromwell_1  | String job_id
cromwell_1  | String job_name
cromwell_1  | String cwd
cromwell_1  | String out
cromwell_1  | String err
cromwell_1  | String script
cromwell_1  | String? docker Int? max_runtime = 2
cromwell_1  | command {
cromwell_1  | /bin/bash ${script}
cromwell_1  | }
cromwell_1  | }
cromwell_1  | 
cromwell_1  | 
cromwell_1  | task submit_docker {
cromwell_1  | 
cromwell_1  | String job_id
cromwell_1  | String job_name
cromwell_1  | String cwd
cromwell_1  | String out
cromwell_1  | String err
cromwell_1  | String script
cromwell_1  | 
cromwell_1  | String docker_cwd
cromwell_1  | String? docker Int? max_runtime = 2
cromwell_1  | command {
cromwell_1  | 
cromwell_1  |         docker run \
cromwell_1  |           --rm -i \
cromwell_1  |           ${"--user " + docker_user} \
cromwell_1  |           --entrypoint /bin/bash \
cromwell_1  |           -v ${cwd}:${docker_cwd} \
cromwell_1  |           ${docker} ${script}
cromwell_1  |         
cromwell_1  | }
cromwell_1  | }
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:50)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace$lzycompute(ConfigInitializationActor.scala:37)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.configWdlNamespace(ConfigInitializationActor.scala:37)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations$lzycompute(ConfigInitializationActor.scala:40)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.declarationValidations(ConfigInitializationActor.scala:39)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder$lzycompute(ConfigInitializationActor.scala:49)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigInitializationActor.runtimeAttributesBuilder(ConfigInitializationActor.scala:48)
cromwell_1  | 	at cromwell.backend.standard.StandardInitializationActor.coerceDefaultRuntimeAttributes(StandardInitializationActor.scala:78)
cromwell_1  | 	at cromwell.backend.BackendWorkflowInitializationActor$class.validateRuntimeAttributes(BackendWorkflowInitializationActor.scala:121)
cromwell_1  | 	at cromwell.backend.BackendWorkflowInitializationActor$class.initSequence(BackendWorkflowInitializationActor.scala:154)
cromwell_1  | 	at cromwell.backend.standard.StandardInitializationActor.initSequence(StandardInitializationActor.scala:42)
cromwell_1  | 	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(BackendWorkflowInitializationActor.scala:146)
cromwell_1  | 	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1$$anonfun$applyOrElse$2.apply(BackendWorkflowInitializationActor.scala:146)
cromwell_1  | 	at cromwell.backend.BackendLifecycleActor$class.performActionThenRespond(BackendLifecycleActor.scala:44)
cromwell_1  | 	at cromwell.backend.standard.StandardInitializationActor.performActionThenRespond(StandardInitializationActor.scala:42)
cromwell_1  | 	at cromwell.backend.BackendWorkflowInitializationActor$$anonfun$receive$1.applyOrElse(BackendWorkflowInitializationActor.scala:146)
cromwell_1  | 	at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
cromwell_1  | 	at cromwell.backend.standard.StandardInitializationActor.aroundReceive(StandardInitializationActor.scala:42)
cromwell_1  | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
cromwell_1  | 	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
cromwell_1  | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
cromwell_1  | 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
cromwell_1  | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
cromwell_1  | 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
cromwell_1  | 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
cromwell_1  | 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
cromwell_1  | 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
cromwell_1  | Caused by: wdl4s.parser.WdlParser$SyntaxError: ERROR: Variable docker_user does not reference any declaration in the task (line 31, col 25):
cromwell_1  | 
cromwell_1  |           ${"--user " + docker_user} \
cromwell_1  |                         ^
cromwell_1  | 
cromwell_1  | Task defined here (line 16, col 6):
cromwell_1  | 
cromwell_1  | task submit_docker {
cromwell_1  |      ^
cromwell_1  |      
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$42$$anonfun$apply$19$$anonfun$apply$22.apply(WdlNamespace.scala:405)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$42$$anonfun$apply$19$$anonfun$apply$22.apply(WdlNamespace.scala:403)
cromwell_1  | 	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:683)
cromwell_1  | 	at scala.collection.immutable.List.foreach(List.scala:381)
cromwell_1  | 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:682)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$42$$anonfun$apply$19.apply(WdlNamespace.scala:403)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$42$$anonfun$apply$19.apply(WdlNamespace.scala:402)
cromwell_1  | 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
cromwell_1  | 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
cromwell_1  | 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
cromwell_1  | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
cromwell_1  | 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
cromwell_1  | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
cromwell_1  | 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
cromwell_1  | 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$42.apply(WdlNamespace.scala:402)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$42.apply(WdlNamespace.scala:401)
cromwell_1  | 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
cromwell_1  | 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
cromwell_1  | 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
cromwell_1  | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
cromwell_1  | 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
cromwell_1  | 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
cromwell_1  | 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
cromwell_1  | 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
cromwell_1  | 	at wdl4s.WdlNamespace$.apply(WdlNamespace.scala:401)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$wdl4s$WdlNamespace$$load$1.apply(WdlNamespace.scala:177)
cromwell_1  | 	at wdl4s.WdlNamespace$$anonfun$wdl4s$WdlNamespace$$load$1.apply(WdlNamespace.scala:177)
cromwell_1  | 	at scala.util.Try$.apply(Try.scala:192)
cromwell_1  | 	at wdl4s.WdlNamespace$.wdl4s$WdlNamespace$$load(WdlNamespace.scala:176)
cromwell_1  | 	at wdl4s.WdlNamespace$.loadUsingSource(WdlNamespace.scala:173)
cromwell_1  | 	at cromwell.backend.impl.sfs.config.ConfigWdlNamespace.<init>(ConfigWdlNamespace.scala:48)
cromwell_1  | 	... 26 more

```

**Comment by antonkulaga** [comment]
In other PC I got another error " docker: command not found". Probably it is because it tries to run docker inside cromwell docker container.

**Comment by antonkulaga** [comment]
@katevoss why is it marked "PO Cleanup"? It still does not work. If you try to run https://github.com/broadinstitute/cromwell/tree/29_hotfix/scripts/docker-compose-mysql and run there any workflow with runtime: docker, it will fail

**Comment by katevoss** [comment]
@antonkulaga I am reviewing the backlog systematically over the next few months so I am using the PO Cleanup label to keep track of Github issues that I am planning to review next or have already reviewed. It's not a reflection of it being fixed or scheduled, it's just for my tracking purposes. 

I haven't reviewed this issue yet, good to know that it is still not functioning as intended. 

@geoffjentry Is there a workaround to using Docker-Compose?
