### ISSUE TITLE
Handle 'insufficient data written' errors from the JES API Query Manager

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#2535]
FC user have seen their job fail with this error message: https://gatkforums.broadinstitute.org/firecloud/discussion/comment/41300

Could be transient in which case retrying it could be the way to go

**Comment by ruchim** [comment]
```Caused by: java.io.IOException: insufficient data written
#011at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
#011at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
#011at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
#011at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
#011at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
#011at akka.dispatch.Mailbox.run(Mailbox.scala:224)
#011at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
#011at akka.actor.ActorCell.invoke(ActorCell.scala:494)
#011at akka.actor.ActorCell.autoReceiveMessage(ActorCell.scala:511)
#011at akka.actor.ActorCell.receivedTerminated(ActorCell.scala:374)
#011at akka.actor.dungeon.DeathWatch$class.receivedTerminated(DeathWatch.scala:46)
#011at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
#011at cromwell.backend.impl.jes.statuspolling.JesApiQueryManager.aroundReceive(JesApiQueryManager.scala:26)
#011at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
#011at cromwell.backend.impl.jes.statuspolling.JesApiQueryManager$$anonfun$receive$1.applyOrElse(JesApiQueryManager.scala:51)
#011at cromwell.backend.impl.jes.statuspolling.JesApiQueryManager.cromwell$backend$impl$jes$statuspolling$JesApiQueryManager$$handleTerminated(JesApiQueryManager.scala:101)
#011at scala.collection.immutable.List.foreach(List.scala:381)
#011at cromwell.backend.impl.jes.statuspolling.JesApiQueryManager$$anonfun$cromwell$backend$impl$jes$statuspolling$JesApiQueryManager$$handleTerminated$1.apply(JesApiQueryManager.scala:101)
#011at cromwell.backend.impl.jes.statuspolling.JesApiQueryManager$$anonfun$cromwell$backend$impl$jes$statuspolling$JesApiQueryManager$$handleTerminated$1.apply(JesApiQueryManager.scala:103)
cromwell.backend.impl.jes.statuspolling.JesApiQueryManager$JesApiException: Unable to complete JES Api Request
2017-08-10 08:29:38,408 cromwell-system-akka.dispatchers.engine-dispatcher-64 ERROR - WorkflowManagerActor Workflow e3f4d391-a0bc-480f-9203-d0ef4ee5b876 failed (during ExecutingWorkflowState): Unable to complete JES Api Request
2017-08-10 08:29:37,713 cromwell-system-akka.dispatchers.io-dispatcher-38 INFO  - $e [UUID(fb9254a8)]: Copying workflow logs from /cromwell-workflow-logs/workflow.fb9254a8-00ec-48bc-b8c8-2f0e5e74fa81.log to gs://fc-35446f22-ea37-483a-bd6c-5e9fc56851ff/9ef84046-7047-423b-88e8-bb138181f5a8/workflow.logs/workflow.fb9254a8-00ec-48bc-b8c8-2f0e5e74fa81.log
2017-08-10 08:29:37,713 cromwell-system-akka.dispatchers.engine-dispatcher-6 INFO  - WorkflowManagerActor WorkflowActor-fb9254a8-00ec-48bc-b8c8-2f0e5e74fa81 is in a terminal state: WorkflowFailedState```

**Comment by ruchim** [comment]
Different stack trace but same exception:

```
Caused by: java.io.IOException: insufficient data written
    at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.close(HttpURLConnection.java:3540)
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:81)
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
    at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:241)
    at cromwell.backend.impl.jes.statuspolling.JesPollingActor.runBatch(JesPollingActor.scala:63)
    at cromwell.backend.impl.jes.statuspolling.JesPollingActor.cromwell$backend$impl$jes$statuspolling$JesPollingActor$$handleBatch(JesPollingActor.scala:57)
    at cromwell.backend.impl.jes.statuspolling.JesPollingActor$$anonfun$receive$1.applyOrElse(JesPollingActor.scala:36)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:496)
    at cromwell.backend.impl.jes.statuspolling.JesPollingActor.aroundReceive(JesPollingActor.scala:22)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
```
