### ISSUE TITLE
503 StorageException failed a workflow, possibly without retry

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2576]
A 503 StorageException seems to have failed one of the centaur JES jobs, and hence the workflow. Via the [cromwell.log](https://console.cloud.google.com/storage/browser/cloud-cromwell-dev/cromwell_execution/travis/centaur_workflow/0310fa51-e985-4c54-8cdb-5058155f452e/call-centaur/cromwell_root/logs/).

```java
2017-08-25 05:43:25,399 cromwell-system-akka.dispatchers.engine-dispatcher-51 ERROR - WorkflowManagerActor Workflow dabddbe7-a385-4df4-be97-c1ef7b884823 failed (during ExecutingWorkflowState): Could not evaluate composeEngineFunctions.y = read_int(stderr()) + x + read_string(blah)
java.lang.RuntimeException: Could not evaluate composeEngineFunctions.y = read_int(stderr()) + x + read_string(blah)
	at wdl4s.wdl.WdlTask$$anonfun$4.applyOrElse(WdlTask.scala:190)
	at wdl4s.wdl.WdlTask$$anonfun$4.applyOrElse(WdlTask.scala:189)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recoverWith(Try.scala:232)
	at wdl4s.wdl.WdlTask.$anonfun$evaluateOutputs$2(WdlTask.scala:189)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at wdl4s.wdl.WdlTask.evaluateOutputs(WdlTask.scala:182)
	at cromwell.backend.wdl.OutputEvaluator$.evaluateOutputs(OutputEvaluator.scala:15)
	at cromwell.backend.standard.StandardAsyncExecutionActor.evaluateOutputs(StandardAsyncExecutionActor.scala:406)
	at cromwell.backend.standard.StandardAsyncExecutionActor.evaluateOutputs$(StandardAsyncExecutionActor.scala:405)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.evaluateOutputs(JesAsyncBackendJobExecutionActor.scala:65)
	at cromwell.backend.standard.StandardAsyncExecutionActor.handleExecutionSuccess(StandardAsyncExecutionActor.scala:458)
	at cromwell.backend.standard.StandardAsyncExecutionActor.handleExecutionSuccess$(StandardAsyncExecutionActor.scala:455)
	at cromwell.backend.impl.jes.JesAsyncBackendJobExecutionActor.handleExecutionSuccess(JesAsyncBackendJobExecutionActor.scala:65)
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionResult$3(StandardAsyncExecutionActor.scala:651)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.google.cloud.storage.StorageException: 503 Service Unavailable
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:189)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:335)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:191)
	at com.google.cloud.storage.StorageImpl$5.call(StorageImpl.java:188)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:94)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:54)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:188)
	at com.google.cloud.storage.StorageImpl.get(StorageImpl.java:202)
	at com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider.readAttributes(CloudStorageFileSystemProvider.java:579)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.Files.size(Files.java:2332)
	at better.files.File.$anonfun$size$1(File.scala:502)
	at better.files.File.$anonfun$size$1$adapted(File.scala:502)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1417)
	at scala.collection.TraversableOnce.sum(TraversableOnce.scala:216)
	at scala.collection.TraversableOnce.sum$(TraversableOnce.scala:216)
	at scala.collection.AbstractIterator.sum(Iterator.scala:1417)
	at better.files.File.size(File.scala:502)
	at cromwell.core.path.BetterFileMethods.size(BetterFileMethods.scala:323)
	at cromwell.core.path.BetterFileMethods.size$(BetterFileMethods.scala:323)
	at cromwell.filesystems.gcs.GcsPath.size(GcsPathBuilder.scala:179)
	at cromwell.backend.wdl.ReadLikeFunctions.$anonfun$fileSize$2(ReadLikeFunctions.scala:18)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.backend.wdl.ReadLikeFunctions.$anonfun$fileSize$1(ReadLikeFunctions.scala:18)
	at cromwell.backend.wdl.ReadLikeFunctions.$anonfun$validateFileSizeIsWithinLimits$1(ReadLikeFunctions.scala:54)
	at scala.util.Success.flatMap(Try.scala:247)
	at cromwell.backend.wdl.ReadLikeFunctions.validateFileSizeIsWithinLimits(ReadLikeFunctions.scala:53)
	at cromwell.backend.wdl.ReadLikeFunctions.validateFileSizeIsWithinLimits$(ReadLikeFunctions.scala:51)
	at cromwell.backend.standard.StandardExpressionFunctions.validateFileSizeIsWithinLimits(StandardExpressionFunctions.scala:22)
	at cromwell.backend.wdl.ReadLikeFunctions.read_string(ReadLikeFunctions.scala:83)
	at cromwell.backend.wdl.ReadLikeFunctions.read_string$(ReadLikeFunctions.scala:81)
	at cromwell.backend.standard.StandardExpressionFunctions.read_string(StandardExpressionFunctions.scala:22)
	at sun.reflect.GeneratedMethodAccessor360.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at wdl4s.wdl.expression.WdlFunctions.$anonfun$getFunction$1(WdlFunctions.scala:11)
	at wdl4s.wdl.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:190)
	at wdl4s.wdl.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:56)
	at wdl4s.wdl.WdlExpression$.evaluate(WdlExpression.scala:91)
	at wdl4s.wdl.WdlExpression.evaluate(WdlExpression.scala:172)
	at wdl4s.wdl.WdlTask.$anonfun$evaluateOutputs$2(WdlTask.scala:188)
	... 34 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 503 Service Unavailable
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.get(HttpStorageRpc.java:333)
	... 80 more
```

If this was due to an extended GCS service outage, a workflow failure is expected. But if cromwell didn't retry at all after a single cloud hiccup, that should be fixed as cloud hiccups are expected.

**Comment by geoffjentry** [comment]
We do retry on 503s

**Comment by Horneth** [comment]
not for WDL functions

**Comment by patmagee** [comment]
@Horneth Out of curiosity has this been addressed. We are using v28.2 and seem to get a lot of these errors when doing `size` lookups

**Comment by Horneth** [comment]
No it hasn't changed, the work done for the CWL support will make implementing retries for those functions a lot easier though. It'll likely not be in 30 but could be in 31 if it gets prioritized: @katevoss

**Comment by patmagee** [comment]
@Horneth Thanks for letting me know. It would be great if this was prioritized, we are unable to fully do call caching at the moment, so having 503 errors can get quite expensive for us. Are there any config properties which you know of that might help with this?

**Comment by Horneth** [comment]
> Are there any config properties which you know of that might help with this?

Not that I can think of unfortunately :/ One quick thing we could maybe do before the fixing it "the right way" would be to enable retries at the GCS library level. We've disabled it because we have our own retry mechanism which is more reliable and asynchronous (but WDL functions couldn't use it so far, which is why they're not retried). We're about to release Cromwell 30 imminently so I don't think this can make it before then but we could consider hotfixing it if this is really becoming urgent.
