### ISSUE TITLE
cromwell and GATK4

### ISSUE THREAD

**Issue by Masber** [broadinstitute/cromwell#2673]
Dear cromwell team,

We are trying to setup a test environment with GATK4 and cromwell for our local users.

I tested the helloHaplotypeCaller.wdl in the data bundle but it is giving the following error:

```
java -jar $cromwell run storage/WDLdata/WDLscripts/helloHaplotypeCaller.wdl -i storage/WDLdata/WDLscripts/helloHaplotypeCaller_inputs.json
[2017-10-04 06:06:48,43] [info] Running with database db.url = jdbc:hsqldb:mem:2812db5e-e9cc-48b0-bc67-62fd2c7887f9;shutdown=false;hsqldb.tx=mvcc
[2017-10-04 06:06:53,48] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2017-10-04 06:06:53,49] [info] [RenameWorkflowOptionsInMetadata] 100%
[2017-10-04 06:06:53,83] [info] Slf4jLogger started
[2017-10-04 06:06:54,01] [info] Metadata summary refreshing every 2 seconds.
[2017-10-04 06:06:54,02] [info] WriteMetadataActor configured to write to the database with batch size 200 and flush rate 5 seconds.
[2017-10-04 06:06:54,32] [info] CallCacheWriteActor configured to write to the database with batch size 100 and flush rate 3 seconds.
[2017-10-04 06:06:55,29] [info] SingleWorkflowRunnerActor: Submitting workflow
[2017-10-04 06:06:55,36] [info] Workflow bf90a37b-6ffa-4122-a12c-24aced32f3b6 submitted.
[2017-10-04 06:06:55,36] [info] SingleWorkflowRunnerActor: Workflow submitted bf90a37b-6ffa-4122-a12c-24aced32f3b6
[2017-10-04 06:06:55,36] [info] 1 new workflows fetched
[2017-10-04 06:06:55,37] [info] WorkflowManagerActor Starting workflow bf90a37b-6ffa-4122-a12c-24aced32f3b6
[2017-10-04 06:06:55,37] [info] WorkflowManagerActor Successfully started WorkflowActor-bf90a37b-6ffa-4122-a12c-24aced32f3b6
[2017-10-04 06:06:55,37] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2017-10-04 06:06:55,63] [info] MaterializeWorkflowDescriptorActor [bf90a37b]: Call-to-Backend assignments: helloHaplotypeCaller.haplotypeCaller -> Local
[2017-10-04 06:06:56,98] [info] WorkflowExecutionActor-bf90a37b-6ffa-4122-a12c-24aced32f3b6 [bf90a37b]: Starting calls: helloHaplotypeCaller.haplotypeCaller:NA:1
[2017-10-04 06:06:58,05] [warn] Localization via hard link has failed: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/ref/ref.dict -> /home/centos/storage/WDLdata/ref/ref.dict: Invalid cross-device link
[2017-10-04 06:06:58,06] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2017-10-04 06:06:58,07] [info] Using noop to send events.
[2017-10-04 06:06:58,09] [warn] Localization via hard link has failed: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/bams/mother.bam -> /home/centos/storage/WDLdata/bams/mother.bam: Invalid cross-device link
[2017-10-04 06:06:58,10] [warn] Localization via hard link has failed: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/bams/mother.bai -> /home/centos/storage/WDLdata/bams/mother.bai: Invalid cross-device link
[2017-10-04 06:06:58,10] [warn] Localization via hard link has failed: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/ref/ref.fasta -> /home/centos/storage/WDLdata/ref/ref.fasta: Invalid cross-device link
[2017-10-04 06:06:58,11] [warn] Localization via hard link has failed: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/opt/gatk/gatk-package-4.beta.5-local.jar -> /opt/gatk/gatk-package-4.beta.5-local.jar: Operation not permitted
[2017-10-04 06:06:58,11] [warn] Localization via hard link has failed: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/ref/ref.fasta.fai -> /home/centos/storage/WDLdata/ref/ref.fasta.fai: Invalid cross-device link
[2017-10-04 06:06:58,14] [info] BackgroundConfigAsyncJobExecutionActor [bf90a37bhelloHaplotypeCaller.haplotypeCaller:NA:1]: java -jar /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/opt/gatk/gatk-package-4.beta.5-local.jar \
        -T HaplotypeCaller \
        -R /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/ref/ref.fasta \
        -I /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/inputs/home/centos/storage/WDLdata/bams/mother.bam \
        -o NA12878.raw.indels.snps.vcf
[2017-10-04 06:06:58,15] [info] BackgroundConfigAsyncJobExecutionActor [bf90a37bhelloHaplotypeCaller.haplotypeCaller:NA:1]: executing: /bin/bash /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/execution/script
[2017-10-04 06:06:58,21] [info] BackgroundConfigAsyncJobExecutionActor [bf90a37bhelloHaplotypeCaller.haplotypeCaller:NA:1]: job id: 13026
[2017-10-04 06:06:58,21] [info] BackgroundConfigAsyncJobExecutionActor [bf90a37bhelloHaplotypeCaller.haplotypeCaller:NA:1]: Status change from - to WaitingForReturnCodeFile
[2017-10-04 06:07:31,28] [info] BackgroundConfigAsyncJobExecutionActor [bf90a37bhelloHaplotypeCaller.haplotypeCaller:NA:1]: Status change from WaitingForReturnCodeFile to Done
[2017-10-04 06:07:31,37] [error] WorkflowManagerActor Workflow bf90a37b-6ffa-4122-a12c-24aced32f3b6 failed (during ExecutingWorkflowState): Job helloHaplotypeCaller.haplotypeCaller:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/execution/stderr
[2017-10-04 06:07:31,37] [info] WorkflowManagerActor WorkflowActor-bf90a37b-6ffa-4122-a12c-24aced32f3b6 is in a terminal state: WorkflowFailedState
[2017-10-04 06:07:35,37] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2017-10-04 06:07:35,41] [info] Message [cromwell.engine.workflow.WorkflowManagerActor$RetrieveNewWorkflows$] without sender to Actor[akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor#-1816723107] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Workflow bf90a37b-6ffa-4122-a12c-24aced32f3b6 transitioned to state Failed
[2017-10-04 06:07:35,44] [info] Automatic shutdown of the async connection
[2017-10-04 06:07:35,44] [info] Gracefully shutdown sentry threads.
[2017-10-04 06:07:35,44] [info] Shutdown finished.
```

Ans this is the output from the stderr file
```
vi /home/centos/cromwell-executions/helloHaplotypeCaller/bf90a37b-6ffa-4122-a12c-24aced32f3b6/call-haplotypeCaller/execution/stderr
^[[32m    BwaSpark                                     ^[[31m(BETA Tool) ^[[36mBWA on Spark^[[0m
^[[32m    CollectBaseDistributionByCycleSpark          ^[[31m(BETA Tool) ^[[36mCollectBaseDistributionByCycle on Spark^[[0m
^[[32m    CollectInsertSizeMetricsSpark                ^[[31m(BETA Tool) ^[[36mCollect Insert Size Distribution on Spark^[[0m
^[[32m    CollectMultipleMetricsSpark                  ^[[31m(BETA Tool) ^[[36mA "meta-metrics" calculating program that produces multiple metrics for the provided SAM/BAM/CRAM file^[[0m
^[[32m    CollectQualityYieldMetricsSpark              ^[[31m(BETA Tool) ^[[36mCollectQualityYieldMetrics on Spark^[[0m
^[[32m    CountBasesSpark                              ^[[31m(BETA Tool) ^[[36mCountBases on Spark^[[0m
^[[32m    CountReadsSpark                              ^[[31m(BETA Tool) ^[[36mCountReads on Spark^[[0m
^[[32m    CountVariantsSpark                           ^[[31m(BETA Tool) ^[[36mCountVariants on Spark^[[0m
^[[32m    CreateHadoopBamSplittingIndex                ^[[31m(BETA Tool) ^[[36mcreate a hadoop-bam splitting index^[[0m
^[[32m    FlagStatSpark                                ^[[31m(BETA Tool) ^[[36mFlagStat on Spark^[[0m
^[[32m    HaplotypeCallerSpark                         ^[[31m(BETA Tool) ^[[36mHaplotypeCaller on Spark^[[0m
^[[32m    MarkDuplicatesSpark                          ^[[31m(BETA Tool) ^[[36mMarkDuplicates on Spark^[[0m
^[[32m    MeanQualityByCycleSpark                      ^[[31m(BETA Tool) ^[[36mMeanQualityByCycle on Spark^[[0m
^[[32m    ParallelCopyGCSDirectoryIntoHDFSSpark        ^[[31m(BETA Tool) ^[[36mParallel copy a file or directory from GCS into HDFS.^[[0m
^[[32m    PileupSpark                                  ^[[31m(BETA Tool) ^[[36mPrint read alignments in Pileup-style format on Spark^[[0m
^[[32m    PrintReadsSpark                              ^[[31m(BETA Tool) ^[[36mPrintReads on Spark^[[0m
^[[32m    QualityScoreDistributionSpark                ^[[31m(BETA Tool) ^[[36mQualityScoreDistribution on Spark^[[0m
^[[32m    SortReadFileSpark                            ^[[31m(BETA Tool) ^[[36mSortSam on Spark (works on SAM/BAM/CRAM)^[[0m

^[[37m--------------------------------------------------------------------------------------
^[[0m^[[31mVCF Tools:                                       Tools for manipulating variants and associated metadata^[[0m
^[[32m    AnnotateVcfWithBamDepth                      ^[[36m(Internal) Annotate a vcf with a bam's read depth at each variant locus^[[0m
^[[32m    AnnotateVcfWithExpectedAlleleFraction        ^[[36m(Internal) Annotate a vcf with expected allele fractions in pooled sequencing^[[0m
^[[32m    ApplyVQSR                                    ^[[36m Apply a score cutoff to filter variants based on a recalibration table^[[0m
^[[32m    CalculateContamination                       ^[[36mCalculate the fraction of reads coming from cross-sample contamination^[[0m
^[[32m    CalculateGenotypePosteriors                  ^[[36mCalculate genotype posterior probabilities given family and/or known population genotypes^[[0m
^[[32m    CalculateMixingFractions                     ^[[36m(Internal) Calculate proportions of different samples in a pooled bam^[[0m
^[[32m    Concordance                                  ^[[31m(BETA Tool) ^[[36mEvaluate concordance of an input VCF against a validated truth VCF^[[0m
^[[32m    CountFalsePositives                          ^[[31m(BETA Tool) ^[[36mCount PASS variants^[[0m
^[[32m    CountVariants                                ^[[36mCount variants in a VCF file^[[0m
^[[32m    CreateSomaticPanelOfNormals                  ^[[31m(BETA Tool) ^[[36mMake a panel of normals for use with Mutect2^[[0m
^[[32m    FilterByOrientationBias                      ^[[31m(BETA Tool) ^[[36m(Experimental) Filter Mutect2 somatic variant calls using orientation bias^[[0m
^[[32m    FilterMutectCalls                            ^[[31m(BETA Tool) ^[[36mFilter somatic SNVs and indels called by Mutect2^[[0m
^[[32m    FilterVcf                                    ^[[36mHard-filters a VCF file^[[0m
^[[32m    GatherTranches                               ^[[36mGathers scattered VQSLOD tranches into a single file^[[0m
^[[32m    GatherVcfs                                   ^[[31m(BETA Tool) ^[[36mGathers multiple VCF files from a scatter operation into a single VCF file^[[0m
^[[32m    GenomicsDBImport                             ^[[36mImport VCFs to GenomicsDB^[[0m
^[[32m    GenotypeConcordance                          ^[[36mCalculates the concordance between genotype data for two samples in two different VCFs^[[0m
^[[32m    GenotypeGVCFs                                ^[[36mPerform joint genotyping on one or more samples pre-called with HaplotypeCaller^[[0m
^[[32m    GetPileupSummaries                           ^[[31m(BETA Tool) ^[[36mCalculate pileup statistics for inferring contamination^[[0m
^[[32m    HaplotypeCaller                              ^[[31m(BETA Tool) ^[[36mCall germline SNPs and indels via local re-assembly of haplotypes^[[0m
^[[32m    IndexFeatureFile                             ^[[36mCreates indices for Feature-containing files (eg VCF and BED files)^[[0m
^[[32m    LiftOverVcf                                  ^[[36mLifts a VCF between genome builds^[[0m
^[[32m    MakeSitesOnlyVcf                             ^[[36mCreates a VCF bereft of genotype information from an input VCF^[[0m
^[[32m    MergeVcfs                                    ^[[36mMerges multiple VCF files into one VCF file^[[0m
^[[32m    Mutect2                                      ^[[31m(BETA Tool) ^[[36mCall somatic SNVs and indels via local assembly of haplotypes^[[0m
^[[32m    RemoveNearbyIndels                           ^[[36m(Internal) Remove indels that are close to each other from a vcf^[[0m
^[[32m    RenameSampleInVcf                            ^[[36mRename a sample within a VCF^[[0m
^[[32m    SelectVariants                               ^[[36mSelect a subset of variants from a VCF file^[[0m
^[[32m    SortVcf                                      ^[[36mSorts one or more VCF files^[[0m
^[[32m    SplitIntervals                               ^[[36mSplit intervals into sub-interval files.^[[0m
^[[32m    SplitVcfs                                    ^[[36mSplits an input VCF file into two VCF files^[[0m
^[[32m    UpdateVCFSequenceDictionary                  ^[[36mUpdates the sequence dictionary in a variant file.^[[0m
^[[32m    ValidateVariants                             ^[[36mValidate VCF^[[0m
^[[32m    VariantFiltration                            ^[[36mFilter variant calls based on INFO and FORMAT annotations^[[0m
^[[32m    VariantRecalibrator                          ^[[36mBuild a recalibration model to score variant quality for filtering purposes^[[0m
^[[32m    VariantsToTable                              ^[[36mExtract specific fields from a VCF file to a tab-delimited table^[[0m
^[[32m    VcfToIntervalList                            ^[[36mConverts a VCF file to a Picard Interval List^[[0m

^[[37m--------------------------------------------------------------------------------------
^[[0m
Exception in thread "main" org.broadinstitute.hellbender.exceptions.UserException: '-T' is not a valid command.

        at org.broadinstitute.hellbender.Main.extractCommandLineProgram(Main.java:291)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:150)
        at org.broadinstitute.hellbender.Main.main(Main.java:233)
```

Any advise?

Thank you very much

**Comment by geoffjentry** [comment]
Hi @Masber - apologies as I just said the same thing over in Gitter but this is a question for the [GATK forum](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team) - whatever is going on here is (probably) not an issue with Cromwell but something regarding the interaction with the WDL from the GATK group.
