### ISSUE TITLE
Bad errors reported validating null.wdl

### ISSUE THREAD

**Issue by katevoss** [broadinstitute/cromwell#2703]
@cjllanwarne commented on [Mon May 22 2017](https://github.com/broadinstitute/wdl4s/issues/112)

This problem presents itself when using `wdltool` but it looks like it's a match error coming from inside `WDL4S`

null.wdl:
```
task empty{
    command {}
    output {
        File out = "${output}"
    }
}
```

On validate:
```
$ java -jar target/scala-2.12/wdltool-0.11.jar validate ~/myWorkflows/null.wdl
null
```

We can see more details when we try to graph it:
```
$ java -jar target/scala-2.12/wdltool-0.11.jar graph ~/myWorkflows/null.wdl
Exception in thread "main" scala.MatchError: null
	at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:44)
	at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:85)
	at wdl4s.WdlExpression.evaluate(WdlExpression.scala:161)
	at wdl4s.expression.ValueEvaluator.replaceInterpolationTag(ValueEvaluator.scala:20)
	at wdl4s.expression.ValueEvaluator.$anonfun$interpolate$2(ValueEvaluator.scala:33)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
```

**Comment by katevoss** [comment]
@cjllanwarne can you explain more about what the problem is?
