### ISSUE TITLE
bug: select_first() in output{}

### ISSUE THREAD

**Issue by leepc12** [broadinstitute/cromwell#2972]
```
workflow test {
	call t1 { input : flag1 = false, }
}

task t1 {
	Boolean? flag1
	command {
		echo test1 > test1.txt
		echo test2 > test2.txt
	}
	output {
		File out_false = if false then glob('test1.txt')[0] else glob('test2.txt')[0] # try commenting this out
		File out = if select_first([flag1,false]) then glob('test1.txt')[0] else glob('test2.txt')[0]
	}
}
```
This code works fine. But If you comment out a line `File out_false = if false then glob('test1.txt')[0] else glob('test2.txt')[0] # try commenting this out` in output {}, then I get an error.

```
$ java -jar ../cromwell-29.jar run test_select_first_in_if_in_output.wdl
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
[2017-12-01 20:00:53,03] [info] Running with database db.url = jdbc:hsqldb:mem:6ae82874-e5ea-4c15-9f1d-09f8d0406019;shutdown=false;hsqldb.tx=mvcc
[2017-12-01 20:01:00,60] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2017-12-01 20:01:00,61] [info] [RenameWorkflowOptionsInMetadata] 100%
[2017-12-01 20:01:01,07] [info] Slf4jLogger started
[2017-12-01 20:01:01,35] [info] Metadata summary refreshing every 2 seconds.
[2017-12-01 20:01:01,37] [info] WriteMetadataActor configured to write to the database with batch size 200 and flush rate 5 seconds.
[2017-12-01 20:01:01,51] [info] CallCacheWriteActor configured to write to the database with batch size 100 and flush rate 3 seconds.
[2017-12-01 20:01:02,89] [info] SingleWorkflowRunnerActor: Submitting workflow
[2017-12-01 20:01:02,94] [info] Workflow 132d7527-a0af-4f08-8291-d935e7cd5632 submitted.
[2017-12-01 20:01:02,94] [info] SingleWorkflowRunnerActor: Workflow submitted 132d7527-a0af-4f08-8291-d935e7cd5632
[2017-12-01 20:01:02,95] [info] 1 new workflows fetched
[2017-12-01 20:01:02,95] [info] WorkflowManagerActor Starting workflow 132d7527-a0af-4f08-8291-d935e7cd5632
[2017-12-01 20:01:02,96] [info] WorkflowManagerActor Successfully started WorkflowActor-132d7527-a0af-4f08-8291-d935e7cd5632
[2017-12-01 20:01:02,96] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2017-12-01 20:01:03,27] [info] MaterializeWorkflowDescriptorActor [132d7527]: Call-to-Backend assignments: test.t1 -> Local
[2017-12-01 20:01:04,64] [info] WorkflowExecutionActor-132d7527-a0af-4f08-8291-d935e7cd5632 [132d7527]: Starting calls: test.t1:NA:1
[2017-12-01 20:01:04,82] [info] BackgroundConfigAsyncJobExecutionActor [132d7527test.t1:NA:1]: echo test1 > test1.txt
echo test2 > test2.txt
[2017-12-01 20:01:04,86] [info] BackgroundConfigAsyncJobExecutionActor [132d7527test.t1:NA:1]: executing: /bin/bash /users/leepc12/code/atac-seq-pipeline/test/cromwell-executions/test/132d7527-a0af-4f08-8291-d935e7cd5632/call-t1/execution/script
[2017-12-01 20:01:04,91] [info] BackgroundConfigAsyncJobExecutionActor [132d7527test.t1:NA:1]: job id: 9836
[2017-12-01 20:01:04,92] [info] BackgroundConfigAsyncJobExecutionActor [132d7527test.t1:NA:1]: Status change from - to WaitingForReturnCodeFile
[2017-12-01 20:01:06,50] [info] BackgroundConfigAsyncJobExecutionActor [132d7527test.t1:NA:1]: Status change from WaitingForReturnCodeFile to Done
[2017-12-01 20:01:06,61] [error] WorkflowManagerActor Workflow 132d7527-a0af-4f08-8291-d935e7cd5632 failed (during ExecutingWorkflowState): Could not evaluate t1.out = if select_first([flag1,false]) then glob("test1.txt")[0] else glob("test2.txt")[0]
java.lang.RuntimeException: Could not evaluate t1.out = if select_first([flag1,false]) then glob("test1.txt")[0] else glob("test2.txt")[0]
        at wdl4s.wdl.WdlTask$$anonfun$4.applyOrElse(WdlTask.scala:189)
        at wdl4s.wdl.WdlTask$$anonfun$4.applyOrElse(WdlTask.scala:188)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at scala.util.Failure.recoverWith(Try.scala:232)
        at wdl4s.wdl.WdlTask.$anonfun$evaluateOutputs$2(WdlTask.scala:188)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at wdl4s.wdl.WdlTask.evaluateOutputs(WdlTask.scala:181)
        at cromwell.backend.wdl.OutputEvaluator$.evaluateOutputs(OutputEvaluator.scala:15)
        at cromwell.backend.standard.StandardAsyncExecutionActor.evaluateOutputs(StandardAsyncExecutionActor.scala:406)
        at cromwell.backend.standard.StandardAsyncExecutionActor.evaluateOutputs$(StandardAsyncExecutionActor.scala:405)
        at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.evaluateOutputs(ConfigAsyncJobExecutionActor.scala:121)
        at cromwell.backend.standard.StandardAsyncExecutionActor.handleExecutionSuccess(StandardAsyncExecutionActor.scala:458)
        at cromwell.backend.standard.StandardAsyncExecutionActor.handleExecutionSuccess$(StandardAsyncExecutionActor.scala:455)
        at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.handleExecutionSuccess(ConfigAsyncJobExecutionActor.scala:121)
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionResult$3(StandardAsyncExecutionActor.scala:651)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.file.NoSuchFileException: /users/leepc12/code/atac-seq-pipeline/test/cromwell-executions/test/132d7527-a0af-4f08-8291-d935e7cd5632/call-t1/execution/glob-c91e47329777637e2370464651ba47aa.list
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixPath.toRealPath(UnixPath.java:837)
        at cromwell.core.path.NioPathMethods.toRealPath(NioPathMethods.scala:70)
        at cromwell.core.path.NioPathMethods.toRealPath$(NioPathMethods.scala:70)
        at cromwell.core.path.DefaultPath.toRealPath(DefaultPathBuilder.scala:53)
        at cromwell.backend.io.GlobFunctions.glob(GlobFunctions.scala:45)
        at cromwell.backend.io.GlobFunctions.glob$(GlobFunctions.scala:43)
        at cromwell.backend.standard.StandardExpressionFunctions.glob(StandardExpressionFunctions.scala:23)
        at cromwell.backend.wdl.ReadLikeFunctions.$anonfun$glob$1(ReadLikeFunctions.scala:168)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at cromwell.backend.wdl.ReadLikeFunctions.glob(ReadLikeFunctions.scala:166)
        at cromwell.backend.wdl.ReadLikeFunctions.glob$(ReadLikeFunctions.scala:164)
        at cromwell.backend.standard.StandardExpressionFunctions.glob(StandardExpressionFunctions.scala:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at wdl4s.wdl.expression.WdlFunctions.$anonfun$getFunction$1(WdlFunctions.scala:11)
        at wdl4s.wdl.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:187)
        at wdl4s.wdl.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:168)
        at wdl4s.wdl.expression.ValueEvaluator.$anonfun$evaluate$32(ValueEvaluator.scala:81)
        at scala.util.Success.flatMap(Try.scala:247)
        at wdl4s.wdl.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:79)
        at wdl4s.wdl.WdlExpression$.evaluate(WdlExpression.scala:85)
        at wdl4s.wdl.WdlExpression.evaluate(WdlExpression.scala:166)
        at wdl4s.wdl.WdlTask.$anonfun$evaluateOutputs$2(WdlTask.scala:187)
        ... 34 more
```

**Comment by mcovarr** [comment]
I can reproduce this problem on Cromwell 29 but happily this runs fine on the forthcoming Cromwell 30. We're hoping to release this **very** soon. 🙂

**Comment by mcovarr** [comment]
30 has been released.
