### ISSUE TITLE
Conditional task with same input twice fails

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#2973]
```wdl
task two_input_task {
    String inA
    String inB
    command { echo ${inA} and ${inB} }
    runtime { docker: "ubuntu" }
}

workflow duplicate_conditional_input {
    String my_input = "input"
    if (false) {
        call two_input_task { input: inA = my_input, inB = my_input }
    }
}
```

Runs in 29 (d45f001). In develop (0fd1635) this crashes with:

```java
[2017-12-02 16:30:57,99] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2017-12-02 16:30:59,03] [error] WorkflowManagerActor Workflow e7ef9b84-2a08-4295-a2ab-fea19ddcba76 failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
Unable to build WOM node for If '$if_0': Two or more nodes have the same FullyQualifiedName: ^.my_input
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unable to build WOM node for If '$if_0': Two or more nodes have the same FullyQualifiedName: ^.my_input
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:665)
	at akka.actor.FSM.processEvent$(FSM.scala:662)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:136)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:136)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:136)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cjllanwarne** [comment]
@kshakir does this also happen with scatter blocks?

**Comment by kshakir** [comment]
Fantastic instincts. This fails in the same develop and passes in the same 29:

```wdl
task two_input_task {
    String inA
    String inB
    command { echo ${inA} and ${inB} }
    runtime { docker: "ubuntu" }
}

workflow duplicate_scatter_input {
    String my_input = "input"
    scatter (i in range(0)) {
        call two_input_task { input: inA = my_input, inB = my_input }
    }
}
```

Produces in this error on develop:
```java
[2017-12-03 14:48:08,10] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2017-12-03 14:48:09,17] [error] WorkflowManagerActor Workflow 986bbc71-2b80-4cf1-aade-e93dd77062b0 failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
Unable to build WOM node for Scatter '$scatter_0': Two or more nodes have the same FullyQualifiedName: ^.my_input
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unable to build WOM node for Scatter '$scatter_0': Two or more nodes have the same FullyQualifiedName: ^.my_input
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:665)
	at akka.actor.FSM.processEvent$(FSM.scala:662)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:136)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:136)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:136)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Confirmed to work in 29 via:

```bash
docker \
  run \
  --rm \
  -v $PWD:$PWD \
  broadinstitute/cromwell:29-d45f001 \
  run \
  $PWD/duplicate_scatter_input.wdl
```

Can use `broadinstitute/cromwell:develop` to reproduce the issue until this is fixed.
