### ISSUE TITLE
cromwell-30 bug?: if in if

### ISSUE THREAD

**Issue by leepc12** [broadinstitute/cromwell#2992]
* `cromwell-30.jar`
* local
* single workflow mode

```
workflow test {
	Boolean b0 = true
	Boolean b1 = true
	Boolean b2 = true	
	if ( b0 ) {
		if ( b2 ) {
			call t0 as t2 { input: i=2 }
		}
		if ( b1 ) {
			call t0 as t1 { input: i=1 }			
		}
		#Boolean tmp = b1 && b2
		#if ( tmp ) {	
		if ( b1 && b2 ) {
			call t0 as t12 { input: i=12 }				
		}
	}
}

task t0 {
	Int? i
	command {
		echo test > ${i}.txt
	}
	output {
		File out = glob('*.txt')[0]
	}
}
```
This code does not work.
```
$ java -jar ../cromwell-30.jar run test_conditionals_in_cromwell-30.wdl
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
[2017-12-05 09:40:22,36] [info] Running with database db.url = jdbc:hsqldb:mem:ee347d5b-2cdf-4b76-b68a-dc5d09a93aeb;shutdown=false;hsqldb.tx=mvcc
[2017-12-05 09:40:28,42] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2017-12-05 09:40:28,44] [info] [RenameWorkflowOptionsInMetadata] 100%
[2017-12-05 09:40:28,54] [info] Running with database db.url = jdbc:hsqldb:mem:68a1b424-aa08-4f22-bc04-952c5eb83e7e;shutdown=false;hsqldb.tx=mvcc
[2017-12-05 09:40:29,02] [info] Slf4jLogger started
[2017-12-05 09:40:29,28] [info] Metadata summary refreshing every 2 seconds.
[2017-12-05 09:40:29,29] [info] Starting health monitor with the following checks: DockerHub, Engine Database
[2017-12-05 09:40:29,30] [info] WriteMetadataActor configured to write to the database with batch size 200 and flush rate 5 seconds.
[2017-12-05 09:40:29,35] [info] CallCacheWriteActor configured to write to the database with batch size 100 and flush rate 3 seconds.
[2017-12-05 09:40:30,63] [info] SingleWorkflowRunnerActor: Submitting workflow
[2017-12-05 09:40:30,68] [info] Workflow 6a6ee0eb-5576-43af-a64c-8ed7d288bbc5 submitted.
[2017-12-05 09:40:30,68] [info] SingleWorkflowRunnerActor: Workflow submitted 6a6ee0eb-5576-43af-a64c-8ed7d288bbc5
[2017-12-05 09:40:30,69] [info] 1 new workflows fetched
[2017-12-05 09:40:30,69] [info] WorkflowManagerActor Starting workflow 6a6ee0eb-5576-43af-a64c-8ed7d288bbc5
[2017-12-05 09:40:30,70] [info] WorkflowManagerActor Successfully started WorkflowActor-6a6ee0eb-5576-43af-a64c-8ed7d288bbc5
[2017-12-05 09:40:30,70] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2017-12-05 09:40:31,66] [error] WorkflowManagerActor Workflow 6a6ee0eb-5576-43af-a64c-8ed7d288bbc5 failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
Unable to build WOM node for If '$if_0': Two or more nodes have the same FullyQualifiedName: ^.b1
Unable to build WOM node for If '$if_0': Two or more nodes have the same FullyQualifiedName: ^.b2
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unable to build WOM node for If '$if_0': Two or more nodes have the same FullyQualifiedName: ^.b1
Unable to build WOM node for If '$if_0': Two or more nodes have the same FullyQualifiedName: ^.b2
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:665)
        at akka.actor.FSM.processEvent$(FSM.scala:662)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
        at akka.actor.Actor.aroundReceive(Actor.scala:514)
        at akka.actor.Actor.aroundReceive$(Actor.scala:512)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2017-12-05 09:40:31,67] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2017-12-05 09:40:31,68] [info] Using noop to send events.
[2017-12-05 09:40:31,70] [info] WorkflowManagerActor WorkflowActor-6a6ee0eb-5576-43af-a64c-8ed7d288bbc5 is in a terminal state: WorkflowFailedState
[2017-12-05 09:40:35,79] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2017-12-05 09:40:35,81] [info] Message [cromwell.core.actor.StreamActorHelper$StreamFailed] without sender to Actor[akka://cromwell-system/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2017-12-05 09:40:35,81] [info] Message [cromwell.core.actor.StreamActorHelper$StreamFailed] without sender to Actor[akka://cromwell-system/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Workflow 6a6ee0eb-5576-43af-a64c-8ed7d288bbc5 transitioned to state Failed
[2017-12-05 09:40:35,85] [info] Automatic shutdown of the async connection
[2017-12-05 09:40:35,85] [info] Gracefully shutdown sentry threads.
[2017-12-05 09:40:35,85] [info] Shutdown finished.
```
As a work-around, I needed to replace 
```
if ( b1 && b2 ) {
```
with
```
Boolean tmp = b1 && b2
if ( tmp ) {
````

**Comment by cjllanwarne** [comment]
Fixed in develop. Question for @katevoss - is this worthy of a hotfix (and if so, should we wait to see if any more WOM issues bubble up in the next few days and patch them all in one go)?

**Comment by geoffjentry** [comment]
My own $0.02 is unless a raging fire shows up we should give it a little time and get more bang for the buck. The develop branch is *so* close to 30 right now that people who are keenly interested can build off of that.

**Comment by leepc12** [comment]
Another if-scatter bug.
i built a new `cromwell-31-d716fd2-SNAP.jar` from your `develop` branch.
```
workflow test {
	Boolean b0 = true
	Boolean b1 = true
	Boolean b2 = true
	scatter( i in range(3) ) {
		if ( b0 ) {
			call t0 as t1 { input: i=i }
		}
	}
	if ( b1 ) {
		scatter( i in range(3) ) {
			call t0 as t2 { input: i=t1.out[i] }
		}
	}
	if ( b1 && b2 ) {
		scatter( i in range(3) ) {
			call t0 as t3 { input: i=t2.out[i] }
		}
	}
}

task t0 {
	Int? i
	command {
		echo ${i}
	}
	output {
		Int out = read_int(stdout())
	}
}
```
error log
```
$ java -jar /users/leepc12/code/cromwell/./target/scala-2.12/cromwell-31-d716fd2-SNAP.jar run test_conditionals_in_cromwell-30.wdl
Picked up _JAVA_OPTIONS: -Xms256M -Xmx1024M -XX:ParallelGCThreads=1
[2017-12-05 20:11:15,13] [info] Running with database db.url = jdbc:hsqldb:mem:7e58cfd2-b9b6-47f9-bda1-6fe045e7a665;shutdown=false;hsqldb.tx=mvcc
[2017-12-05 20:11:21,83] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2017-12-05 20:11:21,84] [info] [RenameWorkflowOptionsInMetadata] 100%
[2017-12-05 20:11:22,02] [info] Running with database db.url = jdbc:hsqldb:mem:e02f9206-cb15-468a-929a-82676a83a9b8;shutdown=false;hsqldb.tx=mvcc
[2017-12-05 20:11:22,47] [info] Slf4jLogger started
[2017-12-05 20:11:22,67] [info] Metadata summary refreshing every 2 seconds.
[2017-12-05 20:11:22,68] [info] Starting health monitor with the following checks: DockerHub, Engine Database
[2017-12-05 20:11:22,69] [info] WriteMetadataActor configured to write to the database with batch size 200 and flush rate 5 seconds.
[2017-12-05 20:11:22,71] [info] CallCacheWriteActor configured to write to the database with batch size 100 and flush rate 3 seconds.
[2017-12-05 20:11:23,78] [info] SingleWorkflowRunnerActor: Submitting workflow
[2017-12-05 20:11:23,82] [info] Workflow 159210e6-fa6a-4a99-b386-5931ae245324 submitted.
[2017-12-05 20:11:23,82] [info] SingleWorkflowRunnerActor: Workflow submitted 159210e6-fa6a-4a99-b386-5931ae245324
[2017-12-05 20:11:23,82] [info] 1 new workflows fetched
[2017-12-05 20:11:23,82] [info] WorkflowManagerActor Starting workflow 159210e6-fa6a-4a99-b386-5931ae245324
[2017-12-05 20:11:23,83] [info] WorkflowManagerActor Successfully started WorkflowActor-159210e6-fa6a-4a99-b386-5931ae245324
[2017-12-05 20:11:23,83] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2017-12-05 20:11:24,82] [error] WorkflowManagerActor Workflow 159210e6-fa6a-4a99-b386-5931ae245324 failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
Unable to build WOM node for If '$if_2': Unable to build WOM node for Scatter '$scatter_2': Unable to build WOM node for WdlTaskCall 't3': Can't index (ArrayOrMapLookup:
  lhs=(MemberAccess:
    lhs=<string:19:29 identifier "dDI=">,
    rhs=<string:19:32 identifier "b3V0">
  ),
  rhs=<string:19:36 identifier "aQ==">
)
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unable to build WOM node for If '$if_2': Unable to build WOM node for Scatter '$scatter_2': Unable to build WOM node for WdlTaskCall 't3': Can't index (ArrayOrMapLookup:
  lhs=(MemberAccess:
    lhs=<string:19:29 identifier "dDI=">,
    rhs=<string:19:32 identifier "b3V0">
  ),
  rhs=<string:19:36 identifier "aQ==">
)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:665)
        at akka.actor.FSM.processEvent$(FSM.scala:662)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
        at akka.actor.Actor.aroundReceive(Actor.scala:514)
        at akka.actor.Actor.aroundReceive$(Actor.scala:512)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2017-12-05 20:11:24,83] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2017-12-05 20:11:24,84] [info] Using noop to send events.
[2017-12-05 20:11:24,85] [info] WorkflowManagerActor WorkflowActor-159210e6-fa6a-4a99-b386-5931ae245324 is in a terminal state: WorkflowFailedState
[2017-12-05 20:11:32,22] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2017-12-05 20:11:32,25] [info] Message [cromwell.core.actor.StreamActorHelper$StreamFailed] without sender to Actor[akka://cromwell-system/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2017-12-05 20:11:32,26] [info] Message [cromwell.core.actor.StreamActorHelper$StreamFailed] without sender to Actor[akka://cromwell-system/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Workflow 159210e6-fa6a-4a99-b386-5931ae245324 transitioned to state Failed
[2017-12-05 20:11:32,30] [info] Automatic shutdown of the async connection
[2017-12-05 20:11:32,30] [info] Gracefully shutdown sentry threads.
[2017-12-05 20:11:32,30] [info] Shutdown finished.
```
This code worked with `cromwell-29.jar`.
