### ISSUE TITLE
Cromwell cyclic dependency error in 30.1, fine in 29

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#3143]
This workflow runs fine on "29-2caec7d" and fails with this stack trace on "30-a3ea825-SNAP" using the Pipelines API backend.

```
failures: [
{
causedBy: [
{
causedBy: [ ],
message: "This workflow contains a cyclic dependency on SomaticPairedEndSingleSampleWorkflow.$scatter_2"
},
{
causedBy: [ ],
message: "wdl.Scope.childGraphNodesSorted(Scope.scala:52)"
},
{
causedBy: [ ],
message: "wdl.Scope.childGraphNodesSorted$(Scope.scala:43)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.childGraphNodesSorted$lzycompute(WdlWorkflow.scala:63)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.childGraphNodesSorted(WdlWorkflow.scala:63)"
},
{
causedBy: [ ],
message: "wdl.WdlGraphNode$.buildWomGraph(WdlGraphNode.scala:140)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow$.womWorkflowDefinition(WdlWorkflow.scala:52)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.womDefinition$lzycompute(WdlWorkflow.scala:73)"
},
{
causedBy: [ ],
message: "wdl.WdlWorkflow.womDefinition(WdlWorkflow.scala:73)"
},
{
causedBy: [ ],
message: "wdl.WdlInputParsing$.buildWomExecutable(WdlInputParsing.scala:27)"
},
{
causedBy: [ ],
message: "wdl.WdlNamespaceWithWorkflow.womExecutable(WdlNamespace.scala:98)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.$anonfun$validateWdlNamespace$15(MaterializeWorkflowDescriptorActor.scala:493)"
},
{
causedBy: [ ],
message: "scala.util.Either.flatMap(Either.scala:338)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.$anonfun$validateWdlNamespace$13(MaterializeWorkflowDescriptorActor.scala:491)"
},
{
causedBy: [ ],
message: "scala.util.Either.flatMap(Either.scala:338)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.validateWdlNamespace(MaterializeWorkflowDescriptorActor.scala:490)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$buildWorkflowDescriptor(MaterializeWorkflowDescriptorActor.scala:231)"
},
{
causedBy: [ ],
message: "cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.$anonfun$applyOrElse$1(MaterializeWorkflowDescriptorActor.scala:157)"
},
{
causedBy: [ ],
message: "scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)"
},
{
causedBy: [ ],
message: "scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)"
},
{
causedBy: [ ],
message: "scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)"
},
{
causedBy: [ ],
message: "akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)"
},
{
causedBy: [ ],
message: "akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)"
},
{
causedBy: [ ],
message: "scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)"
},
{
causedBy: [ ],
message: "scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)"
},
{
causedBy: [ ],
message: "akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)"
},
{
causedBy: [ ],
message: "akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)"
},
{
causedBy: [ ],
message: "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)"
},
{
causedBy: [ ],
message: "akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"
}
],
message: "Workflow input processing failed"
}
],
```

I think the culprit has something to do with both the root and sub workflow both having a task called `GatherbamFiles` because when I renamed the task in the subworkflow (and all subsequent necessary renames) the workflow ran fine.  When I tried to make a simple example of this I couldn't get the error to pop up again so I'm definitely missing some nuances of the cause.  The root workflow passes womtool-30.1.jar validation.

Root workflow - [SomaticPairedSingleSampleWf.txt](https://github.com/broadinstitute/cromwell/files/1635810/SomaticPairedSingleSampleWf.txt)

Sub workflow - [SplitLargeRG.txt](https://github.com/broadinstitute/cromwell/files/1635814/SplitLargeRG.txt)

Dependencies zip - [SomaticPairedSingleSampleWfDependencies.zip](https://github.com/broadinstitute/cromwell/files/1635815/SomaticPairedSingleSampleWfDependencies.zip)

Let me know if theres any more information that might be useful.

**Comment by takutosato** [comment]
I'm getting the same error with this wdl: [mutect2-replicate-validation.zip](https://github.com/broadinstitute/cromwell/files/2242528/mutect2-replicate-validation.zip).

And here is the dependency file: [wdl-dependencies.zip](https://github.com/broadinstitute/cromwell/files/2242529/wdl-dependencies.zip)

This happens in versions 30 and up. When I run this in v29, cromwell doesn't throw an error but it hangs after completing the first task. 

tsato@gsa5:novaseq: java -jar $wom validate mutect2-replicate-validation.wdl
Exception in thread "main" java.lang.RuntimeException: This workflow contains a cyclic dependency on m2.Mutect2.filtered_vcf
	at wdl.draft2.model.Scope.childGraphNodesSorted(Scope.scala:53)
	at wdl.draft2.model.Scope.childGraphNodesSorted$(Scope.scala:44)
	at wdl.draft2.model.WdlWorkflow.childGraphNodesSorted$lzycompute(WdlWorkflow.scala:46)
	at wdl.draft2.model.WdlWorkflow.childGraphNodesSorted(WdlWorkflow.scala:46)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.toWomGraph(WdlDraft2WomGraphMaker.scala:97)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.toWomGraph(WdlDraft2WomGraphMaker.scala:18)
	at wom.transforms.WomGraphMaker$Ops.toWomGraph(WomGraphMaker.scala:8)
	at wom.transforms.WomGraphMaker$Ops.toWomGraph$(WomGraphMaker.scala:8)
	at wom.transforms.WomGraphMaker$ops$$anon$1.toWomGraph(WomGraphMaker.scala:8)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomWorkflowDefinitionMaker$.toWomWorkflowDefinition(WdlDraft2WomWorkflowDefinitionMaker.scala:14)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomWorkflowDefinitionMaker$.toWomWorkflowDefinition(WdlDraft2WomWorkflowDefinitionMaker.scala:10)
	at wom.transforms.WomWorkflowDefinitionMaker$Ops.toWomWorkflowDefinition(WomWorkflowDefinitionMaker.scala:8)
	at wom.transforms.WomWorkflowDefinitionMaker$Ops.toWomWorkflowDefinition$(WomWorkflowDefinitionMaker.scala:8)
	at wom.transforms.WomWorkflowDefinitionMaker$ops$$anon$1.toWomWorkflowDefinition(WomWorkflowDefinitionMaker.scala:8)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomCallableMaker$.toWomCallable(WdlDraft2WomCallableMaker.scala:13)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomCallableMaker$.toWomCallable(WdlDraft2WomCallableMaker.scala:11)
	at wom.transforms.WomCallableMaker$Ops.toWomCallable(WomCallableMaker.scala:8)
	at wom.transforms.WomCallableMaker$Ops.toWomCallable$(WomCallableMaker.scala:8)
	at wom.transforms.WomCallableMaker$ops$$anon$1.toWomCallable(WomCallableMaker.scala:8)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomCallNodeMaker$.toWomCallNode(WdlDraft2WomCallNodeMaker.scala:129)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomCallNodeMaker$.toWomCallNode(WdlDraft2WomCallNodeMaker.scala:21)
	at wom.transforms.WomCallNodeMaker$Ops.toWomCallNode(WomCallNodeMaker.scala:9)
	at wom.transforms.WomCallNodeMaker$Ops.toWomCallNode$(WomCallNodeMaker.scala:9)
	at wom.transforms.WomCallNodeMaker$ops$$anon$1.toWomCallNode(WomCallNodeMaker.scala:9)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.buildNode$1(WdlDraft2WomGraphMaker.scala:68)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.$anonfun$toWomGraph$3(WdlDraft2WomGraphMaker.scala:38)
	at common.validation.ErrorOr$ShortCircuitingFlatMap$.flatMap$extension(ErrorOr.scala:27)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.foldFunction$1(WdlDraft2WomGraphMaker.scala:37)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.$anonfun$toWomGraph$14(WdlDraft2WomGraphMaker.scala:98)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.toWomGraph(WdlDraft2WomGraphMaker.scala:98)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.toWomGraph(WdlDraft2WomGraphMaker.scala:18)
	at wom.transforms.WomGraphMaker$Ops.toWomGraph(WomGraphMaker.scala:8)
	at wom.transforms.WomGraphMaker$Ops.toWomGraph$(WomGraphMaker.scala:8)
	at wom.transforms.WomGraphMaker$ops$$anon$1.toWomGraph(WomGraphMaker.scala:8)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomScatterNodeMaker$.$anonfun$toWomScatterNode$9(WdlDraft2WomScatterNodeMaker.scala:55)
	at common.validation.ErrorOr$ShortCircuitingFlatMap$.flatMap$extension(ErrorOr.scala:27)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomScatterNodeMaker$.$anonfun$toWomScatterNode$7(WdlDraft2WomScatterNodeMaker.scala:52)
	at common.validation.ErrorOr$ShortCircuitingFlatMap$.flatMap$extension(ErrorOr.scala:27)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomScatterNodeMaker$.toWomScatterNode(WdlDraft2WomScatterNodeMaker.scala:51)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomScatterNodeMaker$.toWomScatterNode(WdlDraft2WomScatterNodeMaker.scala:15)
	at wom.transforms.WomScatterNodeMaker$Ops.toWomScatterNode(WomScatterNodeMaker.scala:10)
	at wom.transforms.WomScatterNodeMaker$Ops.toWomScatterNode$(WomScatterNodeMaker.scala:10)
	at wom.transforms.WomScatterNodeMaker$ops$$anon$1.toWomScatterNode(WomScatterNodeMaker.scala:10)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.buildNode$1(WdlDraft2WomGraphMaker.scala:90)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.$anonfun$toWomGraph$3(WdlDraft2WomGraphMaker.scala:38)
	at common.validation.ErrorOr$ShortCircuitingFlatMap$.flatMap$extension(ErrorOr.scala:27)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.foldFunction$1(WdlDraft2WomGraphMaker.scala:37)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.$anonfun$toWomGraph$14(WdlDraft2WomGraphMaker.scala:98)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.toWomGraph(WdlDraft2WomGraphMaker.scala:98)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomGraphMaker$.toWomGraph(WdlDraft2WomGraphMaker.scala:18)
	at wom.transforms.WomGraphMaker$Ops.toWomGraph(WomGraphMaker.scala:8)
	at wom.transforms.WomGraphMaker$Ops.toWomGraph$(WomGraphMaker.scala:8)
	at wom.transforms.WomGraphMaker$ops$$anon$1.toWomGraph(WomGraphMaker.scala:8)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomWorkflowDefinitionMaker$.toWomWorkflowDefinition(WdlDraft2WomWorkflowDefinitionMaker.scala:14)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomWorkflowDefinitionMaker$.toWomWorkflowDefinition(WdlDraft2WomWorkflowDefinitionMaker.scala:10)
	at wom.transforms.WomWorkflowDefinitionMaker$Ops.toWomWorkflowDefinition(WomWorkflowDefinitionMaker.scala:8)
	at wom.transforms.WomWorkflowDefinitionMaker$Ops.toWomWorkflowDefinition$(WomWorkflowDefinitionMaker.scala:8)
	at wom.transforms.WomWorkflowDefinitionMaker$ops$$anon$1.toWomWorkflowDefinition(WomWorkflowDefinitionMaker.scala:8)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomBundleMakers$$anon$1.$anonfun$toWomBundle$1(WdlDraft2WomBundleMakers.scala:19)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:63)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$2(list.scala:65)
	at cats.Eval$.advance(Eval.scala:272)
	at cats.Eval$.loop$1(Eval.scala:354)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
	at cats.Eval$Defer.value(Eval.scala:258)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:72)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
	at cats.Traverse$Ops.traverse(Traverse.scala:19)
	at cats.Traverse$Ops.traverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomBundleMakers$$anon$1.toWomBundle(WdlDraft2WomBundleMakers.scala:19)
	at wdl.transforms.draft2.wdlom2wom.WdlDraft2WomBundleMakers$$anon$1.toWomBundle(WdlDraft2WomBundleMakers.scala:17)
	at wom.transforms.WomBundleMaker$Ops.toWomBundle(WomExecutableMaker.scala:16)
	at wom.transforms.WomBundleMaker$Ops.toWomBundle$(WomExecutableMaker.scala:16)
	at wom.transforms.WomBundleMaker$ops$$anon$2.toWomBundle(WomExecutableMaker.scala:16)
	at languages.wdl.draft2.WdlDraft2LanguageFactory.$anonfun$getWomBundle$3(WdlDraft2LanguageFactory.scala:120)
	at scala.util.Either.flatMap(Either.scala:338)
	at languages.wdl.draft2.WdlDraft2LanguageFactory.$anonfun$getWomBundle$1(WdlDraft2LanguageFactory.scala:119)
	at scala.util.Either.flatMap(Either.scala:338)
	at languages.wdl.draft2.WdlDraft2LanguageFactory.getWomBundle(WdlDraft2LanguageFactory.scala:118)
	at womtool.input.WomGraphMaker$.$anonfun$getBundleAndFactory$1(WomGraphMaker.scala:49)
	at scala.util.Either.flatMap(Either.scala:338)
	at womtool.input.WomGraphMaker$.getBundleAndFactory(WomGraphMaker.scala:40)
	at womtool.input.WomGraphMaker$.getBundle(WomGraphMaker.scala:22)
	at womtool.validate.Validate$.validate(Validate.scala:14)
	at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:47)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:134)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:139)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:21)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:21)
	at womtool.WomtoolMain.main(WomtoolMain.scala)
