### ISSUE TITLE
Fix import zip heuristic to determine root directory

### ISSUE THREAD

**Issue by Horneth** [broadinstitute/cromwell#3297]
When being passed an import zip file, Cromwell behavior is currently as follows:

Lists the content of the zip, if the first element encountered is a directory, this directory is considered the root of imports from which imported files in the workflow are to be resolved.
This means that in the following case:

```
Archive:  imports.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  02-20-18 11:35   tasks/
     4793  02-20-18 11:35   tasks/alignment.wdl
    10530  02-20-18 11:35   tasks/bam_processing.wdl
        6  02-22-18 14:11   lost_import.wdl
```

`lost_import.wdl` will not be found because the root for import resolving will be `tasks`.

I believe this behavior exists to help users that inadvertently zipped the directory containing their imports instead of placing them at the root of the zip.
While maybe convenient this is IMO an awkward special case:

```
Archive:  imports.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  02-20-18 11:35   tasks/
     4793  02-20-18 11:35   tasks/alignment.wdl
    10530  02-20-18 11:35   tasks/bam_processing.wdl
```

incorrect: 
```wdl
  import "tasks/alignment.wdl" as my_tasks
```

correct:
```wdl
  import "alignment.wdl" as my_tasks
```

If we want to keep this behavior I think we should at least change the root if and only if the root of the zip is 1 directory.
I'd advocate to remove this behavior entirely but it would potentially be backward incompatible.

@geoffjentry you might have opinions on this

**Comment by genomics-geek** [comment]
I am having an issue when trying to use `--imports tasks.zip` with Cromwell.  I assume it is related to this issue.  I can't seem to make it work with imports.  I assume the parameter `--workflow-root` may be an alternative to using `imports`?  However, instead of using zip imports, I tried using `--workflow-root` and still did not work.  Thanks in advance for any help.

Details of my scenario:

In my workflow I have:

```
import "tasks/task-1.wdl" as task1
import "tasks/task-2.wdl" as task2
```

my zip file looks like this:

```
c4b301bb01ef:Desktop gonzalezma$ unzip -l tasks.zip 
Archive:  tasks.zip
  Length     Date   Time    Name
 --------    ----   ----    ----
      128  03-17-18 11:57   tasks/task-1.wdl
      119  03-17-18 11:57   tasks/task-2.wdl
 --------                   -------
      247                   2 files
```

Cromwell fails and says it can't find the task wdl files.  How do I make this work?  

The detailed error is as follows:

```
[2018-03-17 14:23:42,03] [error] WorkflowManagerActor Workflow 6d61108d-3a3c-4850-8bd9-2862660f953c failed (during MaterializingWorkflowDescriptorState): Workflow input processing failed:
/var/folders/zm/35r081w17gn1nw2kksqjlp6dyhcq01/T/7591430002708022127.zip7406634406151397777/tasks/task-1.wdl
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
/var/folders/zm/35r081w17gn1nw2kksqjlp6dyhcq01/T/7591430002708022127.zip7406634406151397777/tasks/task-1.wdl
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:203)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:173)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:168)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:665)
	at akka.actor.FSM.processEvent$(FSM.scala:662)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:126)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:801)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:783)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:126)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:126)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by Horneth** [comment]
Hi ! I would advise you to try removing the "tasks" directory and put the wdls directly at the root of the zip file. And also edit the workflow and remove the `tasks/` part of the import statement of course. The `workflowRoot` is currently only useful to run CWL workflows (which is coming very soon but still under development)

**Comment by genomics-geek** [comment]
@Horneth - thanks for the information - this works. 

So I had organized my WDL tasks into folders just for organizational purposes (just like you had posted above).  Sorry if you have answered this before, but is this going to be supported down the road?  Or should I just make sure all WDL tasks are in one folder at the same level?  

Thanks again for getting back to me so quickly

**Comment by Horneth** [comment]
The current behavior when using sub folders is a bug IMO. So yes I would expect this to be fixed !

**Comment by cjllanwarne** [comment]
I agree that "we'll unpack exactly one directory and make the result the root of your imports" is a weird thing to do.

There's a separate but also important question of whether all import paths should be relative to (a) the root of the imports zip; (b) the current WDL; or (c) both, with some tie-breaker in case of collision?

**Comment by genomics-geek** [comment]
@Horneth - haha nice! Yea it would be really nice to have the ability to have sub folders in the zip file - but for now your solution is working for me.  Thanks again.

@cjllanwarne - I would probably vote (b) imports should be relative to the current WDL - I guess similar to how python deals with relative imports.  But I can imagine there are a number of complications with that when using a separate zip file as an input parameter.
