### ISSUE TITLE
re-armorment

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#3410]
Re-armor the Rhino in a way that plays nice with real world CWLs like Wash U rnaseq and doesn't do this:

```
Caused by: java.lang.IllegalStateException
    at org.mozilla.javascript.ContextFactory.initGlobal(ContextFactory.java:177)
    at cwl.internal.EnhancedRhinoSandbox.assertContextFactory(EnhancedRhinoSandbox.scala:94)
    at cwl.internal.EnhancedRhinoSandbox.eval(EnhancedRhinoSandbox.scala:42)
    at cwl.internal.EcmaScriptUtil$.evalRaw(EcmaScriptUtil.scala:71)
```

**Comment by mcovarr** [comment]
Fixed in #3450
