### ISSUE TITLE
`1.0` passthrough float output inappropriately coerced to int

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#3480]
While trying to write call caching tests. Note the `rCopy` is just a recycled `float` input.

```
{
  "radius": 1.0
}
```

```
cwlVersion: v1.0
class: Workflow
# Workflow-level DockerRequirement
requirements:
  DockerRequirement:
    dockerPull: "ubuntu:latest"
inputs:
- id: radius
  type: float
outputs:
- id: area
  outputSource: "#one/rSquared"
  type: float
steps:
- id: one
  in:
  - id: radius
    source: "#radius"
  out:
  - id: rSquared
  - id: rCopy
  run:
    inputs:
    - id: radius
      type: float
    outputs:
    - id: rSquared
      outputBinding:
        glob: stdout.txt
        loadContents: true
        outputEval: $(parseFloat(self[0].contents))
      type: float
    - id: rCopy
      outputBinding:
        outputEval: $(inputs.radius)
      type: float
    class: CommandLineTool
    requirements:
    - class: ShellCommandRequirement
    arguments:
    - valueFrom: echo
    - valueFrom: "`expr "
      shellQuote: false
    - valueFrom: $(inputs.radius)
    - valueFrom: "*"
      shellQuote: false
    - valueFrom: $(inputs.radius)
    - valueFrom: "`"
      shellQuote: false
    stdout: stdout.txt
```

```
name: cwl_caching
testFormat: workflowsuccess
backendsMode: "only"
backends: [Local]
tags: [localdockertest]

files {
  wdl: cwl_caching/cwl_caching.cwl
  inputs: cwl_caching/cwl_caching.json
}

metadata {
  status: Succeeded
}

workflowType: CWL
workflowTypeVersion: v1.0
```

```
cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'rCopy': No coercion defined from '1' of type 'Int' to 'Float'.
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:688)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by cjllanwarne** [comment]
WDL expects to be able to coerce `Int` into `Float`, FWIW
