### ISSUE TITLE
Preemptible exits not retried in Papi V2 

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/cromwell#3732]
See [this travis build](https://travis-ci.org/broadinstitute/cromwell/builds/388562204) for an example where Papi V1 was retrying preemption and Papi V2 was failing.

```
   9605 2018-06-06 11:02:59,838 cromwell-system-akka.dispatchers.engine-dispatcher-32 ERROR - WorkflowManagerActor Workflow c9dfd3ed-8be8-413f-af46-4692142b3248 failed (during ExecutingWorkflowState): Task JointGenotyping.ApplyRecalibration:16:1 failed. Job exited without an error, exit code 0. PAPI error code 9.  Message: Execution failed: action 14: unexpected exit status 1 was not ignored
   9606 Execution failed: action 14: unexpected exit status 1 was not ignored
   9607 Unexpected exit status 1 while running "/bin/sh -c gsutil cp /cromwell_root/stdout gs://cloud-cromwell-dev/cromwell_execution/travis/JointGenotyping/c9dfd3ed-8be8-413f-af46-4692142b3248/call-ApplyRecalibration/shard-16/stdout"
   9608 java.lang.Exception: Task JointGenotyping.ApplyRecalibration:16:1 failed. Job exited without an error, exit code 0. PAPI error code 9.  Message: Execution failed: action 14: unexpected exit status 1 was not ignored
   9609 Execution failed: action 14: unexpected exit status 1 was not ignored
   9610 Unexpected exit status 1 while running "/bin/sh -c gsutil cp /cromwell_root/stdout gs://cloud-cromwell-dev/cromwell_execution/travis/JointGenotyping/c9dfd3ed-8be8-413f-af46-4692142b3248/call-ApplyRecalibration/shard-16/stdout"
   9611         at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor$.StandardException(PipelinesApiAsyncBackendJobExecutionActor.scala:76)
   9612         at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleFailedRunStatus$1(PipelinesApiAsyncBackendJobExecutionActor.scala:532)
   9613         at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:539)
   9614         at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:80)
   9615         at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionResult$3(StandardAsyncExecutionActor.scala:1037)
   9616         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
   9617         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
   9618         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
   9619         at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
   9620         at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
   9621         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
   9622         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
   9623         at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
   9624         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
   9625         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
   9626         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
   9627         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
   9628         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
   9629         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
   9630 
   9631 2018-06-06 11:02:59,840 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowManagerActor WorkflowActor-c9dfd3ed-8be8-413f-af46-4692142b3248 is in a terminal state: WorkflowFailedState
   9632 - should successfully run jointdiscovery *** FAILED *** (2 hours, 13 minutes, 31 seconds)
   9633   java.lang.Exception: Unexpected terminal status Failed but was waiting for Succeeded
   9634   at centaur.test.Operations$$anon$9.doPerform(Test.scala:185)
   9635   at centaur.test.Operations$$anon$9.$anonfun$run$7(Test.scala:200)
   9636   at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
   9637   at scala.util.Success.$anonfun$map$1(Try.scala:251)
   9638   at scala.util.Success.map(Try.scala:209)
   9639   at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
   9640   at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
   9641   at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
   9642   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
   9643   at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
   9644   ...
```

NOTE: Preemption has since been disabled in Travis due to CRON builds being terminated after three hours.

**Comment by ruchim** [comment]
This looks like the preemption error codes are different in PAPI v2. I don't think we expected this

**Comment by Horneth** [comment]
@kshakir I'm hoping this will have fixed this issue. https://github.com/broadinstitute/cromwell/pull/3722/files#diff-7287553692b182c8a58bcbb673e7c398R63
Unavailable is the status I was told would be sent back when the VM gets preempted (or at least there's a very high likelihood that's the reason)

**Comment by kshakir** [comment]
@Horneth was right. Haven't seen this after a rebase / merge to develop.
