### ISSUE TITLE
SGE resource 'cpu' binding error

### ISSUE THREAD

**Issue by aukluobo** [broadinstitute/cromwell#3805]
I clone the source code and assembly the jar. when try to run a sge job, I got and error. the log is following:

[2018-06-21 20:36:29,51] [error] DispatchedConfigAsyncJobExecutionActor [7ec0863atestsge.filter:NA:1]: Error attempting to Execute
java.lang.IllegalArgumentException: No coercion defined from '1' of type 'eu.timepit.refined.api.Refined' to 'Int'.
        at wom.types.WomType.coerceRawValue(WomType.scala:36)
        at wom.types.WomType.coerceRawValue$(WomType.scala:27)
        at wom.types.WomIntegerType$.coerceRawValue(WomIntegerType.scala:9)
        at cromwell.backend.impl.sfs.config.DeclarationValidation.$anonfun$extractWdlValueOption$1(DeclarationValidation.scala:113)
        at scala.Option.map(Option.scala:146)
        at cromwell.backend.impl.sfs.config.DeclarationValidation.extractWdlValueOption(DeclarationValidation.scala:113)
        at cromwell.backend.impl.sfs.config.ConfigAsyncJobExecutionActor.$anonfun$runtimeAttributeInputs$1(ConfigAsyncJobExecutionActor.scala:163)

I use the SGE backend 

 this is my WDL workflow
"""
workflow testsge{
        String Outdir
        String JobName="filter"
        call filter{input:outdir=Outdir,jobname=JobName}
}

task filter{
        String outdir
        String jobname
        command<<<
                echo "test successful" >>${outdir}/log.stdout
                echo 1
                perl -we '{print STDERR 2;}'
                Script="${jobname}"
                Sleep=$SGE_TASK_ID
                QsubRcControl=3
                QsubType=1
        >>>
        runtime{
                backend:"SGE"
                memory:"1 GB"
                sge_queue:"test.q -P test -t 1-3"
                sge_project:"test"
                jobs_name:"${jobname}"
        }
        output{
                String presuccess="done"
                Int rc=read_lines(stdout())[0]
        }
}
"""

this my runtime-attributes setting in the reference.conf file

runtime-attributes = """
        Int cpu = 1
        Float? memory_gb
        String? jobs_name
        String? sge_queue
        String? sge_project
        """

        submit = """
        qsub \
        -clear \
        -terse \
        -N ${job_name} \
        -wd ${cwd}/execution \
        -o ${out}.qsub \
        -e ${err}.qsub \
        ${"-l vf=" + memory_gb +"g,num_proc=" + cpu} \
        ${"-q " + sge_queue} \
        -binding ${"linear:" + cpu} \
        ${script} | perl -ne 's/\..*//;print;'
        """

        kill = "qdel ${job_id}"
        check-alive = "qstat -j ${job_id}"
        job-id-regex = "(\\d+)"
      }

**Comment by Horneth** [comment]
Thanks for reporting this !
It is indeed a recently introduced bug, [this PR](https://github.com/broadinstitute/cromwell/pull/3812) fixes it.
