### ISSUE TITLE
valueFrom in input binding in CWL CommandLineTool ignored

### ISSUE THREAD

**Issue by dpfoose** [broadinstitute/cromwell#3958]
When running a CWL workflow that uses a CWL CommandLineTool with a `valueFrom` field in an `inputBinding` field, the `valueFrom` field is ignored and the input is considered unbound. According to the CWL v1.0 standard, this input should be bound to the value in `valueFrom` unless another value is provided as the tool's input in the workflow.

The binding is also ignored when the input is defined as optional.

The CommandLineTool definition:
```
class: CommandLineTool
cwlVersion: v1.0
id: 13CNMR
baseCommand:
  - batchprocessNMR.py
inputs:
  - id: inputFiles
    type: File[]
    inputBinding:
      position: 0
  - id: frequency
    type: float
    inputBinding:
      position: 1
      valueFrom: '150819500.0'
outputs:
  - id: output
    type: File[]
    outputBinding:
      glob: '*.h5'
label: 13C-NMR
```

The output:
```
2018-08-02 02:23:01,272 cromwell-system-akka.dispatchers.api-dispatcher-105 INFO  - CWL (v1.0) workflow cfc7b055-b8a3-40c4-a0eb-b4636d5c7286 submitted
2018-08-02 02:23:03,860 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - 1 new workflows fetched
2018-08-02 02:23:03,860 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - WorkflowManagerActor Starting workflow UUID(cfc7b055-b8a3-40c4-a0eb-b4636d5c7286)
2018-08-02 02:23:03,860 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - WorkflowManagerActor Successfully started WorkflowActor-cfc7b055-b8a3-40c4-a0eb-b4636d5c7286
2018-08-02 02:23:03,861 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2018-08-02 02:23:03,863 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - MaterializeWorkflowDescriptorActor [UUID(cfc7b055)]: Parsing workflow as CWL v1.0
2018-08-02 02:23:03,869  INFO  - Pre-Processing /tmp/cfc7b055-b8a3-40c4-a0eb-b4636d5c7286.temp.1620266732058368635/cfc7b055-b8a3-40c4-a0eb-b4636d5c7286.cwl
2018-08-02 02:23:05,504  INFO  - Pre-Processing /modules/file-parsers/parsetxtxy.cwl
2018-08-02 02:23:07,089  INFO  - Pre-Processing /modules/processing-modules/13C-NMR.cwl
2018-08-02 02:23:08,703  INFO  - Pre-Processing /modules/core-modules/uploadsamples.cwl
2018-08-02 02:23:10,570 cromwell-system-akka.dispatchers.engine-dispatcher-29 ERROR - WorkflowManagerActor Workflow cfc7b055-b8a3-40c4-a0eb-b4636d5c7286 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Input frequency is required and is not bound to any value
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:200)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:170)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:165)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:670)
	at akka.actor.FSM.processEvent$(FSM.scala:667)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:806)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:788)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:664)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:658)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:123)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2018-08-02 02:23:10,572 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - WorkflowManagerActor WorkflowActor-cfc7b055-b8a3-40c4-a0eb-b4636d5c7286 is in a terminal state: WorkflowFailedState
```

**Comment by mr-c** [comment]
Interesting. To me, `valueFrom` with a non-expression only makes sense for within the `arguments` section, but I agree that the CWl specification isn't clear on this.

As a workaround I suggest using the `default` field one level up, as that appears to be the user intent here:

``` cwl
class: CommandLineTool
cwlVersion: v1.0
id: 13CNMR
baseCommand: batchprocessNMR.py
inputs:
  inputFiles:
    type: File[]
    inputBinding:
      position: 0
  frequency:
    type: float?
    default: 150819500.0
    inputBinding:
      position: 1
outputs:
  output:
    type: File[]
    outputBinding:
      glob: '*.h5'
label: 13C-NMR
