### ISSUE TITLE
womtool validate explodes & hangs when import points to non-existent local path

### ISSUE THREAD

**Issue by danxmoran** [broadinstitute/cromwell#3977]
While doing some WDL refactoring, we changed a local (relative) import but forgot to rename the imported file to match. When we ran `womtool validate` on the importing workflow, it dumped the following stack trace and then hung:
```
Exception in thread "main" java.net.UnknownHostException: tasks%2FAlignment.wdl: Name or service not known
    at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
    at java.net.InetAddress.getAllByName(InetAddress.java:1192)
    at java.net.InetAddress.getAllByName(InetAddress.java:1126)
    at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:159)
    at io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:156)
    at java.security.AccessController.doPrivileged(Native Method)
    at io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:156)
    at io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:52)
    at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:81)
    at io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:73)
    at org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:50)
    at org.asynchttpclient.netty.request.NettyRequestSender.resolveAddresses(NettyRequestSender.java:355)
    at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:298)
    at org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:140)
    at org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:111)
    at org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:240)
    at org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:209)
    at org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:35)
    at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend.$anonfun$send$1(AsyncHttpClientBackend.scala:53)
    at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend.$anonfun$send$1$adapted(AsyncHttpClientBackend.scala:42)
    at cats.effect.IO$.$anonfun$async$1(IO.scala:1042)
    at cats.effect.IO$.$anonfun$async$1$adapted(IO.scala:1040)
    at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:329)
    at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:118)
    at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:35)
    at cats.effect.IO.unsafeRunAsync(IO.scala:269)
    at cats.effect.IO.unsafeToFuture(IO.scala:341)
    at cromwell.languages.util.ImportResolver$.$anonfun$httpResolverWithHeaders$1(ImportResolver.scala:92)
    at common.transforms.package$CheckedAtoB$.$anonfun$firstSuccess$2(package.scala:25)
    at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
    at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
    at scala.collection.immutable.List.foldLeft(List.scala:86)
    at common.transforms.package$CheckedAtoB$.$anonfun$firstSuccess$1(package.scala:22)
    at cats.data.Kleisli.$anonfun$andThen$1(Kleisli.scala:37)
    at wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.wdl$draft3$transforms$wdlom2wom$FileElementToWomBundle$$importWomBundle(FileElementToWomBundle.scala:101)
    at wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.$anonfun$toWomBundle$11(FileElementToWomBundle.scala:74)
    at cats.instances.VectorInstances$$anon$1.$anonfun$traverse$2(vector.scala:77)
    at cats.instances.VectorInstances$$anon$1.loop$2(vector.scala:40)
    at cats.instances.VectorInstances$$anon$1.$anonfun$foldRight$2(vector.scala:41)
    at cats.Eval$.advance(Eval.scala:272)
    at cats.Eval$.loop$1(Eval.scala:354)
    at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
    at cats.Eval$Defer.value(Eval.scala:258)
    at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:76)
    at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:12)
    at cats.Traverse$Ops.traverse(Traverse.scala:19)
    at cats.Traverse$Ops.traverse$(Traverse.scala:19)
    at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
    at wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.toWomBundle(FileElementToWomBundle.scala:74)
    at wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$$anon$1.toWomBundle(FileElementToWomBundle.scala:30)
    at wom.transforms.WomBundleMaker$Ops.toWomBundle(WomExecutableMaker.scala:16)
    at wom.transforms.WomBundleMaker$Ops.toWomBundle$(WomExecutableMaker.scala:16)
    at wom.transforms.WomBundleMaker$ops$$anon$2.toWomBundle(WomExecutableMaker.scala:16)
    at wdl.draft3.transforms.wdlom2wom.FileElementToWomBundle$.convert(FileElementToWomBundle.scala:83)
    at wdl.draft3.transforms.wdlom2wom.package$.$anonfun$fileElementToWomBundle$1(package.scala:13)
    at scala.util.Either$RightProjection.flatMap(Either.scala:702)
    at cats.instances.EitherInstances$$anon$1.flatMap(either.scala:36)
    at cats.instances.EitherInstances$$anon$1.flatMap(either.scala:32)
    at cats.data.Kleisli.$anonfun$andThen$1(Kleisli.scala:37)
    at languages.wdl.draft3.WdlDraft3LanguageFactory.getWomBundle(WdlDraft3LanguageFactory.scala:50)
    at womtool.input.WomGraphMaker$.$anonfun$getBundleAndFactory$1(WomGraphMaker.scala:49)
    at scala.util.Either.flatMap(Either.scala:338)
    at womtool.input.WomGraphMaker$.getBundleAndFactory(WomGraphMaker.scala:40)
    at womtool.input.WomGraphMaker$.getBundle(WomGraphMaker.scala:22)
    at womtool.validate.Validate$.validate(Validate.scala:14)
    at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:44)
    at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:125)
    at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:130)
    at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:18)
    at scala.Function0.apply$mcV$sp(Function0.scala:34)
    at scala.Function0.apply$mcV$sp$(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App.$anonfun$main$1$adapted(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:389)
    at scala.App.main(App.scala:76)
    at scala.App.main$(App.scala:74)
    at womtool.WomtoolMain$.main(WomtoolMain.scala:18)
    at womtool.WomtoolMain.main(WomtoolMain.scala)
```

**Comment by aednichols** [comment]
I guess it tries file imports first, then moves on to HTTP imports - which fails because of course your file name isn't a resolvable DNS name!

Thanks for the report.

**Comment by cjllanwarne** [comment]
@danxmoran I'm trying to recreate this - could you list the `womtool` version that you're using and a minimal WDL that reproduces the issue?

Note: I tried to recreate on `develop` using this WDL:
```wdl
version 1.0

import "not/a/file.wdl" as oops

workflow foo {
  call oops.not_a_thing
}
```

And received an error message and an exit code of 1:
```
Failed to import 'not/a/file.wdl' (reason 1 of 3): Failed to resolve 'not/a/file.wdl' using resolver: 'relative to directory [...]/cromwell (without escaping Some([...]/cromwell))' (reason 1 of 1): Import file not found: not/a/file.wdl
Failed to import 'not/a/file.wdl' (reason 2 of 3): Failed to resolve 'not/a/file.wdl' using resolver: 'relative to directory [...]/bad_import (without escaping None)' (reason 1 of 1): Import file not found: not/a/file.wdl
Failed to import 'not/a/file.wdl' (reason 3 of 3): Failed to resolve 'not/a/file.wdl' using resolver: 'http importer' (reason 1 of 1): Cannot import 'not/a/file.wdl' relative to nothing
```

**Comment by danxmoran** [comment]
`womtool --version` gives "womtool cromwell-version.conf-to-be-generated-by-sbt" 🤦‍♂️ But based on the jar name it should be 63637a6.

That test WDL gives me the same stack trace using our jar, so it's probably been fixed on develop in the time since we assembled it.
