### ISSUE TITLE
CWL restart problem when reading from cache -- unrecognized simpleton WOM type: Long

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/cromwell#4023]
Hi;
I'm running Cromwell 34 and hitting an issue when reading from a cache. The problematic CWL step uses a variable, `min_allele_fraction` that is initially an array of longs:

https://github.com/bcbio/test_bcbio_cwl/blob/eae685b8023126b7f159d3048f4ab4dd1a1833d6/prealign/prealign-workflow/steps/batch_for_variantcall.cwl#L101

and then gets converted into a record with individual long elements:

https://github.com/bcbio/test_bcbio_cwl/blob/eae685b8023126b7f159d3048f4ab4dd1a1833d6/prealign/prealign-workflow/steps/batch_for_variantcall.cwl#L309

This all works fine on the first run of a pipeline, but when reading the step from the cache we get an error about not supporting `Long`:
```
[2018-08-21 10:26:40,02] [info] WorkflowExecutionActor-3e76006c-870a-4c34-9f21-949eee1a5b33 [3e76006c]: Starting batch_for_variantcall
[2018-08-21 10:26:41,10] [error] unrecognized simpleton WOM type: Long
java.lang.RuntimeException: unrecognized simpleton WOM type: Long
        at cromwell.Simpletons$.toSimpleton(Simpletons.scala:30)
        at cromwell.Simpletons$.toSimpleton(Simpletons.scala:16)
        at cromwell.engine.workflow.lifecycle.execution.callcaching.FetchCachedResultsActor.$anonfun$new$2(FetchCachedResultsActor.scala:32)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at cromwell.engine.workflow.lifecycle.execution.callcaching.FetchCachedResultsActor.$anonfun$new$1(FetchCachedResultsActor.scala:32)
        at cromwell.engine.workflow.lifecycle.execution.callcaching.FetchCachedResultsActor.$anonfun$new$1$adapted(FetchCachedResultsActor.scala:30)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
I can reproduce with this test CWL workflow (https://github.com/bcbio/test_bcbio_cwl/tree/master/prealign). The first time running will work fine, and then if you re-run using the cache from the previous run it fails as above.

Thanks for any thoughts/tips about what is going wrong here and how best to fix.

**Comment by aednichols** [comment]
Thanks for reporting, Cromwell definitely shouldn't write something to cache that it cannot read back! 

If you can bear it, a workaround would be to run without call-caching.

---

It looks like we're (at least) missing a
```
case "Long" => WomLongType.coerceRawValue
```
in https://github.com/broadinstitute/cromwell/blob/develop/engine/src/main/scala/cromwell/Simpletons.scala#L25

**Comment by chapmanb** [comment]
Adam;
Thanks so much for looking into this. I'm glad the error makes sense and is translatable to a fix for re-reading. We love call caching for job re-use so prefer not to disable it for now. Looking forward to this fix and having cleaner runs going forward. Thanks again.

**Comment by ruchim** [comment]
Hey @chapmanb, 

Thanks for reporting this! Is it possible to use an array of strings for now? This way you can continue to use call caching?

**Comment by aednichols** [comment]
@chapmanb things lined up nicely to make this a pretty easy fix; it will be in the next release of Cromwell.

**Comment by chapmanb** [comment]
Adam -- awesome, thank you for the quick fix. Ruchi -- Nice idea. I ended up used float instead of long for these as a temporary workaround. Thank you both again for all the help.
