### ISSUE TITLE
continueOnReturnCode doesn't appear to work?

### ISSUE THREAD

**Issue by wbrockman** [broadinstitute/cromwell#404]
https://github.com/broadinstitute/cromwell#continueonreturncode
doesn't seem to work as documented for me.  Here's the test I ran, and the behavior was identical to the behavior without continueOnReturnCode as far as I can tell. 

This isn't a high priority for me - I believe we can get the information we need without this option. 

# cat error_continue.wdl
task hello {
  String addressee
  command {
    echo "Hello ${addressee}!" && exit 1
  }
  output {
    String salutation = read_string(stdout())
  }
  runtime {
    docker: "ubuntu:latest"
    continueOnReturnCode: true
  }
}

workflow w {
  call hello
}
# curl -v "localhost:8000/api/workflows/v1" -F wdlSource=@error_continue.wdl -F workflowInputs=@hello.inputs
-> {
  "id": "dbd26ad6-5a29-4c80-8f49-8b5f53830782",
  "status": "Submitted"
}
curl -v "localhost:8000/api/workflows/v1/dbd26ad6-5a29-4c80-8f49-8b5f53830782/status"
-> {
  "id": "dbd26ad6-5a29-4c80-8f49-8b5f53830782",
  "status": "Failed"
}
curl -v "localhost:8000/api/workflows/v1/dbd26ad6-5a29-4c80-8f49-8b5f53830782/outputs"
{
  "id": "dbd26ad6-5a29-4c80-8f49-8b5f53830782",
  "outputs": {

  }
}

**Comment by cjllanwarne** [comment]
I think this is actually a separate problem w.r.t. how cromwell constructs its script file. If you look in your GCS folder for the exec.sh, you'll probably see something like:
```
echo hello && exit 1
cat $? > rc.txt
```
Although there's no error message returned via the REST api, if you look in the server logs I suspect you'll see something along the lines of "rc file not found"?

**Comment by pgrosu** [comment]
Hi Will,

Try it without the `&& exit 1` portion, as I feel you are exiting before it can complete the workflow.  For instance I ran the following code without the Docker portion on a cluster, and it worked.  Below are all the steps for it:

1)  The wdl file:

```Bash
$ cat error_continue.wdl
task hello {

  String addressee

  command {
    echo "Hello ${addressee}!"
  }

  output {
    String salutation = read_string(stdout())
  }

}

workflow w {
  call hello
}
```

2)  The json inputs file:

```Bash
$ java -jar cromwell.jar inputs error_continue.wdl
{
  "w.hello.addressee": "String"
}
$ java -jar cromwell.jar inputs error_continue.wdl > error_continue.json
$
```

3) And then I ran it:

```Bash
$ java -jar cromwell.jar run error_continue.wdl error_continue.json
[2016-01-25 18:25:31,77] [info] RUN sub-command
[2016-01-25 18:25:31,91] [info]   WDL file: error_continue.wdl
[2016-01-25 18:25:31,92] [info]   Inputs: error_continue.json
[2016-01-25 18:25:31,562] [info] Slf4jLogger started
[2016-01-25 18:25:31,649] [info] SingleWorkflowRunnerActor: launching workflow
[2016-01-25 18:25:32,777] [info] Running with database db.url = jdbc:hsqldb:mem:65a527dd-bc31-462e-bca9-05a545fea48a;shutdown=false;hsqldb.tx=mvcc
[2016-01-25 18:25:33,796] [info] WorkflowManagerActor submitWorkflow input id = None, effective id = 9cdf23a5-1eaa-420a-8fae-ea3e4623d4db
[2016-01-25 18:25:33,812] [info] WorkflowManagerActor Found no workflows to restart.
[2016-01-25 18:25:34,730] [info] WorkflowActor [9cdf23a5]: Start message received
[2016-01-25 18:25:34,997] [info] SingleWorkflowRunnerActor: workflow ID 9cdf23a5-1eaa-420a-8fae-ea3e4623d4db
[2016-01-25 18:25:34,999] [info] WorkflowActor [9cdf23a5]: ExecutionStoreCreated(Start) message received
[2016-01-25 18:25:35,11] [warn] SingleWorkflowRunnerActor: received unexpected message: CurrentState(Actor[akka://cromwell-system/user/WorkflowManagerActor/WorkflowActor-9cdf23a5-1eaa-420a-8fae-ea3e4623d4db#-1942530845],Submitted)
[2016-01-25 18:25:35,12] [info] WorkflowActor [9cdf23a5]: Beginning transition from Submitted to Running.
[2016-01-25 18:25:35,16] [info] WorkflowActor [9cdf23a5]: transitioning from Submitted to Running.
[2016-01-25 18:25:35,17] [info] SingleWorkflowRunnerActor: transitioning to Running
[2016-01-25 18:25:35,19] [info] WorkflowActor [9cdf23a5]: starting calls: w.hello
[2016-01-25 18:25:35,21] [info] WorkflowActor [9cdf23a5]: persisting status of hello to Starting.
[2016-01-25 18:25:35,174] [info] WorkflowActor [9cdf23a5]: inputs for call 'hello':
  addressee -> WdlString(String)
[2016-01-25 18:25:35,177] [info] WorkflowActor [9cdf23a5]: created call actor for hello.
[2016-01-25 18:25:35,186] [info] WorkflowActor [9cdf23a5]: persisting status of hello to Running.
[2016-01-25 18:25:35,231] [info] LocalBackend [9cdf23a5:hello]: echo "Hello String!"
[2016-01-25 18:25:35,279] [info] LocalBackend [9cdf23a5:hello]: command: "/bin/bash" "-c" "cat cromwell-executions/w/9cdf23a5-1eaa-420a-8fae-ea3e4623d4db/call-hello/script |  /bin/bash <&0"
[2016-01-25 18:25:35,305] [info] LocalBackend [9cdf23a5:hello]: Return code: 0
[2016-01-25 18:25:35,377] [info] WorkflowActor [9cdf23a5]: persisting status of hello to Done.
[2016-01-25 18:25:35,413] [info] WorkflowActor [9cdf23a5]: Beginning transition from Running to Succeeded.
[2016-01-25 18:25:35,440] [info] WorkflowActor [9cdf23a5]: transitioning from Running to Succeeded.
{
  "w.hello.salutation": "Hello String!"
}
[2016-01-25 18:25:35,505] [info] SingleWorkflowRunnerActor workflow finished with status 'Succeeded'.
$
```

Hope it helps,
~p

**Comment by wbrockman** [comment]
@cjllanwarne Thanks for the explanation!  Exactly right, this is what the script says: 
#!/bin/bash
export _JAVA_OPTIONS=-Djava.io.tmpdir=/cromwell_root/tmp
export TMPDIR=/cromwell_root/tmp
cd /cromwell_root

echo "Hello foobar!" && exit 1
echo $? > job.rc.txt

@pgrosu The exit 1 was the purpose here - I was modifying the basic hello.wdl test, trying to do a lightweight test simulating the failure of the binary being called.  Turns out, as @cjllanwarne explains, that exit 1 is not a good way to simulate that, because it defeats Cromwell's return-code monitoring.  Here's a better test, which does work as expected: 

task hello {
  String addressee
  command {
    echo "Hello ${addressee}!" && head nonexistent
  }
  output {
    String salutation = read_string(stdout())
  }
  runtime {
    docker: "ubuntu:latest"
    continueOnReturnCode: true
  }
}

workflow w {
  call hello
}

**Comment by pgrosu** [comment]
Hi Will,

I see, but unfortunately I still get an error - I ran the your updated workflow without the Docker portion and specifically sent an `SIGINT`, and it looks like it ended with an error.  Below are the steps - hope this does not affect the launch schedule:

```Bash
$ cat error_continue.wdl
task hello {
String addressee
command {
echo "Hello ${addressee}!" && kill -SIGINT $BASHPID
}
output {
String salutation = read_string(stdout())
}
runtime {
continueOnReturnCode: true
}
}

workflow w {
call hello
}
$
$ java -jar cromwell.jar inputs error_continue.wdl
This functionality is deprecated and will be removed in 0.18. Please use wdltool: https://github.com/broadinstitute/wdltool
{
  "w.hello.addressee": "String"
}
$
$ java -jar cromwell.jar inputs error_continue.wdl > error_continue.json
This functionality is deprecated and will be removed in 0.18. Please use wdltool: https://github.com/broadinstitute/wdltool
$
$ java -jar cromwell.jar run error_continue.wdl error_continue.json
[2016-01-31 16:37:25,449] [info] RUN sub-command
[2016-01-31 16:37:25,469] [info]   WDL file: error_continue.wdl
[2016-01-31 16:37:25,471] [info]   Inputs: error_continue.json
[2016-01-31 16:37:25,989] [info] Slf4jLogger started
[2016-01-31 16:37:26,86] [info] SingleWorkflowRunnerActor: launching workflow
[2016-01-31 16:37:27,345] [info] Running with database db.url = jdbc:hsqldb:mem:748afb13-e3af-4e9d-af14-5c2b3bd209a9;shutdown=false;hsqldb.tx=mvcc
[2016-01-31 16:37:28,247] [info] WorkflowManagerActor submitWorkflow input id = None, effective id = 2a89a995-aa89-4172-a5e1-1054cbccd9e0
[2016-01-31 16:37:28,291] [info] WorkflowManagerActor Found no workflows to restart.
[2016-01-31 16:37:28,660] [info] WorkflowActor [2a89a995]: Start(Some(Actor[akka://cromwell-system/user/SingleWorkflowRunnerActor#-896492658])) message received
[2016-01-31 16:37:28,788] [info] WorkflowActor [2a89a995]: ExecutionStoreCreated(Start(Some(Actor[akka://cromwell-system/user/SingleWorkflowRunnerActor#-896492658]))) message received
[2016-01-31 16:37:28,789] [info] SingleWorkflowRunnerActor: workflow ID 2a89a995-aa89-4172-a5e1-1054cbccd9e0
[2016-01-31 16:37:28,798] [info] WorkflowActor [2a89a995]: Beginning transition from Submitted to Running.
[2016-01-31 16:37:28,800] [warn] SingleWorkflowRunnerActor: received unexpected message: CurrentState(Actor[akka://cromwell-system/user/WorkflowManagerActor/WorkflowActor-2a89a995-aa89-4172-a5e1-1054cbccd9e0#2034772397],Submitted)
[2016-01-31 16:37:28,800] [info] WorkflowActor [2a89a995]: transitioning from Submitted to Running.
[2016-01-31 16:37:28,801] [info] SingleWorkflowRunnerActor: transitioning to Running
[2016-01-31 16:37:28,804] [info] WorkflowActor [2a89a995]: starting calls: w.hello
[2016-01-31 16:37:28,805] [info] WorkflowActor [2a89a995]: persisting status of hello to Starting.
[2016-01-31 16:37:28,959] [info] WorkflowActor [2a89a995]: inputs for call 'hello':
  addressee -> WdlString(String)
[2016-01-31 16:37:28,962] [info] WorkflowActor [2a89a995]: created call actor for hello.
[2016-01-31 16:37:28,970] [info] WorkflowActor [2a89a995]: persisting status of hello to Running.
[2016-01-31 16:37:28,996] [info] LocalBackend [2a89a995:hello]: echo "Hello String!" && kill -SIGINT $BASHPID
[2016-01-31 16:37:29,19] [info] LocalBackend [2a89a995:hello]: command: "/bin/bash" "-c" "cat cromwell-executions/w/2a89a995-aa89-4172-a5e1-1054cbccd9e0/call-hello/script |  /bin/bash <&0"
[2016-01-31 16:37:29,43] [error] CallActor [2a89a995:hello]: Failing call: Call w.hello, Workflow 2a89a995-aa89-4172-a5e1-1054cbccd9e0: return code was (none)

Full command was: "/bin/bash" "-c" "cat cromwell-executions/w/2a89a995-aa89-4172-a5e1-1054cbccd9e0/call-hello/script |  /bin/bash <&0"

Contents of cromwell-executions/w/2a89a995-aa89-4172-a5e1-1054cbccd9e0/call-hello/stderr were empty.

java.lang.Throwable: Call w.hello, Workflow 2a89a995-aa89-4172-a5e1-1054cbccd9e0: return code was (none)

Full command was: "/bin/bash" "-c" "cat cromwell-executions/w/2a89a995-aa89-4172-a5e1-1054cbccd9e0/call-hello/script |  /bin/bash <&0"

Contents of cromwell-executions/w/2a89a995-aa89-4172-a5e1-1054cbccd9e0/call-hello/stderr were empty.

        at cromwell.engine.backend.local.LocalBackend.cromwell$engine$backend$local$LocalBackend$$runSubprocess(LocalBackend.scala:246)
        at cromwell.engine.backend.local.LocalBackend$$anonfun$execute$1.apply(LocalBackend.scala:144)
        at cromwell.engine.backend.local.LocalBackend$$anonfun$execute$1.apply(LocalBackend.scala:138)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.nio.file.NoSuchFileException: /home/pgrosu/me/cromwell/cromwell/cromwell-executions/w/2a89a995-aa89-4172-a5e1-1054cbccd9e0/call-hello/rc
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3149)
        at better.files.File.loadBytes(File.scala:80)
        at better.files.File.byteArray(File.scala:81)
        at better.files.File.contentAsString(File.scala:91)
        at cromwell.engine.backend.local.LocalBackend$$anonfun$3.apply$mcI$sp(LocalBackend.scala:209)
        at cromwell.engine.backend.local.LocalBackend$$anonfun$3.apply(LocalBackend.scala:208)
        at cromwell.engine.backend.local.LocalBackend$$anonfun$3.apply(LocalBackend.scala:208)
        at scala.util.Try$.apply(Try.scala:192)
        at cromwell.engine.backend.local.LocalBackend.cromwell$engine$backend$local$LocalBackend$$runSubprocess(LocalBackend.scala:207)
        ... 10 common frames omitted
[2016-01-31 16:37:29,45] [info] WorkflowActor [2a89a995]: persisting status of hello to Failed.
[2016-01-31 16:37:29,45] [info] WorkflowActor [2a89a995]: Beginning transition from Running to Failed.
[2016-01-31 16:37:29,59] [info] WorkflowActor [2a89a995]: transitioning from Running to Failed.
[2016-01-31 16:37:29,60] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2016-01-31 16:37:29,61] [error] Workflow 2a89a995-aa89-4172-a5e1-1054cbccd9e0 transitioned to state Failed
java.lang.Throwable: Workflow 2a89a995-aa89-4172-a5e1-1054cbccd9e0 transitioned to state Failed
        at cromwell.engine.workflow.SingleWorkflowRunnerActor$RunnerData.addFailure(SingleWorkflowRunnerActor.scala:41)
        at cromwell.engine.workflow.SingleWorkflowRunnerActor$$anonfun$2.applyOrElse(SingleWorkflowRunnerActor.scala:99)
        at cromwell.engine.workflow.SingleWorkflowRunnerActor$$anonfun$2.applyOrElse(SingleWorkflowRunnerActor.scala:77)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.actor.FSM$class.processEvent(FSM.scala:604)
        at cromwell.engine.workflow.SingleWorkflowRunnerActor.akka$actor$LoggingFSM$$super$processEvent(SingleWorkflowRunnerActor.scala:52)
        at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)
        at cromwell.engine.workflow.SingleWorkflowRunnerActor.processEvent(SingleWorkflowRunnerActor.scala:52)
        at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
        at cromwell.engine.workflow.SingleWorkflowRunnerActor.aroundReceive(SingleWorkflowRunnerActor.scala:52)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Workflow 2a89a995-aa89-4172-a5e1-1054cbccd9e0 transitioned to state Failed
$
```

~p

**Comment by pgrosu** [comment]
I would recommend to make this a finite-state machine and have it resubmit if the script-code performs a `SIGINT` for the following line:

```
val processReturnCode = process.exitValue() // blocks until process finishes
```

Below is the location of the line:

https://github.com/broadinstitute/cromwell/blob/599f1ddb31fb11bfd4fdc4c49f0505aba69e03f3/src/main/scala/cromwell/engine/backend/local/LocalBackend.scala#L203

~p

**Comment by dgtester** [comment]
I might be wrong, but this doesn't seem related to Issue #397 - since the SIGINT is being sent to the bash process, not the Cromwell instance?

**Comment by pgrosu** [comment]
@dgtester Since @geoffjentry just brought me up to speed on the exciting changes coming down the line with #401 (as well as #413), it would probably make more sense to revisit some of these tests afterwards, if they are still pertinent at that time.
