### ISSUE TITLE
Tabs whtitespace does not work

### ISSUE THREAD

**Issue by ffinfo** [broadinstitute/cromwell#4051]
When I try to use tabs as whitespace in cromwell I'm getting a error:
```
[2018-08-29 09:25:20,10] [error] WorkflowManagerActor Workflow 1ed0e19c-fa18-4241-8f6b-0b72e181f59a failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Boxed Error
```

The specs say this should be possible, 0x9 == tab:
https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#whitespace-strings-identifiers-constants

I have tested cromwell 34 and the current develop branch (ce27a93).

wdl file that I used (replaced '\t' with '\<tab\>')
```
version 1.0

workflow Test {
<tab>input {
<tab><tab>
<tab>}

<tab>call Echo as echo {
<tab>input:
<tab>}

<tab>output {
<tab>}
}

task Echo {
<tab>input {
<tab>}

<tab>command {
<tab><tab>kill -9 $$
<tab><tab>echo test
<tab>}

<tab>output {
<tab>}
}
```

Full stacktrace:
```
[2018-08-29 09:25:20,10] [error] WorkflowManagerActor Workflow 1ed0e19c-fa18-4241-8f6b-0b72e181f59a failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Boxed Error
scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:280)
scala.concurrent.Promise.complete(Promise.scala:49)
scala.concurrent.Promise.complete$(Promise.scala:48)
scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
scala.concurrent.Promise.failure(Promise.scala:100)
scala.concurrent.Promise.failure$(Promise.scala:100)
scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:183)
cats.effect.IO.$anonfun$unsafeToFuture$2(IO.scala:341)
scala.util.Either.fold(Either.scala:189)
cats.effect.IO.$anonfun$unsafeToFuture$1(IO.scala:341)
cats.effect.IO.$anonfun$unsafeToFuture$1$adapted(IO.scala:341)
cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:99)
cats.effect.internals.IORunLoop$.start(IORunLoop.scala:35)
cats.effect.IO.unsafeRunAsync(IO.scala:269)
cats.effect.IO.unsafeToFuture(IO.scala:341)
cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$1.$anonfun$applyOrElse$1(MaterializeWorkflowDescriptorActor.scala:152)
scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:206)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:179)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:171)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:670)
	at akka.actor.FSM.processEvent$(FSM.scala:667)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:130)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:806)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:788)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:130)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:664)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:658)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:130)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ruchim** [comment]
@aednichols would you mind investigating this and confirming if this is the case? I believe our centaur tests should be using tabs and such, but let me know if I misunderstood. Thanks!

**Comment by aednichols** [comment]
I'll check it out.

**Comment by aednichols** [comment]
@ffinfo I think something else is going wrong with your workflow than tabs.

I created https://github.com/broadinstitute/cromwell/pull/4059 to verify tabs work and it passed CI.

However, your workflow obviously still doesn't work so I will continue to analyze what might be going on.

**Comment by aednichols** [comment]
@ffinfo the fix will be in the next release of Cromwell.
