### ISSUE TITLE
Workflows occasionally fail due to timeouts on read_* functions

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#4057]
A recent review of Travis test failures revealed that some workflows were failing due to timeouts on functions like read_lines() or read_int() timing out:

```cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'int_reader.int': Failed to read_int(""gs://cloud-cromwell-dev/cromwell_execution/travis/globs/57f6e677-c2aa-4d96-bf33-9591fce20da7/call-int_reader/shard-3/stdout"") (reason 1 of 1): Futures timed out after [10 seconds]
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:851)```

It's possible that being queued in the I/O actor can take longer than the 10s timeout and thus that is the issue. It's possible this timeout needs to be raised or output evaluation needs to be retried, but this needs a fix as the outputs being evaluated already exist, so this is a bad failure mode.

AC: Depending on the potential causes for such behavior, either retry this evaluation, raise the timeout or explore another solution to ensure that jobs dont fail because of this timeout.

**Comment by Horneth** [comment]
Didn't @aednichols increase the timeout for that very recently ?

**Comment by aednichols** [comment]
It’s still using the old 10-second timeout, so it seems like this build’s branch probably diverted from develop prior to the timeout commit landing

**Comment by Horneth** [comment]
Right, what I was suggesting is that maybe this is "fixed" already. Or at least we could wait and see if it still happens once a Cromwell with your change gets deployed.

**Comment by ruchim** [comment]
I'll close this then and re-open if a file read timeout is reported again. Thanks Adam + Thibault

**Comment by DavyCats** [comment]
@ruchim @Horneth @aednichols I'm seeing this error pop up running cromwell-35 on SGE, except the timeout is at 60 seconds rather than 10. The error gets repeated a number of times (in the latest log it appears 9 times).

The output in question is a glob and there are 80 calls to the task producing it. 2 fastqs get chucked into 20 chunks each, so 40 total. FastQC is run for these chunks once before adapter clipping and once after, so 80 total. There's a bunch of other jobs being run as well, but I'm only seeing this error for this specifc output (`Fastqc.images`).

```
[2018-10-11 13:48:43,66] [error] WorkflowManagerActor Workflow 0a20b0d2-8ad2-43b1-ba92-49e1c39d6578 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'Fastqc.images': Futures timed out after [60 seconds]
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:858)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by DavyCats** [comment]
Oh right, I forgot about this comment... sorry :sweat_smile:  The issue turned out to be with the call-caching strategy we were using. Because there were a lot of files being created, cromwell needed to do a large amount of hashing, which used up all of the available CPUs eventually leading to the timeouts. We changed the call-caching strategy and are no now longer running into this error.

**Comment by malachig** [comment]
I think we might be having a similar issue:
```
Bad output 'pindel.deletions': Futures timed out after [60 seconds]
Bad output 'pindel.insertions': Futures timed out after [60 seconds]
Bad output 'pindel.long_insertions': Futures timed out after [60 seconds]
        at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:858)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

If we don't want to change our caching strategy, can we simply increase the timeout?  Can that be done with `akka.http.server.request-timeout`?

**Comment by natechols** [comment]
I'm running into the same problem here, also on SGE, for a task with 256 shards each with multiple outputs.  Looks like about a dozen of the shards failed with the same timeout, and Cromwell attempted retries for half of them without success.

@malachig The akka setting only controls the REST API.  The timeout we're seeing appears to be hardcoded in Scala.

**Comment by illusional** [comment]
We're seeing this on SLURM on scatters about 100. Has anyone seen ways to restrict IO maybe to combat this?

**Comment by microbioticajon** [comment]
Im also running into this issue - did anyone find a solution to their problem??

**Comment by illusional** [comment]
We just reduced our use of read functions, usually removing globs helped a lot.

**Comment by microbioticajon** [comment]
Thanks @illusional! I dont think will be an option for us. Given the variable nature of the number of genomes we are going to be dealing with we are eventually going to hit this again even if we did reduce our reliance on the read functions. It feels like it needs an option in the config to increase the timeout.

**Comment by BJWiley233** [comment]
only allowing `read_int()` in the output section is an awful implementation and completely screws up the call caching (i.e. time saving/money saving).  This is equivalent to have a function in python print a string and then using `int()` to convert it.  Why can't we just return an integer inside the task and assign the integer in the output.  Let's think a little bit longer during the "how might implementing something, break down the line in the big picture".  This is more of a senior leader oversight than a coding implementation issue.

**Comment by tobyaicher** [comment]
Was there a solution to this? I am also encountering this using the broad institute mutect2 implementation here:
https://github.com/broadinstitute/gatk/blob/master/scripts/mutect2_wdl/mutect2.wdl

When implemented using slurm/singularity on my institute's HPC.

Specifically my error is below and I think has to do like people above have said to do the 50 scatter I am currently using.

`[INFO] [06/04/2024 06:56:15.291] [cromwell-system-akka.dispatchers.engine-dispatcher-32] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor] WorkflowManagerActor: Workflow ccfe50af-5661-4bcd-b351-9da287c5affb failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'M2.tumor_pileups': Future timed out after [60 seconds]
Bad output 'M2.normal_pileups': Future timed out after [60 seconds]
Bad output 'M2.tumor_sample': Failed to read_string("tumor_name.txt") (reason 1 of 1): Future timed out after [60 seconds]
Bad output 'M2.normal_sample': Failed to read_string("normal_name.txt") (reason 1 of 1): Future timed out after [60 seconds]
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:990)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by tobyaicher** [comment]
I wanted to follow-up on this error: I am now seeing this error after implementing the standard broad institute alignment pipeline on the HPC at my institute: https://portal.firecloud.org/?return=terra#methods/five-dollar-genome-analysis-pipeline-gilad/five-dollar-genome-analysis-pipeline-gilad/1

Specifically my error is: 

[INFO] [08/12/2024 19:26:46.031] [cromwell-system-akka.dispatchers.engine-dispatcher-29] [akka://cromwell-system/user/SingleWorkflowRunnerActor/WorkflowManagerActor] WorkflowManagerActor: Workflow 8b8c576b-50bc-4a33-b326-0f69be43ece9 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'CreateSequenceGroupingTSV.sequence_grouping': Failed to read_tsv("sequence_grouping.txt") (reason 1 of 1): Future timed out after [60 seconds]
Bad output 'CreateSequenceGroupingTSV.sequence_grouping_with_unmapped': Failed to read_tsv("sequence_grouping_with_unmapped.txt") (reason 1 of 1): Future timed out after [60 seconds]

Bad output 'GetBwaVersion.bwa_version': Failed to read_string("/scratch/tpa239/Step123/TN_2036/TN2036_phylogenetics_8_10_testing/slurm/alignment/alignment_TN2036_sample106/cromwell-executions/WholeGenomeGermlineSingleSample/8b8c576b-50bc-4a33-b326-0f69be43ece9/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/207b9946-03a6-4969-bdab-318482635923/call-GetBwaVersion/execution/stdout") (reason 1 of 1): Future timed out after [60 seconds]

I think it has to do with this read_tsv and function - sometimes an identical job will have this error and sometimes they don't, I think it has to do with how busy the cluster is. 

Is there some setting I can change to increase this timeout? Should I increase the number of cpus or memory for these jobs failing?

I am using cromwell version 85. Thank you!

Toby

**Comment by jgainerdewar** [comment]
We recently adjusted this timeout, I would try again with the latest `develop` build. The errors are likely happening because Cromwell is putting work into its IO queue faster than it can finish it. There's a backpressure system that aims to prevent this by stopping Cromwell picking up new work when IO operations aren't getting finished fast enough, but in this case it isn't responsive enough to keep you out of trouble. If you continue seeing these errors, you can tune down `system.io.command-backpressure-staleness` to make the engine more sensitive to long IO queues.

**Comment by paulcao-brown** [comment]
Hi Everyone who is on this thread, 

I ran into this issue running a pipeline that has many shards. Just to document/share what worked for me, 

I had to add the following to my cromwell configuration file and my 800+ shards job working without any timeout issue (I'm using Slurm/HPC environment for what it's worth):

```
system {
 io {
  command-backpressure-staleness = 6 seconds
 }
  timeout {
      default = 3 minutes
      # Copy can be a time consuming operation and its timeout can be set separately.
      copy = 1 hour
 }
}
```
