### ISSUE TITLE
Cromwell attempts to evaluate parameters that are not ready yet, due to incomplete task run

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#4185]
Cromwell version: 34
Backend: local

Fails in cromwell 34.  Worked fine in cromwell 32.

Task M2 is scattered.  Then FuncotateMaf takes the output value from the first shard.

M2 was has not been run by the time this error message appears.

Error:
```
[2018-10-01 10:02:13,68] [error] WorkflowManagerActor Workflow cc28a122-6605-4d53-83d3-245a88f8ad96 failed (during ExecutingWorkflowState): java.lang.RuntimeException: Failed to evaluate 'Mutect2.FuncotateMaf.case_id' (reason 1 of 1): Evaluating M2.tumor_sample[0] failed: Failed to find index Success(WomInteger(0)) on array:

Success([])

0
	at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$processRunnableTaskCallInputExpression$4(WorkflowExecutionActor.scala:483)
	at scala.util.Either.flatMap(Either.scala:338)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$processRunnableTaskCallInputExpression$2(WorkflowExecutionActor.scala:480)
	at scala.util.Either.flatMap(Either.scala:338)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$processRunnableTaskCallInputExpression$1(WorkflowExecutionActor.scala:479)
	at scala.util.Either.flatMap(Either.scala:338)
....
java.lang.RuntimeException: Failed to evaluate 'Mutect2.FuncotateMaf.control_id' (reason 1 of 1): Evaluating M2.normal_sample[0] failed: Failed to find index Success(WomInteger(0)) on array:

Success([])

0
	at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$processRunnableTaskCallInputExpression$4(WorkflowExecutionActor.scala:483)
	at scala.util.Either.flatMap(Either.scala:338)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$processRunnableTaskCallInputExpression$2(WorkflowExecutionActor.scala:480)
	at scala.util.Either.flatMap(Either.scala:338)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$processRunnableTaskCallInputExpression$1(WorkflowExecutionActor.scala:479)
	at scala.util.Either.flatMap(Either.scala:338)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processRunnableTaskCallInputExpression(WorkflowExecutionActor.scala:478)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$4(WorkflowExecutionActor.scala:452)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)

```

**Comment by LeeTL1220** [comment]
Looks like this was a bad error message, but the task works when I change my runtime+configuration.
