### ISSUE TITLE
Cromwell cannot delete workflow log on failed run

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/cromwell#4186]
Cromwell 34
Backend: local

`cc28a122-6605-4d53-83d3-245a88f8ad96` is the current workflow and I did not open the log file.
```
[2018-10-01 10:02:13,69] [error] Failed to delete workflow log
java.nio.file.FileSystemException: /media/sf_broad_oncotator_configs/test_m2_small/cromwell-workflow-logs/workflow.cc28a122-6605-4d53-83d3-245a88f8ad96.log: Text file busy
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at better.files.File.delete(File.scala:619)
	at cromwell.core.path.BetterFileMethods.delete(BetterFileMethods.scala:413)
	at cromwell.core.path.BetterFileMethods.delete$(BetterFileMethods.scala:412)
	at cromwell.core.path.DefaultPath.delete(DefaultPathBuilder.scala:55)
```

**Comment by LeeTL1220** [comment]
Looks like this error was specific to my runtime+configuration.

**Comment by owo12138** [comment]
I also met this error, can you tell me how to solve it? please
