### ISSUE TITLE
Fix flaky health monitor test

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4259]
Error message: The code passed to eventually never returned normally. Attempted 28 times over 20.881773345 seconds. Last failure message: isEmpty was false, and Some(false) did not contain true Instead, a.status.messages = List(Unknown status) and e.status.messages = List(womp womp).

tc: HealthMonitor should fail if any subsystems fail but correctly bin them

Occurred at these times:
2018-10-10 22:25:49 UTC
2018-10-12 06:25:28 UTC
2018-10-13 06:24:31 UTC
2018-10-13 14:25:16 UTC
2018-10-12 04:23:43 UTC
2018-10-15 10:25:31 UTC
2018-10-13 21:27:58 UTC

**Comment by Horneth** [comment]
Happened again last night:

```
 org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 30 times over 3.33454509745 minutes. Last failure message: isEmpty was false, and Some(false) did not contain true Instead, a.status.messages = List(Unknown status) and e.status.messages = List(womp womp).
      at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:432)
      at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
      at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.eventually(HealthMonitorServiceActorSpec.scala:20)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.eventualStatus(HealthMonitorServiceActorSpec.scala:32)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.$anonfun$new$5(HealthMonitorServiceActorSpec.scala:81)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.withFixture(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
      at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
      at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.runTest(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
      at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.runTests(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.Suite.run(Suite.scala:1147)
      at org.scalatest.Suite.run$(Suite.scala:1129)
      at cromwell.core.TestKitSuite.org$scalatest$BeforeAndAfterAll$$super$run(TestKitSuite.scala:16)
      at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
      at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.org$scalatest$FlatSpecLike$$super$run(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
      at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.run(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
      at sbt.TestRunner.runTest$1(TestFramework.scala:113)
      at sbt.TestRunner.run(TestFramework.scala:124)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFunction.apply(TestFramework.scala:294)
      at sbt.Tests$.processRunnable$1(Tests.scala:347)
      at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
      at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
      at sbt.std.Transform$$anon$4.work(System.scala:67)
      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
      at sbt.Execute.work(Execute.scala:278)
      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
      Cause: org.scalatest.exceptions.TestFailedException: isEmpty was false, and Some(false) did not contain true Instead, a.status.messages = List(Unknown status) and e.status.messages = List(womp womp)
      at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
      at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
      at cromwell.core.TestKitSuite.newAssertionFailedException(TestKitSuite.scala:16)
      at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.$anonfun$eventualStatus$5(HealthMonitorServiceActorSpec.scala:48)
      at scala.collection.immutable.List.map(List.scala:283)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.$anonfun$eventualStatus$1(HealthMonitorServiceActorSpec.scala:40)
      at org.scalatest.concurrent.Eventually.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
      at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.eventually(HealthMonitorServiceActorSpec.scala:20)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.eventualStatus(HealthMonitorServiceActorSpec.scala:32)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.$anonfun$new$5(HealthMonitorServiceActorSpec.scala:81)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.withFixture(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
      at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
      at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.runTest(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
      at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.runTests(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.Suite.run(Suite.scala:1147)
      at org.scalatest.Suite.run$(Suite.scala:1129)
      at cromwell.core.TestKitSuite.org$scalatest$BeforeAndAfterAll$$super$run(TestKitSuite.scala:16)
      at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
      at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.org$scalatest$FlatSpecLike$$super$run(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
      at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
      at cromwell.services.healthmonitor.HealthMonitorServiceActorSpec.run(HealthMonitorServiceActorSpec.scala:20)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
      at sbt.TestRunner.runTest$1(TestFramework.scala:113)
      at sbt.TestRunner.run(TestFramework.scala:124)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFunction.apply(TestFramework.scala:294)
      at sbt.Tests$.processRunnable$1(Tests.scala:347)
      at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
      at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
      at sbt.std.Transform$$anon$4.work(System.scala:67)
      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
      at sbt.Execute.work(Execute.scala:278)
      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```
