### ISSUE TITLE
Unrecognized token import with spec version 1.0

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4273]
When executing a workflow with import statements, Cromwell 36 fails when the WDL version is set to `1.0`, but succeeds when the version is set to `draft-2`.

The error I get is:

```
[2018-10-18 14:44:50,45] [error] WorkflowManagerActor Workflow bb8cc90a-75a5-4fca-a38a-13043700dbaf failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Unrecognized token on line 1, column 1:

import "gatk3-data-processing/processing-for-variant-discovery-gatk3.wdl" as processing
^
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:214)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:184)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:179)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:135)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:135)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:135)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

My code is as follows:

```wdl
import "gatk3-data-processing/processing-for-variant-discovery-gatk3.wdl" as processing
import "gatk3-germline-snps-indels/haplotypecaller-vcf-gatk3.wdl" as haplotype
import "seq-format-conversion/paired-fastq-to-unmapped-bam.wdl" as unmap

workflow best_practise {
    call unmap.ConvertPairedFastQsToUnmappedBamWf
    call processing.GenericPreProcessingWorkflow {
        input:
            flowcell_unmapped_bams=ConvertPairedFastQsToUnmappedBamWf.output_bams
    }
    call haplotype.HaplotypeCallerVcf_GATK3 {
        input:
            input_bam=GenericPreProcessingWorkflow.analysis_ready_bam,
            input_bam_index=GenericPreProcessingWorkflow.analysis_ready_bam_index
    }
}
```

If I attempt to run this using this command using cromwell 36, it works:
```bash
cromwell run best_practise.wdl --imports imports.zip --inputs inputs.json --type wdl --type-version draft-2
```

If I run it using this command, it fails:
```bash
cromwell run best_practise.wdl --imports imports.zip --inputs inputs.json --type wdl --type-version 1.0 
```

**Comment by aednichols** [comment]
@TMiguelT can you check whether you have a `version 1.0` identifier at the top of your code - that is [required](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#versioning) for WDL 1.0 onward.

**Comment by TMiguelT** [comment]
Yep you're right, the missing `version` header is why Cromwell was failing to parse the file. However it looks like if I enable `version 1.0` parsing, then it will fail to import any WDL written using `draft-2`, such as the official Broad workflows: https://github.com/gatk-workflows. So at least for my use-case I should not put in this header.
