### ISSUE TITLE
Disk strings should be of the format 'local-disk' or '/mount/point' but got: 'local-disk 100 HDD' on AWS backend

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4274]
When running the official Broad workflows (for example [this one](https://github.com/gatk-workflows/gatk3-data-processing)), on Cromwell 36 setup on AWS, I get the following error:

```
Caused by: cromwell.backend.validation.ValidatedRuntimeAttributesBuilder$$anon$1: Runtime attribute validation failed:
:
Disk strings should be of the format 'local-disk' or '/mount/point' but got: 'local-disk 100 HDD'
        at cromwell.backend.validation.ValidatedRuntimeAttributesBuilder.build(ValidatedRuntimeAttributesBuilder.scala:62)
        at cromwell.backend.validation.ValidatedRuntimeAttributesBuilder.build$(ValidatedRuntimeAttributesBuilder.scala:56)
        at cromwell.backend.standard.StandardValidatedRuntimeAttributesBuilder$StandardValidatedRuntimeAttributesBuilderImpl.build(StandardValidatedRuntimeAttributesBuilder.scala:20)
        at cromwell.backend.standard.StandardCachingActorHelper.validatedRuntimeAttributes(StandardCachingActorHelper.scala:56)
        at cromwell.backend.standard.StandardCachingActorHelper.validatedRuntimeAttributes$(StandardCachingActorHelper.scala:54)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.validatedRuntimeAttributes$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.validatedRuntimeAttributes(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.standard.StandardCachingActorHelper.startMetadataKeyValues(StandardCachingActorHelper.scala:75)
        at cromwell.backend.standard.StandardCachingActorHelper.startMetadataKeyValues$(StandardCachingActorHelper.scala:74)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.startMetadataKeyValues$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:362)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.startMetadataKeyValues(AwsBatchAsyncBackendJobExecutionActor.scala:362)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:942)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:935)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeOrRecover(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:38)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.aroundReceive(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        ... 5 more
```

Basically, it seems that the AWS parser for the disk specification doesn't understand specs in the form `'local-disk 100 HDD'`. This needs to be fixed, since the Broad pipelines won't run without heavy modification otherwise.

I've tracked down the file spec parsing code to https://github.com/broadinstitute/cromwell/blob/develop/supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/io/AwsBatchVolume.scala#L52-L74, but I'm not informed enough about Scala to write a PR for this.

**Comment by TMiguelT** [comment]
I've thought some more about this, and my guess is that this was never implemented because AWS supports auto-expanding compute disks, as explained here: https://docs.opendata.aws/genomics-workflows/aws-batch/create-custom-ami/.

This is of course a great feature, but unfortunately it means that WDL written for Google Cloud will fail when run on AWS because it doesn't understand more complex disk specs.

To fix this, I suggest that we expand the `LocalDiskPattern` to include the disk size and type, but simply ignore it. This will mean that disk specs such as `local-disk 100 HDD` will be interpreted to have the same meaning as `local-disk`, but will add greater compatibility to the AWS executor.

**Comment by wleepang** [comment]
@TMiguelT - Agree.  This is also called out in the backend [README / Future Considerations](https://github.com/broadinstitute/cromwell/blob/develop/supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/README.md#future-considerations).

**Comment by TMiguelT** [comment]
Do you think it's likely that it would be merged if I PR'd that parsed this format of pattern (and ignored most of it)?

**Comment by wleepang** [comment]
I don't approve PR's but that seems like the obvious route to take.

**Comment by rebrown1395** [comment]
@TMiguelT we would be open to a PR of this nature.

**Comment by TMiguelT** [comment]
The most promising file is this one, which does the pattern matching for valid AWS disk strings: https://github.com/broadinstitute/cromwell/blob/d56b81dd2915a59c06724b6e8f58fa3d49743b6c/supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/io/AwsBatchVolume.scala#L57-L73
@geoffjentry

**Comment by geoffjentry** [comment]
@TMiguelT w/ the disclaimer that i mgiht be wrong, I agree w/ your assessment on a solution here

**Comment by TMiguelT** [comment]
I'm having another look at this issue (hoping to resolve it before next week). One dilemma I have is that I would like to pull the disk spec format out from any individual backend, and make it a global pattern used by all backends. This would remove the possibility to make workflows compatible with one backend but not another. However this would be a bit change, and it might require some more serious approval.

Should I refactor the entire disk spec, or just write a quick fix for the AWS backend?

**Comment by geoffjentry** [comment]
@TMiguelT For now I'd not go for the full refactoring

**Comment by aednichols** [comment]
Right now AWS supports spaces in directory names while PAPI does not. This is implemented via regex in `cromwell.backend.impl.aws.io.AwsBatchVolume#Directory` vs. `cromwell.backend.DiskPatterns#Directory`

If we want to support AWS converting `/some/mnt 20 SSD` into `/some/mnt` we must presume that there cannot exist a directory named `/mnt 20 SSD`.

This confused me for a good while when neatening up the pull request https://github.com/broadinstitute/cromwell/pull/4863!

**Comment by TMiguelT** [comment]
I think this would be a perfectly reasonable restriction. I think we could say that Cromwell only supports paths without spaces, in order to get closer to a global disk spec
