### ISSUE TITLE
Could not evaluate expression: write_lines(array_of_files) on AWS

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4275]
I'm running a modified version of the [paired-fastq-to-unmapped-bam](https://github.com/gatk-workflows/seq-format-conversion/blob/master/paired-fastq-to-unmapped-bam.wdl) workflow on Cromwell 36 running on AWS. However, it seems to fail at `write_lines()`. Any idea why this might be happening? Is there flaw in the AWS implementation of this function? I can post my modified WDL if needed but all that's different from the official workflow that I have removed the `disks` blocks, since they fail on AWS (see #4274)
```
2018-10-18 06:51:48,151 cromwell-system-akka.dispatchers.backend-dispatcher-3190 ERROR - Failed command instantiation
java.lang.Exception: Failed command instantiation
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:565)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand$(StandardAsyncExecutionActor.scala:500)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.instantiatedCommand$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.instantiatedCommand(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents(StandardAsyncExecutionActor.scala:313)
        at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents$(StandardAsyncExecutionActor.scala:312)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.commandScriptContents(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:132)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob(AwsBatchAsyncBackendJobExecutionActor.scala:131)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeAsync(AwsBatchAsyncBackendJobExecutionActor.scala:342)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:943)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:935)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeOrRecover(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:38)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.aroundReceive(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: common.exception.AggregatedMessageException: Error(s):
Could not evaluate expression: write_lines(array_of_files): null (Service: S3Client; Status Code: 403; Request ID: null)
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:68)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:64)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:563)
        ... 31 common frames omitted
```

**Comment by TMiguelT** [comment]
To clarify, the reasons I suspect this is an AWS issue are that:
* The stack trace mentions the `AwsBatchAsyncBackendJobExecutionActor`
* The exact same WDL bundle worked fine with the same Cromwell version as a local job (using `cromwell run x.wdl`

**Comment by aednichols** [comment]
The clarity of the output does leave something to be desired but the phrase
>`Service: S3Client; Status Code: 403`

makes me think it's worth checking storage permissions at the source and destination of the `mv`

**Comment by TMiguelT** [comment]
Yep, you were right about this bug, it was because the IAM role that Cromwell uses did not have write access to the S3 bucket. The actual AWS Batch worker instances did have write access, so the workflow didn't fail until it hit `write_lines`, which is executed by the Cromwell server, not by the Batch machine.

However, this is actually the fault of the CloudFormation scripts that generated this role. I used the scripts [hosted here](https://s3.amazonaws.com/aws-genomics-workflows/templates/cromwell/cromwell-server.template.yaml), from [this webpage](https://docs.opendata.aws/genomics-workflows/cromwell/cromwell-aws-batch/).

Notice how the IAM role only has `s3:GetObject` permissions, not `PutObject` etc:

```yaml
  Ec2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
        - PolicyName: !Sub CromwellServer-BatchQueue-Access-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Resource: "*"
              Action:
                - "batch:DescribeJobQueues"
                - "batch:DeregisterJobDefinition"
                - "batch:TerminateJob"
                - "batch:DescribeJobs"
                - "batch:CancelJob"
                - "batch:SubmitJob"
                - "batch:RegisterJobDefinition"
                - "batch:DescribeJobDefinitions"
                - "batch:ListJobs"
                - "batch:DescribeComputeEnvironments"

        - PolicyName: !Sub CromwellServer-S3Bucket-Access-${AWS::Region}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Resource: !Join ["", ["arn:aws:s3:::", !Ref S3BucketName, "/*"]]
              Action:
                - "s3:GetObject"
```

@aednichols Do you happen to know who wrote these scripts or where the code is hosted? Because I would like to submit a change to them to fix this bug

**Comment by wleepang** [comment]
@TMiguelT - Yes!  I'm working on getting them approved for release.  It would be great to have community support for improving them.

**Comment by hmkim** [comment]
Please check this issue.
I think this issue is another problem 


> Caused by: common.exception.AggregatedMessageException: Error(s):
> Could not evaluate expression: write_lines(array_of_files): Access Denied (Service: S3Client; Status
> Code: 403; Request ID: CB48F5CFE95BBD50)
>         at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:68)
>         at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:64)
>         at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExe
> cutionActor.scala:563)
>         ... 31 common frames omitted
> [2019-01-09 05:21:48,83] [error] WorkflowManagerActor Workflow fb387147-f98a-4397-92b3-700d8c607a45 f
> ailed (during ExecutingWorkflowState): java.lang.RuntimeException: AwsBatchAsyncBackendJobExecutionAc
> tor failed and didn't catch its exception.
>         at cromwell.backend.standard.StandardSyncExecutionActor$$anonfun$jobFailingDecider$1.applyOrE
> lse(StandardSyncExecutionActor.scala:183)
>         at cromwell.backend.standard.StandardSyncExecutionActor$$anonfun$jobFailingDecider$1.applyOrE
> lse(StandardSyncExecutionActor.scala:180)
>         at akka.actor.SupervisorStrategy.handleFailure(FaultHandling.scala:298)
>         at akka.actor.dungeon.FaultHandling.handleFailure(FaultHandling.scala:263)
>         at akka.actor.dungeon.FaultHandling.handleFailure$(FaultHandling.scala:254)
>         at akka.actor.ActorCell.handleFailure(ActorCell.scala:431)
>         at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:521)
>         at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
>         at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:224)
>         at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
>         at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> Caused by: java.lang.Exception: Failed command instantiation
>         at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExe
> cutionActor.scala:565)
>         at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand$(StandardAsyncEx
> ecutionActor.scala:500)
>         at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.instantiatedCommand$lzycom
> pute(AwsBatchAsyncBackendJobExecutionActor.scala:74)

**Comment by TMiguelT** [comment]
Hi @wleepang, has there been any progress in releasing these CloudFormation scripts?

**Comment by wleepang** [comment]
@TMiguelT  - I just release them today after a lot of much needed updates:
https://github.com/aws-samples/aws-genomics-workflows/
