### ISSUE TITLE
FileSystemException: File name too long

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4279]
When running a sufficiently nested workflow, I get the error `File name too long`, because WDL is generating a temporary file named `temp-s3-6826696772619511254cromwell-execution_best_practise_3bf9c436-31f7-4d86-ba87-cf54248e05bc_call-ConvertPairedFastQsToUnmappedBamWf_unmap.ConvertPairedFastQsToUnmappedBamWf_e10704e8-7ff4-4e4c-89ad-48270734ba25_call-CreateFoFN_write_lines_238fd975f9e3d166dbec07b20ad88c51.tmp`, which is greater than 256 characters and thus too large for any Linux system.

I'm running Cromwell 36 on with the AWS Batch backend. The traceback is:

```
2018-10-19 01:29:11,310 cromwell-system-akka.dispatchers.backend-dispatcher-8681 ERROR - Failed command instantiation
java.lang.Exception: Failed command instantiation
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:565)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand$(StandardAsyncExecutionActor.scala:500)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.instantiatedCommand$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.instantiatedCommand(AwsBatchAsyncBackendJobExecutionActor.scala:74)  
        at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents(StandardAsyncExecutionActor.scala:313)
        at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents$(StandardAsyncExecutionActor.scala:312)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.commandScriptContents(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:132) 
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob(AwsBatchAsyncBackendJobExecutionActor.scala:131)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeAsync(AwsBatchAsyncBackendJobExecutionActor.scala:342)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:943)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:935)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeOrRecover(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:38)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.aroundReceive(AwsBatchAsyncBackendJobExecutionActor.scala:74)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: common.exception.AggregatedMessageException: Error(s):
Could not evaluate expression: write_lines(array_of_files): [Attempted 1 time(s)] - FileSystemException: /tmp/temp-s3-6826696772619511254cromwell-execution_best_practise_3bf9c436-31f7-4d86-ba87-cf54248e05
bc_call-ConvertPairedFastQsToUnmappedBamWf_unmap.ConvertPairedFastQsToUnmappedBamWf_e10704e8-7ff4-4e4c-89ad-48270734ba25_call-CreateFoFN_write_lines_238fd975f9e3d166dbec07b20ad88c51.tmp: File name too lon
g
        at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:68)
        at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:64)
        at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:563)
        ... 31 common frames omitted
```

It seems that each "segment" of this filename, e.g. `bc_call-ConvertPairedFastQsToUnmappedBamWf_unmap.ConvertPairedFastQsToUnmappedBamWf_e10704e8-7ff4-4e4c-89ad-48270734ba25`, should probably be in a different folder, not just as a different segment of the same filename.

**Comment by ruchim** [comment]
@elerch @wleepang -- any ideas on why there are so many UUIDs the temp file paths? are they required?

**Comment by TMiguelT** [comment]
I just confirmed that this still happens on Cromwell 37, with the latest CloudFormation scripts

**Comment by geoffjentry** [comment]
It looks like centaur test draft3_optional_input_from_scatter runs afoul of this

**Comment by TMiguelT** [comment]
By the way, I don't believe the issue is the number of UUIDs, I expect there's one per workflow/task and that's fine. The problem is that they're all combined into one filename, instead of a series of nested folders, which works, and I believe that's how the other backends deal with this issue.

**Comment by TMiguelT** [comment]
Okay, I've make a very minimal test case that fails on AWS: https://github.com/TMiguelT/WdlFileNameTooLong. Hopefully it's faster than the centaur one so this ends u p being useful
