### ISSUE TITLE
Fix flakey test: SharedFileSystemJobExecutionActorSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4319]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/793/consoleFull

14:08:29 cromwell-test_1  | [info] - should execute calls with input files and localize them appropriately *** FAILED *** (13 seconds, 25 milliseconds)
14:08:29 cromwell-test_1  | [info]   $anon$1 was thrown during property evaluation. (SharedFileSystemJobExecutionActorSpec.scala:119)
14:08:29 cromwell-test_1  | [info]     Message: A timeout occurred waiting for a future to complete. Queried 21 times, sleeping 500 milliseconds between each query.
14:08:29 cromwell-test_1  | [info]     Location: (SharedFileSystemJobExecutionActorSpec.scala:137)
14:08:29 cromwell-test_1  | [info]     Occurred at table row 2 (zero based, not counting headings), which had values (
14:08:29 cromwell-test_1  | [info]       conf = BackendConfigurationDescriptor(Config(SimpleConfigObject({"default-runtime-attributes":{"continueOnReturnCode":0,"cpu":1,"failOnStderr":false},"filesystems":{"local":{"localization":["soft-link"]}},"root":"local-cromwell-executions"})),Config(SimpleConfigObject({}))),
14:08:29 cromwell-test_1  | [info]       isSymLink = true
14:08:29 cromwell-test_1  | [info]     )
14:08:29 cromwell-test_1  | [info]   org.scalatest.exceptions.TableDrivenPropertyCheckFailedException:
14:08:29 cromwell-test_1  | [info]   ...
14:08:29 cromwell-test_1  | [info]   at cromwell.backend.sfs.SharedFileSystemJobExecutionActorSpec.localizationSpec(SharedFileSystemJobExecutionActorSpec.scala:119)
14:08:29 cromwell-test_1  | [info]   at cromwell.backend.sfs.SharedFileSystemJobExecutionActorSpec.$anonfun$new$4(SharedFileSystemJobExecutionActorSpec.scala:156)
14:08:29 cromwell-test_1  | [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
14:08:29 cromwell-test_1  | [info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
14:08:29 cromwell-test_1  | [info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
14:08:29 cromwell-test_1  | [info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
14:08:29 cromwell-test_1  | [info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
14:08:29 cromwell-test_1  | [info]   ...
14:08:29 cromwell-test_1  | [info]   Cause: org.scalatest.concurrent.Futures$FutureConcept$$anon$1: A timeout occurred waiting for a future to complete. Queried 21 times, sleeping 500 milliseconds between each query.
14:08:29 cromwell-test_1  | [info]   ...
14:08:29 cromwell-test_1  | [info]   at cromwell.backend.sfs.SharedFileSystemJobExecutionActorSpec.$anonfun$localizationSpec$1(SharedFileSystemJobExecutionActorSpec.scala:137)
14:08:29 cromwell-test_1  | [info]   at cromwell.backend.sfs.SharedFileSystemJobExecutionActorSpec.$anonfun$localizationSpec$1$adapted(SharedFileSystemJobExecutionActorSpec.scala:119)
14:08:30 cromwell-test_1  | [info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl.$anonfun$forAll$7(TableAsserting.scala:505)
14:08:30 cromwell-test_1  | [info]   at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
14:08:30 cromwell-test_1  | [info]   at scala.collection.immutable.List.foreach(List.scala:389)
14:08:30 cromwell-test_1  | [info]   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
14:08:30 cromwell-test_1  | [info]   at org.scalatest.enablers.UnitTableAsserting$TableAssertingImpl.forAll(TableAsserting.scala:503)
14:08:30 cromwell-test_1  | [info]   ...

**Comment by geoffjentry** [comment]
Removing high priority label.

However **NB** for person who does take this. Let's rework the test to not be a "run a workflow and look at the environment", instead express the things under test as an actual unit test
