### ISSUE TITLE
Fix flakey test: KeyValueServiceActorSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4320]
https://broadinstitute.atlassian.net/browse/GAWB-3950

https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Test%20Runners/job/cromwell-test-runner/790/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/833/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/804/

tc: KeyValueServiceActor should insert a key/value
tc: KeyValueServiceActor should return error if key doesn't exist
tc: KeyValueServiceActor should be able to overwrite values

{quote}
org.scalatest.exceptions.TestFailedException: The future returned an exception of type: akka.pattern.AskTimeoutException, with message: Ask timed out on [Actor[akka://KeyValueServiceActorSpec/user/$a#-1019375090]] after [200000 ms]. Sender[null] sent message of type "cromwell.services.keyvalue.KeyValueServiceActor$KvPut".. at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531) at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550) at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479) at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275) at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476) at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475) at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275) at cromwell.services.keyvalue.impl.KeyValueServiceActorSpec.$anonfun$new$2(KeyValueServiceActorSpec.scala:46) at 
{quote}

**Comment by geoffjentry** [comment]
More:

https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1182/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1171/
