### ISSUE TITLE
Fix flakey test: ServicesStoreSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4328]
Error message: A timeout occurred waiting for a future to complete. Queried 100 times, sleeping 100 milliseconds between each query.

tc: ServicesStore should not deadlock

https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/566/

Update 10/22
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/708/

Update 10/28:
https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Test%20Runners/job/cromwell-test-runner/831/

Update 11/03:
https://fc-jenkins.dsp-techops.broadinstitute.org/view/Testing/view/Test%20Runners/job/cromwell-test-runner/1003/

Update 11/06:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1076/

Update 11/09:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1166/

Further:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1337
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1422
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1445
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1489
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1525
https://fc-jenkins.dsp-techops.broadinstitute.org/job/cromwell-test-runner/1590

**Comment by Horneth** [comment]
It seems that the real reason for that last one is

```
java.lang.ExceptionInInitializerError: null
11:09:46 cromwell-test_1  | 	at cromwell.services.MetadataServicesStore.metadataDatabaseInterface(MetadataServicesStore.scala:9)
11:09:46 cromwell-test_1  | 	at cromwell.services.MetadataServicesStore.metadataDatabaseInterface$(MetadataServicesStore.scala:9)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor.metadataDatabaseInterface(MetadataSummaryRefreshActor.scala:35)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataDatabaseAccess.refreshWorkflowMetadataSummaries(MetadataDatabaseAccess.scala:156)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataDatabaseAccess.refreshWorkflowMetadataSummaries$(MetadataDatabaseAccess.scala:155)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor.refreshWorkflowMetadataSummaries(MetadataSummaryRefreshActor.scala:35)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor$$anonfun$1.applyOrElse(MetadataSummaryRefreshActor.scala:46)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor$$anonfun$1.applyOrElse(MetadataSummaryRefreshActor.scala:44)
11:09:46 cromwell-test_1  | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
11:09:46 cromwell-test_1  | 	at akka.actor.FSM.processEvent(FSM.scala:684)
11:09:46 cromwell-test_1  | 	at akka.actor.FSM.processEvent$(FSM.scala:681)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor.akka$actor$LoggingFSM$$super$processEvent(MetadataSummaryRefreshActor.scala:35)
11:09:46 cromwell-test_1  | 	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
11:09:46 cromwell-test_1  | 	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor.processEvent(MetadataSummaryRefreshActor.scala:35)
11:09:46 cromwell-test_1  | 	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
11:09:46 cromwell-test_1  | 	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
11:09:46 cromwell-test_1  | 	at akka.actor.Actor.aroundReceive(Actor.scala:517)
11:09:46 cromwell-test_1  | 	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
11:09:46 cromwell-test_1  | 	at cromwell.services.metadata.impl.MetadataSummaryRefreshActor.aroundReceive(MetadataSummaryRefreshActor.scala:35)
11:09:46 cromwell-test_1  | 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
11:09:46 cromwell-test_1  | 	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
11:09:46 cromwell-test_1  | 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
11:09:46 cromwell-test_1  | 	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
11:09:46 cromwell-test_1  | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
11:09:46 cromwell-test_1  | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
11:09:46 cromwell-test_1  | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
11:09:46 cromwell-test_1  | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
11:09:46 cromwell-test_1  | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
11:09:46 cromwell-test_1  | Caused by: liquibase.exception.LockException: java.lang.NullPointerException
11:09:46 cromwell-test_1  | 	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:242)
11:09:46 cromwell-test_1  | 	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:170)
11:09:46 cromwell-test_1  | 	at liquibase.Liquibase.update(Liquibase.java:196)
11:09:46 cromwell-test_1  | 	at liquibase.Liquibase.update(Liquibase.java:192)
11:09:46 cromwell-test_1  | 	at cromwell.database.migration.liquibase.LiquibaseUtils$.updateSchema(LiquibaseUtils.scala:58)
11:09:46 cromwell-test_1  | 	at cromwell.database.migration.liquibase.LiquibaseUtils$.updateSchema(LiquibaseUtils.scala:31)
11:09:46 cromwell-test_1  | 	at cromwell.services.ServicesStore$EnhancedSqlDatabase$.$anonfun$initialized$1(ServicesStore.scala:11)
11:09:46 cromwell-test_1  | 	at cromwell.services.ServicesStore$EnhancedSqlDatabase$.$anonfun$initialized$1$adapted(ServicesStore.scala:11)
11:09:46 cromwell-test_1  | 	at cromwell.database.slick.SlickDatabase.$anonfun$withConnection$1(SlickDatabase.scala:96)
11:09:46 cromwell-test_1  | 	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
11:09:46 cromwell-test_1  | 	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
11:09:46 cromwell-test_1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
11:09:46 cromwell-test_1  | 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
11:09:46 cromwell-test_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:09:46 cromwell-test_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:09:46 cromwell-test_1  | 	at java.lang.Thread.run(Thread.java:748)
11:09:46 cromwell-test_1  | Caused by: java.lang.NullPointerException: null
11:09:46 cromwell-test_1  | 	at liquibase.sqlgenerator.SqlGeneratorFactory.getGenerators(SqlGeneratorFactory.java:123)
11:09:46 cromwell-test_1  | 	at liquibase.sqlgenerator.SqlGeneratorFactory.createGeneratorChain(SqlGeneratorFactory.java:189)
11:09:46 cromwell-test_1  | 	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:221)
11:09:46 cromwell-test_1  | 	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.access$700(JdbcExecutor.java:36)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor$QueryStatementCallback.doInStatement(JdbcExecutor.java:338)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:126)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.query(JdbcExecutor.java:134)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:142)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.queryForObject(JdbcExecutor.java:157)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.queryForInt(JdbcExecutor.java:178)
11:09:46 cromwell-test_1  | 	at liquibase.executor.jvm.JdbcExecutor.queryForInt(JdbcExecutor.java:173)
11:09:46 cromwell-test_1  | 	at liquibase.snapshot.SnapshotGeneratorFactory.has(SnapshotGeneratorFactory.java:98)
11:09:46 cromwell-test_1  | 	at liquibase.snapshot.SnapshotGeneratorFactory.hasDatabaseChangeLogLockTable(SnapshotGeneratorFactory.java:190)
11:09:46 cromwell-test_1  | 	at liquibase.lockservice.StandardLockService.hasDatabaseChangeLogLockTable(StandardLockService.java:155)
11:09:46 cromwell-test_1  | 	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:91)
11:09:46 cromwell-test_1  | 	at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:206)
```

**Comment by geoffjentry** [comment]
@Horneth I came here to update the latest failure and noticed your comment. Considering that @kshakir noted Liquibase weirdness in #4320 perhaps these are related in some way?

**Comment by Horneth** [comment]
Yep I think there's a good chance the liqubase weirdness is the cause of both

**Comment by kshakir** [comment]
Hmm… Liquibase isn't thread safe. https://liquibase.jira.com/browse/CORE-2792

The various tests creating temporary databases may need refactoring.

**Comment by Horneth** [comment]
Could we just add a `synchronized` if it's only a problem I'm the tests ?

**Comment by kshakir** [comment]
New theory: I believe this is seen just before every "deadlock" failure.

```java
Exception in thread "db-2" java.lang.IllegalArgumentException: requirement failed: count cannot be increased
     at scala.Predef$.require(Predef.scala:277)
     at slick.util.ManagedArrayBlockingQueue.$anonfun$increaseInUseCount$1(ManagedArrayBlockingQueue.scala:43)
     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
     at slick.util.ManagedArrayBlockingQueue.locked(ManagedArrayBlockingQueue.scala:201)
     at slick.util.ManagedArrayBlockingQueue.increaseInUseCount(ManagedArrayBlockingQueue.scala:42)
     at slick.util.AsyncExecutor$$anon$2$$anon$1.beforeExecute(AsyncExecutor.scala:117)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
```

**Comment by geoffjentry** [comment]
@kshakir **NB** https://github.com/broadinstitute/cromwell/issues/3823

**Comment by geoffjentry** [comment]
@kshakir FWIW it appears that this happened again in build 1337

**Comment by kshakir** [comment]
More evidence of the `count cannot be increased` correlating with the deadlock occurrence. This [log_deadlock_debug.txt](https://github.com/broadinstitute/cromwell/files/2595594/log_deadlock_debug.txt) has a bunch of [debugging](https://github.com/broadinstitute/cromwell/blob/b2aae2b6b28a2711959b710ab090598f776981da/services/src/test/scala/cromwell/services/ServicesStoreSpec.scala#L61) for the `deadlock-test`.

**Comment by geoffjentry** [comment]
Seems to be happening roughly once daily of late

**Comment by geoffjentry** [comment]
@kshakir https://broadworkbench.atlassian.net/browse/WB-84
