### ISSUE TITLE
"no space left on device" when pulling Docker image on Google Cloud

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4337]
I have encountered this issue when running the GATK 4 [Merge BAM Alignment](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl#L334) task, on Cromwell 36 running on Google Cloud.

For some reason, it seems that the docker image `broadinstitute/gatk` is too large for the disk. What I'm not sure about is which disk this is referring to. Is it the machine running Cromwell, or is it the pipelines API worker machine? If it's the latter, how can I stop this error happening?

```
cromwell_1  | 2018-10-25 06:53:52,612 cromwell-system-akka.dispatchers.engine-dispatcher-440 ERROR - WorkflowManagerActor Workflow 28605745-a8d2-43c4-ab02-70e5c5c032fe failed (during ExecutingWorkflowStat
e): java.lang.Exception: Task PreProcessingForVariantDiscovery_GATK4.MergeBamAlignment:0:1 failed. The job was stopped before the command finished. PAPI error code 5. 8: Failed to pull image broadinstitut
e/gatk@sha256:1532dec11e05c471f827f59efdd9ff978e63ebe8f7292adf56c406374c131f71: "docker pull broadinstitute/gatk@sha256:1532dec11e05c471f827f59efdd9ff978e63ebe8f7292adf56c406374c131f71" failed: exit status 1: sha256:1532dec11e05c471f827f59efdd9ff978e63ebe8f7292adf56c406374c131f71: Pulling from broadinstitute/gatk
cromwell_1  | ae79f2514705: Pulling fs layer
cromwell_1  | 5ad56d5fc149: Pulling fs layer
cromwell_1  | 170e558760e8: Pulling fs layer
cromwell_1  | 395460e233f5: Pulling fs layer
cromwell_1  | 6f01dc62e444: Pulling fs layer
cromwell_1  | 98db058f41f6: Pulling fs layer
[...]
cromwell_1  | failed to register layer: Error processing tar file(exit status 1): write /root/.cache/pip/http/5/1/d/8/2/51d82969228464b761a16257d5eefe8e2b3dde3c1ad733721353e785: no space left on device
cromwell_1  |
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor$.StandardException(PipelinesApiAsyncBackendJobExecutionActor.scala:79)
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleFailedRunStatus$1(PipelinesApiAsyncBackendJobExecutionActor.scala:585)
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:592)
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:83)
cromwell_1  |   at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$5.applyOrElse(StandardAsyncExecutionActor.scala:1099)
cromwell_1  |   at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$5.applyOrElse(StandardAsyncExecutionActor.scala:1095)
cromwell_1  |   at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
cromwell_1  |   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
cromwell_1  |   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
cromwell_1  |   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
cromwell_1  |   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
cromwell_1  |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
cromwell_1  |   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
cromwell_1  |   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
cromwell_1  |   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
cromwell_1  |   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
cromwell_1  |
cromwell_1  | 2018-10-25 06:53:52,637 cromwell-system-akka.dispatchers.engine-dispatcher-399 INFO  - WorkflowManagerActor WorkflowActor-28605745-a8d2-43c4-ab02-70e5c5c032fe is in a terminal state: WorkflowFailedState
```

**Comment by danbills** [comment]
Take a look at this runtime attribute:

https://cromwell.readthedocs.io/en/stable/RuntimeAttributes/#bootdisksizegb

**Comment by TMiguelT** [comment]
Right. So it sounds like this is an issue with disk space on the PAPI worker. Since I'm using the official Broad pipelines, the way to configure this is with the `flowcell_medium_disk` input field to the `PreProcessingForVariantDiscovery_GATK4` workflow

**Comment by geoffjentry** [comment]
@TMiguelT also the GATK docker was recently updated to be much smaller. 

@vdauwera are there updated versions of the GATK workflows to use the smaller images?

**Comment by geoffjentry** [comment]
@TMiguelT Did you wind up resolving this or did it remain a blocker? If the latter, is this happening on newer GATK dockers? They are much smaller.

**Comment by geoffjentry** [comment]
@TMiguelT We're going to close this as multiple things have occurred in between which should have resolved the issue. Please reopen if you're still encountering this.
