### ISSUE TITLE
S3 localization not working, mount point missed in localized path

### ISSUE THREAD

**Issue by asmoe4** [broadinstitute/cromwell#4356]
Hi 
We have a WDL script which has a complex workflow with multiple task.  It basically takes input files and do alignment, deduplication and finally variant calling.  There is a step in there which is calling `gatk FilterByOrientationBias`.  The actual command that was generated by cromwell is

```
[2018-11-02 17:24:33,42] [info] AwsBatchAsyncBackendJobExecutionActor [1651349bSomaticSNVInDel.FilterByOrientationBias:1:1]: gatk FilterByOrientationBias \
      \
     -V /cromwell_root/s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-Mutect2_First_Filter/shard-1/JL027_Tumor-JL027_Normal.mutect2.oncefiltered.vcf.gz \
     -O JL027_Tumor-JL027_Normal.mutect2.twicefiltered.vcf.gz \
     -P /cromwell_root/s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt \
     -R /cromwell_root/s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/ucsc.hg19.fasta \
     -L /cromwell_root/s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/SureSelect.hg19.regions.v5.interval_list \
     -AM G/T -AM C/T \
```

All the input files that were mentioned in the above command are on s3 and as you can see from the command line from above that cromwell correctly localized those.  However, cromwell is failing to create a job with the following error:

```
[2018-11-02 17:24:33,44] [error] Absolute path /s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt doesn't appear to be under any mount points: local-disk /cromwell_root
java.lang.Exception: Absolute path /s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt doesn't appear to be under any mount points: local-disk /cromwell_root
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.relativePathAndVolume(AwsBatchAsyncBackendJobExecutionActor.scala:236)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.generateAwsBatchSingleFileOutputs(AwsBatchAsyncBackendJobExecutionActor.scala:297)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.$anonfun$generateAwsBatchOutputs$9(AwsBatchAsyncBackendJobExecutionActor.scala:258)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.immutable.List.flatMap(List.scala:352)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.$anonfun$generateAwsBatchOutputs$8(AwsBatchAsyncBackendJobExecutionActor.scala:256)
        at scala.collection.immutable.List.flatMap(List.scala:335)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.generateAwsBatchOutputs(AwsBatchAsyncBackendJobExecutionActor.scala:255)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:141)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob(AwsBatchAsyncBackendJobExecutionActor.scala:131)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeAsync(AwsBatchAsyncBackendJobExecutionActor.scala:339)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:934)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:926)
        at 
```
Can you please advise?

Thank you.

**Comment by asmoe4** [comment]
The path is declared as a File.  I even tried running the same thing by removing `?` to make non optional.  But got the same error.

The task definition is as follow:

```
task FilterByOrientationBias {
    File ref_fasta
    File ref_index
    File ref_dict
    File ref_alt
    File? intervals
    File oncefiltered_mutect2_vcf
    File oncefiltered_mutect2_vcf_index
    File? pre_adapter_matrix

    String? java_options
    String? gatk_options
    String? mutect2_extra_filtering_args

    String out_base = basename(oncefiltered_mutect2_vcf ,".mutect2.oncefiltered.vcf.gz")
    String output_vcf = out_base + ".mutect2.twicefiltered.vcf.gz"
    String output_vcf_index = out_base + ".mutect2.twicefiltered.vcf.gz.tbi"

    Array[String] artifact_modes


    command {
        gatk FilterByOrientationBias \
             ${"--java-options " + java_options} \
             -V ${oncefiltered_mutect2_vcf} \
             -O ${output_vcf} \
             ${"-P " + pre_adapter_matrix} \
             -R ${ref_fasta} \
             ${"-L " + intervals} \
             -AM ${sep=' -AM ' artifact_modes} \
             ${gatk_options}
    }

    runtime {
    }

    output {
        File twice_filtered_vcf = "${output_vcf}"
        File twice_filtered_vcf_index = "${output_vcf_index}"
        File twice_filtered_pre_adapter_matrix = "${pre_adapter_matrix}"
    }
}

```

**Comment by TMiguelT** [comment]
It's a bit confusing, you've posted the error log from a stage called `CollectSequencingArtifactMetrics`, but posted the WDL for a task called `FilterByOrientationBias`. Could you please send the WDL for the same task that's failing?

A case where this bug can happen is when you do doing string manipulation with `File` type variables. For example, if you `sub()` a `File` object to generate a new filename, it will use the S3 URL, as the input to `sub`. However, by the S3 URL, when interpreted by Bash as a path, doesn't exist on the right disk. I wrote an issue about it [here](https://github.com/openwdl/wdl/issues/260). Tell me if it's this same issue.

**Comment by asmoe4** [comment]
@TMiguelT 

The error is happening at `FilterByOrientationBias` stage.  Not the `CollectSequencingArtifactMetrics` stage.  `CollectSequencingArtifactMetrics` is the previous task where the input file is coming from (it uses output files from `CollectSequencingArtifactMetrics` stage)  I'm re-pasting the whole error ( as I previously split it out into two) for clarification.

```
[2018-11-02 17:24:33,42] [info] AwsBatchAsyncBackendJobExecutionActor [1651349bSomaticSNVInDel.FilterByOrientationBias:1:1]: gatk FilterByOrientationBias \
      \
     -V /cromwell_root/s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-Mutect2_First_Filter/shard-1/JL027_Tumor-JL027_Normal.mutect2.oncefiltered.vcf.gz \
     -O JL027_Tumor-JL027_Normal.mutect2.twicefiltered.vcf.gz \
     -P /cromwell_root/s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt \
     -R /cromwell_root/s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/ucsc.hg19.fasta \
     -L /cromwell_root/s4-somaticgenomicsrd-benchmark-gatk4/database/1.0/SureSelect.hg19.regions.v5.interval_list \
     -AM G/T -AM C/T \
[2018-11-02 17:24:33,44] [error] Absolute path /s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt doesn't appear to be under any mount points: local-disk /cromwell_root
java.lang.Exception: Absolute path /s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt doesn't appear to be under any mount points: local-disk /cromwell_root
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.relativePathAndVolume(AwsBatchAsyncBackendJobExecutionActor.scala:236)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.generateAwsBatchSingleFileOutputs(AwsBatchAsyncBackendJobExecutionActor.scala:297)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.$anonfun$generateAwsBatchOutputs$9(AwsBatchAsyncBackendJobExecutionActor.scala:258)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.immutable.List.flatMap(List.scala:352)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.$anonfun$generateAwsBatchOutputs$8(AwsBatchAsyncBackendJobExecutionActor.scala:256)
        at scala.collection.immutable.List.flatMap(List.scala:335)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.generateAwsBatchOutputs(AwsBatchAsyncBackendJobExecutionActor.scala:255)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob$lzycompute(AwsBatchAsyncBackendJobExecutionActor.scala:141)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.batchJob(AwsBatchAsyncBackendJobExecutionActor.scala:131)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeAsync(AwsBatchAsyncBackendJobExecutionActor.scala:339)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:934)
        at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:926)
        at cromwell.backend.impl.aws.AwsBatchAsyncBackendJobExecutionActor.executeOrRecover(AwsBatchAsyncBackendJobExecutionActor.scala:75)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.core.retry.Retry$.withRetry(Retry.scala:37)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
        at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
        at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
        at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
```

It's not the same issue as you other issue because 1) I'm not manipulating any file name in my task and 2) if you look at the `gatk` command, it correctly used the right localized file path.  The error itself is something about the mount point:

```
java.lang.Exception: Absolute path /s4-somaticgenomicsrd-valinor/JL027/Tigris-1.1.0.dev1/tigris_workflow/5c8ee2ab-f1bd-4c6c-ad0b-4af7b52d29f1/call-SomaticSNVInDel/vc.SomaticSNVInDel/1651349b-2144-4e0f-ab6e-2aeb7e96c760/call-CollectSequencingArtifactMetrics/shard-1/JL027_Tumor.dedup.recal.artifactmetrics.pre_adapter_detail_metrics.txt doesn't appear to be under any mount points: local-disk /cromwell_root
```
One other possible thing is that the input file path are just very long.  So, I'll try to copy over input file to a different bucket and see if it works with if the file path is shortened.

**Comment by asmoe4** [comment]
@TMiguelT 

I separated out the part that is failing into a separate WDL and tried running just that WDL with different inputs, it all failed with the same error message.  The WDL is attached so that you can just run to see the error.

[cromwell_4356.zip](https://github.com/broadinstitute/cromwell/files/2555124/cromwell_4356.zip)

**Comment by asmoe4** [comment]
Hi - I'm wondering if anyone has taken a look into this?  Apologies if someone is.  It's been quite some time since the last comment on this issue, so I just want to make sure that this does not get lost among other issues.

Thank you in advance for your help.

**Comment by asmoe4** [comment]
I finally found the issue.  The issue was we have an input parameter defined as File object and one of our outputs was using that File object.

```
 output {
        File twice_filtered_vcf = "${output_vcf}"
        File twice_filtered_vcf_index = "${output_vcf_index}"
        File twice_filtered_pre_adapter_matrix = "${pre_adapter_matrix}" <<=== defined as File object
    }
```
Changing it to use the String variable fixed the problem.

This issue can be closed out.
