### ISSUE TITLE
relative imports from local-submitted CWL seems to fail

### ISSUE THREAD

**Issue by denis-yuen** [broadinstitute/cromwell#4366]
Running a CWL workflow with local relative imports seems to fail. This is possibly related to #4308 but unsure. 

Running with cromwell 36. 

Process looks like the following
```
$ git clone https://github.com/dockstore-testing/dockstore-workflow-md5sum-unified.git
$ cd dockstore-workflow-md5sum-unified
$ cwltool checker_workflow_wrapping_workflow.cwl md5sum.json
/usr/local/bin/cwltool 1.0.20180403145700
<snip>
Final process status is success
$ wget https://github.com/broadinstitute/cromwell/releases/download/36/cromwell-36.jar
$ java -jar cromwell-36.jar  run https://raw.githubusercontent.com/dockstore-testing/dockstore-workflow-md5sum-unified/develop/checker_workflow_wrapping_workflow.cwl --inputs md5sum.json
<snip>
[2018-11-07 14:34:25,13] [info] Pre-Processing /tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl
[2018-11-07 14:34:34,94] [error] WorkflowManagerActor Workflow a3cb6a14-3672-4132-8a24-2e0a4e66ff96 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
running cwltool on file /tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl failed with Traceback (most recent call last):
  File "/home/dyuen/dockstore_tools/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/heterodon/__init__.py", line 24, in apply
  File "<string>", line 1, in <module>
  File "<string>", line 12, in cwltool_salad
  File "/home/dyuen/dockstore_tools/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/cwltool/load_tool.py", line 279, in validate_document
  File "/home/dyuen/dockstore_tools/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/schema_salad/ref_resolver.py", line 915, in resolve_all
  File "/home/dyuen/dockstore_tools/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/schema_salad/ref_resolver.py", line 1087, in validate_links
schema_salad.validate.ValidationException: ../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl:24:1: checking field steps
../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl:30:3:   checking object ../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl#checker
../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl:31:5:     Field run contains undefined reference to file:///tmp/cwl_temp_dir_7264114231127246601/checker/md5sum_checker.cwl
../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl:25:3:   checking object ../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl#md5sum
../../../../tmp/cwl_temp_dir_7264114231127246601/cwl_temp_file_a3cb6a14-3672-4132-8a24-2e0a4e66ff96.cwl:26:5:     Field run contains undefined reference to file:///tmp/cwl_temp_dir_7264114231127246601/md5sum/md5sum.cwl
<snip>
$ java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

Inspecting the directory `/tmp/cwl_temp_dir_7264114231127246601` the relative imports are indeed not present (or anything else really)

**Comment by ruchim** [comment]
Hey @denis-yuen, thanks for providing an easily reproducible case.

I had a question though, what is the significance of 'local-submitted CWL'? While you clone the github repo that contains the CWL workflow, you submit it to Cromwell using an https link, which would seem to imply you're trying to use http imports. 

I wonder what happens if you just run it against Cromwell using the local CWL files as imports:

`java -jar cromwell-36.jar  run checker_workflow_wrapping_workflow.cwl --inputs md5sum.json`

**Comment by geoffjentry** [comment]
@ruchim @denis-Yuen https://github.com/broadinstitute/cromwell/pull/4308

**Comment by denis-yuen** [comment]
@ruchim @geoffjentry 

Hi, 
Sorry, it looks like I copied the wrong history. The correct history at https://gist.github.com/denis-yuen/b3aa8b0e882dee1fe8cb6cab82286e46

The error message is pretty similar, is it possible #4308 affects both scenarios?

Equivalent excerpts below:
```
dyuen@odl-dyuen2:~/test$ git clone https://github.com/dockstore-testing/dockstore-workflow-md5sum-unified.git
Cloning into 'dockstore-workflow-md5sum-unified'...
remote: Enumerating objects: 113, done.
remote: Total 113 (delta 0), reused 0 (delta 0), pack-reused 113
Receiving objects: 100% (113/113), 24.79 KiB | 1.24 MiB/s, done.
Resolving deltas: 100% (50/50), done.
dyuen@odl-dyuen2:~/test$ cd dockstore-workflow-md5sum-unified
dyuen@odl-dyuen2:~/test/dockstore-workflow-md5sum-unified$ cwltool checker_workflow_wrapping_workflow.cwl md5sum.json
/usr/local/bin/cwltool 1.0.20180403145700
Resolved 'checker_workflow_wrapping_workflow.cwl' to 'file:///home/dyuen/test/dockstore-workflow-md5sum-unified/checker_workflow_wrapping_workflow.cwl'
<snip>
Final process status is success
dyuen@odl-dyuen2:~/test/dockstore-workflow-md5sum-unified$ wget https://github.com/broadinstitute/cromwell/releases/download/36/cromwell-36.jar
--2018-11-09 10:24:06--  https://github.com/broadinstitute/cromwell/releases/download/36/cromwell-36.jar
<snip>
2018-11-09 10:24:25 (9.05 MB/s) - ‘cromwell-36.jar’ saved [175930401/175930401]

dyuen@odl-dyuen2:~/test/dockstore-workflow-md5sum-unified$ java -jar cromwell-36.jar run checker_workflow_wrapping_workflow.cwl  --inputs md5sum.json
[2018-11-09 10:25:13,02] [info] Running with database db.url = jdbc:hsqldb:mem:563ca6aa-5d9b-4e8f-b0c6-f3901066317d;shutdown=false;hsqldb.tx=mvcc
[2018-11-09 10:25:18,31] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-11-09 10:25:18,32] [info] [RenameWorkflowOptionsInMetadata] 100%
[2018-11-09 10:25:18,39] [info] Running with database db.url = jdbc:hsqldb:mem:254e87aa-251d-4bd6-bc6f-663624317535;shutdown=false;hsqldb.tx=mvcc
<snip>
[2018-11-09 10:25:19,54] [info] MaterializeWorkflowDescriptorActor [ec689f2a]: Parsing workflow as CWL v1.0
[2018-11-09 10:25:19,60] [info] Pre-Processing /tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl
[2018-11-09 10:25:30,04] [error] WorkflowManagerActor Workflow ec689f2a-c5a8-4c3a-9356-531b3cf0f2da failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
running cwltool on file /tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl failed with Traceback (most recent call last):
  File "/home/dyuen/test/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/heterodon/__init__.py", line 24, in apply
  File "<string>", line 1, in <module>
  File "<string>", line 12, in cwltool_salad
  File "/home/dyuen/test/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/cwltool/load_tool.py", line 279, in validate_document
  File "/home/dyuen/test/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/schema_salad/ref_resolver.py", line 915, in resolve_all
  File "/home/dyuen/test/dockstore-workflow-md5sum-unified/cromwell-36.jar/Lib/schema_salad/ref_resolver.py", line 1087, in validate_links
schema_salad.validate.ValidationException: ../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl:24:1: checking field steps
../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl:30:3:   checking object ../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl#checker
../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl:31:5:     Field run contains undefined reference to file:///tmp/cwl_temp_dir_2148913290991206234/checker/md5sum_checker.cwl
../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl:25:3:   checking object ../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl#md5sum
../../../../tmp/cwl_temp_dir_2148913290991206234/cwl_temp_file_ec689f2a-c5a8-4c3a-9356-531b3cf0f2da.cwl:26:5:     Field run contains undefined reference to file:///tmp/cwl_temp_dir_2148913290991206234/md5sum/md5sum.cwl

	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:214)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:184)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:179)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

<snip>
Workflow ec689f2a-c5a8-4c3a-9356-531b3cf0f2da transitioned to state Failed
```

**Comment by geoffjentry** [comment]
@denis-yuen good point. Sorry, was on my phone and always struggle w/ github comments in that context. That may or may not be directly related - coming out of the leadup to Basel we found a number of similar problems as this (including **this** IIRC) and I know that @cjllanwarne had been working through it all.

Chris will be back next week, I think we should hold off and let him comment when he gets a chance.

**Comment by TMiguelT** [comment]
Did you try using ` --imports .`? It looks like it's moving your CWL file into a temporary directory for running, but missing out on the other files it imports. It seems like `--imports` would tell Cromwell about the imports

**Comment by denis-yuen** [comment]
Interesting,

The above command gives me 
```
$ java -jar cromwell-36.jar run checker_workflow_wrapping_workflow.cwl  --inputs md5sum.json --imports .
[2018-11-13 10:26:04,67] [info] Running with database db.url = jdbc:hsqldb:mem:5089344a-b618-4a55-bf07-de1c4d6a9a1e;shutdown=false;hsqldb.tx=mvcc
[2018-11-13 10:26:09,77] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-11-13 10:26:09,78] [info] [RenameWorkflowOptionsInMetadata] 100%                                    
[2018-11-13 10:26:09,89] [info] Running with database db.url = jdbc:hsqldb:mem:740605a3-c63f-4491-b41a-58b162626bcb;shutdown=false;hsqldb.tx=mvcc
[2018-11-13 10:26:10,18] [info] Slf4jLogger started                                                                                                                   
Exception in thread "main" java.io.IOException: Is a directory    
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)                                                                                                                                               
        at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46)                                       
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)                                                    
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)                        
```

The same error occurs with a full path like 
```
java -jar cromwell-36.jar run checker_workflow_wrapping_workflow.cwl  --inputs md5sum.json --imports `pwd`
```

It does give me a workaround since the following does lead to success!
```
$ zip -r foo.zip .
$ java -jar cromwell-36.jar run checker_workflow_wrapping_workflow.cwl  --inputs md5sum.json --imports foo.zip
```

**Comment by TMiguelT** [comment]
Ah yes I forgot Cromwell requires you to zip your inputs. I'm glad this helps!

**Comment by denis-yuen** [comment]
Thanks, 
It is a bit confusing since the usage message is  `-p, --imports <value>    A directory or zipfile to search for workflow imports` which seems to say both would work.

**Comment by cjllanwarne** [comment]
Hi @denis-yuen - I'll have a look at this after completing my fix for "relative imports from remote URLs" - hopefully this will either be taken care of for free or a very similar fix
