### ISSUE TITLE
AWS hello output parsing failure

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4373]
successfully run hello on AWS: 

Failed to evaluate job outputs

https://travis-ci.org/broadinstitute/cromwell/jobs/452508725

```
Bad output 'hello.salutation': [Attempted 1 time(s)] - IOException: Could not read from s3://cromwell-centaur-execution/cromwell-execution/wf_hello/6934bee8-44ed-4534-97a7-3507a2f53413/call-hello/hello-stdout.log: s3://s3.amazonaws.com/cromwell-centaur-execution/cromwell-execution/wf_hello/6934bee8-44ed-4534-97a7-3507a2f53413/call-hello/hello-stdout.log
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$handleExecutionSuccess$1(StandardAsyncExecutionActor.scala:867)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ruchim** [comment]
It seems like the feature request here is to retry S3 operations

**Comment by wleepang** [comment]
I think this is related to PR #4377

**Comment by geoffjentry** [comment]
I'm going to close this as it doesn't seem to be reproducible
