### ISSUE TITLE
Cromwell missing command line arguments

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4381]
Cromwell: 36
Mode: Server
Backend: Google Cloud
***
I've noticed a strange error that only happens on the Google Cloud backend. Cromwell runs the WDL tasks with the correct command line, but somehow the arguments after the initial command aren't being picked up by the . It seems like only the first argument is actually being used. This isn't an issue with my python script, because I can run it directly and everything works fine.

Cromwell showing the command line:
```
cromwell_1  | 2018-11-12 06:57:56,451 cromwell-system-akka.dispatchers.backend-dispatcher-40 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(5d4c4459)germline_variant_calling.fastqc:0:1]: `/app/fastqc_docker.py --output-dir . --read "/cromwell_root/genovic-test-data/cardiom/NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz" --format fastq`
```

Cromwell failing with an error because of missing arguments:
```
cromwell_1  | java.lang.Exception: Task germline_variant_calling.fastqc:0:1 failed. The job was stopped before the command finished. PAPI error code 10. 11: Docker run failed: command failed: usage: fastqc_docker.py [-h] -r READ -o OUTPUT_DIR [-c CONTAMINANTS]
cromwell_1  |                         [-a ADAPTERS] [-l LIMITS] [-f FORMAT] [-n NO_GROUP]
cromwell_1  |                         [-e EXTRA_OPTIONS]
cromwell_1  | fastqc_docker.py: error: argument -r/--read is required
cromwell_1  | . See logs at gs://genovic-cromwell/cromwell-execution/trio/f5454139-c51d-4d04-ae0a-9b9d4ce650aa/call-germline_variant_calling/shard-0/germline_variant_calling/5d4c4459-a91c-4d3b-8ca4-b98457134750/call-fastqc/shard-0/
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor$.StandardException(PipelinesApiAsyncBackendJobExecutionActor.scala:79)
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleFailedRunStatus$1(PipelinesApiAsyncBackendJobExecutionActor.scala:585)
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:592)
cromwell_1  |   at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:83)
cromwell_1  |   at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$5.applyOrElse(StandardAsyncExecutionActor.scala:1099)
cromwell_1  |   at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$5.applyOrElse(StandardAsyncExecutionActor.scala:1095)
cromwell_1  |   at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
cromwell_1  |   at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
cromwell_1  |   at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
cromwell_1  |   at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
cromwell_1  |   at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
cromwell_1  |   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
cromwell_1  |   at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
cromwell_1  |   at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
cromwell_1  |   at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
cromwell_1  |   at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
cromwell_1  |   at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Docker Script (generated by cromwell):
```bash
#!/bin/bash

cd /cromwell_root
tmpDir=$(mkdir -p "/cromwell_root/tmp.1de26137" && echo "/cromwell_root/tmp.1de26137")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell_root

)
out5d4c4459="${tmpDir}/out.$$" err5d4c4459="${tmpDir}/err.$$"
mkfifo "$out5d4c4459" "$err5d4c4459"
trap 'rm "$out5d4c4459" "$err5d4c4459"' EXIT
tee '/cromwell_root/stdout' < "$out5d4c4459" &
tee '/cromwell_root/stderr' < "$err5d4c4459" >&2 &
(
cd /cromwell_root


/app/fastqc_docker.py --output-dir . --read "/cromwell_root/genovic-test-data/cardiom/NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz" --format fastq
)  > "$out5d4c4459" 2> "$err5d4c4459"
echo $? > /cromwell_root/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell_root
find . -type d -empty -print0 | xargs -0 -I % touch %/.file
)
(
cd /cromwell_root
sync
# make the directory which will keep the matching files
mkdir /cromwell_root/glob-9a5013be5b75be907a1e45a835412b84

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-9a5013be5b75be907a1e45a835412b84/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/*fastqc.zip /cromwell_root/glob-9a5013be5b75be907a1e45a835412b84 2> /dev/null ) || ( ln /cromwell_root/*fastqc.zip /cromwell_root/glob-9a5013be5b75be907a1e45a835412b84 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-9a5013be5b75be907a1e45a835412b84 | grep -v cromwell_glob_control_file > /cromwell_root/glob-9a5013be5b75be907a1e45a835412b84.list

# make the directory which will keep the matching files
mkdir /cromwell_root/glob-c36f18b89b7c5f50e2dc9ce3b4cc3952

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-c36f18b89b7c5f50e2dc9ce3b4cc3952/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/*report.html /cromwell_root/glob-c36f18b89b7c5f50e2dc9ce3b4cc3952 2> /dev/null ) || ( ln /cromwell_root/*report.html /cromwell_root/glob-c36f18b89b7c5f50e2dc9ce3b4cc3952 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-c36f18b89b7c5f50e2dc9ce3b4cc3952 | grep -v cromwell_glob_control_file > /cromwell_root/glob-c36f18b89b7c5f50e2dc9ce3b4cc3952.list

# make the directory which will keep the matching files
mkdir /cromwell_root/glob-a678e8cb2ce368b6b92853d6f0816af7

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-a678e8cb2ce368b6b92853d6f0816af7/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/*data.txt /cromwell_root/glob-a678e8cb2ce368b6b92853d6f0816af7 2> /dev/null ) || ( ln /cromwell_root/*data.txt /cromwell_root/glob-a678e8cb2ce368b6b92853d6f0816af7 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-a678e8cb2ce368b6b92853d6f0816af7 | grep -v cromwell_glob_control_file > /cromwell_root/glob-a678e8cb2ce368b6b92853d6f0816af7.list


)
mv /cromwell_root/rc.tmp /cromwell_root/rc
```

**Comment by Horneth** [comment]
That is strange indeed. You're saying if you start a container with the same image and try to run the same exact command that's in the script it works ?
(`/app/fastqc_docker.py --output-dir . --read "/cromwell_root/genovic-test-data/cardiom/NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz" --format fastq`)

**Comment by TMiguelT** [comment]
Yep, if I run the container myself, it works fine:

```bash
(base) root@27c805ebd156:/app# /app/fastqc_docker.py --output-dir . --read /root/in/NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz --format fastq
Started analysis of NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 5% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 10% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 15% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 20% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 25% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 30% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 35% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 40% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 45% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 50% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 55% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 60% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 65% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 70% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 75% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 80% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 85% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 90% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Approx 95% complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
Analysis complete for NA12878_CARDIACM_MUTATED_L001_R1.fastq.gz
```
