### ISSUE TITLE
Failed to import workflow

### ISSUE THREAD

**Issue by egarciarivera** [broadinstitute/cromwell#4482]
Hello, I'm cross-posting this issue from the GATK git since it doesn't seem to be active. I'm encountering the following issue with Cromwell:

cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed: Unable to load namespace from workflow: Failed to import workflow SomaticPairedSingleSampleWf.wdl.: File not found /wdl_runner/SomaticPairedSingleSampleWf.wdl at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:186) at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:156) at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:151) at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34) at akka.actor.FSM.processEvent(FSM.scala:663) at akka.actor.FSM.processEvent$(FSM.scala:660) at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:114) at akka.actor.LoggingFSM.processEvent(FSM.scala:799) at akka.actor.LoggingFSM.processEvent$(FSM.scala:781) at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:114) at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:657) at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651) at akka.actor.Actor.aroundReceive(Actor.scala:513) at akka.actor.Actor.aroundReceive$(Actor.scala:511) at cromwell.engine.workflow.lifecycle.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:114) at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) at akka.actor.ActorCell.invoke(ActorCell.scala:496) at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) at akka.dispatch.Mailbox.run(Mailbox.scala:224) at akka.dispatch.Mailbox.exec(Mailbox.scala:234) at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

This is the command I use to start Cromwell:

gcloud alpha genomics pipelines run \ --pipeline-file wdl_runner/wdl_pipeline.yaml \ --zones us-east1-c \ --memory 5 \ --logging "${GATK_OUTPUT_DIR}/logging" \ --inputs-from-file WDL="${GATK_GOOGLE_DIR}/FullSomaticPipeline.wdl" \ --inputs-from-file WORKFLOW_INPUTS="${GATK_GOOGLE_DIR}/FullSomaticPipeline_public_urls.json" \ --inputs-from-file WORKFLOW_OPTIONS="${GATK_GOOGLE_DIR}/FullSomaticPipeline.options.json" \ --inputs WORKSPACE="${GATK_OUTPUT_DIR}/workspace" \ --inputs OUTPUTS="${GATK_OUTPUT_DIR}/outputs"

Attempting to run this pipeline: https://github.com/gatk-workflows/gatk4-somatic-with-preprocessing

Any help here would be appreciated, and apologies if this is the wrong forum for this issue.

**Comment by aednichols** [comment]
Are you creating a .zip file of dependencies to submit to Cromwell alongside the root WDL?
