### ISSUE TITLE
Workflow import not working in Cromwell AWS

### ISSUE THREAD

**Issue by asmoe4** [broadinstitute/cromwell#4509]
Hi

I have a workflow named `main_wf.wdl` which imports a subworkflow named `sub_wf.wdl` like the following:
```
import "sub_wf.wdl" as sub
```
I am able to run `main_wf.wdl` in run mode.  But when I run a cromwell server and uses the swagger UI to commit the above workflow, I get the following error:

```
2018-12-17 11:47:12,214 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2018-12-17 11:47:12,235 cromwell-system-akka.dispatchers.engine-dispatcher-34 INFO  - WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
2018-12-17 11:47:13,348 cromwell-system-akka.dispatchers.engine-dispatcher-28 ERROR - WorkflowManagerActor Workflow 3bd35e44-d8a7-41ed-8271-c773949e8c5c failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
error in opening zip file
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:214)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:184)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:179)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:135)
```
I put the `sub_wf.wdl` into a `workflow.zip` file like below:
```
workflow.zip
 |----- sub_wf.wdl
```

Can you please advice? 

Thanks

**Comment by aednichols** [comment]
Thanks for reporting, @asmoe4.

A few questions:
- Which Cromwell version are you using?
- Have you ever run this workflow successfully on a previous version of Cromwell?
- Does the workflow run on a backend other than AWS? You could try e.g. the [local backend](https://cromwell.readthedocs.io/en/stable/backends/Local/).

---

Developer notes:
- I've never seen the error message `error in opening zip file` before, a quick Google suggests it's coming straight out of `java.util.zip`
- The only recent zip change I can think of is one that Shouldn't Break Anything, https://github.com/broadinstitute/cromwell/pull/4399. If this is a regression (based on reported Cromwell version), that's where I'd start looking.

**Comment by asmoe4** [comment]
@aednichols 

* I'm running cromwell server using v36.  I haven't tested cromwell 35 in server mode.  
* This same workflow has been run successfully on local backend using both Cromwell version 35 and 36.

**Comment by aednichols** [comment]
When you say it's successful on local backend, is that run mode or server mode?

**Comment by aednichols** [comment]
#4399 is not in 36, so we can exclude that possibility.

The easiest case to debug is server mode with local backend. I'm curious what program you're using to create your zip file.

The only other similar issue I could find in Cromwell is https://github.com/broadinstitute/cromwell/issues/1799, which was a problem with the user's input.

**Comment by aednichols** [comment]
I get the same error message when e.g. renaming an arbitrary `.txt` file to `.zip` - that's not necessarily what's happening, but a clue that the zip itself may be bad.

**Comment by asmoe4** [comment]
I'm using `tar` to create `*.zip` like below on a Mac OS
```
tar -czvf workflow.zip sub_wf.wdl
```

Also, if you are running a local server, I'm assuming there's a place where zip file is downloaded and unzip to?  Do you know where on local machine that is running server does that zip file get unzipped to?

**Comment by aednichols** [comment]
It is a bit suspicious to me that the target of your `tar` command is a WDL file, not a directory containing WDL file(s).

I would try zipping with Finder - right click the directory, "Compress"

**Comment by aednichols** [comment]
>if it's a directory containing the sub_wf.wdl file then, I would have to change my import statement.

I think you can just use the bare file name in your import statement and Cromwell will locate it in the unzipped directory.

Cromwell unzips the compressed imports to a temporary directory with a random name, there's no way you would be required to write `import whereever_cromwell_unzipped_things/sub_wf.wdl`

**Comment by aednichols** [comment]
Ah, I see the issue: `tar -czvf workflow.zip sub_wf.wdl` is creating a `.tar.gz` file, confusingly with a `.zip` extension.

Only ZIP files are supported for imports.

**Comment by asmoe4** [comment]
I see.   Thanks!
