### ISSUE TITLE
Fix flakey test: MetadataDatabaseAccessSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4520]
Straight from the log: "Something has gone horribly wrong!"

Jenkins build 2475 (2 errors)
Jenkins build 2470
Jenkins build 2426

**Comment by mcovarr** [comment]
```
- should return pagination metadata only when page and pagesize query params are specified *** FAILED *** (9 seconds, 457 milliseconds)
java.sql.SQLTransientConnectionException: db - Connection is not available, request timed out after 3608ms.
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:548)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:145)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83)
at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:14)
at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:453)
at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
```
