### ISSUE TITLE
Fix flakey test: WorkflowFailSlowSpec

### ISSUE THREAD

**Issue by geoffjentry** [broadinstitute/cromwell#4521]
Another CromwellTestKitSpecial

jenkins build 2438

**Comment by mcovarr** [comment]
This issue should not be closed since the problem has not been addressed at all. The associated PR was closed because it was fundamentally wrong. 🙁

**Comment by geoffjentry** [comment]
2667

```
org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 210 times over 3.3447279390999998 minutes. Last failure message: Submitted did not equal Failed.
      at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:432)
      at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
      at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
      at cromwell.CromwellTestKitSpec.eventually(CromwellTestKitSpec.scala:251)
      at cromwell.CromwellTestKitSpec.runWdl(CromwellTestKitSpec.scala:323)
      at cromwell.WorkflowFailSlowSpec.$anonfun$new$2(WorkflowFailSlowSpec.scala:18)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at cromwell.CromwellTestKitWordSpec.withFixture(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
      at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
      at cromwell.CromwellTestKitWordSpec.runTest(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
      at cromwell.CromwellTestKitWordSpec.runTests(CromwellTestKitSpec.scala:250)
      at org.scalatest.Suite.run(Suite.scala:1147)
      at org.scalatest.Suite.run$(Suite.scala:1129)
      at cromwell.CromwellTestKitSpec.org$scalatest$BeforeAndAfterAll$$super$run(CromwellTestKitSpec.scala:251)
      at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
      at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
      at cromwell.CromwellTestKitWordSpec.org$scalatest$WordSpecLike$$super$run(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
      at cromwell.CromwellTestKitWordSpec.run(CromwellTestKitSpec.scala:250)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
      at sbt.TestRunner.runTest$1(TestFramework.scala:113)
      at sbt.TestRunner.run(TestFramework.scala:124)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFunction.apply(TestFramework.scala:294)
      at sbt.Tests$.processRunnable$1(Tests.scala:347)
      at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
      at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
      at sbt.std.Transform$$anon$4.work(System.scala:67)
      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
      at sbt.Execute.work(Execute.scala:278)
      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
      Cause: org.scalatest.exceptions.TestFailedException: Submitted did not equal Failed
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6716)
      at cromwell.CromwellTestKitSpec.verifyWorkflowState(CromwellTestKitSpec.scala:377)
      at cromwell.CromwellTestKitSpec.$anonfun$runWdl$1(CromwellTestKitSpec.scala:323)
      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
      at org.scalatest.concurrent.Eventually.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
      at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
      at cromwell.CromwellTestKitSpec.eventually(CromwellTestKitSpec.scala:251)
      at cromwell.CromwellTestKitSpec.runWdl(CromwellTestKitSpec.scala:323)
      at cromwell.WorkflowFailSlowSpec.$anonfun$new$2(WorkflowFailSlowSpec.scala:18)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at cromwell.CromwellTestKitWordSpec.withFixture(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
      at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
      at cromwell.CromwellTestKitWordSpec.runTest(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
      at cromwell.CromwellTestKitWordSpec.runTests(CromwellTestKitSpec.scala:250)
      at org.scalatest.Suite.run(Suite.scala:1147)
      at org.scalatest.Suite.run$(Suite.scala:1129)
      at cromwell.CromwellTestKitSpec.org$scalatest$BeforeAndAfterAll$$super$run(CromwellTestKitSpec.scala:251)
      at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
      at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
      at cromwell.CromwellTestKitWordSpec.org$scalatest$WordSpecLike$$super$run(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
      at cromwell.CromwellTestKitWordSpec.run(CromwellTestKitSpec.scala:250)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
      at sbt.TestRunner.runTest$1(TestFramework.scala:113)
      at sbt.TestRunner.run(TestFramework.scala:124)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFunction.apply(TestFramework.scala:294)
      at sbt.Tests$.processRunnable$1(Tests.scala:347)
      at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
      at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
      at sbt.std.Transform$$anon$4.work(System.scala:67)
      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
      at sbt.Execute.work(Execute.scala:278)
      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```

**Comment by geoffjentry** [comment]
Build 3730

```
org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 210 times over 3.3499629773500006 minutes. Last failure message: Submitted did not equal Failed.
      at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:432)
      at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
      at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
      at cromwell.CromwellTestKitSpec.eventually(CromwellTestKitSpec.scala:251)
      at cromwell.CromwellTestKitSpec.runWdl(CromwellTestKitSpec.scala:323)
      at cromwell.WorkflowFailSlowSpec.$anonfun$new$4(WorkflowFailSlowSpec.scala:30)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at cromwell.CromwellTestKitWordSpec.withFixture(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
      at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
      at cromwell.CromwellTestKitWordSpec.runTest(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
      at cromwell.CromwellTestKitWordSpec.runTests(CromwellTestKitSpec.scala:250)
      at org.scalatest.Suite.run(Suite.scala:1147)
      at org.scalatest.Suite.run$(Suite.scala:1129)
      at cromwell.CromwellTestKitSpec.org$scalatest$BeforeAndAfterAll$$super$run(CromwellTestKitSpec.scala:251)
      at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
      at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
      at cromwell.CromwellTestKitWordSpec.org$scalatest$WordSpecLike$$super$run(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
      at cromwell.CromwellTestKitWordSpec.run(CromwellTestKitSpec.scala:250)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
      at sbt.TestRunner.runTest$1(TestFramework.scala:113)
      at sbt.TestRunner.run(TestFramework.scala:124)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFunction.apply(TestFramework.scala:294)
      at sbt.Tests$.processRunnable$1(Tests.scala:347)
      at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
      at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
      at sbt.std.Transform$$anon$4.work(System.scala:67)
      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
      at sbt.Execute.work(Execute.scala:278)
      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
      Cause: org.scalatest.exceptions.TestFailedException: Submitted did not equal Failed
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6716)
      at cromwell.CromwellTestKitSpec.verifyWorkflowState(CromwellTestKitSpec.scala:377)
      at cromwell.CromwellTestKitSpec.$anonfun$runWdl$1(CromwellTestKitSpec.scala:323)
      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
      at org.scalatest.concurrent.Eventually.makeAValiantAttempt$1(Eventually.scala:395)
      at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:409)
      at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
      at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
      at cromwell.CromwellTestKitSpec.eventually(CromwellTestKitSpec.scala:251)
      at cromwell.CromwellTestKitSpec.runWdl(CromwellTestKitSpec.scala:323)
      at cromwell.WorkflowFailSlowSpec.$anonfun$new$4(WorkflowFailSlowSpec.scala:30)
      at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
      at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
      at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
      at org.scalatest.Transformer.apply(Transformer.scala:22)
      at org.scalatest.Transformer.apply(Transformer.scala:20)
      at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
      at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
      at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
      at cromwell.CromwellTestKitWordSpec.withFixture(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
      at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
      at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
      at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
      at cromwell.CromwellTestKitWordSpec.runTest(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
      at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
      at scala.collection.immutable.List.foreach(List.scala:389)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
      at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
      at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
      at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
      at cromwell.CromwellTestKitWordSpec.runTests(CromwellTestKitSpec.scala:250)
      at org.scalatest.Suite.run(Suite.scala:1147)
      at org.scalatest.Suite.run$(Suite.scala:1129)
      at cromwell.CromwellTestKitSpec.org$scalatest$BeforeAndAfterAll$$super$run(CromwellTestKitSpec.scala:251)
      at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
      at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
      at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
      at cromwell.CromwellTestKitWordSpec.org$scalatest$WordSpecLike$$super$run(CromwellTestKitSpec.scala:250)
      at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
      at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
      at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
      at cromwell.CromwellTestKitWordSpec.run(CromwellTestKitSpec.scala:250)
      at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
      at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
      at sbt.TestRunner.runTest$1(TestFramework.scala:113)
      at sbt.TestRunner.run(TestFramework.scala:124)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
      at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
      at sbt.TestFunction.apply(TestFramework.scala:294)
      at sbt.Tests$.processRunnable$1(Tests.scala:347)
      at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
      at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
      at sbt.std.Transform$$anon$4.work(System.scala:67)
      at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
      at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
      at sbt.Execute.work(Execute.scala:278)
      at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
      at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```
