### ISSUE TITLE
glob functionality seems to be broken in Cromwell 36: "glob(path, pattern) not implemented yet"

### ISSUE THREAD

**Issue by oneillkza** [broadinstitute/cromwell#4526]
When I try to use globs, I get the following error:

```
Evaluating glob(file_pattern) failed: glob(path, pattern) not implemented yet
```

I've created a minimal reproducible example:

## File `glob.wdl`
```
task hello {
  File in

  command {
    egrep 'CROMWELL' '${in}'
  }

  output {
    Array[String] matches = read_lines(stdout())
  }
}


workflow example {
  String file_pattern = '*.sh' 
  Array[File] files = glob(file_pattern)
  scatter(path in files) {
    call hello {input: in=path}
  }
}
```

When run with all-default paramters as follows:

```
java -jar cromwell-36.jar run glob.wdl
```

The following output results:

```
[2019-01-07 16:21:06,14] [info] Running with database db.url = jdbc:hsqldb:mem:094e8bf9-be0f-4d7c-854a-0cf1a15dc0d7;shutdown=false;hsqldb.tx=mvcc
[2019-01-07 16:21:16,40] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-01-07 16:21:16,42] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-01-07 16:21:16,62] [info] Running with database db.url = jdbc:hsqldb:mem:2efc8123-f7e8-4fe3-abed-48d1bcf8eb97;shutdown=false;hsqldb.tx=mvcc
[2019-01-07 16:21:17,27] [info] Slf4jLogger started
[2019-01-07 16:21:17,78] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-231ef13",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-01-07 16:21:17,87] [info] Metadata summary refreshing every 2 seconds.
[2019-01-07 16:21:17,94] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-01-07 16:21:18,00] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-01-07 16:21:18,02] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-01-07 16:21:19,53] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-01-07 16:21:19,58] [info] SingleWorkflowRunnerActor: Version 36
[2019-01-07 16:21:19,61] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-01-07 16:21:19,69] [info] Unspecified type (Unspecified version) workflow 18de8166-5f29-4288-9fa4-6741565446fd submitted
[2019-01-07 16:21:19,74] [info] SingleWorkflowRunnerActor: Workflow submitted [38;5;2m18de8166-5f29-4288-9fa4-6741565446fd[0m
[2019-01-07 16:21:19,75] [info] 1 new workflows fetched
[2019-01-07 16:21:19,77] [info] WorkflowManagerActor Starting workflow [38;5;2m18de8166-5f29-4288-9fa4-6741565446fd[0m
[2019-01-07 16:21:19,77] [info] WorkflowManagerActor Successfully started WorkflowActor-18de8166-5f29-4288-9fa4-6741565446fd
[2019-01-07 16:21:19,77] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-01-07 16:21:19,78] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-01-07 16:21:19,80] [[38;5;220mwarn[0m] SingleWorkflowRunnerActor: received unexpected message: Done in state RunningSwraData
[2019-01-07 16:21:19,98] [info] MaterializeWorkflowDescriptorActor [[38;5;2m18de8166[0m]: Parsing workflow as WDL draft-2
[2019-01-07 16:21:21,18] [info] MaterializeWorkflowDescriptorActor [[38;5;2m18de8166[0m]: Call-to-Backend assignments: example.hello -> Local
[2019-01-07 16:21:23,89] [[38;5;1merror[0m] WorkflowManagerActor Workflow 18de8166-5f29-4288-9fa4-6741565446fd failed (during ExecutingWorkflowState): java.lang.RuntimeException: Failed to evaluate 'example.files' (reason 1 of 1): Evaluating glob(file_pattern) failed: glob(path, pattern) not implemented yet
	at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$7(WorkflowExecutionActor.scala:510)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:63)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$2(list.scala:65)
	at cats.Eval$.advance(Eval.scala:272)
	at cats.Eval$.loop$1(Eval.scala:354)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
	at cats.Eval$Defer.value(Eval.scala:258)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:72)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
	at cats.Traverse$Ops.traverse(Traverse.scala:19)
	at cats.Traverse$Ops.traverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableNodes(WorkflowExecutionActor.scala:504)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:186)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:184)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:168)
	at akka.actor.FSM.processEvent(FSM.scala:687)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:49)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:49)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$Timers$$super$aroundReceive(WorkflowExecutionActor.scala:49)
	at akka.actor.Timers.aroundReceive(Timers.scala:51)
	at akka.actor.Timers.aroundReceive$(Timers.scala:40)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:49)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2019-01-07 16:21:23,91] [info] WorkflowManagerActor WorkflowActor-18de8166-5f29-4288-9fa4-6741565446fd is in a terminal state: WorkflowFailedState
[2019-01-07 16:21:30,36] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2019-01-07 16:21:32,96] [info] Workflow polling stopped
[2019-01-07 16:21:32,99] [info] Shutting down WorkflowStoreActor - Timeout = 5 seconds
[2019-01-07 16:21:32,99] [info] Shutting down WorkflowLogCopyRouter - Timeout = 5 seconds
[2019-01-07 16:21:33,02] [info] Aborting all running workflows.
[2019-01-07 16:21:33,03] [info] WorkflowStoreActor stopped
[2019-01-07 16:21:33,03] [info] Shutting down JobExecutionTokenDispenser - Timeout = 5 seconds
[2019-01-07 16:21:33,05] [info] JobExecutionTokenDispenser stopped
[2019-01-07 16:21:33,05] [info] WorkflowLogCopyRouter stopped
[2019-01-07 16:21:33,05] [info] Shutting down WorkflowManagerActor - Timeout = 3600 seconds
[2019-01-07 16:21:33,05] [info] WorkflowManagerActor All workflows finished
[2019-01-07 16:21:33,05] [info] WorkflowManagerActor stopped
[2019-01-07 16:21:33,05] [info] Connection pools shut down
[2019-01-07 16:21:33,07] [info] Shutting down SubWorkflowStoreActor - Timeout = 1800 seconds
[2019-01-07 16:21:33,07] [info] Shutting down JobStoreActor - Timeout = 1800 seconds
[2019-01-07 16:21:33,08] [info] Shutting down CallCacheWriteActor - Timeout = 1800 seconds
[2019-01-07 16:21:33,08] [info] Shutting down ServiceRegistryActor - Timeout = 1800 seconds
[2019-01-07 16:21:33,08] [info] Shutting down DockerHashActor - Timeout = 1800 seconds
[2019-01-07 16:21:33,08] [info] Shutting down IoProxy - Timeout = 1800 seconds
[2019-01-07 16:21:33,08] [info] SubWorkflowStoreActor stopped
[2019-01-07 16:21:33,08] [info] JobStoreActor stopped
[2019-01-07 16:21:33,08] [info] CallCacheWriteActor Shutting down: 0 queued messages to process
[2019-01-07 16:21:33,08] [info] WriteMetadataActor Shutting down: 0 queued messages to process
[2019-01-07 16:21:33,09] [info] KvWriteActor Shutting down: 0 queued messages to process
[2019-01-07 16:21:33,09] [info] DockerHashActor stopped
[2019-01-07 16:21:33,09] [info] CallCacheWriteActor stopped
[2019-01-07 16:21:33,09] [info] ServiceRegistryActor stopped
[2019-01-07 16:21:33,10] [info] IoProxy stopped
[2019-01-07 16:21:33,14] [info] Database closed
[2019-01-07 16:21:33,14] [info] Stream materializer shut down
[2019-01-07 16:21:33,15] [info] WDL HTTP import resolver closed
Workflow 18de8166-5f29-4288-9fa4-6741565446fd transitioned to state Failed
```

**Comment by oneillkza** [comment]
OK, digging further, it seems glob doesn't work in workflows, but it does work in tasks, ie this works fine:

```
task glob_task {
  String pattern
  command {}
  output { Array[File] files = glob(pattern) }
}

task hello {
  File in

  command {
    egrep 'CROMWELL' '${in}'
  }

  output {
    Array[String] matches = read_lines(stdout())
  }
}


workflow example {
  String file_pattern = '*.sh' 

  call glob_task{input: pattern="*.sh"}

  scatter(path in glob_task.files) {
    call hello {input: in=path}
  }
}
```

**Comment by oneillkza** [comment]
Fair enough, I guess?

Is there any particular reason why this decision was made? I definitely found it to be a gotcha, and the solution (making a task just to run glob) feels kinda hacky.

**Comment by delocalizer** [comment]
At a guess, because the implementation of globbing is backend-dependent and therefore depends on having a task for context.

**Comment by geoffjentry** [comment]
That’s exactly why. At least with how Cromwell works it’d be difficult at best to implement glob at the workflow level, so it was disallowed.

Since the WDL spec is separate from Cromwell now it could be changed but NB that’d be brutal on anyone hoping for a multibackended workflow in the future

**Comment by oneillkza** [comment]
Thanks for the explanation. "It'll be a huge headache" is good enough for me.

Is there any danger in using glob_tasks as above in terms of backend portability?

Also, could I ask what you mean here by "backend"? Do you mean Cromwell itself, as opposed to another WMS that might implement WDL, or do you mean it in the sense of the backend definition specified in the Cromwell conf file (ie Google Cloud vs SLURM etc)?

**Comment by geoffjentry** [comment]
@oneillkza 

re portability: If you're concerned about portability and I understand what you're trying to do, this won't do what you want.

 If what you're trying to say is "For every file in this location, DoSomething(File)" and you want to be portable to the cloud backends the problem your going to have is that the tasks run on a VM with a local filesystem but the files you want to glob will be in object storage (e.g. GCS, S3). You could make those files an input to the task, they'd get localized to the VM and you'd be good to go, but now we're back to the original problem - if you knew all of the files you wouldn't need a glob :)

I **think** you can get what you want by using the relatively new [Directory](hub.com/openwdl/wdl/blob/master/versions/development/SPEC.md#types) type, which is in the developmental version of WDL and unofficially supported by Cromwell at the moment. What I'm picturing is supplying a Directory input to `glob_tasks`, and then globbing out the files that you want from there (unless you're literally trying to get **all** the files in a Directory, in which case just use a Directory type in the first place).

cc'ing @cjllanwarne in case I've misspoke somewhere in here, he's a lot more knowledgable on the fine details

re backends: The words I use are an artifact of how Cromwell is constructed but I draw a mental distinction between the workflow engine itself (e.g. Cromwell, Nextflow, Snakemake, etc) and the underlying job execution platform (e.g. local machine, SLURM, SGE, GCP, AWS). They're often tightly coupled but aren't necessarily that way. There's increasing desire for engines which can compute across multiple execution platforms within the same workflow - so in Cromwell terms perhaps some of your `call`s are run on a local SLURM cluster backend, some are run on GCP backend, and some on AWS backend.

**Comment by oneillkza** [comment]
Thanks @geoffjentry !

Yeah, I'd realised that I needed to pass an absolute path into the workflow I'm trying to run, which works for running on our local SLURM cluster, but definitely wouldn't be portable or the "right" way to create the workflow.

It sounds like the Directory type would be the right way to do this in future, and as you say, passing a Directory down to a task to pick the needed files out. 

In the meanwhile, do you know if Cromwell's CWL implementation supports the CWL Directory type? Switching to CWL might also make sense for now.

**Comment by oneillkza** [comment]
Thanks again! 

And yep -- other than my immediate trial run, I'm in the process of tool evaluation for a wider roll-out of a workflow management system. We're definitely going to look more broadly at what best fulfils our needs.

**Comment by oneillkza** [comment]
Thanks, Geoff!
