### ISSUE TITLE
Problems with CWL when output is specified

### ISSUE THREAD

**Issue by kmavrommatis** [broadinstitute/cromwell#4538]
Hi, 
I have a CWL workflow which works well when no output is specified but fails with the following when output is added:

```
[2019-01-09 17:56:27,87] [error] WorkflowManagerActor Workflow b240bd3e-cdfd-45c8-be1e-046794929e90 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
Workflow output parameters such as WorkflowOutputParameter(file:///var/folders/34/kzv1pzl57s92dbz54rvr1px00000gn/T/b240bd3e-cdfd-45c8-be1e-046794929e90.temp.4180597054306144316/b240bd3e-cdfd-45c8-be1e-046794929e90.cwl#outputwf,None,None,None,None,None,None,Some(Inr(Inl([Ljava.lang.String;@2ff95103))),None,Some(Inl(Inl(File)))) are not supported.
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:211)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:181)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:176)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:684)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:135)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


```

The same workflow works on cwltool

The command I used is `java -jar cromwell-35.jar run -i exampleInput/cat.yml -p ../CWL/workflows/cat.zip ../CWL/workflows/wf_cat.cwl` 

the CWL worfklow:
```
class: Workflow
cwlVersion: v1.0
id: wf_cat
label: wf_cat
inputs:
  - id: input
    type: File
outputs:
  - id: outputwf
    outputSource:
      - cat_test/output
    type: File
steps:
  - id: cat_test
    in:
      - id: input
        source: input
    out:
      - id: output
    run: ./cat-test.cwl
    label: cat-test
requirements: []
```

When in the above wflow the outputs section is replaced with
```
outputs: []
```
The workflow is executed to completion (and the output is stored in the execution directory)
So it seems that cromwell cannot accept the outputs section in the workflow description, is this expected? 

 

The command line tool  which is then zipped in cat.zip and provided as input to the cromwell command line:
```
class: CommandLineTool
cwlVersion: v1.0
id: cat_test
baseCommand:
  - cat
inputs:
  - id: input
    type: File
    inputBinding:
      position: 0
outputs:
  - id: output
    type: File
    outputBinding:
      glob: '*.out'
label: cat-test
requirements:
  - class: DockerRequirement
    dockerPull: 'ubuntu:latest'
  - class: InlineJavascriptRequirement
stdout: '${ return inputs.input.basename + ".out" }'
```

**Comment by cjllanwarne** [comment]
Hi @kmavrommatis, having looked at this it appears that the Cromwell code is expecting `outputSource` to be a String, whereas you have that as an array. 

Given that it passes cwltool, I think this is a bug on our side, but it suggests that you might be able to try working around it for now by using `outputSource: "cat_test/output"`?

**Comment by kmavrommatis** [comment]
Thanks for the response.
Indeed it works when I follow your suggestion.
it would be nice to comply with the CWL spec, but works for now
Thanks

**Comment by cjllanwarne** [comment]
I totally agree! If it's ok with you I'd like to leave this ticket open as a bug marker, even if you were able to work around it for now?

Thanks!

**Comment by kmavrommatis** [comment]
@cjllanwarne 
works for me :)
Thanks

**Comment by ctjoreilly** [comment]
@cjllanwarne I've run into this issue also, while I can work around it currently, it will likely become an issue down the road when trying to build workflows comprising of scatter operations when you want to collect up the results.
