### ISSUE TITLE
Specify AWS location as final output directories does not work

### ISSUE THREAD

**Issue by kmavrommatis** [broadinstitute/cromwell#4541]
Hi,
following the example on how to use AWS Batch I am able to run the tests using the suggested edits to aws.conf.

I then try to specify the output directories using the following `options.json` file

```
{
    "final_workflow_outputs_dir": "s3://bucket/cromwell/outputs",
    "final_call_logs_dir": "s3:/bucket/cromwell/call_logs",
    "final_workflow_log_dir": "s3://bucket/cromwell/wf_logs"
}
```

When running cromwell : `java -Dconfig.file=awsbatch/aws.conf -jar cromwell-36.jar run awsbatch/hello.wdl -i awsbatch/hello.inputs  -o options.json`

it results with the error:

```
[2019-01-12 00:31:03,94] [info] $a [866d19d0]: Copying workflow logs from /rcecloud/kmavrommatis/workspace/Workflows/cromwell/cromwell-workflow-logs/workflow.866d19d0-64da-45c3-9b69-830f0475ba12.log to s3://celgene-rnd-riku-researchanalytics/cromwell/wf_logs/workflow.866d19d0-64da-45c3-9b69-830f0475ba12.log
[2019-01-12 00:31:04,03] [error] Key cannot be empty
java.lang.IllegalArgumentException: Key cannot be empty
	at software.amazon.awssdk.core.util.ValidationUtils.assertStringNotEmpty(ValidationUtils.java:111)
	at software.amazon.awssdk.core.runtime.transform.PathMarshallers$GreedyPathMarshaller.marshall(PathMarshallers.java:109)
	at software.amazon.awssdk.services.s3.transform.HeadObjectRequestMarshaller.marshall(HeadObjectRequestMarshaller.java:87)
	at software.amazon.awssdk.services.s3.transform.HeadObjectRequestMarshaller.marshall(HeadObjectRequestMarshaller.java:31)
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:88)
	at software.amazon.awssdk.core.client.SyncClientHandlerImpl.execute(SyncClientHandlerImpl.java:76)
	at software.amazon.awssdk.core.client.SdkClientHandler.execute(SdkClientHandler.java:45)
	at software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:1628)
	at org.lerch.s3fs.util.S3Utils.getS3ObjectSummary(S3Utils.java:47)
	at org.lerch.s3fs.S3FileSystemProvider.exists(S3FileSystemProvider.java:624)
	at org.lerch.s3fs.S3FileSystemProvider.checkAccess(S3FileSystemProvider.java:469)
	at java.nio.file.Files.exists(Files.java:2385)
	at better.files.File.exists(File.scala:138)
	at cromwell.core.path.BetterFileMethods.exists(BetterFileMethods.scala:70)
	at cromwell.core.path.BetterFileMethods.exists$(BetterFileMethods.scala:70)
	at cromwell.filesystems.s3.S3Path.exists(S3PathBuilder.scala:156)
	at cromwell.core.path.EvenBetterPathMethods.createPermissionedDirectories(EvenBetterPathMethods.scala:63)
	at cromwell.core.path.EvenBetterPathMethods.createPermissionedDirectories$(EvenBetterPathMethods.scala:62)
	at cromwell.filesystems.s3.S3Path.createPermissionedDirectories(S3PathBuilder.scala:156)
	at cromwell.core.path.EvenBetterPathMethods.createPermissionedDirectories(EvenBetterPathMethods.scala:64)
	at cromwell.core.path.EvenBetterPathMethods.createPermissionedDirectories$(EvenBetterPathMethods.scala:62)
	at cromwell.filesystems.s3.S3Path.createPermissionedDirectories(S3PathBuilder.scala:156)
	at cromwell.core.path.EvenBetterPathMethods.createPermissionedDirectories(EvenBetterPathMethods.scala:64)
	at cromwell.core.path.EvenBetterPathMethods.createPermissionedDirectories$(EvenBetterPathMethods.scala:62)
	at cromwell.filesystems.s3.S3Path.createPermissionedDirectories(S3PathBuilder.scala:156)
	at cromwell.engine.workflow.lifecycle.finalization.CopyWorkflowLogsActor.copyLog(CopyWorkflowLogsActor.scala:36)
	at cromwell.engine.workflow.lifecycle.finalization.CopyWorkflowLogsActor$$anonfun$copyLogsReceive$1.$anonfun$applyOrElse$1(CopyWorkflowLogsActor.scala:67)
	at scala.Option.foreach(Option.scala:257)
	at cromwell.engine.workflow.lifecycle.finalization.CopyWorkflowLogsActor$$anonfun$copyLogsReceive$1.applyOrElse(CopyWorkflowLogsActor.scala:62)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.finalization.CopyWorkflowLogsActor.aroundReceive(CopyWorkflowLogsActor.scala:30)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
```

Is there additional configuration required to specify outputs on s3? 

Thanks in advance for your help

**Comment by geoffjentry** [comment]
@kmavrommatis We believe this has been resolved in Cromwell 41. Can you check if this is working for you now?
