### ISSUE TITLE
Cromwell gives wrong error message with unclosed brace

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell#4549]
Cromwell: 36

I had the following config file, missing a brace:

```
backend {
  default = spartan

  providers {
    spartan {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
      config {
        runtime-attributes = """
        Int runtime_minutes = 600
        Int cpus = 2
        Int requested_memory_mb_per_core = 8000
        String queue = "short"
        """

        submit = """
            sbatch -J ${job_name} -D ${cwd} -o ${out} -e ${err} -t ${runtime_minutes} -p ${queue} \
            ${"-c " + cpus} \
            --mem-per-cpu=${requested_memory_mb_per_core} \
            --wrap "/bin/bash ${script}"
        """
        kill = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "Submitted batch job (\\d+).*"
      
    }
  }
}
```

When I ran `java -Dconfig.file=$(realpath spartan.conf) -jar cromwell-36.jar`, the error it printed was:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at cromwell.CromwellApp$.runCromwell(CromwellApp.scala:14)
	at cromwell.CromwellApp$.delayedEndpoint$cromwell$CromwellApp$1(CromwellApp.scala:25)
	at cromwell.CromwellApp$delayedInit$body.apply(CromwellApp.scala:3)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at cromwell.CromwellApp$.main(CromwellApp.scala:3)
	at cromwell.CromwellApp.main(CromwellApp.scala)
Caused by: com.typesafe.config.ConfigException$Parse: /data/cephfs/punim0751/spartan.conf: 27: expecting a close parentheses ')' here, not: end of file
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseKey(ConfigDocumentParser.java:279)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:450)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:458)
	at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
	at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
	at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:689)
	at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:51)
	at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:259)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:256)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:65)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:92)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:256)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:232)
	at cromwell.CromwellEntryPoint$.config$lzycompute(CromwellEntryPoint.scala:39)
	at cromwell.CromwellEntryPoint$.config(CromwellEntryPoint.scala:39)
	at cromwell.CromwellEntryPoint$.<init>(CromwellEntryPoint.scala:42)
	at cromwell.CromwellEntryPoint$.<clinit>(CromwellEntryPoint.scala)
```

In other words it tells me I'm missing a parenthesis `)`, but actually I was missing a brace `}`.

**Comment by aednichols** [comment]
Which brace was missing? The file you provided looks syntactically correct, based on an extremely scientific Command-F for `{` and `}`.

**Comment by TMiguelT** [comment]
Well I opened 4 braces and only closed 3

**Comment by geoffjentry** [comment]
FWIW that parser is a 3rd party library (https://github.com/lightbend/config)

**Comment by aednichols** [comment]
@TMiguelT I looked into this and we are using the latest version of the configuration library, so short of someone submitting a PR to fix their parsing issue, there is not much we can do.

Lightbend recommends a linting tool, http://www.hoconlint.com/, which when run on your sample file gives the correct error message!

**Comment by TMiguelT** [comment]
I might open this issue in the lightbend repo, then.

**Comment by geoffjentry** [comment]
@TMiguelT That'd be great if you're up for doing that. That stacktrace looks like it should have the information they'd need
