### ISSUE TITLE
Unhelpful Error Message

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/cromwell#4570]
(Probably related to #4081). 

Using cromwell v36. I had the following code block in my wdl:

```
call MergePileupSummaries as MergeTumorPileups {
            input:
                input_tables = TumorPileups.pileups,
                output_name = , // <--- forgot to specify this input
                ref_dict = ref_dict,
                gatk_override = gatk_override,
                gatk_docker = gatk_docker,
                preemptible_attempts = preemptible_attempts,
                max_retries = max_retries,
                disk_space = ceil(SumSubVcfs.total_size * large_input_to_output_multiplier) + disk_pad
        }
```

Cromwell error didn't give me anything, and `womtool validate` threw an exception:

```
tsato@gsa5:fc-read-orientation: java -jar womtool-36.jar validate mutect2.wdl
Exception in thread "main" scala.MatchError: null
	at wdl.draft2.model.WdlExpression$.toString(WdlExpression.scala:117)
	at wdl.draft2.model.WdlExpression.toString(WdlExpression.scala:200)
	at wdl.draft2.model.WdlExpression.toWomString(WdlExpression.scala:203)
	at wom.values.WomValue.valueString(WomValue.scala:50)
	at wom.values.WomValue.valueString$(WomValue.scala:50)
	at wdl.draft2.model.WdlExpression.valueString(WdlExpression.scala:185)
	at wdl.draft2.model.WdlWomExpression.sourceString(WdlExpression.scala:219)
	at wom.graph.expression.ExpressionNode$.$anonfun$buildFromConstructor$4(ExpressionNode.scala:66)
	at cats.data.NonEmptyList.map(NonEmptyList.scala:76)
	at wom.graph.expression.ExpressionNode$.$anonfun$buildFromConstructor$3(ExpressionNode.scala:66)
	at cats.data.Validated.leftMap(Validated.scala:203)
	at wom.graph.expression.ExpressionNode$.buildFromConstructor(ExpressionNode.scala:66)
	at wom.graph.expression.AnonymousExpressionNode$.fromInputMapping(AnonymousExpressionNode.scala:17)
	at wdl.draft2.model.WdlWomExpression$.$anonfun$toAnonymousExpressionNode$1(WdlExpression.scala:293)
	at common.validation.ErrorOr$ShortCircuitingFlatMap$.flat
```

**Comment by ruchim** [comment]
Hey Takuto, based on the linked issue which was resolved, would you mind confirming whether this behavior still exists on Cromwell v38? Thanks.
