### ISSUE TITLE
liquibase ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jeremiahsavage** [broadinstitute/cromwell#4605]
I get an `ArrayIndexOutOfBoundsException` error when starting the latest `develop` branch in server mode with a mysql (`mariadb-10.3.12-5.fc30.x86_64`) backend.
```
[jeremiah@localhost cromwell]$ java -Dconfig.file=/home/jeremiah/cromwell.mysql.conf -jar server/target/scala-2.12/cromwell-37-56b0390-SNAP.jar server
2019-01-31 18:29:28,169  INFO  - Running with database db.url = jdbc:mysql://localhost/cromwell?rewriteBatchedStatements=true
2019-01-31 18:29:32,763  INFO  - SELECT COUNT(*) FROM cromwell.DATABASECHANGELOGLOCK
2019-01-31 18:29:32,786  INFO  - CREATE TABLE cromwell.DATABASECHANGELOGLOCK (ID INT NOT NULL, `LOCKED` BIT(1) NOT NULL, LOCKGRANTED datetime NULL, LOCKEDBY VARCHAR(255) NULL, CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))
2019-01-31 18:29:32,845  INFO  - SELECT COUNT(*) FROM cromwell.DATABASECHANGELOGLOCK
2019-01-31 18:29:32,853  INFO  - DELETE FROM cromwell.DATABASECHANGELOGLOCK
2019-01-31 18:29:32,854  INFO  - INSERT INTO cromwell.DATABASECHANGELOGLOCK (ID, `LOCKED`) VALUES (1, 0)
2019-01-31 18:29:32,869  INFO  - SELECT `LOCKED` FROM cromwell.DATABASECHANGELOGLOCK WHERE ID=1
2019-01-31 18:29:32,888  INFO  - Successfully acquired change log lock
2019-01-31 18:29:35,077  INFO  - Creating database history table with name: cromwell.DATABASECHANGELOG
2019-01-31 18:29:35,078  INFO  - CREATE TABLE cromwell.DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME VARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NOT NULL, MD5SUM VARCHAR(35) NULL, `DESCRIPTION` VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(255) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID VARCHAR(10) NULL)
2019-01-31 18:29:35,271  INFO  - SELECT COUNT(*) FROM cromwell.DATABASECHANGELOG
2019-01-31 18:29:35,279  INFO  - Reading from cromwell.DATABASECHANGELOG
2019-01-31 18:29:35,280  INFO  - SELECT * FROM cromwell.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2019-01-31 18:29:35,282  INFO  - SELECT COUNT(*) FROM cromwell.DATABASECHANGELOGLOCK
2019-01-31 18:29:35,461  INFO  - Successfully released change log lock
2019-01-31 18:29:35,469  ERROR - Failed to instantiate Cromwell System. Shutting down Cromwell.
java.lang.ArrayIndexOutOfBoundsException: 1
	at liquibase.datatype.DataTypeFactory.fromDescription(DataTypeFactory.java:251)
	at liquibase.change.core.CreateTableChange.generateStatements(CreateTableChange.java:70)
	at liquibase.change.AbstractChange.generateStatementsVolatile(AbstractChange.java:287)
	at liquibase.change.AbstractChange.warn(AbstractChange.java:358)
	at liquibase.changelog.visitor.ValidatingVisitor.visit(ValidatingVisitor.java:109)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:269)
	at liquibase.Liquibase.update(Liquibase.java:198)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at cromwell.database.migration.liquibase.LiquibaseUtils$.updateSchema(LiquibaseUtils.scala:62)
	at cromwell.database.migration.liquibase.LiquibaseUtils$.updateSchema(LiquibaseUtils.scala:34)
	at cromwell.services.ServicesStore$EnhancedSqlDatabase$.$anonfun$initialized$1(ServicesStore.scala:11)
	at cromwell.services.ServicesStore$EnhancedSqlDatabase$.$anonfun$initialized$1$adapted(ServicesStore.scala:11)
	at cromwell.database.slick.SlickDatabase.$anonfun$withConnection$1(SlickDatabase.scala:155)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
with the linked change
https://github.com/jeremiahsavage/cromwell/commit/88f82a0d699184358149a17a5c1d957704cdced3
the database table creation proceeds
as it undoes one of the changes in this commit
https://github.com/broadinstitute/cromwell/commit/775d2cb414734080978cc9c2533cab41b4acfad5
```
[jeremiah@localhost cromwell]$ java -Dconfig.file=/home/jeremiah/cromwell.mysql.conf -jar server/target/scala-2.12/cromwell-37-88f82a0-SNAP.jar server
2019-01-31 18:42:55,062  INFO  - Running with database db.url = jdbc:mysql://localhost/cromwell?rewriteBatchedStatements=true
2019-01-31 18:43:01,372  INFO  - Successfully acquired change log lock
2019-01-31 18:43:04,396  INFO  - Creating database history table with name: cromwell.DATABASECHANGELOG
2019-01-31 18:43:04,492  INFO  - Reading from cromwell.DATABASECHANGELOG
2019-01-31 18:43:04,918  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,926  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,926  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,927  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,927  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,928  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,928  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,929  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,934  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,936  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,937  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,937  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:04,937  WARN  - modifyDataType will lose primary key/autoincrement/not null settings for mysql.  Use <sql> and re-specify all configuration if this is the case
2019-01-31 18:43:05,044  INFO  - changelog.xml: changesets/db_schema.xml::db_schema_other_table_alldb::scottfrazer: Table WORKFLOW_EXECUTION created
2019-01-31 18:43:05,122  INFO  - changelog.xml: changesets/db_schema.xml::db_schema_other_table_alldb::scottfrazer: Table EXECUTION created
2019-01-31 18:43:05,285  INFO  - changelog.xml: changesets/db_schema.xml::db_schema_other_table_alldb::scottfrazer: Table JES_JOB created
2019-01-31 18:43:05,477  INFO  - changelog.xml: changesets/db_schema.xml::db_schema_other_table_alldb::scottfrazer: Table LOCAL_JOB created
2019-01-31 18:43:05,477  INFO  - changelog.xml: changesets/db_schema.xml::db_schema_other_table_alldb::scottfrazer: ChangeSet changesets/db_schema.xml::db_schema_other_table_alldb::scottfrazer ran successfully in 538ms
2019-01-31 18:43:05,650  INFO  - changelog.xml: changesets/db_schema.xml::db_schema_symbol_table_mysql::scottfrazer: Table SYMBOL created
```

**Comment by kshakir** [comment]
We will likely need to upgrade liquibase at some point but for the moment PR #4619 does a temporary downgrade. Issue #4618 tracks that MariaDB needs to be CI tested to make sure this doesn't re-occur.

Thanks for the report!
