### ISSUE TITLE
Workflow Actor Crash

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#4916]
From a quick reading of the parent `WorkflowManagerActor` code it appears the default supervision strategy with "restart on generic Exception" is being used. Simply restarting a crashed `WorkflowActor` FSM appears to put it back into its initial `WorkflowUnstartedState` where it wouldn't do anything to progress a workflow until it receives a `StartWorkflowCommand` which is not being re-sent. So it looks like this would create a zombie workflow, though it does appear to be abortable.
```
ERROR akka.actor.OneForOneStrategy - Google credentials are invalid: Error getting access token for service account: 400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT Signature."
}
java.lang.RuntimeException: Google credentials are invalid: Error getting access token for service account: 400 Bad Request
{
  "error": "invalid_grant",
  "error_description": "Invalid JWT Signature."
}
	at cromwell.cloudsupport.gcp.auth.GoogleAuthMode.validateCredentials(GoogleAuthMode.scala:175)
	at cromwell.cloudsupport.gcp.auth.GoogleAuthMode.validateCredentials$(GoogleAuthMode.scala:173)
	at cromwell.cloudsupport.gcp.auth.UserServiceAccountMode.validateCredentials(GoogleAuthMode.scala:237)
	at cromwell.cloudsupport.gcp.auth.UserServiceAccountMode.credentials(GoogleAuthMode.scala:250)
	at cromwell.cloudsupport.gcp.auth.UserServiceAccountMode.credentials(GoogleAuthMode.scala:237)
	at cromwell.filesystems.drs.DrsPathBuilderFactory.withOptions(DrsPathBuilderFactory.scala:86)
	at cromwell.core.path.PathBuilderFactory$.$anonfun$instantiatePathBuilders$2(PathBuilderFactory.scala:23)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:74)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:64)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$1(list.scala:64)
	at cats.Eval$$anon$11.$anonfun$start$3(Eval.scala:275)
	at cats.Eval$.loop$1(Eval.scala:336)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
	at cats.Eval$Defer.value(Eval.scala:257)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:73)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
	at cats.Traverse$Ops.traverse(Traverse.scala:19)
	at cats.Traverse$Ops.traverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
	at cromwell.core.path.PathBuilderFactory$.instantiatePathBuilders(PathBuilderFactory.scala:23)
	at cromwell.engine.EngineFilesystems$.pathBuildersForWorkflow(EngineFilesystems.scala:27)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$8.bruteForcePathBuilders$1(WorkflowActor.scala:432)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$8.applyOrElse(WorkflowActor.scala:436)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$8.applyOrElse(WorkflowActor.scala:407)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.$anonfun$handleTransition$1(FSM.scala:627)
	at akka.actor.FSM.$anonfun$handleTransition$1$adapted(FSM.scala:627)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at akka.actor.FSM.handleTransition(FSM.scala:627)
	at akka.actor.FSM.makeTransition(FSM.scala:709)
	at akka.actor.FSM.makeTransition$(FSM.scala:702)
	at cromwell.engine.workflow.WorkflowActor.makeTransition(WorkflowActor.scala:186)
	at akka.actor.FSM.applyState(FSM.scala:694)
	at akka.actor.FSM.applyState$(FSM.scala:692)
	at cromwell.engine.workflow.WorkflowActor.applyState(WorkflowActor.scala:186)
	at akka.actor.FSM.processEvent(FSM.scala:689)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.WorkflowActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowActor.scala:186)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.WorkflowActor.processEvent(WorkflowActor.scala:186)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.WorkflowActor.akka$actor$Timers$$super$aroundReceive(WorkflowActor.scala:186)
	at akka.actor.Timers.aroundReceive(Timers.scala:55)
	at akka.actor.Timers.aroundReceive$(Timers.scala:40)
	at cromwell.engine.workflow.WorkflowActor.aroundReceive(WorkflowActor.scala:186)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by aednichols** [comment]
@mcovarr do you have acceptance criteria in mind for this story?

It looks like maybe this slipped into the sprint without being fully refined ("Needs Refinement")?

**Comment by mcovarr** [comment]
I don't know what's going on with the labels. Ruchi, Gemma and I discussed this when I was Acting Delivery Czar for a day in your absence. It definitely was in the sprint at one point.

A/C: at a minimum emulate the exception above and confirm that a running WorkflowActor does not crash and hang forever without making progress. Some very nice-to-haves would be understanding what actually is going on here; could we be failing faster with conspicuous broken credentials? Also de-scary any error messages a la the other `OneForOneStrategy` tickets as appropriate.

**Comment by aednichols** [comment]
Happens in bursts, and only started relatively recently

![Screenshot-2019-5-21 Kibana](https://user-images.githubusercontent.com/1087943/58131039-980c8880-7beb-11e9-8927-c167cc1acc55.png)

**Comment by gemmalam** [comment]
Issue moved to Jira
https://broadworkbench.atlassian.net/browse/BA-4916
