### ISSUE TITLE
Unable to read_string in task outputs for files containing ${xyz}

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#4928]
For example:
```
task foo {
  String dollar = "$"
  command <<<
    cat > foo.txt << 'EOF'
      oops ${dollar}{BLAH}
    EOF
  >>>

  output {
    String x = read_string(foo.txt)
  }
}
```

Note: If I made a mistake constructing this example and it seems to work fine, we might need to ask @salonishah11 for a known-to-not-work WDL file

**Comment by salonishah11** [comment]
@cjllanwarne that wdl does look right. I was able to reproduce the error successfully using a similar wdl in Papiv2 backend:
```
task random_words {

  String dollar = "$"
  command <<<
    cat << 'EOF' > random.txt
    This should fail. ${dollar}{Hello} blah blah
    EOF
  >>>

  runtime {
    docker: "ubuntu:latest"
  }

  output {
    String text = read_string("random.txt")
  }
}

workflow read_random_words {
  call random_words

  output {
    String random_text = random_words.text
  }
}
```

The error thrown by Cromwell is:
```
ERROR - WorkflowManagerActor Workflow a8de1168-8b70-4d54-83f6-aa41adc8f87e failed (during ExecutingWorkflowState): java.lang.RuntimeException: Failed to evaluate 'read_random_words.random_text' (reason 1 of 1): Evaluating random_words.text failed: key not found: random_words
	at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$7(WorkflowExecutionActor.scala:523)
	at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:74)
	at cats.instances.ListInstances$$anon$1.loop$2(list.scala:64)
	at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$2(list.scala:66)
	at cats.Eval$.advance(Eval.scala:271)
	at cats.Eval$.loop$1(Eval.scala:350)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
	at cats.Eval$Defer.value(Eval.scala:257)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:73)
	at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
	at cats.Traverse$Ops.traverse(Traverse.scala:19)
	at cats.Traverse$Ops.traverse$(Traverse.scala:19)
	at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableNodes(WorkflowExecutionActor.scala:517)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:188)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:186)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:168)
	at akka.actor.FSM.processEvent(FSM.scala:687)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:51)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:51)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$Timers$$super$aroundReceive(WorkflowExecutionActor.scala:51)
	at akka.actor.Timers.aroundReceive(Timers.scala:51)
	at akka.actor.Timers.aroundReceive$(Timers.scala:40)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:51)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
