### ISSUE TITLE
Access to optional variables in conditionals broken for WDL 1.0 (works w draft-2)

### ISSUE THREAD

**Issue by jdidion** [broadinstitute/cromwell#4981]
I've attached two workflows that are essentially the same, one that conforms to draft-2 and the other that conforms to 1.0. The former runs fine (Cromwell v40), the latter one fails. It looks like there's a regression in handling the following situation:

```wdl
task bar {
  input {
    Array[Array[String]]? baz
  }
  command <<<
  echo ~{ if defined(baz) then write_tsv(baz) else 'no file' }
  >>>
  ...
}

Error:

```java
Failed to process task definition 'bar' (reason 1 of 1): Failed to process expression 'if defined(baz) then write_tsv(baz) else ""' (reason 1 of 1): Invalid parameter 'IdentifierLookup(baz)'. Expected 'Array[Array[String]]' but got 'Array[Array[String]]?'
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:215)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:185)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:180)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.actor.FSM.processEvent(FSM.scala:684)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.akka$actor$LoggingFSM$$super$processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
        at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.processEvent(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.aroundReceive(MaterializeWorkflowDescriptorActor.scala:136)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
        at akka.actor.ActorCell.invoke(ActorCell.scala:557)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
        at akka.dispatch.Mailbox.run(Mailbox.scala:225)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)


```

**Comment by jdidion** [comment]
Failing workflow:

```wdl
version 1.0

workflow foo {
  call bar
  output {
    File? baz = bar.baz
  }
}

task bar {
  input {
    Array[Array[String]]? baz 
  }
  command <<<
  x=~{ if defined(baz) then write_tsv(baz) else '' }
  if [[ -z "$x" ]]; then
    echo "no file"
  else
    cp $x output.tsv
  fi
  >>>
  output {
    Array[File] baz = glob("*.tsv")
  }
}
```

**Comment by jdidion** [comment]
Working workflow:

```wdl
workflow foo {
  call bar
  output {
    Array[File] baz = bar.baz
  }
}

task bar {
  File? f
  command <<<
  x=${ if defined(f) then write_tsv(f) else '' }
  if [[ -z "$x" ]]; then
    echo "no file"
  else
    cp $x output.tsv
  fi
  >>>
  output {
   Array[File] baz = glob("*.tsv")
  }
}
```

**Comment by jdidion** [comment]
Still broke in v41

**Comment by cjllanwarne** [comment]
hey @jdidion, the expression logic got tidied up a lot for our 1.0 support, and it appears that something which was evidently a useful "bug" in our draft-2 support got "fixed" for 1.0.

If you look over in the spec, the [`write_tsv` function](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#file-write_tsvarrayarraystring) requires a `Array[Array[String]]` argument (whereas you are passing in a `Array[Array[String]]?`). That's why Cromwell is no longer accepting the workflow.

I would suggest making a PR over in openWDL to explicitly allow `write_tsv` to accept optional inputs. In the meantime, you might be able to do something like this to work around this for now:

```wdl
  input {
    Array[Array[String]]? baz 
  }
  baz_if_defined = select_first([baz, []])

  command {
    x=~{ if defined(baz) then write_tsv(definitely_baz) else '' }
  }
```

**Comment by jdidion** [comment]
Thanks @cjllanwarne. However, it seems the issue here is that Cromwell is trying to evaluate the `write_tsv(baz)` part of the expression regardless of whether `defined(baz)` is true. Should conditionals be evaluated lazily?

**Comment by jdidion** [comment]
Your work-around works, so I'll go with that for now. Thanks

**Comment by ruchim** [comment]
@cjllanwarne -- my understanding is that the read/write functions can't be optionally performed in the command, since the write and read involve file functions --which tend to happen upstream of the command being initiated?

**Comment by gemmalam** [comment]
This issue exists in Jira now. Please add new comments to this link 
https://broadworkbench.atlassian.net/browse/BA-4981

You will be required to create a Jira account if you don't have one already.

**Comment by jdidion** [comment]
@gemmalam I tried to create an account but got an error saying I don't have access

**Comment by gemmalam** [comment]
@jdidion what is your email? I will look into this.

**Comment by gemmalam** [comment]
@jdidion I talked to a site admin and this setting should be updated. Please let me know if you run into this error again and I will add you manually and continue to communicate with our site admin about this issue.

**Comment by jdidion** [comment]
Thanks. Do you know what email address they updated? I still cannot access the project containing that issue.

**Comment by gemmalam** [comment]
@jdidion I didn't receive an email address from you so I didn't manually add you. You should be able to sign up with a gmail account. Full access sometimes is delayed so you may need to try and log in again later.

**Comment by jdidion** [comment]
I signed up with my gmail account awhile ago but still don't have access. It is johndidion@gmail.com.

**Comment by gemmalam** [comment]
@jdidion I've added you. Let me know if you still need help with access.

**Comment by jdidion** [comment]
It works now, thank you. I'm going to remove my email address from the previous comment.
