### ISSUE TITLE
transient lack of Google Cloud resources causes permanent workflow failure

### ISSUE THREAD

**Issue by notestaff** [broadinstitute/cromwell#5001]
I saw a case where lack of Google Cloud resources caused a permanent workflow failure, for what seems like a transient condition that could be overcome by retries:

2019-05-24 12:32:07,173 cromwell-system-akka.dispatchers.backend-dispatcher-38 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID\
(a309b1f1)assemble_denovo.filter_to_taxon:NA:1]: Status change from Running to Failed
2019-05-24 12:32:08,258 cromwell-system-akka.dispatchers.engine-dispatcher-74 ERROR - WorkflowManagerActor Workflow a309b1f1-2b35-4396\
-9f42-bcb3c2d01724 failed (during ExecutingWorkflowState): java.lang.Exception: Task assemble_denovo.filter_to_taxon:NA:1 failed. The \
job was stopped before the command finished. PAPI error code 2. The zone 'projects/viral-comp-dev/zones/us-central1-b' does not have e\
nough resources available to fulfill the request.  '(resource type:compute)'.
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor$.StandardException(PipelinesApiAsyncBack\
endJobExecutionActor.scala:84)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleFailedRunStatus$1(PipelinesApiAsyn\
cBackendJobExecutionActor.scala:629)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsync\
BackendJobExecutionActor.scala:636)
        at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsync\
BackendJobExecutionActor.scala:88)
        at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$5.applyOrElse(StandardAsyncExecutionAc\
tor.scala:1114)
        at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$5.applyOrElse(StandardAsyncExecutionAc\
tor.scala:1110)
        at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:413)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2019-05-24 12:32:08,259 cromwell-system-akka.dispatchers.engine-dispatcher-74 INFO  - WorkflowManagerActor WorkflowActor-a309b1f1-2b35\
-UU-:@----F2  cromwell.log.10329.txt    9% L305   (Text) Fri May 24 13:02 1.17 --------------------------------------------------------

**Comment by geoffjentry** [comment]
Assuming you're using PAPI2 (I believe you are), my understanding is that this **is** retried at the PAPI level, for quite some time.

If your'e using PAPI1, this is a known issue with PAPI1.

**Comment by notestaff** [comment]
Thanks.  What's strange is that many other analyses _were_ being run successfully at the time.  If the PAPI retry mechanism is somewhat deficient, maybe it makes sense for Cromwell to mask that by resubmitting the analysis?  E.g. there could be a config setting for the number of times to retry analyses that fail for transient-looking reasons.
