### ISSUE TITLE
Localization via hard link has failed and also Localization via copy has failed

### ISSUE THREAD

**Issue by tAndreani** [broadinstitute/cromwell#5066]
Hello,

I am having a problem that has been already discussed but I haven't been able to solve it using the suggestions. Basically, In the wdl workflow, I have two tasks (at the moment). The first works fine but the second is not starting because the output of the first task cannot be 'linked' or 'copied'. This cause the workflow to fail. The interesting part is that in the input folder of the second task there are two subfolders: 1 is empty named as `13016223` and the other is not accessible `-1976550098`.

The workflow to run needs installed:
`cutadapt` and the script named `moveBarcodeToID.pl` that can be downloaded from here:

 https://drive.google.com/open?id=1AizxTwjOEhL5XA7rsx-wbY97p0duB1nw

input fastq files can be retrieved here (they are small ~10000 reads each):

https://drive.google.com/file/d/1-c14Tja4zY3lyr6icFWT06stznR_-Zqr/view?usp=sharing
https://drive.google.com/file/d/1oJd_U9MjTllL0_kpNivw8I_LtSyvqpXH/view?usp=sharing

How can I solve this issue and make the workflow running smoothly?

###  Which backend are you running? 
I am running locally the workflow for now (because I am in the first phase of the development)

### Workflow is this:
```
#workflow validated before running with: wdltool validate example.wdl and womtool validate scMeth_v2.wdl.sh -i scMeth_input_3.json

workflow scMeth {
  # information for trimming the cell barcode
  File command
  Int bases
  File input_fastq1
  File input_fastq2
  String sampleName

  # information for trimming the adapters and low quality reads
  File file_format
  Int low_quality_cutoff
  Int read_length_cutoff
  String adapters_1
  String adapters_2
  Int trim_start_R1
  Int trim_end_R1
  Int trim_start_R2
  Int trim_end_R2
  String TAG
  call trimCellBarcode {
       input:
          sampleName=sampleName,
          bases=bases,
          input_fastq1=input_fastq1,
          input_fastq2=input_fastq2,
          command=command
 }
  call trimAdapters {
       input:
          file_format=file_format,
          input_r1 = trimCellBarcode.fastq_debarcoded_R1,
          input_r2 = trimCellBarcode.fastq_debarcoded_R2,
          low_quality_cutoff=low_quality_cutoff,
          read_length_cutoff=read_length_cutoff,
          adapters_1=adapters_1,
          adapters_2=adapters_2,
          trim_start_R1=trim_start_R1,
          trim_end_R1=trim_end_R1,
          trim_start_R2=trim_start_R2,
          trim_end_R2=trim_end_R2,
          TAG=TAG
 }
}

task trimCellBarcode {
 File command
 Int  bases
 File input_fastq1
 File input_fastq2
 String sampleName
 command {
  perl ${command} paired ${input_fastq1} ${input_fastq2} ${bases} ${sampleName}.R1.debarcoded.fq.gz ${sampleName}.R2.debarcoded.fq.gz
 }
 output {
   File fastq_debarcoded_R1 = "${sampleName}.R1.debarcoded.fq.gz"
   File fastq_debarcoded_R2 = "${sampleName}.R2.debarcoded.fq.gz"
 }
}

task trimAdapters {
  File file_format
  File input_r1
  File input_r2
  Int low_quality_cutoff
  Int read_length_cutoff
  String adapters_1
  String adapters_2
  Int trim_start_R1
  Int trim_end_R1
  Int trim_start_R2
  Int trim_end_R2
  String TAG
  String sampleName
  command {
     cutadapt -f ${file_format} -q ${low_quality_cutoff} -m ${read_length_cutoff} -a ${adapters_1} -A ${adapters_2} -u ${trim_start_R1} -u ${trim_end_R1} -U ${trim_start_R2} -U ${trim_end_R2} --length-tag=$TAG -o ${sampleName}.R1.trimmed.gz -p ${sampleName}.R2.trimmed.gz ${input_r1} ${input_r2}
 }
 output {
    File fastq_trimmed_R1 = "${sampleName}.R1.trimmed.gz"
    File fastq_trimmed_R2 = "${sampleName}.R2.trimmed.gz"
 }
}
```

### Input for the workflow is this:
```
#input WDL

{
  "scMeth.sampleName": "sub",
  "scMeth.input_fastq1": "sub_1.fastq.gz",
  "scMeth.input_fastq2": "sub_2.fastq.gz",
  "scMeth.file_format": "fastq",
  "scMeth.command": "moveBarcodeToID.pl",
  "scMeth.low_quality_cutoff": 21,
  "scMeth.read_length_cutoff": 62,
  "scMeth.TAG": "'length='",
  "scMeth.bases": 6,
  "scMeth.trim_start_R1": 11,
  "scMeth.trim_end_R1": -16,
  "scMeth.trim_start_R2": 25,
  "scMeth.trim_end_R2": -2,
  "scMeth.trimAdapters.sampleName": "sub",
  "scMeth.adapters_1": "AGATCGGAAGAGCACACGTCTGAAC",
  "scMeth.adapters_2": "AGATCGGAAGAGCGTCGTGTAGGGA"
}

```

### configuration named as `your_2.conf` file is:
```
include required(classpath("application"))
```

### Run as:
`java -jar -Dconfig.file=your_2.conf cromwell-42.jar run -i scMeth_input_3.json scMeth_v2.wdl.sh`

### Error is:

```
[2019-07-10 14:32:46,75] [info] Running with database db.url = jdbc:hsqldb:mem:fad09ca5-b589-4874-b5de-bbd1dc0064fe;shutdown=false;hsqldb.tx=mvcc
[2019-07-10 14:32:53,36] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2019-07-10 14:32:53,38] [info] [RenameWorkflowOptionsInMetadata] 100%
[2019-07-10 14:32:53,46] [info] Running with database db.url = jdbc:hsqldb:mem:39174976-89f7-4769-a52c-7d5a4afc6cf4;shutdown=false;hsqldb.tx=mvcc
[2019-07-10 14:32:53,81] [info] Slf4jLogger started
[2019-07-10 14:32:54,07] [info] Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-1cf43fa",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
[2019-07-10 14:32:54,11] [info] Metadata summary refreshing every 1 second.
[2019-07-10 14:32:54,12] [warn] 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
[2019-07-10 14:32:54,12] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2019-07-10 14:32:54,13] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-07-10 14:32:54,13] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2019-07-10 14:32:54,18] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2019-07-10 14:32:54,43] [info] SingleWorkflowRunnerActor: Version 42
[2019-07-10 14:32:54,44] [info] SingleWorkflowRunnerActor: Submitting workflow
[2019-07-10 14:32:54,48] [info] Unspecified type (Unspecified version) workflow 41d3eecf-c5a9-42e4-8a29-8be9c252b7f5 submitted
[2019-07-10 14:32:54,50] [info] SingleWorkflowRunnerActor: Workflow submitted 41d3eecf-c5a9-42e4-8a29-8be9c252b7f5
[2019-07-10 14:32:54,50] [info] 1 new workflows fetched by cromid-1cf43fa: 41d3eecf-c5a9-42e4-8a29-8be9c252b7f5
[2019-07-10 14:32:54,51] [info] WorkflowManagerActor Starting workflow 41d3eecf-c5a9-42e4-8a29-8be9c252b7f5
[2019-07-10 14:32:54,51] [info] WorkflowManagerActor Successfully started WorkflowActor-41d3eecf-c5a9-42e4-8a29-8be9c252b7f5
[2019-07-10 14:32:54,52] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2019-07-10 14:32:54,53] [info] WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
[2019-07-10 14:32:54,60] [info] MaterializeWorkflowDescriptorActor [41d3eecf]: Parsing workflow as WDL draft-2
[2019-07-10 14:32:55,28] [info] MaterializeWorkflowDescriptorActor [41d3eecf]: Call-to-Backend assignments: scMeth.trimAdapters -> Local, scMeth.trimCellBarcode -> Local
[2019-07-10 14:32:57,55] [info] WorkflowExecutionActor-41d3eecf-c5a9-42e4-8a29-8be9c252b7f5 [41d3eecf]: Starting scMeth.trimCellBarcode
[2019-07-10 14:32:58,20] [info] Assigned new job execution tokens to the following groups: 41d3eecf: 1
[2019-07-10 14:32:58,36] [info] BackgroundConfigAsyncJobExecutionActor [41d3eecfscMeth.trimCellBarcode:NA:1]: perl /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimCellBarcode/inputs/13016223/moveBarcodeToID.pl paired /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimCellBarcode/inputs/13016223/sub_1.fastq.gz /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimCellBarcode/inputs/13016223/sub_2.fastq.gz 6 sub.R1.debarcoded.fq.gz sub.R2.debarcoded.fq.gz
[2019-07-10 14:32:58,39] [info] BackgroundConfigAsyncJobExecutionActor [41d3eecfscMeth.trimCellBarcode:NA:1]: executing: /bin/bash /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimCellBarcode/execution/script
[2019-07-10 14:32:59,19] [info] BackgroundConfigAsyncJobExecutionActor [41d3eecfscMeth.trimCellBarcode:NA:1]: job id: 39755
[2019-07-10 14:32:59,19] [info] BackgroundConfigAsyncJobExecutionActor [41d3eecfscMeth.trimCellBarcode:NA:1]: Status change from - to Done
[2019-07-10 14:32:59,19] [info] Not triggering log of token queue status. Effective log interval = None
[2019-07-10 14:33:00,77] [info] WorkflowExecutionActor-41d3eecf-c5a9-42e4-8a29-8be9c252b7f5 [41d3eecf]: Starting scMeth.trimAdapters
[2019-07-10 14:33:01,19] [info] Assigned new job execution tokens to the following groups: 41d3eecf: 1
[2019-07-10 14:33:01,22] [warn] Localization via hard link has failed: /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimAdapters/inputs/13016223/fastq -> /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/fastq
[2019-07-10 14:33:01,23] [warn] Localization via copy has failed: /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/fastq
[2019-07-10 14:33:01,24] [error] BackgroundConfigAsyncJobExecutionActor [41d3eecfscMeth.trimAdapters:NA:1]: Error attempting to Execute
java.lang.Exception: Failed command instantiation
	at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:576)
	at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand$(StandardAsyncExecutionActor.scala:511)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.instantiatedCommand$lzycompute(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.instantiatedCommand(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents(StandardAsyncExecutionActor.scala:319)
	at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents$(StandardAsyncExecutionActor.scala:318)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.commandScriptContents(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.writeScriptContents(SharedFileSystemAsyncJobExecutionActor.scala:175)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.writeScriptContents$(SharedFileSystemAsyncJobExecutionActor.scala:174)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.cromwell$backend$sfs$BackgroundAsyncJobExecutionActor$$super$writeScriptContents(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.sfs.BackgroundAsyncJobExecutionActor.writeScriptContents(BackgroundAsyncJobExecutionActor.scala:12)
	at cromwell.backend.sfs.BackgroundAsyncJobExecutionActor.writeScriptContents$(BackgroundAsyncJobExecutionActor.scala:11)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.writeScriptContents(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute(SharedFileSystemAsyncJobExecutionActor.scala:158)
	at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute$(SharedFileSystemAsyncJobExecutionActor.scala:155)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.execute(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$executeAsync$1(StandardAsyncExecutionActor.scala:639)
	at scala.util.Try$.apply(Try.scala:209)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync(StandardAsyncExecutionActor.scala:639)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync$(StandardAsyncExecutionActor.scala:639)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.executeAsync(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:954)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:946)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.executeOrRecover(ConfigAsyncJobExecutionActor.scala:200)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
	at cromwell.core.retry.Retry$.withRetry(Retry.scala:38)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.backend.impl.sfs.config.BackgroundConfigAsyncJobExecutionActor.aroundReceive(ConfigAsyncJobExecutionActor.scala:200)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: common.exception.AggregatedMessageException: Error(s):
:
Could not localize fastq -> /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimAdapters/inputs/13016223/fastq:
	fastq doesn't exist
	File not found /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/cromwell-executions/scMeth/41d3eecf-c5a9-42e4-8a29-8be9c252b7f5/call-trimAdapters/inputs/13016223/fastq -> /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/fastq
	File not found fastq
	File not found /data/PROJECTS/2019_01_28_scMeth/scripts/Automated_Pipeline/cromwell/example_wdl/fastq
	at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:77)
	at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:73)
	at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:574)

```

**Comment by chetana93** [comment]
Hi @tAndreani ,

Were you able to fix this error? I'm actually having a similar issue where I'm providing the files in a singularity container as an input to the workflow and localization via hard link and copy fails. I would appreciate your help.

Thanks,
Chetana

**Comment by tAndreani** [comment]
Hi Chetana,

in my case, the problem was the variable"file_format" that I was passing to cutadapt 

`cutadapt -f ${file_format}`

in the json file, one of the input was: `"scMeth.file_format": "fastq"`, but cutadapt didn't like it.

Therefore I have substituted the initial command above with:

`cutadapt -f fastq`

I don't know if this might help. If you type the error from Cromwell maybe I can help you better.

Best
Tommaso
