### ISSUE TITLE
cromwell server start error with MySQL: Error searching for abort requests

### ISSUE THREAD

**Issue by bw2** [broadinstitute/cromwell#5084]
Starting up a new cromwell-44 server on CentOS7 with MySQL v5.7  (mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper)

migrations complete without error:
```
2019-07-21 23:34:35,925  INFO  - DROP INDEX METADATA_JOB_AND_KEY_IDX ON cromwell.METADATA_ENTRY
2019-07-21 23:34:35,935  INFO  - Index METADATA_JOB_AND_KEY_IDX dropped from table METADATA_ENTRY
2019-07-21 23:34:35,936  INFO  - DROP INDEX METADATA_JOB_IDX ON cromwell.METADATA_ENTRY
2019-07-21 23:34:35,947  INFO  - Index METADATA_JOB_IDX dropped from table METADATA_ENTRY
2019-07-21 23:34:35,948  INFO  - ChangeSet metadata_changesets/metadata_index_removals.xml::metadata_index_removals::mcovarr ran successfully in 24ms
2019-07-21 23:34:35,949  INFO  - INSERT INTO cromwell.SQLMETADATADATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('metadata_index_removals', 'mcovarr', 'metadata_changesets/metadata_index_removals.xml', NOW(), 8, '8:b32b63103dfbe3664806be3eccf78b09', 'dropIndex indexName=METADATA_JOB_AND_KEY_IDX, tableName=METADATA_ENTRY; dropIndex indexName=METADATA_JOB_IDX, tableName=METADATA_ENTRY', '', 'EXECUTED', NULL, NULL, '3.6.3', '3752074629')
2019-07-21 23:34:35,956  INFO  - Successfully released change log lock
2019-07-21 23:34:36,224  WARN  - Unrecognized configuration key(s) for Jes: filesystems.gcs.project, name-for-call-caching-purposes, slow-job-warning-time
2019-07-21 23:34:36,976  INFO  - Slf4jLogger started
2019-07-21 23:34:37,408 cromwell-system-akka.dispatchers.engine-dispatcher-7 INFO  - Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-673c553",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
2019-07-21 23:34:37,771 cromwell-system-akka.actor.default-dispatcher-3 INFO  - KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
2019-07-21 23:34:37,918 cromwell-system-akka.dispatchers.service-dispatcher-14 INFO  - Metadata summary refreshing every 1 second.
2019-07-21 23:34:38,046  WARN  - 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
2019-07-21 23:34:38,160 cromwell-system-akka.dispatchers.service-dispatcher-13 INFO  - WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
2019-07-21 23:34:38,160 cromwell-system-akka.dispatchers.engine-dispatcher-26 INFO  - JobStoreWriterActor configured to flush with batch size 1000 and process rate 1 second.
2019-07-21 23:34:38,594 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
2019-07-21 23:34:38,667 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
2019-07-21 23:34:39,131 cromwell-system-akka.dispatchers.backend-dispatcher-36 INFO  - Running with 3 PAPI request workers
2019-07-21 23:34:39,132 cromwell-system-akka.dispatchers.backend-dispatcher-36 INFO  - PAPI request worker batch interval is 33333 milliseconds
2019-07-21 23:34:39,157 cromwell-system-akka.dispatchers.backend-dispatcher-37 INFO  - PAPI request worker batch interval is 33333 milliseconds
2019-07-21 23:34:39,233 cromwell-system-akka.dispatchers.backend-dispatcher-38 INFO  - PAPI request worker batch interval is 33333 milliseconds
```

but then it immediately starts printing these errors:
```
2019-07-21 23:34:40,010 cromwell-system-akka.actor.default-dispatcher-32 ERROR - Error searching for abort requests
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"WORKFLOW_STORE_ENTRY" where ("WORKFLOW_STATE" = cast('Aborting' as varchar(1677' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:387)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:216)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:216)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.$anonfun$run$4$adapted(DBIOAction.scala:533)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at slick.dbio.SynchronousDatabaseAction$FusedAndThenAction.run(DBIOAction.scala:533)
	at slick.dbio.SynchronousDatabaseAction$$anon$11.run(DBIOAction.scala:570)
	at slick.dbio.SynchronousDatabaseAction$$anon$6.run(DBIOAction.scala:469)
	at slick.dbio.SynchronousDatabaseAction$$anon$10.run(DBIOAction.scala:561)
	at slick.dbio.SynchronousDatabaseAction$$anon$7.run(DBIOAction.scala:486)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-21 23:34:40,417 cromwell-system-akka.dispatchers.service-dispatcher-14 ERROR - Failed to summarize metadata
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"SUMMARY_STATUS_ENTRY" where "SUMMARY_NAME" = 'WORKFLOW_METADATA_SUMMARY_ENTRY_I' at line 1
```

**Comment by bw2** [comment]
going to try switching to a managed cloud sql instance.

**Comment by flexray** [comment]
I've got the same issue, mysql running locally, user with all privileges and grant options..
What was Your solution @bw2 ?

**Comment by usevani** [comment]
I am having the same issue. Was there a solution for this error?
cromwell version: 47
MySQL version: 5.5.64-MariaDB
centos-release-7-7.1908.0.el7.centos.x86_64

**Comment by dongspy** [comment]
I am having the same issue. 
cromwell version:  84
MySQL version:  5.6.51
MacOS 10.14.6
