### ISSUE TITLE
No response from server after "Not a valid Google Cloud Storage URL"

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#520]
Give a JES-pointing server a non-GCS url in the inputs file and the API gives no response. Looking in the server logs you get 
```
java.lang.IllegalArgumentException: Not a valid Google Cloud Storage URI: /Users/chrisl/Desktop/workflowTimings.html
	at cromwell.engine.io.gcs.GcsPath$.parse(GcsPath.scala:32)
	at cromwell.engine.io.gcs.GcsPath$.apply(GcsPath.scala:22)
	at cromwell.engine.io.gcs.GoogleCloudStorage.hash(GoogleCloudStorage.scala:76)
	at cromwell.engine.WorkflowDescriptor$$anonfun$fileHasher$1.apply(WorkflowDescriptor.scala:62)
	at cromwell.engine.WorkflowDescriptor$$anonfun$fileHasher$1.apply(WorkflowDescriptor.scala:62)
	at wdl4s.values.WdlValue$class.computeHash(WdlValue.scala:63)
	at wdl4s.values.WdlSingleFile.computeHash(WdlFile.scala:39)
	at cromwell.engine.WorkflowDescriptor.hash(WorkflowDescriptor.scala:176)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$52.apply(WorkflowActor.scala:1050)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$52.apply(WorkflowActor.scala:1049)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at cromwell.engine.workflow.WorkflowActor.buildSymbolStoreEntries(WorkflowActor.scala:1049)
	at cromwell.engine.workflow.WorkflowActor.createWorkflow(WorkflowActor.scala:241)
	at cromwell.engine.workflow.WorkflowActor$Start.runInitialization(WorkflowActor.scala:120)
	at cromwell.engine.workflow.WorkflowActor.cromwell$engine$workflow$WorkflowActor$$initializeExecutionStore(WorkflowActor.scala:326)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$1.applyOrElse(WorkflowActor.scala:364)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$1.applyOrElse(WorkflowActor.scala:360)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at cromwell.engine.workflow.WorkflowActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowActor.scala:237)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)
	at cromwell.engine.workflow.WorkflowActor.processEvent(WorkflowActor.scala:237)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at cromwell.engine.workflow.WorkflowActor.aroundReceive(WorkflowActor.scala:237)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by mcovarr** [comment]
this bug has so been refactored out of existence
