### ISSUE TITLE
500 Internal error post success processing of task (call caching turned off)

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#577]
This happened after we turned off call caching to work around DSDEEPB-2938 for now and this error popped up in what seems to be post success processing of the task.  Logs are in the comment.  This was run on gotc-prod against JES-staging.

```scala
34108:2016-03-10 22:53:11,258 cromwell-system-akka.actor.default-dispatcher-8 INFO  - JES Run [UUID(7721686a):StripBamExtension:8]: Status change from - to Initializing
50265:2016-03-10 22:55:07,880 cromwell-system-akka.actor.default-dispatcher-27 INFO  - JES Run [UUID(7721686a):StripBamExtension:8]: Status change from Initializing to Running
64201:2016-03-10 22:57:00,293 cromwell-system-akka.actor.default-dispatcher-27 INFO  - JES Run [UUID(7721686a):StripBamExtension:8]: Status change from Running to Success


2016-03-10 22:57:05,450 cromwell-system-akka.actor.default-dispatcher-27 ERROR - CallActor [UUID(7721686a):StripBamExtension:8]: Failing call: 500 Internal Server Error
Internal Error
cromwell.util.AggregatedException: 500 Internal Server Error
Internal Error
	at cromwell.util.TryUtil$.sequenceIterable(TryUtil.scala:112) ~[cromwell.jar:0.19]
	at cromwell.util.TryUtil$.sequenceMap(TryUtil.scala:124) ~[cromwell.jar:0.19]
	at cromwell.engine.backend.jes.JesBackend.postProcess(JesBackend.scala:623) ~[cromwell.jar:0.19]
	at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:662) ~[cromwell.jar:0.19]
	at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:657) ~[cromwell.jar:0.19]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[cromwell.jar:0.19]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run_aroundBody0(Future.scala:24) ~[cromwell.jar:0.19]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable$AjcClosure1.run(Future.scala:1) ~[cromwell.jar:0.19]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[cromwell.jar:0.19]
	at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:44) ~[cromwell.jar:0.19]
	at kamon.trace.Tracer$.withContext(TracerModule.scala:53) ~[cromwell.jar:0.19]
	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:43) ~[cromwell.jar:0.19]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) ~[cromwell.jar:0.19]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[cromwell.jar:0.19]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
2016-03-10 22:57:05,450 cromwell-system-akka.actor.default-dispatcher-27 INFO  - WorkflowActor [UUID(7721686a)]: persisting status of StripBamExtension:8 to Failed.
```

**Comment by kshakir** [comment]
I'm pretty sure this is an ongoing issue where we need retries when talking to external services, at some point between the extremes of retrying a single HTTP request, all the way up to retrying the call. Hopefully after a short bit of time to give the various servers a chance to resolve any transient issues, without blocking an important thread/pool during the wait.

**Comment by cjllanwarne** [comment]
Closing since we now retry all of these sorts of calls. Please reopen if something similar reappears
