### ISSUE TITLE
Release 53: womtool.jar does not work!

### ISSUE THREAD

**Issue by rhpvorderman** [broadinstitute/cromwell#5808]
@cjllanwarne Something went wrong with the latest release of the womtool.
The cromwell.jar does properly display the CLI usage when run.
```
$ java -jar womtool-53.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: scala/concurrent/duration/Duration
	at scopt.Read$.liftedTree1$1(options.scala:67)
	at scopt.Read$.<init>(options.scala:66)
	at scopt.Read$.<clinit>(options.scala)
	at womtool.cmdline.WomtoolCommandLineParser.<init>(WomtoolCommandLineParser.scala:30)
	at womtool.cmdline.WomtoolCommandLineParser$.instance$lzycompute(WomtoolCommandLineParser.scala:13)
	at womtool.cmdline.WomtoolCommandLineParser$.instance(WomtoolCommandLineParser.scala:13)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:158)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:166)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:27)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:27)
	at womtool.WomtoolMain.main(WomtoolMain.scala)
Caused by: java.lang.ClassNotFoundException: scala.concurrent.duration.Duration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```

**Comment by taozhi8833998** [comment]
got same issue +1

**Comment by aednichols** [comment]
Hi all, we are investigating. Could you please report your `java -version` in this thread?

**Comment by rhpvorderman** [comment]
On my OS
```
java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1deb10u1, mixed mode, sharing)
```
Using conda-forge compiled java (default for conda package of cromwell)
```
java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)
```

Both give the same error. Maybe it is Oracle vs OpenJDK related errors?

**Comment by TuBieJun** [comment]
I got the same error.

**Comment by aednichols** [comment]
Fixed in a point update. Apologies for the inconvenience.

https://github.com/broadinstitute/cromwell/releases/tag/53.1
