### ISSUE TITLE
Multiple Cromwell restarts fails successful tasks

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#588]
Here is the general pattern we saw during this last 200 (3/17).  This is a very basic outline but the logs can be found in the log file 20160317-cromwell.log on gotc-prod

WorkflowActor [UUID(71b8d356)]: persisting status of StripUnmappedBamSuffix:17 to Starting
WorkflowActor [UUID(71b8d356)]: persisting status of StripUnmappedBamSuffix:17 to Running
JES Run [UUID(71b8d356):StripUnmappedBamSuffix:17]: Status change from - to Initializing
----- Cromwell restarted -----
JES Run [UUID(71b8d356):StripUnmappedBamSuffix:17]: Status change from - to Initializing
----- Cromwell restarted -----
JES Run [UUID(71b8d356):StripUnmappedBamSuffix:17]: Status change from - to Success
----- Cromwell restarted -----
JES Run [UUID(71b8d356):StripUnmappedBamSuffix:17]: Status change from - to Success
WorkflowActor [UUID(71b8d356)]: persisting status of StripUnmappedBamSuffix:17 to Running.
WorkflowActor [UUID(71b8d356)]: Completion work failed for call StripUnmappedBamSuffix:17
WorkflowActor [UUID(71b8d356)]: persisting status of StripUnmappedBamSuffix:17 to Failed.
WorkflowActor [UUID(71b8d356)]: Duplicate entry '558-PairedEndSingleSampleWorkflow.StripUnmappedBamSuffix-base_na' for key 'UK_SYM_WORKFLOW_EXECUTION_ID_SCOPE_NAME_ITERATION_IO'

times of the 3 restarts:
20:55:14,969
22:22:09,207
23:02:54,544

**Comment by jsotobroad** [comment]
```
2016-04-26 18:26:08,035 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowManagerActor Found 4 workflows to restart.
2016-04-26 18:26:08,035 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowManagerActor Restarting workflow IDs: 0bbd4dc6-bfa5-4ccb-bcdf-bb3a62bbc24b, 81182fb4-22b5-460b-b78e-72f7750aa598, abafd1cc-977a-47d6-acce-c1b2907829a8, ea0272fc-42ef-4852-8143-8b14d34bfd8a

2016-04-26 18:26:08,700 cromwell-system-akka.actor.default-dispatcher-11 INFO  - Invoking restartableWorkflow on ea0272fc
2016-04-26 18:26:08,700 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowManagerActor submitWorkflow input id = Some(ea0272fc-42ef-4852-8143-8b14d34bfd8a), effective id = ea0272fc-42ef-4852-8143-8b14d34bfd8a
2016-04-26 18:26:08,772 cromwell-system-akka.actor.default-dispatcher-10 INFO  - Updating WorkflowManager state. New Data: (ea0272fc-42ef-4852-8143-8b14d34bfd8a,Actor[akka://cromwell-system/user/WorkflowManagerActor/WorkflowActor-ea0272fc-42ef-4852-8143-8b14d34bfd8a#787056469])
2016-04-26 18:26:08,773 cromwell-system-akka.actor.default-dispatcher-3 INFO  - WorkflowActor [UUID(ea0272fc)]: Restart message received
2016-04-26 18:26:09,112 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: Initial symbols:

2016-04-26 18:26:09,129 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: Initial executions:

2016-04-26 18:26:09,156 cromwell-system-akka.actor.default-dispatcher-2 INFO  - WorkflowActor [UUID(ea0272fc)]: ExecutionStoreCreated(Restart) message received
2016-04-26 18:26:09,432 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: Beginning transition from Submitted to Running.
2016-04-26 18:26:09,432 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: transitioning from Submitted to Running.
2016-04-26 18:26:09,646 cromwell-system-akka.actor.default-dispatcher-7 INFO  - WorkflowActor [UUID(ea0272fc)]: starting calls: GenomeStripBamWorkflow.ComputeMetadata, GenomeStripBamWorkflow.ComputeStatistics
2016-04-26 18:26:09,646 cromwell-system-akka.actor.default-dispatcher-7 INFO  - WorkflowActor [UUID(ea0272fc)]: persisting status of ComputeStatistics to Starting.
2016-04-26 18:26:09,657 cromwell-system-akka.actor.default-dispatcher-7 INFO  - WorkflowActor [UUID(ea0272fc)]: persisting status of ComputeMetadata to Starting.

2016-04-26 18:26:09,845 cromwell-system-akka.actor.default-dispatcher-11 ERROR - WorkflowActor [UUID(ea0272fc)]: Could not persist runtime attributes
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '163979-preemptible' for key 'UK_RUNTIME_ATTRIBUTE'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_72]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_72]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_72]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.Util.getInstance(Util.java:383) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:507) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:504) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:354) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:407) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:636) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1$$anonfun$run$1.apply(DBIOAction.scala:161) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1$$anonfun$run$1.apply(DBIOAction.scala:161) ~[cromwell.jar:0.19]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[cromwell.jar:0.19]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[cromwell.jar:0.19]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[cromwell.jar:0.19]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:161) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:158) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
2016-04-26 18:26:09,846 cromwell-system-akka.actor.default-dispatcher-11 ERROR - WorkflowActor [UUID(ea0272fc)]: Could not persist runtime attributes
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '163980-preemptible' for key 'UK_RUNTIME_ATTRIBUTE'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_72]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_72]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_72]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.Util.getInstance(Util.java:383) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:507) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction$$anonfun$run$7.apply(JdbcActionComponent.scala:504) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:354) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:407) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:636) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:504) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1$$anonfun$run$1.apply(DBIOAction.scala:161) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1$$anonfun$run$1.apply(DBIOAction.scala:161) ~[cromwell.jar:0.19]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[cromwell.jar:0.19]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[cromwell.jar:0.19]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[cromwell.jar:0.19]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:161) ~[cromwell.jar:0.19]
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:158) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
2016-04-26 18:26:09,846 cromwell-system-akka.actor.default-dispatcher-11 ERROR - WorkflowActor [UUID(ea0272fc)]: Call failed to initialize: Could not persist runtime attributes: Duplicate entry '163980-preemptible' for key 'UK_RUNTIME_ATTRIBUTE'
2016-04-26 18:26:09,885 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: persisting status of ComputeStatistics to Failed.
2016-04-26 18:26:09,888 cromwell-system-akka.actor.default-dispatcher-11 ERROR - WorkflowActor [UUID(ea0272fc)]: Call failed to initialize: Could not persist runtime attributes: Duplicate entry '163979-preemptible' for key 'UK_RUNTIME_ATTRIBUTE'
2016-04-26 18:26:09,889 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: persisting status of ComputeMetadata to Failed.
2016-04-26 18:26:10,263 cromwell-system-akka.actor.default-dispatcher-11 INFO  - WorkflowActor [UUID(ea0272fc)]: Beginning transition from Running to Failed.
2016-04-26 18:26:12,042 cromwell-system-akka.actor.default-dispatcher-7 INFO  - WorkflowActor [UUID(ea0272fc)]: transitioning from Running to Failed.

```

**Comment by mcovarr** [comment]
This second class of failure seems straightforward: there's code in `WorkflowActor` to `setRuntimeAttributes` that makes no allowance for the attributes already having been written, but this scenario can definitely occur.  For a master-like branch, the most expedient solution is probably to turn these inserts into upserts.  For develop it would be nice to write these attributes in an event-sourcish way that for writes doesn't clobber existing values, but which always takes the latest values for reads.

Still investigating the first class of failure.

**Comment by jsotobroad** [comment]
wdl from the first error
[wdl.txt](https://github.com/broadinstitute/cromwell/files/238897/wdl.txt)

wdl from the second error
[wdl2.txt](https://github.com/broadinstitute/cromwell/files/238908/wdl2.txt)

**Comment by mcovarr** [comment]
The first class of failure is similar to the second, we write outputs and execution events before attempting to write status.  The code is written to `setOutputs` and `setExecutionEvents` and does not deal well with preexisting data.  Similar fixes as per the second failure class should apply here.

**Comment by Horneth** [comment]
> we write outputs and execution events before attempting to write status
I remember doing that because there was a bug when we were writing status and then outputs. But if writing outputs fails then you have a "Successful" call with no outputs

**Comment by mcovarr** [comment]
yeah all that stuff should be in a transaction
