### ISSUE TITLE
Call Caching bug for JES

### ISSUE THREAD

**Issue by scottfrazer** [broadinstitute/cromwell#603]
With a clean database, run this with the JES backend (no inputs):

```
task x {
  String s
  command {echo ${s}}
  output {String t = read_string(stdout())}
  runtime {docker: "ubuntu:latest"}
}

workflow w {
  call x {input: s="foo"}
  call x as y {input: s=x.t}
}
```

call x runs fine.

call y *should* get a cache hit to call x, but instead:

```
[2016-03-22 15:20:59,921] [info] WorkflowActor [54108c5b]: starting calls: w.y
[2016-03-22 15:20:59,921] [info] WorkflowActor [54108c5b]: persisting status of y to Starting.
[2016-03-22 15:21:00,344] [info] WorkflowActor [54108c5b]: Call Caching: Cache hit. Using 54108c5b:x as results for 54108c5b:y
[2016-03-22 15:21:00,351] [info] WorkflowActor [54108c5b]: inputs for call 'y':
  s -> WdlString(foo)
[2016-03-22 15:21:00,352] [info] WorkflowActor [54108c5b]: created call actor for y.
[2016-03-22 15:21:00,352] [info] WorkflowActor [54108c5b]: persisting status of y to Running.
[2016-03-22 15:21:05,567] [error] CallActor [54108c5b:y]: Failing call: Item not found: cromwell-dev/w/54108c5b-29a7-430e-b16b-07bd8dba47e7/call-y/y-stdout.log
cromwell.util.AggregatedException: Item not found: cromwell-dev/w/54108c5b-29a7-430e-b16b-07bd8dba47e7/call-y/y-stdout.log
	at cromwell.util.TryUtil$.sequenceIterable(TryUtil.scala:112)
	at cromwell.util.TryUtil$.sequenceMap(TryUtil.scala:124)
	at cromwell.engine.backend.jes.JesBackend.postProcess(JesBackend.scala:640)
	at cromwell.engine.backend.jes.JesBackend$$anonfun$useCachedCall$1.apply(JesBackend.scala:424)
	at cromwell.engine.backend.jes.JesBackend$$anonfun$useCachedCall$1.apply(JesBackend.scala:418)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[2016-03-22 15:21:05,568] [info] WorkflowActor [54108c5b]: persisting status of y to Failed.
```

**Comment by cjllanwarne** [comment]
Looks fixed as of develop today. Closing.
