### ISSUE TITLE
failed (during ExecutingWorkflowState): java.lang.Exception: Job

### ISSUE THREAD

**Issue by Trandamere** [broadinstitute/cromwell#6352]
```
java -Dconfig.file=/root/cromwell-application.conf -jar /root/cromwell/cromwell-62.jar run hello.wdl
```

```
WorkflowManagerActor: Workflow 19f1873b-7e61-4683-9585-747bf842a261 failed (during ExecutingWorkflowState): java.lang.Exception: Job id job-0000000060963A8300007BD2000D7072 failed: 'cluster(job-0000000060963A8300007BD2000D7072_cromwell_0) error: InvalidArgument'
	at cromwell.backend.impl.bcs.BcsAsyncBackendJobExecutionActor.handleExecutionFailure(BcsAsyncBackendJobExecutionActor.scala:281)
	at cromwell.backend.impl.bcs.BcsAsyncBackendJobExecutionActor.handleExecutionFailure(BcsAsyncBackendJobExecutionActor.scala:32)
	at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1315)
	at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1311)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```
My mirror doesn't work properly

**Comment by Trandamere** [comment]
When run the server modle
```
root@NanoTNGS-DEV:~# java -jar /root/cromwell/cromwell-62.jar submit -t wdl hello.wdl -h http://localhost:8000
[2021-05-14 14:28:43,33] [info] Slf4jLogger started
[2021-05-14 14:28:44,23] [info] Workflow 51376acd-e9c5-485a-856f-6aa501f25808 submitted to http://localhost:8000
[ERROR] [05/14/2021 14:28:44.259] [SubmitSystem-akka.actor.default-dispatcher-16] [akka://SubmitSystem/system/pool-master] connection pool for Pool(shared->http://localhost:8000) has shut down unexpectedly
java.lang.IllegalStateException: Pool shutdown unexpectedly
	at akka.http.impl.engine.client.PoolInterface$Logic.postStop(PoolInterface.scala:214)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:579)
	at akka.stream.impl.fusing.GraphInterpreter.finish(GraphInterpreter.scala:310)
	at akka.stream.impl.fusing.GraphInterpreterShell.tryAbort(ActorGraphInterpreter.scala:644)
	at akka.stream.impl.fusing.ActorGraphInterpreter.$anonfun$postStop$1(ActorGraphInterpreter.scala:780)
	at akka.stream.impl.fusing.ActorGraphInterpreter.$anonfun$postStop$1$adapted(ActorGraphInterpreter.scala:780)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:181)
	at akka.stream.impl.fusing.ActorGraphInterpreter.postStop(ActorGraphInterpreter.scala:780)
	at akka.actor.Actor.aroundPostStop(Actor.scala:558)
	at akka.actor.Actor.aroundPostStop$(Actor.scala:558)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPostStop(ActorGraphInterpreter.scala:671)
	at akka.actor.dungeon.FaultHandling.finishTerminate(FaultHandling.scala:215)
	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:173)
	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:143)
	at akka.actor.ActorCell.terminate(ActorCell.scala:447)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:555)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:571)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by tamadezhenshiyuncai** [comment]
> When run the server modle
> 
> ```
> root@NanoTNGS-DEV:~# java -jar /root/cromwell/cromwell-62.jar submit -t wdl hello.wdl -h http://localhost:8000
> [2021-05-14 14:28:43,33] [info] Slf4jLogger started
> [2021-05-14 14:28:44,23] [info] Workflow 51376acd-e9c5-485a-856f-6aa501f25808 submitted to http://localhost:8000
> [ERROR] [05/14/2021 14:28:44.259] [SubmitSystem-akka.actor.default-dispatcher-16] [akka://SubmitSystem/system/pool-master] connection pool for Pool(shared->http://localhost:8000) has shut down unexpectedly
> java.lang.IllegalStateException: Pool shutdown unexpectedly
> 	at akka.http.impl.engine.client.PoolInterface$Logic.postStop(PoolInterface.scala:214)
> 	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:579)
> 	at akka.stream.impl.fusing.GraphInterpreter.finish(GraphInterpreter.scala:310)
> 	at akka.stream.impl.fusing.GraphInterpreterShell.tryAbort(ActorGraphInterpreter.scala:644)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.$anonfun$postStop$1(ActorGraphInterpreter.scala:780)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.$anonfun$postStop$1$adapted(ActorGraphInterpreter.scala:780)
> 	at scala.collection.immutable.Set$Set2.foreach(Set.scala:181)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.postStop(ActorGraphInterpreter.scala:780)
> 	at akka.actor.Actor.aroundPostStop(Actor.scala:558)
> 	at akka.actor.Actor.aroundPostStop$(Actor.scala:558)
> 	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPostStop(ActorGraphInterpreter.scala:671)
> 	at akka.actor.dungeon.FaultHandling.finishTerminate(FaultHandling.scala:215)
> 	at akka.actor.dungeon.FaultHandling.terminate(FaultHandling.scala:173)
> 	at akka.actor.dungeon.FaultHandling.terminate$(FaultHandling.scala:143)
> 	at akka.actor.ActorCell.terminate(ActorCell.scala:447)
> 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:555)
> 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:571)
> 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
> 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> ```

i met the same question, have you solved it? any advice will be appreciate,thanks
