### ISSUE TITLE
Java NoSuchFileException with "s3://s3.amazonaws.com" URI prefix

### ISSUE THREAD

**Issue by yihming** [broadinstitute/cromwell#6504]
Hi,

I recently encountered an issue on running Cromwell jobs on AWS Batch. In brief, all of my testing WDL jobs failed with the following error message:

```
2021-09-23 00:08:18,813  INFO  - Submitting taskId: cumulus.cluster-None-1, job definition : arn:aws:batch:us-west-2:752311211819:job-definition/cromwell_quay_io_cumulus_cumulus_1_4_377407181fbea1f33a22931df258b16d20d4c6ab3:1, script: s3://gred-cumulus-dev/scripts/c157137e2097795846ae1f4069ccd7a2
2021-09-23 00:08:20,269 cromwell-system-akka.dispatchers.backend-dispatcher-118 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(cf00212c)cumulus.cluster:NA:1]: job id: 12836c6a-6d1a-4429-bb86-68b8f9883acf
2021-09-23 00:08:20,287 cromwell-system-akka.dispatchers.backend-dispatcher-118 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(cf00212c)cumulus.cluster:NA:1]: Status change from - to Initializing
2021-09-23 00:12:17,120 cromwell-system-akka.dispatchers.backend-dispatcher-136 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(cf00212c)cumulus.cluster:NA:1]: Status change from Initializing to Running
2021-09-23 00:14:08,015 cromwell-system-akka.dispatchers.backend-dispatcher-146 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(cf00212c)cumulus.cluster:NA:1]: Having to fall back to AWS query for status
2021-09-23 00:14:09,596 cromwell-system-akka.dispatchers.backend-dispatcher-146 INFO  - AwsBatchAsyncBackendJobExecutionActor [UUID(cf00212c)cumulus.cluster:NA:1]: Status change from Running to Failed
2021-09-23 00:14:10,457 cromwell-system-akka.dispatchers.engine-dispatcher-33 INFO  - WorkflowManagerActor: Workflow cf00212c-9c18-4f14-a953-c7a4450ada7c failed (during ExecutingWorkflowState): cromwell.engine.io.IoAttempts$EnhancedCromwellIoException: [Attempted 1 time(s)] - IOException: Could not read from s3://gred-cumulus-dev/cromwell-execution/cumulus/cf00212c-9c18-4f14-a953-c7a4450ada7c/call-cluster/cluster-rc.txt: s3://s3.amazonaws.com/gred-cumulus-dev/cromwell-execution/cumulus/cf00212c-9c18-4f14-a953-c7a4450ada7c/call-cluster/cluster-rc.txt
Caused by: java.io.IOException: Could not read from s3://gred-cumulus-dev/cromwell-execution/cumulus/cf00212c-9c18-4f14-a953-c7a4450ada7c/call-cluster/cluster-rc.txt: s3://s3.amazonaws.com/gred-cumulus-dev/cromwell-execution/cumulus/cf00212c-9c18-4f14-a953-c7a4450ada7c/call-cluster/cluster-rc.txt
	at cromwell.core.path.EvenBetterPathMethods$$anonfun$fileIoErrorPf$1.applyOrElse(EvenBetterPathMethods.scala:117)
	at cromwell.core.path.EvenBetterPathMethods$$anonfun$fileIoErrorPf$1.applyOrElse(EvenBetterPathMethods.scala:116)
	at map @ cromwell.engine.io.nio.NioFlow.handleSingleCommand(NioFlow.scala:74)
	at map @ cromwell.engine.io.nio.NioFlow.$anonfun$processCommand$5(NioFlow.scala:60)
	at flatMap @ cromwell.engine.io.nio.NioFlow.$anonfun$processCommand$1(NioFlow.scala:59)
Caused by: java.nio.file.NoSuchFileException: s3://s3.amazonaws.com/gred-cumulus-dev/cromwell-execution/cumulus/cf00212c-9c18-4f14-a953-c7a4450ada7c/call-cluster/cluster-rc.txt
	at org.lerch.s3fs.S3FileSystemProvider.newInputStream(S3FileSystemProvider.java:355)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at better.files.File.newInputStream(File.scala:455)
	at cromwell.core.path.BetterFileMethods.newInputStream(BetterFileMethods.scala:249)
	at cromwell.core.path.BetterFileMethods.newInputStream$(BetterFileMethods.scala:248)
	at cromwell.filesystems.s3.S3Path.newInputStream(S3PathBuilder.scala:157)
	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream(EvenBetterPathMethods.scala:97)
	at cromwell.core.path.EvenBetterPathMethods.mediaInputStream$(EvenBetterPathMethods.scala:94)
	at cromwell.filesystems.s3.S3Path.mediaInputStream(S3PathBuilder.scala:157)
	at cromwell.core.path.EvenBetterPathMethods.$anonfun$withBufferedStream$1(EvenBetterPathMethods.scala:135)
	at cromwell.util.TryWithResource$.$anonfun$tryWithResource$1(TryWithResource.scala:14)
	at scala.util.Try$.apply(Try.scala:213)
	at cromwell.util.TryWithResource$.tryWithResource(TryWithResource.scala:10)
	at cromwell.core.path.EvenBetterPathMethods.withBufferedStream(EvenBetterPathMethods.scala:135)
	at cromwell.core.path.EvenBetterPathMethods.withBufferedStream$(EvenBetterPathMethods.scala:134)
	at cromwell.filesystems.s3.S3Path.withBufferedStream(S3PathBuilder.scala:157)
	at cromwell.core.path.EvenBetterPathMethods.limitFileContent(EvenBetterPathMethods.scala:142)
	at cromwell.core.path.EvenBetterPathMethods.limitFileContent$(EvenBetterPathMethods.scala:142)
	at cromwell.filesystems.s3.S3Path.limitFileContent(S3PathBuilder.scala:157)
	at cromwell.engine.io.nio.NioFlow.$anonfun$readAsString$1(NioFlow.scala:110)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2021-09-23 00:14:15,315 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - WorkflowManagerActor: Workflow actor for cf00212c-9c18-4f14-a953-c7a4450ada7c completed with status 'Failed'. The workflow will be removed from the workflow store.
```

In particular, Cromwell tried to fetch file `s3://s3.amazonaws.com/gred-cumulus-dev/cromwell-execution/cumulus/cf00212c-9c18-4f14-a953-c7a4450ada7c/call-cluster/cluster-rc.txt`, while I only have `s3://gred-cumulus-dev` bucket. 

I'm wondering where `s3.amazonaws.com` prefix came from. I searched through Cromwell's source code, and found [this](https://github.com/broadinstitute/cromwell/blob/develop/filesystems/s3/src/main/java/org/lerch/s3fs/S3FileSystemProvider.java#L47.) file is probably the place to check. Due to its specification, The S3 Filesystem Provider will attach `s3.amazonaws.com` if `endpoint` is missing, to be `s3://[endpoint]/{bucket}/{key}` for the URI. However, I could not find any information regarding endpoint on Cromwell's readthedocs website.

I'm wondering if this error was because I missed something in my conf file. My conf file is the following:

```
include required(classpath("application"))

aws {
    application-name = "cromwell"
    auths = [
        {
            name = "default"
            scheme = "default"
        }
    ]

    region = "us-west-2"
}

engine {
    filesystems {
        s3 {
            auth = "default"
        }
    }
}

backend {
    default = "AWSBatch"

    providers {
        AWSBatch {
            actor-factory = "cromwell.backend.impl.aws.AwsBatchBackendLifecycleActorFactory"
            config {
                default-runtime-attributes {
                    scriptBucketName = "gred-cumulus-dev"
                    queueArn: "arn:aws:batch:us-west-2:752311211819:job-queue/priority-gwfcore-test"
                }

                filesystems {
                    s3 {
                        # A reference to a potentially different auth for manipulating files via engine functions.
                        auth = "default"
                    }
                }

                # Emit a warning if jobs last longer than this amount of time. This might indicate that something got stuck in the cloud.
                slow-job-warning-time: "24 hours"

                concurrent-job-limit = 1000
                numSubmitAttempts = 6
                numCreateDefinitionAttempts = 6
                # A reference to an auth defined in the `aws` stanza at the top.  This auth is used to create
                # Jobs and manipulate auth JSONs.
                auth = "default"
                # Base bucket for workflow executions
                root = "s3://gred-cumulus-dev/cromwell-execution"
            }
        }
    }
}
```

Could anyone please give me a hand on resolving this issue? Thanks!

Sincerely,
Yiming

**Comment by aednichols** [comment]
I agree, it looks like introducing `s3.amazonaws.com` before the bucket path breaks the path.
```
> aws s3 ls "s3://aen-test/cromwell-execution/test/1e346768-e95f-415c-9afd-5b1e8886ff02/call-local_disk/"
2019-04-23 15:41:46          0 
2019-04-23 15:46:35          2 local_disk-rc.txt
2019-04-23 15:46:36          0 local_disk-stderr.log
2019-04-23 15:46:35       1304 local_disk-stdout.log
2019-04-23 15:41:46       1117 script
```
```
> aws s3 ls "s3://s3.amazonaws.com/aen-test/cromwell-execution/test/1e346768-e95f-415c-9afd-5b1e8886ff02/call-local_disk/"

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by mihirsamdarshi** [comment]
> I agree, it looks like introducing `s3.amazonaws.com` before the bucket path breaks the path. What version of Cromwell are you on?

This happens to me on Cromwell 59

**Comment by yihming** [comment]
I was able to see the actual error message from CloudWatch logs. It seems that my Cromwell server instance got the same error as shown here, while on the instance automatically created by AWS Batch compute environment, errors were different in different jobs. So probably the Cromwell server is not the correct place for diagnosis. I'll just close this issue.

**Comment by mihirsamdarshi** [comment]
I see the same thing - the actual error was logged in CloudWatch
