### ISSUE TITLE
Cromwell on Google Cloud cannot pull GCR docker images when running jobs

### ISSUE THREAD

**Issue by yihming** [broadinstitute/cromwell#6506]
Hello,

I'm running a Cromwell service as Google Cloud VM instance. The Cromwell's version is 68, with the following conf:

```
include required(classpath("application"))

webservice {
    interface = xx.xxx.xxx.xx
    port = xxxx
}

google {
    application-name = "cromwell"
    auths = [
        {
            name = "application-default"
            scheme = "application_default"
        }
    ]
}

engine {
    filesystems {
        gcs {
            auth = "application-default"
            project = "gred-cumulus-sb-01-991a49c4"
        }

    }
}

workflow-options {
    workflow-log-temporary = false
}

call-caching {
    enabled = true
    invalidate-bad-cache-results = true
}

database {
    profile = "slick.jdbc.MySQLProfile$"
    db {
        driver = "com.mysql.cj.jdbc.Driver"
	url = "jdbc:mysql://localhost/cromwell?rewriteBatchedStatements=true"
	user = "root"
	password = "cromwell"
	connectionTimeout = 5000
    }
}

backend {
    default = PAPIv2

    providers {
        PAPIv2 {
            actor-factory = "cromwell.backend.google.pipelines.v2alpha1.PipelinesApiLifecycleActorFactory"
            config {
                # Google project
                project = "gred-cumulus-sb-01-991a49c4"

                # Base bucket for workflow executions
                root = "gs://gred-cumulus-output/cromwell_execution"

                virtual-private-cloud {
                    network-label-key = "my-private-network"
                    subnetwork-label-key = "my-private-subnetwork"
                    auth = "application-default"
                }

                # Make the name of the backend used for call caching purposes insensitive to the PAPI version.
                name-for-call-caching-purposes: PAPI

                # Emit a warning if jobs last longer than this amount of time. This might indicate that something got stuck in PAPI.
                slow-job-warning-time: "24 hours"

                # Set this to the lower of the two values "Queries per 100 seconds" and "Queries per 100 seconds per user" for
                # your project.
                #
                # Used to help determine maximum throughput to the Google Genomics API. Setting this value too low will
                # cause a drop in performance. Setting this value too high will cause QPS based locks from Google.
                # 1000 is the default "Queries per 100 seconds per user", 50000 is the default "Queries per 100 seconds"
                # See https://cloud.google.com/genomics/quotas for more information
                genomics-api-queries-per-100-seconds = 1000

                # Polling for completion backs-off gradually for slower-running jobs.
                # This is the maximum polling interval (in seconds):
                maximum-polling-interval = 600

                # Number of workers to assign to PAPI requests
                request-workers = 3

                genomics {
                    # A reference to an auth defined in the `google` stanza at the top.
                    # This auth is used to create pipelines and manipulate auth JSONs.
                    auth = "application-default"

                    # Endpoint for APIs, no reason to change this unless directed by Google.
                    endpoint-url = "https://genomics.googleapis.com/"

                    # Currently Cloud Life Sciences API is available only in `us-central1` and `europe-west2` locations.
                    location = "us-west1"

                    # Restrict access to VM metadata. Useful in cases when untrusted containers are running under a service
                    # account not owned by the submitting user
                    restrict-metadata-access = false

                    # Pipelines v2 only: specify the number of times localization and delocalization operations should be attempted
                    # There is no logic to determine if the error was transient or not, everything is retried upon failure
                    # Defaults to 3
                    localization-attempts = 3

                    # Specifies the minimum file size for `gsutil cp` to use parallel composite uploads during delocalization.
                    # Parallel composite uploads can result in a significant improvement in delocalization speed for large files
                    # but may introduce complexities in downloading such files from GCS, please see
                    # https://cloud.google.com/storage/docs/gsutil/commands/cp#parallel-composite-uploads for more information.
                    #
                    # If set to 0 parallel composite uploads are turned off. The default Cromwell configuration turns off
                    # parallel composite uploads, this sample configuration turns it on for files of 150M or larger.
                    parallel-composite-upload-threshold="150M"
                }

                filesystems {
                    gcs {
                        # A reference to a potentially different auth for manipulating files via engine functions.
                        auth = "application-default"

                        # Google project which will be billed for the requests
                        project = "gred-cumulus-sb-01-991a49c4"

                        caching {
                            # When a cache hit is found, the following duplication strategy will be followed to use the cached outputs
                            # Possible values: "copy", "reference". Defaults to "copy"
                            # "copy": Copy the output files
                            # "reference": DO NOT copy the output files but point to the original output files instead.
                            #              Will still make sure than all the original output files exist and are accessible before
                            #              going forward with the cache hit.
                            duplication-strategy = "copy"
                        }
                    }

                    http { }
                }

                default-runtime-attributes {
                    cpu: 1
                    failOnStderr: false
                    continueOnReturnCode: 0
                    memory: "2048 MB"
                    bootDiskSizeGb: 10
                    # Allowed to be a String, or a list of Strings
                    disks: "local-disk 10 SSD"
                    noAddress: false
                    preemptible: 0
                    zones: ["us-west1-a", "us-west1-b", "us-west1-c"]
                }
            }
        }
    }
}

```

However, when I tried to run a WDL workflow test which used "gcr.io/broad-cumulus/cellranger:6.1.1" docker image, the execution failed with the following log:

```
2021-09-27 13:47:50,363  INFO  - Running with database db.url = jdbc:mysql://localhost/cromwell?rewriteBatchedStatements=true
Skipping auto-registration
2021-09-27 13:47:55,753  WARN  - Skipping auto-registration
2021-09-27 13:47:55,833  INFO  - Running with database db.url = jdbc:mysql://localhost/cromwell?rewriteBatchedStatements=true
Skipping auto-registration
2021-09-27 13:47:56,493  WARN  - Skipping auto-registration
2021-09-27 13:47:57,524  INFO  - Reference disks feature for PAPIv2 backend is not configured.
2021-09-27 13:47:58,075  INFO  - Slf4jLogger started
2021-09-27 13:47:58,470 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - Workflow heartbeat configuration:
{
  "cromwellId" : "cromid-69bdc1a",
  "heartbeatInterval" : "2 minutes",
  "ttl" : "10 minutes",
  "failureShutdownDuration" : "5 minutes",
  "writeBatchSize" : 10000,
  "writeThreshold" : 10000
}
2021-09-27 13:47:58,845 cromwell-system-akka.dispatchers.service-dispatcher-15 INFO  - Metadata summary refreshing every 1 second.
2021-09-27 13:47:58,865 cromwell-system-akka.dispatchers.service-dispatcher-15 INFO  - No metadata archiver defined in config
2021-09-27 13:47:58,865 cromwell-system-akka.dispatchers.service-dispatcher-15 INFO  - No metadata deleter defined in config
2021-09-27 13:47:58,926 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - JobStoreWriterActor configured to flush with batch size 1000 and process rate 1 second.
2021-09-27 13:47:58,929 cromwell-system-akka.dispatchers.service-dispatcher-14 INFO  - WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
2021-09-27 13:47:58,935 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
2021-09-27 13:47:58,937 cromwell-system-akka.actor.default-dispatcher-7 INFO  - KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
2021-09-27 13:47:59,274 cromwell-system-akka.dispatchers.engine-dispatcher-31 INFO  - JobExecutionTokenDispenser - Distribution rate: 20 per 10 seconds.
2021-09-27 13:47:59,340 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - Running with 3 PAPI request workers
2021-09-27 13:47:59,340 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - 'resetAllWorkers()' called to fill vector with 3 new workers
2021-09-27 13:48:00,372 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - Request manager PAPIQueryManager created new PAPI request worker PAPIQueryWorker-9bdf68fb-2a83-40d7-9836-596fb3ff4aa2 with batch interval of 33333 milliseconds
2021-09-27 13:48:00,381 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - Request manager PAPIQueryManager created new PAPI request worker PAPIQueryWorker-51f769c6-7a82-4746-810c-c31fa5342ca3 with batch interval of 33333 milliseconds
2021-09-27 13:48:00,382 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - Request manager PAPIQueryManager created new PAPI request worker PAPIQueryWorker-d221f12d-7c19-49a6-a189-cef13e87c273 with batch interval of 33333 milliseconds
2021-09-27 13:48:01,696 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - Cromwell 68 service started on 10.153.114.15:3721...
2021-09-27 13:48:04,270 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - Not triggering log of token queue status. Effective log interval = None
2021-09-27 13:48:13,186 cromwell-system-akka.dispatchers.api-dispatcher-41 INFO  - Unspecified type (Unspecified version) workflow 075e0cf3-194b-4f53-a43d-d31f0b370f79 submitted
2021-09-27 13:48:20,474 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - 1 new workflows fetched by cromid-69bdc1a: 075e0cf3-194b-4f53-a43d-d31f0b370f79
2021-09-27 13:48:20,484 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - WorkflowManagerActor: Starting workflow UUID(075e0cf3-194b-4f53-a43d-d31f0b370f79)
2021-09-27 13:48:20,511 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - WorkflowManagerActor: Successfully started WorkflowActor-075e0cf3-194b-4f53-a43d-d31f0b370f79
2021-09-27 13:48:20,511 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - Retrieved 1 workflows from the WorkflowStoreActor
2021-09-27 13:48:20,547 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - WorkflowStoreHeartbeatWriteActor configured to flush with batch size 10000 and process rate 2 minutes.
Sep 27, 2021 1:48:20 PM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
2021-09-27 13:48:21,326 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - MaterializeWorkflowDescriptorActor [UUID(075e0cf3)]: Parsing workflow as WDL draft-2
2021-09-27 13:48:22,359 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - MaterializeWorkflowDescriptorActor [UUID(075e0cf3)]: Call-to-Backend assignments: wf_hello.hello -> PAPIv2
2021-09-27 13:48:24,671 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowExecutionActor-075e0cf3-194b-4f53-a43d-d31f0b370f79 [UUID(075e0cf3)]: Starting wf_hello.hello
2021-09-27 13:48:29,304 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - Assigned new job execution tokens to the following groups: 075e0cf3: 1
2021-09-27 13:48:31,233 cromwell-system-akka.dispatchers.engine-dispatcher-12 INFO  - BT-322 075e0cf3:wf_hello.hello:-1:1 is eligible for call caching with read = true and write = true
2021-09-27 13:48:31,314 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - BT-322 075e0cf3:wf_hello.hello:-1:1 cache hit copying nomatch: could not find a suitable cache hit.
2021-09-27 13:48:31,320 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - 075e0cf3-194b-4f53-a43d-d31f0b370f79-EngineJobExecutionActor-wf_hello.hello:NA:1 [UUID(075e0cf3)]: Could not copy a suitable cache hit for 075e0cf3:wf_hello.hello:-1:1. No copy attempts were made.
2021-09-27 13:48:31,449 cromwell-system-akka.dispatchers.backend-dispatcher-33 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(075e0cf3)wf_hello.hello:NA:1]: `echo "Hello Cromwell! Welcome to Cromwell . . . on AWS!"`
2021-09-27 13:48:33,376 cromwell-system-akka.dispatchers.backend-dispatcher-33 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(075e0cf3)wf_hello.hello:NA:1]: Adjusting boot disk size to 16 GB: 10 GB (runtime attributes) + 5 GB (user command image) + 1 GB (Cromwell support images)
2021-09-27 13:48:38,987 cromwell-system-akka.dispatchers.backend-dispatcher-33 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(075e0cf3)wf_hello.hello:NA:1]: job id: projects/gred-cumulus-sb-01-991a49c4/operations/15427360049616748078
2021-09-27 13:49:07,692 cromwell-system-akka.dispatchers.backend-dispatcher-35 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(075e0cf3)wf_hello.hello:NA:1]: Status change from - to Running
2021-09-27 13:50:48,340 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - PipelinesApiAsyncBackendJobExecutionActor [UUID(075e0cf3)wf_hello.hello:NA:1]: Status change from Running to Failed
2021-09-27 13:50:49,875 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - WorkflowManagerActor: Workflow 075e0cf3-194b-4f53-a43d-d31f0b370f79 failed (during ExecutingWorkflowState): java.lang.Exception: Task wf_hello.hello:NA:1 failed. The job was stopped before the command finished. PAPI error code 7. Execution failed: generic::permission_denied: pulling image: docker pull: running ["docker" "pull" "gcr.io/broad-cumulus/cellranger@sha256:a3e918f232f7ae125cf46bd38bff928bb92dafc8a8f9213c5e52be1de7924356"]: exit status 1 (standard error: "Error response from daemon: pull access denied for gcr.io/broad-cumulus/cellranger, repository does not exist or may require 'docker login': denied: Permission denied for \"sha256:a3e918f232f7ae125cf46bd38bff928bb92dafc8a8f9213c5e52be1de7924356\" from request \"/v2/broad-cumulus/cellranger/manifests/sha256:a3e918f232f7ae125cf46bd38bff928bb92dafc8a8f9213c5e52be1de7924356\".\n")
	at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor$.StandardException(PipelinesApiAsyncBackendJobExecutionActor.scala:91)
	at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleFailedRunStatus$1(PipelinesApiAsyncBackendJobExecutionActor.scala:803)
	at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.$anonfun$handleExecutionFailure$1(PipelinesApiAsyncBackendJobExecutionActor.scala:815)
	at scala.util.Try$.apply(Try.scala:213)
	at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:812)
	at cromwell.backend.google.pipelines.common.PipelinesApiAsyncBackendJobExecutionActor.handleExecutionFailure(PipelinesApiAsyncBackendJobExecutionActor.scala:95)
	at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1340)
	at cromwell.backend.standard.StandardAsyncExecutionActor$$anonfun$handleExecutionResult$11.applyOrElse(StandardAsyncExecutionActor.scala:1336)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

2021-09-27 13:50:53,979 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - WorkflowManagerActor: Workflow actor for 075e0cf3-194b-4f53-a43d-d31f0b370f79 completed with status 'Failed'. The workflow will be removed from the workflow store.
```

On the server instance, I was able to pull this GCR docker image after running `gcloud auth login`. Before running test workflows, I've also run `gcloud auth application-default login` command with the same user account.

So I'm wondering how I should configure my Cromwell to make it be able to pull GCR docker images. Thanks!

Sincerely,
Yiming

**Comment by yihming** [comment]
To add up, the GCR docker image is in a different Google Cloud project from where my Cromwell service instance is running.

**Comment by yihming** [comment]
I was able to resolve it by using `gcloud auth activate-service-account ACCOUNT --key-file=KEY-FILE` to change my `application-default`, and add my service account to the user list of the target private GCR docker image.
