### ISSUE TITLE
Private File variables should not be localized

### ISSUE THREAD

**Issue by jlumpe** [broadinstitute/cromwell#6562]
Cromwell seems to erroneously treat private/internal variables with File type as input files and attempts to localize them:

```
version 1.0

task mytask {
	input {
		String mystr = "Hello World!"
	}

	File myfile = "myfile"

	command <<<
		echo ~{mystr} > ~{myfile}
	>>>

	output {
		String file_contents = read_string(myfile)
	}
}

workflow wf {
	call mytask
}
```

```
Could not localize myfile -> /home/jared/projects/gambit/data/misc/211031-apollo_illumina_pe-miniwdl/test-cromwell/cromwell-executions/wf/51d2f863-0e91-45b6-9e7b-f2365c259144/call-mytask/inputs/1979661608/myfile:
	myfile doesn't exist
	File not found /home/jared/projects/gambit/data/misc/211031-apollo_illumina_pe-miniwdl/test-cromwell/cromwell-executions/wf/51d2f863-0e91-45b6-9e7b-f2365c259144/call-mytask/inputs/1979661608/myfile -> /home/jared/projects/gambit/data/misc/211031-apollo_illumina_pe-miniwdl/test-cromwell/myfile
	File not found myfile
	File not found /home/jared/projects/gambit/data/misc/211031-apollo_illumina_pe-miniwdl/test-cromwell/myfile
	at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:94)
	at common.validation.Validation$ValidationTry$.toTry$extension0(Validation.scala:90)
	at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:669)
	... 35 common frames omitted
```

**Comment by jlumpe** [comment]
Actually, after some more thought I realized there's absolutely no reason to use `File` instead of `String` for non-inputs, so this is probably irrelevant.
