### ISSUE TITLE
cromwell-system-akka.dispatchers.service-dispatcher-9 ERROR - Failed to summarize metadata

### ISSUE THREAD

**Issue by kevin-furant** [broadinstitute/cromwell#6583]
I have locally configured mariaDB my.cnf as follows：

> [mysqld]
max_connections=5024
thread_cache_size=1000
datadir=/zfsyt1/B2C_RD_P2/USER/fuxiangke/Cromwell/Data/
socket=/zfsyt1/B2C_RD_P2/USER/fuxiangke/Cromwell/socket/cromwell.sock
default-time-zone='+8:00'
port=3310
skip-character-set-client-handshake
init_connect='SET collation_connection = utf8mb4_unicode_ci'
init_connect='SET NAMES utf8mb4'
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
#open  slow query logging
slow_query_log = ON
slow_query_log_file = /zfsyt1/B2C_RD_P2/USER/fuxiangke/Cromwell/log-files/slow_cromwell.log
long_query_time = 1
[mysqld_safe]
log-error=/zfsyt1/B2C_RD_P2/USER/fuxiangke/Cromwell/log-files/error.log
pid-file=/zfsyt1/B2C_RD_P2/USER/fuxiangke/Cromwell/pid/mysqld_cromwell.pid
[client]
default-character-set=utf8mb4
> 

Then I configured the flow. The following error was reported when scatter 478 tasks were needed in one step：

> 2021-12-06 17:03:51,401 cromwell-system-akka.dispatchers.service-dispatcher-9 ERROR - Failed to summarize metadata

java.sql.SQLException: null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2045)
        at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:388)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
        at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:511)
        at slick.jdbc.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:37)
        at slick.jdbc.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:34)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
2021-12-06 17:03:51,401 cromwell-system-akka.dispatchers.service-dispatcher-9 ERROR - Error summarizing metadata
java.sql.SQLException: null
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2045)
        at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:388)
        at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
        at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:511)
        at slick.jdbc.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:37)
        at slick.jdbc.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:34)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
        at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: null
> 

These two days I also saw some people here have a similar error, it seems that this is not the process of the problem, error of this step process can run normally, but he cannot update the data in the database, cause I will continue to run again don't think this step is to run, and start to run this step, then the metadata can't collect the mistakes, then the process stopped again, I don't know how to solve this anymore, can anyone give me some help?

**Comment by kevin-furant** [comment]
some one help me!!!!!!!!!

**Comment by 2uschauer** [comment]
@kevin-furant hello，how did you solve this problems？
