### ISSUE TITLE
Womtool graph bug

### ISSUE THREAD

**Issue by shengbing** [broadinstitute/cromwell#6744]
womtool graph bug:
Exception in thread "main" java.util.NoSuchElementException: key not found: ScatterVariableNode(WomIdentifier(LocalName(lane),FullyQualifiedName(lane)),PlainAnonymousExpressionNode(WomIdentifier(LocalName(lane),FullyQualifiedName(lane)),WdlWomExpression(WdlExpression(<string:255:22 identifier "TWVyZ2VJbnB1dFJlYWRz">),[Scatter fqn=MAPRSEQSingleSampleMasterWF.$scatter_0, item=lane, collection=MergeInputReads]),WomMaybeEmptyArrayType(WomMaybeEmptyArrayType(WomSingleFileType)),Map(MergeInputReads -> ConnectedInputPort(MergeInputReads,WomMaybeEmptyArrayType(WomMaybeEmptyArrayType(WomSingleFileType)),GraphNodeOutputPort(MAPRSEQSingleSampleMasterWF.MergeInputReads),wom.graph.GraphNode$GraphNodeSetter$$Lambda$512/0x0000000800491040@2a9fd482))),WomMaybeEmptyArrayType(WomSingleFileType))
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:101)
	at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:99)
	at wom.views.GraphPrint$.relevantAsUpstream$1(GraphPrint.scala:177)
	at wom.views.GraphPrint$.upstreamPortToRelevantNodes$1(GraphPrint.scala:187)
	at wom.views.GraphPrint$.$anonfun$upstreamLinks$1(GraphPrint.scala:190)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at wom.views.GraphPrint$.upstreamLinksforNode$1(GraphPrint.scala:190)
	at wom.views.GraphPrint$.relevantAsUpstream$1(GraphPrint.scala:176)
	at wom.views.GraphPrint$.upstreamPortToRelevantNodes$1(GraphPrint.scala:184)
	at wom.views.GraphPrint$.relevantAsUpstream$1(GraphPrint.scala:178)
	at wom.views.GraphPrint$.upstreamPortToRelevantNodes$1(GraphPrint.scala:187)
	at wom.views.GraphPrint$.$anonfun$upstreamLinks$1(GraphPrint.scala:190)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at wom.views.GraphPrint$.upstreamLinksforNode$1(GraphPrint.scala:190)
	at wom.views.GraphPrint$.relevantAsUpstream$1(GraphPrint.scala:176)
	at wom.views.GraphPrint$.upstreamPortToRelevantNodes$1(GraphPrint.scala:187)
	at wom.views.GraphPrint$.$anonfun$upstreamLinks$1(GraphPrint.scala:190)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at wom.views.GraphPrint$.upstreamLinksforNode$1(GraphPrint.scala:190)
	at wom.views.GraphPrint$.upstreamLinks(GraphPrint.scala:191)
	at wom.views.GraphPrint.$anonfun$listAllGraphNodes$2(GraphPrint.scala:33)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:160)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:158)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
	at cats.kernel.Monoid.combineAll(Monoid.scala:82)
	at cats.kernel.Monoid.combineAll$(Monoid.scala:81)
	at cats.derived.MkMonoidDerivation$$anon$1.combineAll(monoid.scala:45)
	at cats.instances.ListInstances$$anon$1.foldMap(list.scala:70)
	at cats.instances.ListInstances$$anon$1.foldMap(list.scala:12)
	at cats.Foldable$Ops.foldMap(Foldable.scala:31)
	at cats.Foldable$Ops.foldMap$(Foldable.scala:31)
	at cats.Foldable$ToFoldableOps$$anon$5.foldMap(Foldable.scala:31)
	at wom.views.GraphPrint.listAllGraphNodes(GraphPrint.scala:32)
	at wom.views.GraphPrint.handleConditional(GraphPrint.scala:87)
	at wom.views.GraphPrint.$anonfun$listAllGraphNodes$2(GraphPrint.scala:36)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:160)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:158)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
	at cats.kernel.Monoid.combineAll(Monoid.scala:82)
	at cats.kernel.Monoid.combineAll$(Monoid.scala:81)
	at cats.derived.MkMonoidDerivation$$anon$1.combineAll(monoid.scala:45)
	at cats.instances.ListInstances$$anon$1.foldMap(list.scala:70)
	at cats.instances.ListInstances$$anon$1.foldMap(list.scala:12)
	at cats.Foldable$Ops.foldMap(Foldable.scala:31)
	at cats.Foldable$Ops.foldMap$(Foldable.scala:31)
	at cats.Foldable$ToFoldableOps$$anon$5.foldMap(Foldable.scala:31)
	at wom.views.GraphPrint.listAllGraphNodes(GraphPrint.scala:32)
	at wom.views.GraphPrint.dotString(GraphPrint.scala:16)
	at womtool.WomtoolMain$.graph(WomtoolMain.scala:132)
	at womtool.WomtoolMain$.dispatchCommand(WomtoolMain.scala:55)
	at womtool.WomtoolMain$.runWomtool(WomtoolMain.scala:157)
	at womtool.WomtoolMain$.delayedEndpoint$womtool$WomtoolMain$1(WomtoolMain.scala:162)
	at womtool.WomtoolMain$delayedInit$body.apply(WomtoolMain.scala:25)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at womtool.WomtoolMain$.main(WomtoolMain.scala:25)
	at womtool.WomtoolMain.main(WomtoolMain.scala)

**Comment by lxwgcool** [comment]
I also encountered the same error. Could anyone make some comments?
