### ISSUE TITLE
Installing the Cromwell To Use Local Scratch Device

### ISSUE THREAD

**Issue by peterjuv** [broadinstitute/cromwell#6757]
Hi!

I've followed the instructions at https://cromwell.readthedocs.io/en/stable/tutorials/HPCSlurmWithLocalScratch/ and I've run into the following errors during 'sbt assembly': 

    [error] /home/cromwell/cromwell/cromwell/wom/src/main/scala/wom/views/GraphPrint.scala:111:57: type mismatch;                                         
    [error]  found   : java.util.stream.Stream[String]
    [error]  required: scala.collection.GenTraversableOnce[?]
    [error]           |  ${digraph.links.toList.flatMap(_.dotString.lines).mkString(System.lineSeparator + "  ")}
    [error]                                                         ^
    [error] /home/cromwell/cromwell/cromwell/wom/src/main/scala/wom/views/GraphPrint.scala:114:57: type mismatch;
    [error]  found   : java.util.stream.Stream[String]
    [error]  required: scala.collection.GenTraversableOnce[?]
    [error]           |  ${digraph.nodes.toList.flatMap(_.dotString.lines).mkString(System.lineSeparator + "  ")}
    [error]                                                         ^
    [error] /home/cromwell/cromwell/cromwell/wom/src/main/scala/wom/views/GraphPrint.scala:157:49: type mismatch;
    [error]  found   : java.util.stream.Stream[String]
    [error]  required: scala.collection.GenTraversableOnce[?]
    [error]           |  ${nodes.toList.flatMap(_.dotString.lines).mkString(System.lineSeparator() + "  ")}
    [error]                                                 ^
    [error] /home/cromwell/cromwell/cromwell/wom/src/main/scala/wom/views/GraphPrint.scala:166:48: type mismatch;
    [error]  found   : java.util.stream.Stream[String]
    [error]  required: scala.collection.GenTraversableOnce[?]
    [error]          |  ${nodes.toList.flatMap(_.dotString.lines).mkString(System.lineSeparator() + "  ")}
    [error]                                                ^

I've tried it with the following javas, but no difference:

    sdk install java 11.0.15-tem 
    sdk install java 11.0.15-tem 
    sdk install java 11.0.14.1-tem
    sdk install java 11.0.14-tem

I've switched to cromwell version 78 and managed to 'sbt assembly' w/o errors.

While executing jointGenotyping.wdl I've run into the following error that I'm unable to debug:

    2022-05-09 13:21:41,743 ERROR - DispatchedConfigAsyncJobExecutionActor [UUID(d5a90666)JointGenotyping.CheckSamplesUnique:NA:1]: Error attempting to Execute
    java.lang.IllegalArgumentException: null
	    at java.base/sun.nio.fs.UnixPath.subpath(UnixPath.java:328)
	    at java.base/sun.nio.fs.UnixPath.subpath(UnixPath.java:43)
	    at cromwell.core.path.NioPathMethods.subpath(NioPathMethods.scala:18)
	    at cromwell.core.path.NioPathMethods.subpath$(NioPathMethods.scala:18)
	    at cromwell.core.path.DefaultPath.subpath(DefaultPathBuilder.scala:55)
	    at cromwell.backend.io.JobPathsWithDocker.toDockerPath(JobPathsWithDocker.scala:56)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.$anonfun$mapCommandLineWomFile$1(SharedFileSystemAsyncJobExecutionActor.scala:147)
	    at wom.values.WomSingleFile.mapFile(WomFile.scala:201)
	    at wom.values.WomSingleFile.mapFile(WomFile.scala:182)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.mapCommandLineWomFile(SharedFileSystemAsyncJobExecutionActor.scala:145)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.mapCommandLineWomFile$(SharedFileSystemAsyncJobExecutionActor.scala:144)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.mapCommandLineWomFile(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$commandLineValueMapper$2(StandardAsyncExecutionActor.scala:206)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$mapOrNoResolve$1(StandardAsyncExecutionActor.scala:168)
	    at wom.WomFileMapper$.$anonfun$mapWomFiles$1(WomFileMapper.scala:24)
	    at scala.util.Try$.apply(Try.scala:213)
	    at wom.WomFileMapper$.mapWomFiles(WomFileMapper.scala:24)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$mapOrNoResolve$2(StandardAsyncExecutionActor.scala:163)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$commandLineValueMapper$1(StandardAsyncExecutionActor.scala:206)
	    at mouse.AnyOps$.$bar$greater$extension(any.scala:8)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.localize$1(StandardAsyncExecutionActor.scala:474)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$runtimeEnvironmentPathMapper$2(StandardAsyncExecutionActor.scala:475)
	    at mouse.AnyOps$.$bar$greater$extension(any.scala:8)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.runtimeEnvironmentPathMapper(StandardAsyncExecutionActor.scala:475)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.runtimeEnvironmentPathMapper$(StandardAsyncExecutionActor.scala:473)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.runtimeEnvironmentPathMapper(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$runtimeEnvironment$1(StandardAsyncExecutionActor.scala:479)
	    at mouse.AnyOps$.$bar$greater$extension(any.scala:8)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.runtimeEnvironment(StandardAsyncExecutionActor.scala:479)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.runtimeEnvironment$(StandardAsyncExecutionActor.scala:479)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.runtimeEnvironment$lzycompute(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.runtimeEnvironment(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand(StandardAsyncExecutionActor.scala:637)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.instantiatedCommand$(StandardAsyncExecutionActor.scala:607)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.instantiatedCommand$lzycompute(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.instantiatedCommand(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents(StandardAsyncExecutionActor.scala:383)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.commandScriptContents$(StandardAsyncExecutionActor.scala:382)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.commandScriptContents(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.writeScriptContents(SharedFileSystemAsyncJobExecutionActor.scala:175)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.writeScriptContents$(SharedFileSystemAsyncJobExecutionActor.scala:174)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.writeScriptContents(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute(SharedFileSystemAsyncJobExecutionActor.scala:158)
	    at cromwell.backend.sfs.SharedFileSystemAsyncJobExecutionActor.execute$(SharedFileSystemAsyncJobExecutionActor.scala:155)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.execute(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$executeAsync$1(StandardAsyncExecutionActor.scala:749)
	    at scala.util.Try$.apply(Try.scala:213)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync(StandardAsyncExecutionActor.scala:749)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.executeAsync$(StandardAsyncExecutionActor.scala:749)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeAsync(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:1139)
	    at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:1131)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.executeOrRecover(ConfigAsyncJobExecutionActor.scala:215)
	    at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
	    at cromwell.core.retry.Retry$.withRetry(Retry.scala:46)
	    at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:61)
	    at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
	    at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:88)
	    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	    at akka.actor.Actor.aroundReceive(Actor.scala:539)
	    at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	    at cromwell.backend.impl.sfs.config.DispatchedConfigAsyncJobExecutionActor.aroundReceive(ConfigAsyncJobExecutionActor.scala:215)
	    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	    at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	    at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	    at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

I've been using slurm backend with singlularity dockers.

Best regards,
Peter Juvan

**Comment by peterjuv** [comment]
The issue was solved by adding cromwell configuration shown in **bold**:

backend {
  providers {
    slurm {
      config {
        **temporary-directory = "/scratch/slurm/$SLURM_JOB_ID"**
        submit-docker = """
            sbatch \
              --wrap "singularity exec **-B /scratch**"
        ""
      }
    }
  }
}
