### ISSUE TITLE
Cromwell out of memory error large array

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#695]
We are trying to scatter over a large array and it seems we ran out of heap space.  The object was an array of arrays.  The outer array had a length of 3457 and the inner arrays had a length of 3 each.  The values of these were gs paths.  This happened in the process of starting scattered calls over this array.

Here is the part of the wdl where this is happening.  `partition_indexing_list` is a list of integers from 0-3456 used to index into the array of arrays `RotateGVCF.output_matrix`, `RotateGVCFIndex.output_matrix` and the array of strings `tiledb_partitions_list`

  scatter (idx in partition_indexing_list) {
    call TileDBCombineGVCF {
      input:
        output_gvcf_filename = "output.vcf.gz",
        gvcf_list = RotateGVCF.output_matrix[idx],
        gvcf_index_list = RotateGVCFIndex.output_matrix[idx],
        ref_fasta = ref_fasta,
        ref_fasta_index = ref_fasta_index,
        partition = tiledb_partitions_list[idx],
        size_per_column_partition = size_per_column_partition,
        vid_mapping_file = vid_mapping_file,
        vcf_header = vcf_header,
        sample_name_map = sample_name_map,
        disk_size = medium_disk
    }

**snippet of the array in question:**

`Success([["gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/606107ba-fb48-489f-8d14-e19192331b82/call-SplitGvcf/shard-0/glob-a859a146d6b8e5fd268a04d997240e7e/NWD113429.7682e7b9-824b-4307-a101-98d0bcc31e82.0000.g.vcf.gz.tbi", "gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/606107ba-fb48-489f-8d14-e19192331b82/call-SplitGvcf/shard-1/glob-a859a146d6b8e5fd268a04d997240e7e/NWD123256.a69a5041-cdcc-4c7d-82e4-47f3d422c441.0000.g.vcf.gz.tbi", "gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/606107ba-fb48-489f-8d14-e19192331b82/call-SplitGvcf/shard-2/glob-a859a146d6b8e5fd268a04d997240e7e/NWD145410.61ccb202-d666-4fad-ba17-351fabd79cd1.0000.g.vcf.gz.tbi"], ["gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/606107ba-fb48-489f-8d14-e19192331b82/call-SplitGvcf/shard-0/glob-a859a146d6b8e5fd268a04d997240e7e/NWD113429.7682e7b9-824b-4307-a101-98d0bcc31e82.0001.g.vcf.gz.tbi", "gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/606107ba-fb48-489f-8d14-e19192331b82/call-SplitGvcf/shard-1/glob-a859a146d6b8e5fd268a04d997240e7e/NWD123256.a69a5041-cdcc-4c7d-82e4-47f3d422c441.0001.g.vcf.gz.tbi", "gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/606107ba-fb48-489f-8d14-e19192331b82/call-SplitGvcf/shard-2/glob-a859a146d6b8e5fd268a04d997240e7e/NWD145410.61ccb202-d666-4fad-ba17-351fabd79cd1.0001.g.vcf.gz.tbi"]`

**Start of the logs**

2016-04-11 22:41:00,479 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: persisting status of TileDBCombineGVCF:1048 to Starting.
2016-04-11 22:41:00,479 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,490 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,521 cromwell-system-akka.actor.default-dispatcher-2683 ERROR - WorkflowActor [UUID(606107ba)]: Failed to fetch locally qualified inputs for call TileDBCombineGVCF:1048
wdl4s.WdlExpressionException: Failed to find index Success(WdlInteger(1048)) on array:

**and the following stacktrace associated with these:**

1048
	at wdl4s.expression.ValueEvaluator.evaluate(ValueEvaluator.scala:112) ~[cromwell.jar:0.19]
	at wdl4s.WdlExpression$.evaluate(WdlExpression.scala:79) ~[cromwell.jar:0.19]
	at wdl4s.WdlExpression.evaluate(WdlExpression.scala:192) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$fetchLocallyQualifiedInputs$1$$anonfun$apply$16.apply(WorkflowActor.scala:987) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$fetchLocallyQualifiedInputs$1$$anonfun$apply$16.apply(WorkflowActor.scala:982) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.Iterator$class.foreach(Iterator.scala:742) ~[cromwell.jar:0.19]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194) ~[cromwell.jar:0.19]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[cromwell.jar:0.19]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$fetchLocallyQualifiedInputs$1.apply(WorkflowActor.scala:982) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$fetchLocallyQualifiedInputs$1.apply(WorkflowActor.scala:962) ~[cromwell.jar:0.19]
	at scala.util.Try$.apply(Try.scala:192) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor.fetchLocallyQualifiedInputs(WorkflowActor.scala:962) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor.cromwell$engine$workflow$WorkflowActor$$processRunnableCall(WorkflowActor.scala:1254) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$33.apply(WorkflowActor.scala:868) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$33.apply(WorkflowActor.scala:867) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221) ~[cromwell.jar:0.19]
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[cromwell.jar:0.19]
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[cromwell.jar:0.19]
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor.cromwell$engine$workflow$WorkflowActor$$startRunnableCalls(WorkflowActor.scala:867) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$2.applyOrElse(WorkflowActor.scala:532) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor$$anonfun$2.applyOrElse(WorkflowActor.scala:467) ~[cromwell.jar:0.19]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[cromwell.jar:0.19]
	at akka.actor.FSM$class.processEvent(FSM.scala:604) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowActor.scala:236) ~[cromwell.jar:0.19]
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor.processEvent(WorkflowActor.scala:236) ~[cromwell.jar:0.19]
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598) ~[cromwell.jar:0.19]
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592) ~[cromwell.jar:0.19]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[cromwell.jar:0.19]
	at cromwell.engine.workflow.WorkflowActor.aroundReceive(WorkflowActor.scala:236) ~[cromwell.jar:0.19]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [cromwell.jar:0.19]
	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487) [cromwell.jar:0.19]
	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1) [cromwell.jar:0.19]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) [cromwell.jar:0.19]
	at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:63) [cromwell.jar:0.19]
	at kamon.trace.Tracer$.withContext(TracerModule.scala:53) [cromwell.jar:0.19]
	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:62) [cromwell.jar:0.19]
	at akka.actor.ActorCell.invoke(ActorCell.scala:483) [cromwell.jar:0.19]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [cromwell.jar:0.19]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [cromwell.jar:0.19]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
2016-04-11 22:41:00,528 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,543 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,556 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,617 cromwell-system-akka.actor.default-dispatcher-2683 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,841 cromwell-system-akka.actor.default-dispatcher-2666 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
2016-04-11 22:41:00,912 cromwell-system-akka.actor.default-dispatcher-2666 INFO  - WorkflowActor [UUID(606107ba)]: Call Caching: cache miss
Uncaught error from thread [cromwell-system-akka.actor.default-dispatcher-2676] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[cromwell-system]

**java.lang.OutOfMemoryError: Java heap space**
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at scala.StringContext.standardInterpolator(StringContext.scala:128)
	at scala.StringContext.s(StringContext.scala:95)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$34.apply(WorkflowActor.scala:885)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$34.apply(WorkflowActor.scala:881)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:155)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:155)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at cromwell.engine.workflow.WorkflowActor.cromwell$engine$workflow$WorkflowActor$$startRunnableCalls(WorkflowActor.scala:881)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$2.applyOrElse(WorkflowActor.scala:532)
	at cromwell.engine.workflow.WorkflowActor$$anonfun$2.applyOrElse(WorkflowActor.scala:467)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at cromwell.engine.workflow.WorkflowActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowActor.scala:236)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)
	at cromwell.engine.workflow.WorkflowActor.processEvent(WorkflowActor.scala:236)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at cromwell.engine.workflow.WorkflowActor.aroundReceive(WorkflowActor.scala:236)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:487)
	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at akka.kamon.instrumentation.ActorCellInstrumentation$$anonfun$aroundBehaviourInvoke$1.apply(ActorCellInstrumentation.scala:63)
2016-04-11 22:41:17,520 cromwell-system-akka.actor.default-dispatcher-2661 ERROR - Uncaught error from thread [cromwell-system-akka.actor.default-dispatcher-2676] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled

**Comment by ruchim** [comment]
@kshakir since the PR is closed, I closed the issue, but let me know if it shouldn't have been!
