### ISSUE TITLE
Parse Error when using variables prepended by if*

### ISSUE THREAD

**Issue by patmagee** [broadinstitute/cromwell#6956]
## Bug
Cromwell appears to be improperly tokenizing string interpolations when using a variable that is prepended by  the letters: `if` in any format. It seems to think that this is actually the start of a conditional `if _ then _ else` block instead of a variable name. The parser does not appear to be discriminating against the lack of whitespace in variables with the form `if[a-zA-Z0-9_]+` and fails to parse with an error.

### How to reproduce

```
cat <<EOF > test.wdl
version 1.0
task test_task {
 String ifl_token="a"
 command <<<
  echo "~{ifl_token}"
 >>>
}

workflow test {
 call test_task
}
EOF

java -jar cromwell-84.jar run. test.wdl
```

### Expected
1. The workflow to parse correctly and to echo `a` when running

### Actual Error

The workflow fails to parse with the following error:

```
[2022-11-25 11:10:39,68] [info] WorkflowManagerActor: Workflow 45701495-7113-40d6-ac32-dab5247f37e7 failed (during MaterializingWorkflowDescriptorState): cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anon$1: Workflow input processing failed:
ERROR: Unexpected symbol (line 5, col 20) when parsing 'e'.

Expected then, got "}".

  echo "~{ifl_token}"
                   ^

$e = :identifier <=> :lparen $_gen23 :rparen -> FunctionCall( name=$0, params=$2 )
     
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor.cromwell$engine$workflow$lifecycle$materialization$MaterializeWorkflowDescriptorActor$$workflowInitializationFailed(MaterializeWorkflowDescriptorActor.scala:257)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:227)
	at cromwell.engine.workflow.lifecycle.materialization.MaterializeWorkflowDescriptorActor$$anonfun$2.applyOrElse(MaterializeWorkflowDescriptorActor.scala:222)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
```

### Environment:
Tested on:
- Cromwell 84
- Cromwell 66

**Comment by aednichols** [comment]
Nice report, thanks! That is indeed very "junior varsity" of our parser.
