### ISSUE TITLE
Could not acquire change log lock

### ISSUE THREAD

**Issue by lindenb** [broadinstitute/cromwell#7009]
hi all,
I'm trying to run cromwell 84 will the following config, with, as far as I understand, a local HTSQLDB cache :

```
include required(classpath("application"))
# the file below was fixed in https://github.com/broadinstitute/cromwell/issues/7007
include "SGE.conf"

call-caching {
	enabled = true
        invalidate-bad-cache-results = false
        }


database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    url = """
    jdbc:hsqldb:file:cromwell-executions/cromwell-db/cromwell-db;
    shutdown=false;
    hsqldb.default_table_type=cached;hsqldb.tx=mvcc;
    hsqldb.result_max_memory_rows=10000;
    hsqldb.large_data=true;
    hsqldb.applog=1;
    hsqldb.lob_compressed=true;
    hsqldb.script_format=3
    """
    connectionTimeout = 120000
    numThreads = 1
  }
}
```

but when I execute the workflow 

`java  -Dconfig.file=${PWD}/app.conf -jar  ${CROMWELL_JAR} run test.wdl --inputs input.json`

the configuration takes a long time with messages about `Checkpoint...` that takes about 10 minutes. 

```
(...)
[2023-02-08 16:24:28,90] [info] dataFileCache commit start
[2023-02-08 16:24:28,91] [info] dataFileCache commit end
[2023-02-08 16:24:28,94] [info] checkpointClose end
[2023-02-08 16:24:28,96] [info] Checkpoint end - txts: 3051
[2023-02-08 16:24:29,05] [info] Checkpoint start
[2023-02-08 16:24:29,05] [info] checkpointClose start
[2023-02-08 16:24:29,07] [info] checkpointClose synched
[2023-02-08 16:24:29,08] [info] checkpointClose script done
[2023-02-08 16:24:29,08] [info] dataFileCache commit start
[2023-02-08 16:24:29,20] [info] dataFileCache commit end
[2023-02-08 16:24:29,53] [info] checkpointClose end
[2023-02-08 16:24:29,53] [info] Checkpoint end - txts: 3058
[2023-02-08 16:24:29,53] [info] Checkpoint start
[2023-02-08 16:24:29,53] [info] checkpointClose start
[2023-02-08 16:24:30,52] [info] checkpointClose synched
[2023-02-08 16:24:30,52] [info] checkpointClose script done
[2023-02-08 16:24:30,52] [info] dataFileCache commit start
[2023-02-08 16:24:30,53] [info] dataFileCache commit end
[2023-02-08 16:24:30,58] [info] checkpointClose end
[2023-02-08 16:24:30,58] [info] Checkpoint end - txts: 3060
[2023-02-08 16:24:30,59] [info] Checkpoint start
[2023-02-08 16:24:30,59] [info] checkpointClose start
[2023-02-08 16:24:31,52] [info] checkpointClose synched
[2023-02-08 16:24:31,65] [info] checkpointClose script done
[2023-02-08 16:24:31,65] [info] dataFileCache commit start
(...)
```

And at the end:
```
2023-02-08 16:32:11,54] [info] checkpointClose synched
[2023-02-08 16:32:11,57] [info] checkpointClose script done
[2023-02-08 16:32:11,57] [info] dataFileCache commit start
[2023-02-08 16:32:11,57] [info] dataFileCache commit end
[2023-02-08 16:32:11,69] [info] checkpointClose end
[2023-02-08 16:32:11,69] [info] Checkpoint end - txts: 5342
[2023-02-08 16:32:21,70] [info] Checkpoint start
[2023-02-08 16:32:21,70] [info] checkpointClose start
[2023-02-08 16:32:21,70] [info] checkpointClose synched
[2023-02-08 16:32:21,74] [info] checkpointClose script done
[2023-02-08 16:32:21,74] [info] dataFileCache commit start
[2023-02-08 16:32:21,76] [info] dataFileCache commit end
[2023-02-08 16:32:21,82] [info] checkpointClose end
[2023-02-08 16:32:21,82] [info] Checkpoint end - txts: 5348
[2023-02-08 16:32:21,89] [error] Failed to instantiate Cromwell System. Shutting down Cromwell.
liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by fdb0:cafe:d0d0:ceb4:ba59:9fff:fec3:33de%p1p1 (fdb0:cafe:d0d0:ceb4:ba59:9fff:fec3:33de%p1p1) since 2/8/23, 4:23 PM
	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:270)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:214)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at cromwell.database.migration.liquibase.LiquibaseUtils$.updateSchema(LiquibaseUtils.scala:74)
	at cromwell.database.migration.liquibase.LiquibaseUtils$.updateSchema(LiquibaseUtils.scala:46)
	at cromwell.services.ServicesStore$EnhancedSqlDatabase$.$anonfun$initialized$1(ServicesStore.scala:11)
	at cromwell.services.ServicesStore$EnhancedSqlDatabase$.$anonfun$initialized$1$adapted(ServicesStore.scala:11)
	at cromwell.database.slick.SlickDatabase.$anonfun$withConnection$1(SlickDatabase.scala:156)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
	at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

What Am I doing wrong ?

**Comment by lindenb** [comment]
I asked SO: https://stackoverflow.com/questions/75390283/

**Comment by lindenb** [comment]
The solution was given on SO: https://stackoverflow.com/questions/75390283/

when changing the hsqldb directory NOT inside in the cromwell directory.
