### ISSUE TITLE
problem with applying metadata archiving with gcs filesystem

### ISSUE THREAD

**Issue by avigailmo** [broadinstitute/cromwell#7171]
When trying to configure metadata-archive in cromwell server by adding the configuration below:
```
archive-metadata {
    # A filesystem able to access the specified bucket:
    filesystems {
      gcs {
        # A reference to the auth to use for storing and retrieving metadata:
        auth = "user-service-account"
      }
    }

    # Which bucket to use for storing the archived metadata
    bucket = "{{ backend_bucket }}"
}
```

when the user-service-account auth is declared up in the configuration :
```
google {

  application-name = "cromwell"

  auths = [
    {
      name = "user-service-account"
      scheme = "user_service_account"
    }
  ]
}
```
We got the following error in Cromwell server initialization :
cromwell_1  | [ERROR] [06/21/2023 11:55:25.094] [cromwell-system-akka.actor.default-dispatcher-30] [akka://cromwell-system/user] Failed to parse the archive-metadata config:
cromwell_1  | Failed to construct archiver path builders from factories (reason 1 of 1): Missing parameters in workflow options: user_service_account_json
cromwell_1  | akka.actor.ActorInitializationException: akka://cromwell-system/user/cromwell-service/ServiceRegistryActor/MetadataService: exception during creation
cromwell_1  | 	at akka.actor.ActorInitializationException$.apply(Actor.scala:202)
cromwell_1  | 	at akka.actor.ActorCell.create(ActorCell.scala:698)
cromwell_1  | 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:549)
cromwell_1  | 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:571)
cromwell_1  | 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:293)
cromwell_1  | 	at akka.dispatch.Mailbox.run(Mailbox.scala:228)
cromwell_1  | 	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
cromwell_1  | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

this code line causes the error above:
https://github.com/broadinstitute/cromwell/blob/develop/services/src/main/scala/cromwell/services/metadata/impl/archiver/ArchiveMetadataConfig.scala#L38:

`PathBuilderFactory.instantiatePathBuilders(pathBuilderFactories.values.toList, WorkflowOptions.empty)`

`WorkflowOptions.empty` probably doesn't have a user_service_account_json set...

**Comment by aednichols** [comment]
As mentioned in Slack archiving is undocumented/untested/unsupported on self-hosted instances. I'll leave the issue open on the off chance somebody actually got it working.
