### ISSUE TITLE
Histogram array index out of bounds exception

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#735]
When running our joint genotyping workflow, after when starting workflows, we run into an array out of bounds index exception that references a histogram.  This causes the machine to become locked up because all cpu resources are being used and then weirdness ensues.

![image](https://cloud.githubusercontent.com/assets/13023616/14790046/781a034a-0add-11e6-90b4-05df4ff61433.png)

```
2016-04-22 04:01:20,697 cromwell-system-akka.actor.default-dispatcher-36 INFO  - WorkflowActor [UUID(1f5b729c)]: starting calls: JointGenotyping.TabixAndGenotypeGVCF
2016-04-22 04:01:20,697 cromwell-system-akka.actor.default-dispatcher-36 INFO  - WorkflowActor [UUID(1f5b729c)]: persisting status of TabixAndGenotypeGVCF:2596 to Starting.
2016-04-22 04:01:20,703 cromwell-system-akka.actor.default-dispatcher-21 ERROR - Uncaught error from thread [cromwell-system-akka.actor.default-dispatcher-41]
java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 4737
        at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:441) ~[cromwell.jar:0.19]
        at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:433) ~[cromwell.jar:0.19]
        at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:346) ~[cromwell.jar:0.19]
        at kamon.metric.instrument.HdrHistogram.record(Histogram.scala:115) ~[cromwell.jar:0.19]
        at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorCellInstrumentation.scala:69) ~[cromwell.jar:0.19]
        at akka.actor.ActorCell.invoke(ActorCell.scala:483) [cromwell.jar:0.19]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [cromwell.jar:0.19]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [cromwell.jar:0.19]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
```

**Comment by kshakir** [comment]
Talked to @jsotobroad in person.

- Kamon was removed in develop, but no hotfix needed because
- Green team changed their `java ...` script to not invoke the kamon code

No longer seems to be an issue. Closing and removing my branch that, in parallel, tested the kamon removal against a stale version of 0.19_hotfix.
