### ISSUE TITLE
Communications link Failure

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#742]
Post task success processing failed with a Communications link failure.

```
2016-04-26 14:06:36,930 cromwell-system-akka.actor.default-dispatcher-8 INFO  - JES Run [UUID(143681e1):GatherBqsrReports]: Status change from Running to Success
2016-04-26 14:06:37,506 cromwell-system-akka.actor.default-dispatcher-15 ERROR - WorkflowActor [UUID(143681e1)]: Completion work failed for call GatherBqsrReports.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 324 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor102.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_72]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3434) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3334) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3774) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2541) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4882) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.ConnectionProxy.setAutoCommit(ConnectionProxy.java:334) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.setAutoCommit(ConnectionJavassistProxy.java) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:437) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:41) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:38) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2926) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3344) ~[cromwell.jar:0.19]
	... 16 common frames omitted
2016-04-26 14:06:37,506 cromwell-system-akka.actor.default-dispatcher-15 INFO  - WorkflowActor [UUID(143681e1)]: persisting status of GatherBqsrReports to Failed.
2016-04-26 14:06:37,506 cromwell-system-akka.actor.default-dispatcher-15 ERROR - WorkflowActor [UUID(143681e1)]: Communications link failure

The last packet successfully received from the server was 324 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
2016-04-26 14:06:37,741 cromwell-system-akka.actor.default-dispatcher-10 INFO  - WorkflowActor [UUID(143681e1)]: Beginning transition from Running to Failed.
2016-04-26 14:06:39,456 cromwell-system-akka.actor.default-dispatcher-15 INFO  - WorkflowActor [UUID(143681e1)]: transitioning from Running to Failed.
```

**Comment by jrose77** [comment]
We've now seen a new "flavor" of this failure mode, where this same "Communications link failure" error is cropping up but it's following some type of HttpRequest failure: 
2016-05-16 23:42:39,080 cromwell-system-akka.actor.default-dispatcher-18 INFO  - WorkflowActor [UUID(e7e4c6d2)]: Collection complete for Scattered Call CollectQualityYieldMetrics.
2016-05-16 23:42:39,365 cromwell-system-akka.actor.default-dispatcher-10 INFO  - WorkflowActor [UUID(e7e4c6d2)]: persisting status of CollectQualityYieldMetrics to Done.
2016-05-16 23:42:45,957 cromwell-system-akka.actor.default-dispatcher-21 INFO  - JES Run [UUID(303ad2dd):ScatterIntervalList]: Status change from Running to Success
2016-05-16 23:42:50,399 cromwell-system-akka.actor.default-dispatcher-18 INFO  - WorkflowActor [UUID(303ad2dd)]: persisting status of ScatterIntervalList to Done.
2016-05-16 23:42:51,977 cromwell-system-akka.actor.default-dispatcher-10 INFO  - WorkflowActor [UUID(303ad2dd)]: persisting status of $scatter_2 to Starting.
2016-05-16 23:42:55,593 cromwell-system-akka.actor.default-dispatcher-10 INFO  - WorkflowActor [UUID(303ad2dd)]: persisting status of $scatter_2 to Done.
2016-05-16 23:43:15,790 cromwell-system-akka.actor.default-dispatcher-17 INFO  - JES Run [UUID(303ad2dd):CollectQualityYieldMetrics:0:2]: Status change from Initializing to Running
2016-05-16 23:43:18,436 cromwell-system-akka.actor.default-dispatcher-4 INFO  - JES Run [UUID(7bbc0491):HaplotypeCaller:35]: Status change from Running to Success
2016-05-16 23:43:19,178 cromwell-system-akka.actor.default-dispatcher-17 INFO  - WorkflowActor [UUID(7bbc0491)]: persisting status of HaplotypeCaller:35 to Done.
2016-05-16 23:43:29,519 cromwell-system-akka.actor.default-dispatcher-21 ERROR - Error during processing of request HttpRequest(GET,http://app:8000/api/workflows/v1/9c68fe34-7a9e-434a-b958-aa4d91339da9/status,List(Connection: Keep-Alive, X-Forwarded-Server: cromwell.gotc-prod.broadinstitute.org, X-Forwarded-Host: cromwell.gotc-prod.broadinstitute.org, X-Forwarded-For: 69.173.127.107, User-Agent: Java/1.8.0, Host: app:8000),Empty,HTTP/1.1)
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 0 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor101.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_72]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3434) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3334) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3774) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2541) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4882) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.ConnectionProxy.setAutoCommit(ConnectionProxy.java:334) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.ConnectionJavassistProxy.setAutoCommit(ConnectionJavassistProxy.java) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.endInTransaction(JdbcBackend.scala:443) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$Commit$.run(JdbcActionComponent.scala:48) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$Commit$.run(JdbcActionComponent.scala:46) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2926) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3344) ~[cromwell.jar:0.19]
	... 16 common frames omitted

**Comment by cjllanwarne** [comment]
@jsotobroad our DB layer is handled completely differently now. But let us know if this ever reappears in 21+
