### ISSUE TITLE
Preemptible retry behavior for Error Code 13

### ISSUE THREAD

**Issue by ruchim** [broadinstitute/cromwell#744]
As of right now, when using preemptible instances, Google has two types of error messages: 13 & 14. We want to to be able to retry when receiving Error Code 13 in the same way we currently retry for Error Code 14.

**Comment by mcovarr** [comment]
This appears to be the way it already works

```scala
  private def preempted(errorCode: Int, errorMessage: Option[String], jobDescriptor: BackendCallJobDescriptor, logger: WorkflowLogger): Boolean = {
    def isPreemptionCode(code: Int) = code == 13 || code == 14

    try {
      errorCode == 10 && errorMessage.isDefined && isPreemptionCode(extractErrorCodeFromErrorMessage(errorMessage.get)) && jobDescriptor.preemptible
    } catch {
      case _: NumberFormatException | _: StringIndexOutOfBoundsException =>
        logger.warn(s"Unable to parse JES error code from error message: ${errorMessage.get}, assuming this was not a preempted VM.")
        false
    }
  }
```

**Comment by ruchim** [comment]
So then there should have been a retry... @jacarey, can you please share logs/other information related to the specific case you emailed Dion about?

**Comment by jacarey** [comment]
Let me know if there is any more information that would be useful. Thanks.

Workflow Id:

`129f0510-5d6b-4c4c-b266-116a9a52f325`

Step meta data:
```

{
      "preemptible": false,
      "executionStatus": "Failed",
      "stdout": "gs://broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/129f0510-5d6b-4c4c-b266-116a9a52f325/call-CollectQualityYieldMetrics/shard-2/CollectQualityYieldMetrics-2-stdout.log",
      "backendStatus": "Failed",
      "shardIndex": 2,
      "outputs": {

      },
      "runtimeAttributes": {
        "preemptible": "0",
        "failOnStderr": "false",
        "bootDiskSizeGb": "10",
        "disks": "local-disk 100 HDD",
        "continueOnReturnCode": "0",
        "docker": "broadinstitute/genomes-in-the-cloud:2.0.0",
        "cpu": "1",
        "zones": "us-central1-c",
        "memory": "2 GB"
      },
      "cache": {
        "allowResultReuse": true
      },
      "inputs": {
        "disk_size": "flowcell_small_disk",
        "input_bam": "unmapped_bam",
        "metrics_filename": "sub(sub(unmapped_bam, sub_strip_path, \"\"), sub_strip_unmapped, \"\") + \".unmapped.quality_yield_metrics\""
      },
      "failures": [{
        "failure": "Task 129f0510-5d6b-4c4c-b266-116a9a52f325:CollectQualityYieldMetrics failed: error code 10. Message: 13: VM ggp-12606127296447203756 shut down unexpectedly.",
        "timestamp": "2016-04-24T20:04:45.145Z"
      }],
      "jobId": "operations/EIXH28fEKhisk93Qxr_9-K4BIJ-ikOmeDSoPcHJvZHVjdGlvblF1ZXVl",
      "backend": "JES",
      "end": "2016-04-24T20:04:45.000Z",
      "stderr": "gs://broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/129f0510-5d6b-4c4c-b266-116a9a52f325/call-CollectQualityYieldMetrics/shard-2/CollectQualityYieldMetrics-2-stderr.log",
      "attempt": 1,
      "executionEvents": [],
      "backendLogs": {
        "log": "gs://broad-gotc-prod-storage/cromwell_execution/PairedEndSingleSampleWorkflow/129f0510-5d6b-4c4c-b266-116a9a52f325/call-CollectQualityYieldMetrics/shard-2/CollectQualityYieldMetrics-2.log"
      },
      "start": "2016-04-24T15:50:19.000Z"
    }

```

Log stack trace: 
 
```
3589853:2016-04-24 20:04:45,142 cromwell-system-akka.actor.default-dispatcher-16 INFO  - JES Run [UUID(129f0510):CollectQualityYieldMetrics:2]: Status change from Running to Failed
3589854:2016-04-24 20:04:45,145 cromwell-system-akka.actor.default-dispatcher-16 ERROR - CallActor [UUID(129f0510):CollectQualityYieldMetrics:2]: Failing call: Task 129f0510-5d6b-4c4c-b266-116a9a52f325:CollectQualityYieldMetrics failed: error code 10. Message: 13: VM ggp-12606127296447203756 shut down unexpectedly.
3589855:java.lang.Throwable: Task 129f0510-5d6b-4c4c-b266-116a9a52f325:CollectQualityYieldMetrics failed: error code 10. Message: 13: VM ggp-12606127296447203756 shut down unexpectedly.
3589856-	at cromwell.engine.backend.jes.JesBackend.cromwell$engine$backend$jes$JesBackend$$handleFailure(JesBackend.scala:774) ~[cromwell.jar:0.19]
3589857-	at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:685) ~[cromwell.jar:0.19]
3589858-	at cromwell.engine.backend.jes.JesBackend$$anonfun$executionResult$1.apply(JesBackend.scala:659) ~[cromwell.jar:0.19]
3589859-	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[cromwell.jar:0.19]
3589860-	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run_aroundBody0(Future.scala:24) ~[cromwell.jar:0.19]
3589861-	at scala.concurrent.impl.Future$PromiseCompletingRunnable$AjcClosure1.run(Future.scala:1) ~[cromwell.jar:0.19]
3589862-	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[cromwell.jar:0.19]
3589863-	at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:44) ~[cromwell.jar:0.19]
3589864-	at kamon.trace.Tracer$.withContext(TracerModule.scala:53) ~[cromwell.jar:0.19]
3589865-	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:43) ~[cromwell.jar:0.19]
3589866-	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) ~[cromwell.jar:0.19]
3589867-	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[cromwell.jar:0.19]
3589868-	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [cromwell.jar:0.19]
3589869-	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
3589870-	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
3589871-	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
3589872-	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
3589873:2016-04-24 20:04:45,145 cromwell-system-akka.actor.default-dispatcher-16 INFO  - WorkflowActor [UUID(129f0510)]: persisting status of CollectQualityYieldMetrics:2 to Failed.
3589874:2016-04-24 20:04:45,145 cromwell-system-akka.actor.default-dispatcher-16 ERROR - WorkflowActor [UUID(129f0510)]: Task 129f0510-5d6b-4c4c-b266-116a9a52f325:CollectQualityYieldMetrics failed: error code 10. Message: 13: VM ggp-12606127296447203756 shut down unexpectedly.
```

**Comment by mcovarr** [comment]
The metadata appears to say preemptible was set to false, in which case this would be the expected behavior.

**Comment by jacarey** [comment]
/facepalm

Thanks @mcovarr punting this back to the JES team and closing this issue. We still want to figure out why a non-preemptable instance would die before anything was done.

**Comment by mcovarr** [comment]
No problem.  😄   It's definitely strange for a non-preemptible instance to die that way.
