### ISSUE TITLE
google-api-client version issue with Cromwell v87

### ISSUE THREAD

**Issue by yihming** [broadinstitute/cromwell#7481]
I'm using Cromwell v87 on GCP Genomics API. When submitting a job, the error I got is the following:

```
Caused by: java.lang.IllegalStateException: You are currently running with version 2.2.0 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.32.1 of the Genomics API library.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
        at com.google.api.client.util.Preconditions.checkState(Preconditions.java:113)
        at com.google.api.services.genomics.v2alpha1.Genomics.<clinit>(Genomics.java:44)
        ... 12 common frames omitted
```

It seems that I need to downgrade the version of `google-api-client`. However, I don't know how to do it on my machine. Could anyone help? Thanks!

**Comment by aednichols** [comment]
GCP shut down Genomics on July 9, 2024 and the backend will be removed from Cromwell.

Life Sciences is the replacement, for example
```
endpoint-url = "https://lifesciences.googleapis.com/"
```
