### ISSUE TITLE
GCP Batch backend not recovering workflows on restart

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#7495]
Launch any workflow, let it run long enough to start a job in GCP Batch. Shut down Cromwell, restart Cromwell:

```
2024-08-19 14:47:51 cromwell-system-akka.dispatchers.engine-dispatcher-5 INFO  - Cromwell 88-e59a6aa-SNAP service started on 0:0:0:0:0:0:0:0:8000...
2024-08-19 14:47:51 cromwell-system-akka.dispatchers.engine-dispatcher-55 INFO  - MaterializeWorkflowDescriptorActor [UUID(119e11a5)]: Call-to-Backend assignments: wf_hello.hello -> GCPBATCH
2024-08-19 14:47:52 cromwell-system-akka.dispatchers.engine-dispatcher-54 INFO  - WorkflowExecutionActor-119e11a5-b981-4510-a6d9-b5c26dfbb4e3 [UUID(119e11a5)]: Restarting wf_hello.hello
2024-08-19 14:47:53 cromwell-system-akka.dispatchers.engine-dispatcher-53 INFO  - Assigned new job restart checking tokens to the following groups: 119e11a5: 1
2024-08-19 14:47:55 cromwell-system-akka.dispatchers.engine-dispatcher-49 INFO  - Not triggering log of restart checking token queue status. Effective log interval = None
2024-08-19 14:47:55 cromwell-system-akka.dispatchers.engine-dispatcher-41 INFO  - Triggering log of execution token queue status. Effective log interval = 300 seconds
2024-08-19 14:48:00 cromwell-system-akka.dispatchers.engine-dispatcher-47 INFO  - Assigned new job execution tokens to the following groups: 119e11a5: 1
2024-08-19 14:48:00 cromwell-system-akka.dispatchers.engine-dispatcher-47 INFO  - BT-322 119e11a5:wf_hello.hello:-1:1 is eligible for call caching with read = true and write = true
2024-08-19 14:48:00 cromwell-system-akka.dispatchers.engine-dispatcher-43 INFO  - BT-322 119e11a5:wf_hello.hello:-1:1 cache hit copying nomatch: could not find a suitable cache hit.
2024-08-19 14:48:00 cromwell-system-akka.dispatchers.engine-dispatcher-43 INFO  - 119e11a5-b981-4510-a6d9-b5c26dfbb4e3-EngineJobExecutionActor-wf_hello.hello:NA:1 [UUID(119e11a5)]: Could not copy a suitable cache hit for 119e11a5:wf_hello.hello:-1:1. No copy attempts were made.
2024-08-19 14:48:00 cromwell-system-akka.dispatchers.backend-dispatcher-84 ERROR - GcpBatchAsyncBackendJobExecutionActor [UUID(119e11a5)wf_hello.hello:NA:1]: Error attempting to Recover(StandardAsyncJob(projects/broad-dsde-cromwell-dev/locations/us-central1/jobs/job-7ce25791-3731-4a69-97f1-b7b65ac8ff71))
java.lang.UnsupportedOperationException: Neither execute() nor executeAsync() implemented by class cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor
	at cromwell.backend.standard.StandardAsyncExecutionActor.execute(StandardAsyncExecutionActor.scala:805)
	at cromwell.backend.standard.StandardAsyncExecutionActor.execute$(StandardAsyncExecutionActor.scala:804)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.execute(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recover(StandardAsyncExecutionActor.scala:821)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recover$(StandardAsyncExecutionActor.scala:821)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.recover(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$recoverAsync$1(StandardAsyncExecutionActor.scala:829)
	at scala.util.Try$.apply(Try.scala:210)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recoverAsync(StandardAsyncExecutionActor.scala:829)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recoverAsync$(StandardAsyncExecutionActor.scala:829)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.recoverAsync(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:1253)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:1248)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.executeOrRecover(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
	at cromwell.core.retry.Retry$.withRetry(Retry.scala:46)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:62)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:86)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.aroundReceive(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2024-08-19 14:48:03 cromwell-system-akka.dispatchers.engine-dispatcher-51 INFO  - WorkflowManagerActor: Workflow 119e11a5-b981-4510-a6d9-b5c26dfbb4e3 failed (during ExecutingWorkflowState): cromwell.core.CromwellFatalException: java.lang.UnsupportedOperationException: Neither execute() nor executeAsync() implemented by class cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor
	at cromwell.core.CromwellFatalException$.apply(core.scala:22)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:47)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:46)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:490)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.UnsupportedOperationException: Neither execute() nor executeAsync() implemented by class cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor
	at cromwell.backend.standard.StandardAsyncExecutionActor.execute(StandardAsyncExecutionActor.scala:805)
	at cromwell.backend.standard.StandardAsyncExecutionActor.execute$(StandardAsyncExecutionActor.scala:804)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.execute(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recover(StandardAsyncExecutionActor.scala:821)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recover$(StandardAsyncExecutionActor.scala:821)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.recover(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$recoverAsync$1(StandardAsyncExecutionActor.scala:829)
	at scala.util.Try$.apply(Try.scala:210)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recoverAsync(StandardAsyncExecutionActor.scala:829)
	at cromwell.backend.standard.StandardAsyncExecutionActor.recoverAsync$(StandardAsyncExecutionActor.scala:829)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.recoverAsync(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover(StandardAsyncExecutionActor.scala:1253)
	at cromwell.backend.standard.StandardAsyncExecutionActor.executeOrRecover$(StandardAsyncExecutionActor.scala:1248)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.executeOrRecover(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.$anonfun$robustExecuteOrRecover$1(AsyncBackendJobExecutionActor.scala:65)
	at cromwell.core.retry.Retry$.withRetry(Retry.scala:46)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.withRetry(AsyncBackendJobExecutionActor.scala:62)
	at cromwell.backend.async.AsyncBackendJobExecutionActor.cromwell$backend$async$AsyncBackendJobExecutionActor$$robustExecuteOrRecover(AsyncBackendJobExecutionActor.scala:65)
	at cromwell.backend.async.AsyncBackendJobExecutionActor$$anonfun$receive$1.applyOrElse(AsyncBackendJobExecutionActor.scala:86)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:270)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at cromwell.backend.google.batch.actors.GcpBatchAsyncBackendJobExecutionActor.aroundReceive(GcpBatchAsyncBackendJobExecutionActor.scala:132)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	... 4 more

2024-08-19 14:48:05 cromwell-system-akka.dispatchers.engine-dispatcher-37 INFO  - WorkflowManagerActor: Workflow actor for 119e11a5-b981-4510-a6d9-b5c26dfbb4e3 completed with status 'Failed'. The workflow will be removed from the workflow store.

```

**Comment by mcovarr** [comment]
Addressed in #7498
