### ISSUE TITLE
system.workflow-restart not optional, not documented

### ISSUE THREAD

**Issue by mcovarr** [broadinstitute/cromwell#845]
```
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'system.workflow-restart'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189) ~[config-1.3.0.jar:na]
	at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:214) ~[config-1.3.0.jar:na]
	at cromwell.engine.workflow.WorkflowManagerActor.preStart(WorkflowManagerActor.scala:83) ~[classes/:na]
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:472) ~[akka-actor_2.11-2.3.12.jar:na]
	at cromwell.engine.workflow.WorkflowManagerActor.aroundPreStart(WorkflowManagerActor.scala:69) ~[classes/:na]
	at akka.actor.ActorCell.create(ActorCell.scala:580) ~[akka-actor_2.11-2.3.12.jar:na]
```

**Comment by kcibul** [comment]
@ruchim -- related to your previous work in this area

**Comment by scottfrazer** [comment]
I'm a bit confused by this... it's labelled with 0.20 milestone but this is for a feature that's only in 0.19?  This should be fixed on the 0.19 hotfix branch right?

**Comment by mcovarr** [comment]
It's true that restarts aren't actually working in the New Worlde, but the problem here is that this value must be specified in the conf or Cromwell will throw an exception on startup.

**Comment by scottfrazer** [comment]
Interesting... because my new-world config does not have a value for system.workflow-restart and it works fine

**Comment by mcovarr** [comment]
Hmm yeah you're right.  Scrolling up it looks like this ticket was referencing hotfix and not develop.  And yeah we're not even trying to load this key on develop so Cromwell certainly shouldn't fail for its absence.

**Comment by ruchim** [comment]
It's a mix of both, Miguel is right in the sense that this was an issue on develop a few weeks ago, but then someone ended up removing the system stanza entirely, and so Scott you don't see it as an issue currently.

**Comment by scottfrazer** [comment]
I guess I'm still confused... is there anything for me to do with this ticket?  On both hotfix and develop, I can leave out the `system.workflow-restart` and it works.

**Comment by mcovarr** [comment]
If you can do that I'd say there's nothing for you to do here.  😄
