### ISSUE TITLE
Cromwell restart MySQL Constraint Violation Duplicate Entry

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#880]
This task failed after a restart of Cromwell with the following stack trace.  We have seen similar errors before - #588.  This was only after one restart though.
```
2016-05-24 16:59:43,266 cromwell-system-akka.actor.default-dispatcher-6 INFO  - JesBackend [UUID(fd62961b):ApplyBQSR:11]: Starting call with pre-emptible VM

2016-05-24 16:59:43,431 cromwell-system-akka.actor.default-dispatcher-17 INFO  - WorkflowActor [UUID(fd62961b)]: persisting status of ApplyBQSR:11 to Running.

2016-05-24 16:59:43,526 cromwell-system-akka.actor.default-dispatcher-6 INFO  - JES Run [UUID(fd62961b):ApplyBQSR:11]: Status change from - to Success

2016-05-24 16:59:44,173 cromwell-system-akka.actor.default-dispatcher-13 ERROR - WorkflowActor [UUID(fd62961b)]: Completion work failed for call ApplyBQSR:11.
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '741-PairedEndSingleSampleWorkflow.ApplyBQSR-recalibrated_bam-11-' for key 'UK_SYM_WORKFLOW_EXECUTION_ID_SCOPE_NAME_ITERATION_IO'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_72]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_72]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_72]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.Util.getInstance(Util.java:383) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:973) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049) ~[cromwell.jar:0.19]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61) ~[cromwell.jar:0.19]
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$anonfun$run$8$$anonfun$apply$1.apply(JdbcActionComponent.scala:520) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$anonfun$run$8$$anonfun$apply$1.apply(JdbcActionComponent.scala:517) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:354) ~[cromwell.jar:0.19]
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:407) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:636) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$anonfun$run$8.apply(JdbcActionComponent.scala:517) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[cromwell.jar:0.19]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[cromwell.jar:0.19]
	at scala.collection.immutable.List.map(List.scala:285) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:522) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:32) ~[cromwell.jar:0.19]
	at slick.driver.JdbcActionComponent$SimpleJdbcDriverAction.run(JdbcActionComponent.scala:29) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[cromwell.jar:0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
2016-05-24 16:59:44,174 cromwell-system-akka.actor.default-dispatcher-12 INFO  - JesBackend [UUID(fd62961b):ApplyBQSRToUnmappedReads]: Starting call with pre-emptible VM
2016-05-24 16:59:44,175 cromwell-system-akka.actor.default-dispatcher-22 INFO  - WorkflowActor [UUID(fd62961b)]: persisting status of ApplyBQSR:11 to Failed.
2016-05-24 16:59:44,180 cromwell-system-akka.actor.default-dispatcher-13 ERROR - WorkflowActor [UUID(fd62961b)]: Duplicate entry '741-PairedEndSingleSampleWorkflow.ApplyBQSR-recalibrated_bam-11-' for key 'UK_SYM_WORKFLOW_EXECUTION_ID_SCOPE_NAME_ITERATION_IO'

2016-05-24 16:59:44,175 cromwell-system-akka.actor.default-dispatcher-22 INFO  - WorkflowActor [UUID(fd62961b)]: persisting status of ApplyBQSR:11 to Failed.

```

**Comment by cjllanwarne** [comment]
This particular problem cannot happen with the new database layout in 21+.

We may have other problems, but this one is done.
