### ISSUE TITLE
Possible write_tsv issue with data > ~85MB

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/cromwell#932]
When running this task:

```
task MatrixRotation {
  Array[Array[String]] input_matrix

    command <<<
      python <<CODE
      import csv
      with open("${write_tsv(input_matrix)}") as tsv_in:
        input_matrix = [line.strip().split("\t") for line in tsv_in]
        final_matrix = [["" for x in range(len(input_matrix))] for y in range(len(input_matrix[0]))]
        for x in range(len(input_matrix)):
          for y in range(len(input_matrix[0])):
            final_matrix[y][x] = input_matrix[x][y]
      with open("output.tsv", "w") as tsv_out:
        # lineterminator is a workaround for a cromwell bug that doesnt allow for "\r\n" line endings which this outputs by default
        writer = csv.writer(tsv_out, delimiter="\t", lineterminator="\n")
        writer.writerows(final_matrix)
      CODE
      >>>

    runtime {
      docker: "python:2.7"
      memory: "1 GB"
    }

    output {
        File output_tsv = "output.tsv"
        Array[Array[String]] output_matrix = read_tsv("output.tsv")
    }
}
```

It seems that if you give it an `input_matrix` that is greater than 85 MB worth of data, you get the stack trace below.  I reached this size of data with an inputs Array of Arrays that had dimensions 500x901 where each element was a gcs path like "gs://broad-gotc-dev-storage/cromwell_execution/JointGenotyping/cab6dea2-8a01-4130-8973-96023637de29/call-SplitGvcf/shard-100/split_gvcfs/11C118416.7ca5a79a-1369-4dc1-8f41-4180d7b3c1ab.0000.g.vcf.gz.tbi".  Whoever picks up this ticket can talk to me about specifics and why we think its an 85MB issue

```
2016-06-02 00:18:27,540 cromwell-system-akka.actor.default-dispatcher-341 INFO  - WorkflowActor [UUID(fa18fa5f)]: persisting status of RotateGVCFIndex to Running.
2016-06-01T20:19:00.527-0400: 104257.028: [GC (Allocation Failure) [PSYoungGen: 1821155K->270322K(1864192K)] 4006446K->2894561K(7456768K), 0.1718483 secs] [Times: user=1.22 sys=0.01, real=0.17 secs] 
2016-06-02 00:19:39,491 ForkJoinPool-3-worker-7 ERROR - Exception not convertible into handled response
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_72]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_72]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_72]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_72]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_72]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_72]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[na:1.8.0_72]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[na:1.8.0_72]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_72]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_72]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_72]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_72]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_72]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_72]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[na:1.8.0_72]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_72]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_72]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338) ~[na:1.8.0_72]
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37) ~[cromwell.jar:0.19]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94) ~[cromwell.jar:0.19]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequest(MediaHttpUploader.java:562) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:419) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[cromwell.jar:0.19]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[cromwell.jar:0.19]
	at com.google.cloud.hadoop.util.AbstractGoogleAsyncWriteChannel$UploadOperation.call(AbstractGoogleAsyncWriteChannel.java:357) ~[cromwell.jar:0.19]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_72]
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [cromwell.jar:0.19]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [cromwell.jar:0.19]
2016-06-01T20:19:40.362-0400: 104296.863: [GC (Allocation Failure) [PSYoungGen: 1130870K->235812K(1864192K)] 3755109K->2861554K(7456768K), 0.0464226 secs] [Times: user=0.25 sys=0.00, real=0.04 secs] 
2016-06-01T20:19:42.554-0400: 104299.055: [GC (Allocation Failure) [PSYoungGen: 1052454K->177588K(1864192K)] 3678197K->2815074K(7456768K), 0.0805924 secs] [Times: user=0.59 sys=0.00, real=0.08 secs] 
2016-06-01T20:20:06.449-0400: 104322.950: [GC (Allocation Failure) [PSYoungGen: 1109940K->381765K(1864192K)] 3747426K->3196632K(7456768K), 0.1380993 secs] [Times: user=1.00 sys=0.01, real=0.14 secs] 
2016-06-01T20:20:06.832-0400: 104323.333: [GC (Allocation Failure) [PSYoungGen: 1157703K->173892K(1864192K)] 3972570K->3267545K(7456768K), 0.0688009 secs] [Times: user=0.50 sys=0.00, real=0.07 secs] 
2016-06-02 00:20:07,325 cromwell-system-akka.actor.default-dispatcher-332 INFO  - JesBackend [UUID(fa18fa5f):RotateGVCF]: `python <<CODE
```

**Comment by kcibul** [comment]
@jsotobroad -- I heard this was a "can't reproduce" can you comment?

**Comment by jsotobroad** [comment]
Seems to be a transient (GCS/JES) issue as it was reproducible multiple times the day the error was first seen.  Since then it has not been reproducible.  Closing issue, will reopen if it pops up again.
