### ISSUE TITLE
Fix test: Write Lines

### ISSUE THREAD

**Issue by cjllanwarne** [broadinstitute/cromwell#955]
The centaur test `write_lines` is failing on JES. That's very sad. Make it work again! You can run it by checking out centaur and running:

```
sbt "test-only * -- -n write_lines"
```

The error:
```
- should fail during execution write_lines *** FAILED *** (6 minutes, 0 seconds)
  java.lang.Exception: Unexpected terminal status Succeeded but was waiting for Failed
```

**Comment by mcovarr** [comment]
The workflow itself seems to succeed, but Centaur thinks there is a failure due to #962.

**Comment by mcovarr** [comment]
Once I implemented a cache locally the workflow runs to Succeeded, but then the Centaur test fails because it's configured to expect workflowfailure.  Judging by the fact that this test was part of [Tyburn](broadinstitute.org/tyburn#27) which I believe lacked support for asserting failures, I don't think this is the correct expectation.

**Comment by cjllanwarne** [comment]
@mcovarr yeah, when I ran this I got `Succeeded but expected Failed` which seemed odd - hence the "Fix/Investigate Test" rather than "Missing Functionality"

**Comment by geoffjentry** [comment]
@mcovarr I'd be careful - I don't know about this one in particular but some of those tests aren't 100% ports from tyburn and actually have changed For Reasons

**Comment by mcovarr** [comment]
I thought it might be a good idea to run Centaur against 0.19_hotfix for comparison.  It turns out that this particular Centaur test "passes" on 0.19_hotfix since the workflow fails consistently.  However this failure appears to be due to botched call path construction when pulling down call logs and not for any reason related to write_lines:

```
java.io.FileNotFoundException: Item not found: cromwell-dev/mlc-executions/write_lines/1b7836f6-841c-4eaa-8d63-8225f67d9507/call-a2f/cromwell-dev/mlc-executions/write_lines/1b7836f6-841c-4eaa-8d63-8225f67d9507/call-a2f/a2f-stdout.log
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageExceptions.getFileNotFoundException(GoogleCloudStorageExceptions.java:42) ~[gcsio-1.4.4.jar:na]
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.getMetadata(GoogleCloudStorageReadChannel.java:579) ~[gcsio-1.4.4.jar:na]
.
.
.
2016-06-07 10:39:03,194 cromwell-system-akka.actor.default-dispatcher-10 INFO  - WorkflowActor [UUID(1b7836f6)]: persisting status of a2f to Failed.
2016-06-07 10:39:03,194 cromwell-system-akka.actor.default-dispatcher-10 ERROR - WorkflowActor [UUID(1b7836f6)]: Item not found: cromwell-dev/mlc-executions/write_lines/1b7836f6-841c-4eaa-8d63-8225f67d9507/call-a2f/cromwell-dev/mlc-executions/write_lines/1b7836f6-841c-4eaa-8d63-8225f67d9507/call-a2f/a2f-stdout.log
2016-06-07 10:39:03,207 cromwell-system-akka.actor.default-dispatcher-10 INFO  - WorkflowActor [UUID(1b7836f6)]: Beginning transition from Running to Failed.
2016-06-07 10:39:05,018 cromwell-system-akka.actor.default-dispatcher-12 INFO  - WorkflowActor [UUID(1b7836f6)]: transitioning from Running to Failed.
```

So AFAICT this workflow should be passing on develop.
